### ISSUE TITLE
建议在 README 中增加借鉴说明

### ISSUE THREAD

**Issue by Allenxuxu** [panjf2000/gnet#1]
看了代码，发现 gnet 文件名都和 [eviop](https://github.com/Allenxuxu/eviop) 差不多。。。

在对 [evio](https://github.com/tidwall/evio) 的优化时照搬了 [eviop](https://github.com/Allenxuxu/eviop) 项目中对 evio 优化时采用的 自动扩容 Ring Buffer。

**Comment by panjf2000** [comment]
嗯，loop 里的 read/write 这两个操作的优化是参考 eviop 的，ringbuffer文件里已经留了你版权的，不过 eviop 的网络模型还是沿用 evio 的那个，gnet 里是我写的一个全新网络模型，完全不同的。

我等下在鸣谢里加一下 eviop吧~~

**Comment by panjf2000** [comment]
已加上。

**Comment by panjf2000** [comment]
已加上。
