### ISSUE TITLE
the frame on React can be changed befor React return

### ISSUE THREAD

**Issue by su47flying** [panjf2000/gnet#101]
i use gnet in the redis-server, and  receive redis-client packages.
my handle redis protocol on the  function React. but before handle function return , the frame be changed, sometimes.

my code on the fellow:

``` Go

func (cs *codecServer) OnOpened(c gnet.Conn) (out []byte, action gnet.Action) {
	reader := &Reader{		
		cmds: []byte  ///  redis command
                argus: [][]byte /// redis arguments
	}
	w := &Writer{
		c: c,
		b:make([]byte,0),
	}
	cli := &client{
		reader: reader,
		rWriter: w,
	}
	c.SetContext(cli)  // save cli on conn
	return
}
// async is fasle. 
// codes: use default BuiltInFrameCodec
func testCodecServe(addr string, multicore, async bool, codec gnet.ICodec) {
	var err error
	if maxPool > 0 {
		pollInit()
	}
	cs := &codecServer{addr: addr, multicore: multicore, async: async,  workerPool: goroutine.Default()}
	err = gnet.Serve(cs, addr,  gnet.WithTCPKeepAlive(time.Minute*5), gnet.WithCodec(codec),
		  gnet.WithNumEventLoop(maxEventLoops), gnet.WithLoadBalancing(gnet.SourceAddrHash))
	if err != nil {
		panic(err)
	}
}

func (cs *codecServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	// response ok to redis client.  test only for redis string set key
	if cs.async {		
		// don't use async 
		return
	} else {
		out = handlerConn(frame, c)
	}
	return
}

func handlerConn(frame []byte, c gnet.Conn) []byte {
	ctx := c.Context()
	cli := ctx.(*client)
	if len(cli.reader.buf) == 0 {
		cli.reader.buf = frame
		log.Printf("init frame:buf:%v", string(frame))
	} else {
		cli.reader.buf = append(cli.reader.buf, frame...)
		log.Printf("appern frame:buf:%v", string(frame))
	}

       for { 
           argus, leftover,err := parseRedisProtocol(frame)
           // parse complete will break
       }
       /// copy leftover to cli.reader.buf
      cli.reader.copyLeftFrame(clie.reader.buf, leftover)
      resp []byte
      /// set response

     /// check cli.Reader.arugs
    doSomingCheck()   /// ERROR!!!... cli.Reader.arugs was not same as input
    return resp
}
```
when  i use tool memtier_benchmark to test my server,  and set 60 threads.  
and error will be happend.

if i use copy fram to cli.Reader.buf, my server will be correctly.
```go
func handlerConn(frame []byte, c gnet.Conn) []byte {
	ctx := c.Context()
	cli := ctx.(*client)
	if len(cli.reader.buf) == 0 {
                cli.reder.buf = make([]byte, len(frame))
                //copy(cli.reader.buf, frame)		
		log.Printf("init frame:buf:%v", string(frame))
	} else {
		cli.reader.buf = append(cli.reader.buf, frame...)
		log.Printf("appern frame:buf:%v", string(frame))
	}
       
       return
}
```
##  现象 ##
doSomingCheck: 的主要逻辑就是把redis的command的参数比如key 生成一个map的value，
  然后做一些业务逻辑，最后，在根据这个key校验一下map的内容。这时候发现这个key不map里面
也就是说这个key被更改了。不是frame传入的key了。

## 综述 ##
当我在我的处理函数中，不使用copy frame的时候，
使用多线程的压测工具，并发压测的时候，就会出现doSomingCheck 的错误。
当我在我的处理函数中，使用copy frame的时候，同样的压测参数就可以正常运行。
（这样就排除了业务代码的影响）
另外：我尝试在cli里面增加一个锁，在处理函数开始就是lock， 处理结束unlock，也仍然出现这个错误。所以我排除了是多个goroutine调用同一个cli的处理函数。
        我也尝试增加codec， 则decode里面做 handlerConn也是同样的表现。

**Comment by panjf2000** [comment]
`React` 的入参 `frame` 是会被内部复用的，所以 `frame` 在业务端的生命周期应该是 `React` 函数体，也就是说如果想不拷贝一份 `frame` 的数据，`React` 里的业务逻辑就必须只对 `frame` 做读操作且 `React` 返回之后就不再引用 `frame` 的内容了 (slice 赋值之后底层引用的是同一个数组)，否则的话，必须拷贝 `frame` 的数据，不然就可能会有数据错乱的问题。

**Comment by su47flying** [comment]
> `React` 的入参 `frame` 是会被内部复用的，所以 `frame` 在业务端的生命周期应该是 `React` 函数体，也就是说如果想不拷贝一份 `frame` 的数据，`React` 里的业务逻辑就必须只对 `frame` 做读操作且 `React` 返回之后就不再引用 `frame` 的内容了 (slice 赋值之后底层引用的是同一个数组)，否则的话，必须拷贝 `frame` 的数据，不然就可能会有数据错乱的问题。

我的handleConon 也是在React里调用的。我的理解应该是在我React返回之前都不应该被修改的。
现在我的测试好像是在React返回之前就被修改了。
后来我有写了一个Decode 方法：也是需要copy， 如果直接 buf仍然是会被修改。
虽然copy能正常运行，但是我觉得copy只是把改变的窗口变小了。仍然是有bug。
不知道是不是我的使用方法有问题吗？
```
// Encode ...
func (cc *RedisFrameCodec) Encode(c gnet.Conn, buf []byte) ([]byte, error) {
	return buf, nil
}

// Decode ...
func (cc *RedisFrameCodec) Decode(c gnet.Conn) ([]byte, error) {
	buf := c.Read()
	ctx := c.Context()
	cli := ctx.(*Client)
        // if don't use copy , before handleConn return, frame can be changed sometimes.
	frame := make([]byte, len(buf))
	copy(frame, buf)
	cli.handleConn(frame, c)
	out := cli.rWriter.GetAndClean()
	c.ResetBuffer()
	return out, nil
}
func (cs *codecServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	//log.Log.Info("client id", c.Context())
	if cs.async {		
		log.Log.Error("not support async")
		return
	} else {
		out = frame
	}
	return
}
```

**Comment by panjf2000** [comment]
> 我的handleConon 也是在React里调用的。我的理解应该是在我React返回之前都不应该被修改的。
现在我的测试好像是在React返回之前就被修改了。

`React` 返回前 `frame` 肯定是不会被修改的。

> doSomingCheck: 的主要逻辑就是把redis的command的参数比如key 生成一个map的value，
然后做一些业务逻辑，最后，在根据这个key校验一下map的内容。这时候发现这个key不map里面
也就是说这个key被更改了。不是frame传入的key了。

你这段话我不是很懂，map 里的 key 变了和 `frame` 有什么关系？

> 后来我有写了一个Decode 方法：也是需要copy， 如果直接 buf仍然是会被修改。
虽然copy能正常运行，但是我觉得copy只是把改变的窗口变小了。仍然是有bug。

只要是在 `React` 函数的作用域内且没有启动单独的 goroutine 去处理 frame，而且对 `frame` 是读操作，是不需要 copy 的，你看看前面这几个条件是不是都满足了？

**Comment by su47flying** [comment]
> 
> 只要是在 `React` 函数的作用域内且没有启动单独的 goroutine 去处理 frame，而且对 `frame` 是读操作，是不需要 copy 的，你看看前面这几个条件是不是都满足了？

没有修改frame，也是使用了frame的引用。没有单独的goroutine。
排查过了，没有发现这些情况。
如果是这样的原因，不会因为后面copy frame就能正常运行。

**Comment by panjf2000** [comment]
问题解决了吗？如果没有的话，更新到最新版 v1.2.5 再试试。
