### ISSUE TITLE
conn.AsyncWrite里的写事件可能发生阻塞

### ISSUE THREAD

**Issue by ek233** [panjf2000/gnet#103]
[https://github.com/panjf2000/gnet/blob/master/connection_unix.go#L192](url)
conn.AsyncWrite函数里，调用了write函数回包，但是套接字是否可写应该是未知的，
为什么不是先写到outboundBuffer，然后调用c.loop.poller.ModReadWrite(c.fd)
完全交给epoll，可写事件触发后再写入。
```go
func (c *conn) AsyncWrite(buf []byte) (err error) {
	var encodedBuf []byte
	if encodedBuf, err = c.codec.Encode(c, buf); err == nil {
		return c.loop.poller.Trigger(func() error {
			if c.opened {
				_, _ = c.outboundBuffer.Write(encodedBuf)
				_ = c.loop.poller.ModReadWrite(c.fd)
			}
			return nil
		})
	}
	return
}
```

**Comment by panjf2000** [comment]
你仔细看下 `c.write([]byte)` 的实现，里面的逻辑是先判断 `outboundBuffer` 是否已经有了待发送的数据，是的话就直接把 `c.AsyncWrite([]byte)` 的数据 append 到 buffer 里然后返回，否则就先尝试直接把数据写回 socket，因为 socket 在一开始就已经设置成非阻塞的了，所以如果此时 socket 暂时不可写的话会直接返回 `EAGAIN` 错误不会阻塞，然后就把数据 append 到 `outboundBuffer`，同时调用 c.loop.poller.ModReadWrite(c.fd)，后面就是你说的那种处理逻辑了：
https://github.com/panjf2000/gnet/blob/31c9ddaee09db36ed7a9ac965ccc6558e98777d2/connection_unix.go#L92-L111
这部分逻辑是比较周全的。
