### ISSUE TITLE
sdk：1.14.4，出现这个引用错误

### ISSUE THREAD

**Issue by zhuqiyun** [panjf2000/gnet#105]
go: finding module for package github.com/panjf2000/gnet
go: downloading github.com/panjf2000/gnet v1.2.3
go-admin/service/tcpservice imports
        github.com/panjf2000/gnet: github.com/panjf2000/gnet@v1.2.3: verifying module: checksum mismatch
        downloaded: h1:maJme8lnr4+S0BpEinvNVCcgW9E46HAcTx0WLvWToI0=
        sum.golang.org: h1:m0jNClfFns9ghBDoLxuST8js8GR5t2VmWA0DnztU06c=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.

**Comment by panjf2000** [comment]
看看这个 issue: https://github.com/panjf2000/ants/issues/49，应该能解决。
