### ISSUE TITLE
go get fail for checksum

### ISSUE THREAD

**Issue by Alberthchang** [panjf2000/gnet#106]
go: downloading github.com/panjf2000/gnet v1.2.3
go get github.com/panjf2000/gnet: github.com/panjf2000/gnet@v1.2.3: verifying module: checksum mismatch
        downloaded: h1:maJme8lnr4+S0BpEinvNVCcgW9E46HAcTx0WLvWToI0=
        sum.golang.org: h1:m0jNClfFns9ghBDoLxuST8js8GR5t2VmWA0DnztU06c=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

go version
go version go1.14.2 darwin/amd64

**Comment by panjf2000** [comment]
See https://github.com/panjf2000/ants/issues/49

**Comment by Alberthchang** [comment]
sorry，but follow that，also error

**Comment by panjf2000** [comment]
Have you tried removing `go.sum`? https://github.com/panjf2000/ants/issues/49#issuecomment-544790952
