### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by zhuyanxi** [panjf2000/gnet#107]
Hi,
When I use `go get -u github.com/panjf2000/gnet` to install gnet, I got this error

```bash
go: downloading github.com/panjf2000/gnet v1.2.3
go get github.com/panjf2000/gnet: github.com/panjf2000/gnet@v1.2.3: verifying module: checksum mismatch
        downloaded: h1:maJme8lnr4+S0BpEinvNVCcgW9E46HAcTx0WLvWToI0=
        sum.golang.org: h1:m0jNClfFns9ghBDoLxuST8js8GR5t2VmWA0DnztU06c=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

So, do I need to downgrade the package version, or is there another way to solve this problem?

**Comment by InasaXia** [comment]
specify the version
```go
require (
    github.com/panjf2000/gnet v1.2.0
)
```

**Comment by panjf2000** [comment]
See https://github.com/panjf2000/ants/issues/49

**Comment by zhuyanxi** [comment]
@InasaXia Thanks.
@panjf2000  Now I downgrade it to version 1.2.0 and my code runs well.
But maybe it's better to solve this issue that we don't need to manually specify the version every time, thanks a lot.
