### ISSUE TITLE
Mac上运行“pushServer”的demo，但是在ws连接测试的时候，连接上就断开

### ISSUE THREAD

**Issue by LuDell** [panjf2000/gnet#108]
**What is your question about gnet?**
Please describe your question meticulously.

Got a connection, launched process /private/var/folders/gn/2j9bm6m136s041cdcrc3f_rw0000gn/T/___go_build_open_ws (pid = 50149).
2020/07/01 11:17:33 Push server is listening on [::]:9000 (multi-cores: true, loops: 8), pushing data every 0s ...
2020/07/01 11:17:41 Socket with addr: 127.0.0.1:52279 has been opened...
2020/07/01 11:17:41 Socket with prewrite...
2020/07/01 11:17:41 Socket with addr: 127.0.0.1:52279 is closing...
2020/07/01 11:17:44 Socket with addr: 127.0.0.1:52280 has been opened...
2020/07/01 11:17:44 Socket with prewrite...
2020/07/01 11:17:44 Socket with addr: 127.0.0.1:52280 is closing...

**Comment by panjf2000** [comment]
贴一下你的 client 代码我看下。

**Comment by panjf2000** [comment]
长时间未回复，暂时关闭，有问题再重新打开。
