### ISSUE TITLE
TCP Package sequencing problem,Receive on the server and send to the client

### ISSUE THREAD

**Issue by xiaochai1027** [panjf2000/gnet#112]
Server accepts data，I use goroutine.Pool.

I know the connection pool is ants，I read the introduction.

- All tasks submitted to ants pool will not be guaranteed to be addressed in order, because those tasks scatter among a series of concurrent workers, thus those tasks would be executed concurrently. 

So, I want to know whether the order in which the data is received for the same connection will be reversed.

My business scenario needs to receive data in order.

For example：
Connections A and B send data to the server.
a: 1,2,3,4,5,6,7,8
b: a,b,c,d,e,f,g,h

Does asynchronous processing through connection pooling change to the following order
A: 1,2,3,5,4,6,7,8
B: a, c, b, d, e, f, g, h

Hope to answer, thank you.

**Comment by xiaochai1027** [comment]
### My test results

#### server code
```
func (cs *customCodecServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	fmt.Println("frame:", string(frame))

	// store customize protocol header param using `c.SetContext()`
	item := protocol.CustomLengthFieldProtocol{Version: protocol.DefaultProtocolVersion, ActionType: protocol.ActionData}
	c.SetContext(item)

	if cs.async {
		_ = cs.workerPool.Submit(func() {
			i,_:=strconv.Atoi(string(frame))
			if i ==1 || i ==3 {
				time.Sleep(10*time.Second)
				fmt.Println("我在处理。。。",i)
			} else {
				fmt.Println("我在处理。。。",i)
			}
			c.AsyncWrite(frame)
		})
		return
	}

	out = frame
	return
}

```

#### client code

```
	go func() {
		for {

			response, err := ClientDecode(conn)
			if err != nil {
				log.Printf("ClientDecode error, %v\n", err)
			}

			log.Printf("receive , %v, data:%s\n", response, string(response.Data))

		}
	}()

	for i := 0; i < 10; i++ {

		data := []byte(strconv.FormatInt(int64(i),10))
		pbdata, err := ClientEncode(protocol.DefaultProtocolVersion, protocol.ActionData, data)
		if err != nil {
			panic(err)
		}
		conn.Write(pbdata)
	}
``` 

### results

```
server 

frame: 0
frame: 1
frame: 2
frame: 3
frame: 4
frame: 5
frame: 6
frame: 7
frame: 8
我在处理。。。 0
我在处理。。。 8
frame: 9
我在处理。。。 4
我在处理。。。 2
我在处理。。。 5
我在处理。。。 6
我在处理。。。 7
我在处理。。。 9
我在处理。。。 3
我在处理。。。 1


client

2020/07/10 11:29:20 receive , &{32769 240 1 [48]}, data:0
2020/07/10 11:29:20 receive , &{32769 240 1 [56]}, data:8
2020/07/10 11:29:20 receive , &{32769 240 1 [50]}, data:2
2020/07/10 11:29:20 receive , &{32769 240 1 [52]}, data:4
2020/07/10 11:29:20 receive , &{32769 240 1 [53]}, data:5
2020/07/10 11:29:20 receive , &{32769 240 1 [54]}, data:6
2020/07/10 11:29:20 receive , &{32769 240 1 [55]}, data:7
2020/07/10 11:29:20 receive , &{32769 240 1 [57]}, data:9
2020/07/10 11:29:30 receive , &{32769 240 1 [51]}, data:3
2020/07/10 11:29:30 receive , &{32769 240 1 [49]}, data:1

```
You can see that the execution of the coroutines is unordered.
However, in our usage scenario, the data is executed sequentially.
So, if you want to use your frame，Don't want to block event-loop.
I need to maintain the sequential nature of the data myself，Implement asynchronous processing, Also, it cannot be used ants.

Do you have any good proposals？

**Comment by panjf2000** [comment]
我个人是建议每个包设置序列号，然后在客户端重排序，如果你实在不想在客户端排序的话，可以在服务器端用一个单独的 goroutine 维护一个队列，同样是按照包的序列号进行排序，在那个 goroutine 里串行地把有序队列里的包依次发挥客户端，就行了。

**Comment by xiaochai1027** [comment]
嗯，我是打算重构一下我们公司现有的服务，在调研tcp处理的框架，目前我们是每个tcp链接一个协程去处理。

**Comment by xiaochai1027** [comment]
而且，我们的信令包是没有序列号的，真正的这样做的话，改动特别大

**Comment by xiaochai1027** [comment]
有没有计划可以支持我这样的场景？

**Comment by xiaochai1027** [comment]
我们是音视频直播业务，音视频的上发数据是要保证顺序处理的，但是又不能阻塞其他上传的音视频

**Comment by panjf2000** [comment]
你们的包协议不好改动的话，那就在外面自己包一层，把序列号加进去呗。

**Comment by xiaochai1027** [comment]
嗯，谢谢建议，我们在研究下

**Comment by panjf2000** [comment]
先关掉这个 issue，有需要可以随时打开。
