### ISSUE TITLE
gnet 针对 evio 做了什么优化？

### ISSUE THREAD

**Issue by choleraehyq** [panjf2000/gnet#12]
看到 readme 里说在 evio 基础上改的，性能优于 evio，想知道主要有哪方面的优化？最好能说明在 README 里

**Comment by panjf2000** [comment]
主要是用 multi-reactors 模型替换掉它原来的网络模型，其他的就是一些小优化：减少不必要的唤醒，减少内存拷贝。

现在还在持续开发，还有不少可以优化的地方，等有一个初步的版本出来之后我再抽时间把这些优化点都写一下。
