### ISSUE TITLE
Two gnet.Serve instances or bind two inrefaces

### ISSUE THREAD

**Issue by oicnysa** [panjf2000/gnet#124]
**What is your question about gnet?**
Please describe your question meticulously.

**Comment by oicnysa** [comment]
Hi, 
Is there a performance penalty for running two instances of gnet.Serve? Or is there a possibility to bind server to numerous interfaces.
My use case - receive udp traffic on two interfaces.
Thanks in advance.

**Comment by panjf2000** [comment]
Sorry, I didn't quite get it when you said binding server to numerous interfaces, did you mean that you were running multiple `gnet` servers which listen on the same `ip:port`?

Why would you try to set up multiple `gnet` servers on one `ip:port`? Couldn't you just set up one `gnet` server and enable the `multi-cores` in `gnet`?

@oicnysa

**Comment by oicnysa** [comment]
I mean to run multiple gnet server instances, which listern on different ip:port.

**Comment by panjf2000** [comment]
> I mean to run multiple gnet server instances, which listern on different ip:port.

Then I don't see what makes `gnet` special in doing so, I thought it's just like other frameworks when you do that.

**Comment by panjf2000** [comment]
BTY, if you are available right now, I suggest we chat in IM, that would be more effective, here is the IM link: https://gitter.im/gnet-io/gnet

**Comment by oicnysa** [comment]
@panjf2000 thanks for your answer. Actually, already decided to use just only one interface.
