### ISSUE TITLE
能否提供一个获取fd的接口

### ISSUE THREAD

**Issue by amwfhv** [panjf2000/gnet#127]
在项目中需要使用到一个唯一的Key,这个Key需要传递给其它服务器，因此想到使用fd做为Key，如果自己生成则需要判断重复，使用Addr开销较大

**Comment by panjf2000** [comment]
暴露底层 fd 是不安全的做法，很容易造成 fd 的误用，为什么使用 addr 开销较大？是因为 String() 方法？

**Comment by iHDJ** [comment]
不能，也不推荐使用fd作为key。可以考虑uuid或者是自增长int类型的话用redis或者雪花也是行得通的

**Comment by amwfhv** [comment]
1、因为字符串需要在几个不同的应用中传递，一个外网的IP+Port字符串需要近二十位，而传递fd只需要4或者8位
2、因为是想将老系统转到Go，中间会有转换过程，因此需要做到兼容，以前老系统是使用的fd做为Key
3、目前已使用了一个自增长的int，替代fd
