### ISSUE TITLE
[问题]直接将bytebuffer.Put(c.byteBuffer)返还，不会导致Read的内容被改吗？

### ISSUE THREAD

**Issue by vxzhong** [panjf2000/gnet#132]
**What is your question about gnet?**
Please describe your question meticulously.
```
func (c *conn) Read() []byte {
	if c.inboundBuffer.IsEmpty() {
		return c.buffer
	}
	c.byteBuffer = c.inboundBuffer.WithByteBuffer(c.buffer)
	return c.byteBuffer.Bytes()
}

func (c *conn) ResetBuffer() {
	c.buffer = c.buffer[:0]
	c.inboundBuffer.Reset()
	bytebuffer.Put(c.byteBuffer)
	c.byteBuffer = nil
}
func (cc *BuiltInFrameCodec) Decode(c Conn) ([]byte, error) {
	buf := c.Read()
	if len(buf) == 0 {
		return nil, nil
	}
	c.ResetBuffer()
	return buf, nil
}
```
`ResetBuffer`后，`c.byteBuffer`被返还，不就有可能被其它goroutine的`bytebuffer.Get`拿到，因为底层`B`重用，那`Read`的内容不是可能被修改吗？想不通，请指点。多谢🙏

**Comment by panjf2000** [comment]
分两种情况：
1. React 里是同步代码，这样的话 buffer 就只在同步逻辑里被使用，也就是只有一个消费者，用完之后才会被回收，就不存在 buffer 被同时读写的问题；
2. React 里需要用 goroutine 去并发地处理 buffer，这时候就应该提前把 buffer 里的数据拷贝到新的内存地址上，让 goroutine 去引用新的内存，避免 race 问题。

**Comment by vxzhong** [comment]
1,2这两种读的情况，我都明白。但是这里的`buffer`底层可能是指向`c.byteBuffer.Bytes()`，但是bytebufferpool是所有connection共享的吧，有多个SubReactor，不就有多个同时的eventloop，就有多个conn同时在Read，一个conn在resetbuffer后就已经将底层的`c.byteBuffer`的`B`返还给pool了，然后才在`React`里处理；而另一个conn同时在Read通过`bytebufferpool.Get`不就可能拿到这个`bytebuffer`的`B`，这两个conn不就通过bytebufferpool读写一样的底层的`B`了吗？可能我理解有问题，但是困扰我好久，没想明白，多有打扰。

**Comment by panjf2000** [comment]
> 一个conn在resetbuffer后就已经将底层的c.byteBuffer的B返还给pool了，然后才在React里处理

不是，你要确保处理完数据之后才调用 ResetBuffer
