### ISSUE TITLE
Two questions about performance

### ISSUE THREAD

**Issue by rock59** [panjf2000/gnet#133]
1- I need to use a nonblocking C library in io loops. The library uses thread local storage so I have to use LockOSThread in each io loop. Is it safe and does it affect gent performance (Excluding cgo overhead) ?

2- Gnet's thread pool system uses channels to pass blocking tasks to worker goroutines. I guess using channels , mutexes and anything else that cause go scheduler to switch goroutines may affect performance of io loops. Am I correct ?

**Comment by panjf2000** [comment]
> 1- I need to use a nonblocking C library in io loops. The library uses thread local storage so I have to use LockOSThread in each io loop. Is it safe and does it affect gent performance (Excluding cgo overhead) ?

Where do you call `LockOSThread` to lock each IO loop goroutine to a specified thread?

> 2- Gnet's thread pool system uses channels to pass blocking tasks to worker goroutines. I guess using channels , mutexes and anything else that cause go scheduler to switch goroutines may affect performance of io loops. Am I correct ?

goroutine pool `ants` uses mutex+LIFO queue for delivering tasks instead of channel. If you are worried about blocking IO loop goroutine by mutex, you can leverage the nonblocking mechanism of `ants` to avoid blocking IO loop goroutines, https://github.com/panjf2000/ants/blob/master/options.go#L33

**Comment by rock59** [comment]
@panjf2000  Thanks for your response.


> Where do you call `LockOSThread` to lock each IO loop goroutine to a specified thread?

I need to call LockOSThread at the start of IO loop goroutine (the server startup) and call UnLockOSThread at the server shutdown.

**Comment by panjf2000** [comment]
> @panjf2000 Thanks for your response.
> 
> > Where do you call `LockOSThread` to lock each IO loop goroutine to a specified thread?
> 
> I need to call LockOSThread at the start of IO loop goroutine (the server startup) and call UnLockOSThread at the server shutdown.

I'm afraid that it won't work as you expected, `OnInitComplete` happens before I/O loops start running, so you're not going to get the results you want with calling `runtime. LockOSThread ()` in `OnInitComplete`, it can only be done by modifying the source code and provide a functional option for users to determine whether to lock each I/O loop to a specified thread.

**Comment by panjf2000** [comment]
I'll have this feature up and running by the end of the week, stay tuned!
