### ISSUE TITLE
Possible for you to compare linux and freebsd deployment on the same hardware specs?

### ISSUE THREAD

**Issue by gitmko0** [panjf2000/gnet#138]
possible to run the benchmark of freebsd on the same machine as the one ran on linux?
which will be faster? running gnet on linux or freebsd?
# Machine information
        OS : Ubuntu 18.04/x86_64
       CPU : 8 Virtual CPUs
    Memory : 16.0 GiB

# Go version and configurations
Go Version : go1.12.9 linux/amd64
GOMAXPROCS=8

**Comment by panjf2000** [comment]
I don't currently have two machines with identical hardware but different operating systems, if you do, please test it out.

**Comment by gitmko0** [comment]
do you think it's faster to use freebsd than linux? i mean is the performance better on freebsd than linux or linux has better performance?

**Comment by panjf2000** [comment]
It's irresponsible to draw a conclusion without a benchmark.
