### ISSUE TITLE
possible to write gnet http as a replacement for a faster fasthttp?

### ISSUE THREAD

**Issue by gitmko0** [panjf2000/gnet#140]
if compared with fasthttp, this is totally "unusable" / not very programmer friendly like fasthttp
https://github.com/gnet-io/gnet-examples/blob/master/examples/http/http.go

do u hv any intent on making it more programmer friendly with API like fasthttp? that'll really improve adoption.

great software by the way.

**Comment by panjf2000** [comment]
> if compared with fasthttp, this is totally "unusable" / not very programmer friendly like fasthttp

You should first have a clear understanding of network layers, `fasthttp` is an HTTP implementation that works in the application layer, while `gnet` is a networking framework which works in the more low-level network layer: transport layer, you can implement any networking application that works on top of TCP/UDP/UNIX Domain Socket, including HTTP, RPC, WebSocket, Redis, etc. 

`gnet` was not created only for HTTP, the `gnet` HTTP example is only an example. So comparing gnet to fasthttp is inappropriate.

> do u hv any intent on making it more programmer friendly with API like fasthttp? that'll really improve adoption.

Like I said above, `gnet` is not more than HTTP, so the answer is no.
