### ISSUE TITLE
UDP AsyncWrite 不能成功发送

### ISSUE THREAD

**Issue by finishy1995** [panjf2000/gnet#141]
您好，在创建 UDP 监听并在 React 收到消息后，尝试调用gnet.Conn.AsyncWrite无法成功发送消息，打印日志发现 gnet.Conn 的地址被清空了
UDP 是否不支持 AsyncWrite

**Comment by panjf2000** [comment]
https://github.com/panjf2000/gnet/blob/6fd6413920618f8cd9906923bd5768a43ce1c3b7/gnet.go#L121-L122

**Comment by finishy1995** [comment]
https://github.com/panjf2000/gnet/blob/83d304c26f33b0695bb77c18d0d13b91102176f6/eventloop_unix.go#L309

React执行完后 conn 被释放，需要持久化 conn

**Comment by finishy1995** [comment]
谢谢！
再看了代码，release只是释放本地地址，SendTo能够成功发送
