### ISSUE TITLE
Cannot reconnect quickly when client close

### ISSUE THREAD

**Issue by finishy1995** [panjf2000/gnet#142]
**Describe the bug**
OS: Windows X86_64
When client close and quick reconnect(about Second * 1) to gnet server, gnet will not call OnOpened(c Conn). And net.Listener.Accept() return err "use of closed network connection"

**To Reproduce**
1. serve local tcp
2. use net.Dial to connect gnet server
3. close this connection when connected
4. wait 1 second
5. use net.Dial to connect gnet server
6. cannot connect to gnet server

**Expected behavior**
Expect to reconnect to server quickly

**Screenshots**
/ 

**System Info (please complete the following information):**
 - OS (e.g. Ubuntu 18.04): Windows 10
 - Go version (e.g. Go 1.13): 1.15
 - gnet version (e.g. v1.0.0): 1.3.0

**Additional context**
This issue is related to both udp server. When udp client try to reconnect quickly, it will not call React() method.

**Comment by finishy1995** [comment]
https://github.com/panjf2000/gnet/blob/83d304c26f33b0695bb77c18d0d13b91102176f6/connection_windows.go#L224

I change this code to
c.loop.loopCloseConn(c) // Will return err because conn is closed by client
return nil
And this issue will not happen.

**Comment by panjf2000** [comment]
Let's make it clear, you closed the connection on the client first and then closed it on the server by calling `c.Close()`, right?

**Comment by finishy1995** [comment]
> Let's make it clear, you closed the connection on the client first and then closed it on the server by calling `c.Close()`, right?

I close the connection on the client. Then server OnClose oncall. I tried both use c.Close() and not use. But when the client try to reconnect. Server OnOpened is not been called.
I also tried to use another thread client to connect. That can be connect successfully. But only the first client which just close the connection cannot connect again.

**Comment by finishy1995** [comment]
I know that vc++can use WSAECONNREST to get this situation, and WSAIoctl() to fix it. It caused by reuse the same bind port by  client. UDP is OK. Forgot the issue description about UDP.
