### ISSUE TITLE
How to handle this error?

### ISSUE THREAD

**Issue by rolancia** [panjf2000/gnet#149]
1  payload: [104 105]
2020-11-02T17:22:00.032Z        ERROR   gnet@v1.3.0/reactor_linux.go:87 Event-loop(0) is exiting due to an unexpected error: connection reset by peer
github.com/panjf2000/gnet.(*server).activateSubReactor
        /root/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/reactor_linux.go:87
github.com/panjf2000/gnet.(*server).startSubReactors.func1.1
        /root/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/server_unix.go:91
2020-11-02T17:22:00.032Z        INFO    gnet@v1.3.0/reactor_linux.go:85 Event-loop(1) is exiting normally on the signal error: server is going to be shutdown
2020-11-02T17:22:00.032Z        INFO    gnet@v1.3.0/reactor_linux.go:40 Main reactor is exiting normally on the signal error: server is going to be shutdown

while requesting many packets, the panic occurs and server shutdown if the client closes the connection.
i used your example server base code. (codec server)
(just added write/read goroutine with for loop to client )

why server shutdown when client close their connection?
how may i solve this ..?

**Comment by rolancia** [comment]
and this is from windows

2020/11/03 02:30:51 recv proto: 1  payload: [104 105]
2020/11/03 02:30:51 recv proto: 1  payload: [104 105]
2020/11/03 02:30:51 write tcp [::1]:9000->[::1]:51850: wsasend: An existing connection was forcibly closed by the remote host.
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xc89d69]

goroutine 10 [running]:
github.com/panjf2000/gnet.(*eventloop).loopError(0xc000062580, 0xc00009c000, 0xd274c0, 0xc0001840a0, 0x0, 0x0)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/eventloop_windows.go:184 +0x69
github.com/panjf2000/gnet.(*eventloop).loopEgress(0xc000062580)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/eventloop_windows.go:143 +0x228
github.com/panjf2000/gnet.(*eventloop).loopRun.func1(0xc000062580, 0xc0004c3f80)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/eventloop_windows.go:56 +0x94
panic(0xcb66c0, 0xe3b210)
        c:/go/src/runtime/panic.go:969 +0x176
github.com/panjf2000/gnet/ringbuffer.(*RingBuffer).IsEmpty(...)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/ringbuffer/ring_buffer.go:368
github.com/panjf2000/gnet.(*stdConn).Read(0xc00009c000, 0xbff80d, 0xe453e0, 0xb14d5b)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/connection_windows.go:126 +0x31
github.com/panjf2000/gnet.(*LengthFieldBasedFrameCodec).Decode(0xc000064360, 0xd2b2c0, 0xc00009c000, 0xc0000660a0, 0xc000064598, 0x0, 0xc0000660a0, 0x15)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/codec.go:246 +0x67
github.com/panjf2000/gnet.(*stdConn).read(...)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/connection_windows.go:120
github.com/panjf2000/gnet.(*eventloop).loopRead(0xc000062580, 0xc00009c000, 0xc0000598e0, 0x0)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/eventloop_windows.go:103 +0x62
github.com/panjf2000/gnet.(*eventloop).loopRun(0xc000062580, 0xb0e200)
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/eventloop_windows.go:72 +0x47f
created by github.com/panjf2000/gnet.(*server).startEventLoops.func1
        C:/Users/leeth/go/pkg/mod/github.com/panjf2000/gnet@v1.3.0/server_windows.go:100 +0x56
exit status 2

**Comment by rolancia** [comment]
though i set multicore false, same...

**Comment by rolancia** [comment]
i found out *RingBuffer, *stdConn can be nil.
server dies while reading buffer or something through conn

etc.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x675351]

goroutine 10 [running]:
github.com/panjf2000/gnet/ringbuffer.(*RingBuffer).Length(...)
        C:/Users/NineM/go/pkg/mod/github.com/panjf2000/gnet@v1.3.1-0.20201102141801-89723ed339a3/ringbuffer/ring_buffer.go:261
github.com/panjf2000/gnet.(*stdConn).ShiftN(0xc00009e000, 0x8, 0x4)
        C:/Users/NineM/go/pkg/mod/github.com/panjf2000/gnet@v1.3.1-0.20201102141801-89723ed339a3/connection_windows.go:168 +0x31
github.com/panjf2000/gnet.(*LengthFieldBasedFrameCodec).Decode(0xc000040360, 0x78b440, 0xc00009e000, 0xc0000421e0, 0x0, 0x0, 0xc0000421e0, 0x8)
        C:/Users/NineM/go/pkg/mod/github.com/panjf2000/gnet@v1.3.1-0.20201102141801-89723ed339a3/codec.go:270 +0x25d

**Comment by panjf2000** [comment]
Please provide the required info: go version, gnet version, ...

**Comment by rolancia** [comment]
> Please provide the required info: go version, gnet version, ...

Go 1.15, gnet 1.3.0 and error-handling branch.

**Comment by panjf2000** [comment]
Fixed by e586a89 and 053b78c

**Comment by rolancia** [comment]
Appreciate
I've been inspired by you these days.
Appreciate again
