### ISSUE TITLE
非阻塞模式

### ISSUE THREAD

**Issue by zhaoke0513** [panjf2000/gnet#15]
老哥，最新tag版本
好像没有暴露异步处理的接口啊。

**Comment by panjf2000** [comment]
@zhaoke0513 
对，还没有打 tag，因为现在我感觉近期还有很多新的变更，如果要建新tag的话因为是非兼容更新只能打v1.x.x开头的了，但是我还不想这么快release v1.0，因为想等功能都稳定了再打v1.0，你如果想用异步接口，用 go modules 的话，可以 `go get github.com/panjf2000/gnet@master` 获取最新版本，感谢关注~
