### ISSUE TITLE
Proxy for gnet built in.

### ISSUE THREAD

**Issue by gitmko0** [panjf2000/gnet#150]
With reference to this issue:
https://github.com/gnet-io/gnet-examples/issues/2

Can't wait to see it works! I will be first to contribute actual use case for gnet.
It'll be a serious game changer for proxy like software such as haproxy etc

**Comment by gitmko0** [comment]
Will be great if can do bandwidth throttling, like incorporate this, or an in built function
https://github.com/efarrer/iothrottler/

**Comment by panjf2000** [comment]
Duplicate #120
