### ISSUE TITLE
Shutdown on interrupt signal to be configurable

### ISSUE THREAD

**Issue by o447** [panjf2000/gnet#154]
**Is your feature request related to a problem? Please describe.**
I would like to be able to continue proccessing requests for some time after receving an interrupt, and decide in my application when to shutdown the server.

Currently as soon as an interrupt signal is fired, I cannot override the behavior of gnet to prevent a shutdown.

**Describe the solution you'd like**
A new field in the options when calling the Serve function, just a boolean to turn off this default behaviour

**Describe alternatives you've considered**
Couldn't find any workarounds, because my application still needs to listen for the interrupt signal, to eventually shutdown the server, just not immediately.

**Comment by panjf2000** [comment]
I believe #148 is what you were looking for, please try it out.

**Comment by o447** [comment]
I can't find anything in that PR regarding this feature request.

I mean specfically this code block, should be made optional because a user cannot override this behavior. Also don't think it makes sense for a library to be listening to interrupts to the application, its better that the application handles interrupts on its own.

https://github.com/panjf2000/gnet/blob/36258e289be2ed37ef11181a99ef385920eed98c/server_unix.go#L259-L268

**Comment by panjf2000** [comment]
You may get a point here, I'll consider removing this signal handling part.

**Comment by lookfirst** [comment]
Another vote for this. I use [uberfx](https://github.com/uber-go/fx) as my 'app server' framework. I run gnet within it. uberfx handles the signal events for me and provides me with a standard lifecycle for all the modules in my app. All I need is the ability to call something like EventServer.Stop().

There is probably some twist in this which is the ability to wait for pending connections to be processed before shutting down or to 'force' shutdown.

**Comment by lookfirst** [comment]
@panjf2000 Fantastic. Thanks.

**Comment by lookfirst** [comment]
@panjf2000 "2020-11-17T18:56:43.105-0800	INFO	gnet@v1.3.2-0.20201117173319-c1245fb4b43f/reactor_bsd.go:40	Main reactor is exiting due to error: server is going to be shutdown"

It isn't really an error. =)

**Comment by lookfirst** [comment]
Also... not the end of the world, but the API still feels a little funny with this gnet singleton. It seems like if you had `gnet.Serve()` return some object, then I would call `.Stop()` on that object.... instead of passing in the `protoAddr` to `.Stop()`.... not the end of the world though.

**Comment by panjf2000** [comment]
> Also... not the end of the world, but the API still feels a little funny with this gnet singleton. It seems like if you had `gnet.Serve()` return some object, then I would call `.Stop()` on that object.... instead of passing in the `protoAddr` to `.Stop()`.... not the end of the world though.

That's indeed the conventional way, but only for the `Server` instance that is external and contains exported fields, while the `gnet` server instance is internal and there are no exported fields for users to manipulate for safety. So it's unnecessary to return a gnet internal server instance from gnet.Serve(), then the protoAddr becomes the only identifier for each gnet server.

**Comment by lookfirst** [comment]
Yup, up to you. Thanks for the explanation. I'm just not a huge fan of singletons... makes writing tests harder and tends to make code more brittle.

**Comment by panjf2000** [comment]
Why would you say singleton? I don't quite get it, care to explain a bit?

**Comment by lookfirst** [comment]
https://en.wikipedia.org/wiki/Singleton_pattern

`gnet.Serve()` keeps state 'serverFarm' in a 'global' gnet object. You've basically got a globally namespaced object.

This is why you have to have a 'serverFarm' managed internally within a serve object.

For example, what if I wanted my own implementation of a serverFarm that wasn't stored in a slow sync.Map or I wanted to store other data with each 'server'? How would I do that?

Again, it all falls into the configurability of your library. You could make things a lot more flexible with a different API design.
