### ISSUE TITLE
主动断开

### ISSUE THREAD

**Issue by dengdajun** [panjf2000/gnet#156]
因为我不断的向链接里面发送消息，然后非阻塞，导致，tcp主动断开，我现在想发送的时候阻塞一下，有什么办法么

**Comment by mikeqoo1** [comment]
channel

**Comment by dengdajun** [comment]
我就是用的channl，但是我有个定时任务，每秒都有下发，

**Comment by panjf2000** [comment]
你这说的是客户端的问题吧？和 `gnet` 有什么关系呢？

**Comment by panjf2000** [comment]
还有，开 issue 的时候注意选对类型，你提的这个是加新功能的 issue，麻烦下次注意一下。

**Comment by panjf2000** [comment]
如前面所说，按我的理解这个问题似乎不是 gnet 的问题，暂时关闭，如果我理解有误或者还有其他问题可以再重新打开。
