### ISSUE TITLE
TCP no_delay options

### ISSUE THREAD

**Issue by li-ma** [panjf2000/gnet#161]
Hi, panjf2000,

I wonder if I can enable or disable no_delay for TCP connection. It seems there's no such option from public interfaces.

**Comment by panjf2000** [comment]
Sorry for the delay, somewhat busy recently!

I'm going to add a new functional option for setting up TCP/UDP socket options into `Options`:
https://github.com/panjf2000/gnet/blob/6fd6413920618f8cd9906923bd5768a43ce1c3b7/options.go#L41-L76

This feature will be completed within the week.

**Comment by li-ma** [comment]
Thank you for update.
