### ISSUE TITLE
Q: why incompatible with net package?

### ISSUE THREAD

**Issue by ivanjaros** [panjf2000/gnet#168]
I am curious to know why gnet is not a replacement for the net package when the net package has only two important components - listener and connection. Listener has only one important method - Accept, which returns the connection, which itself has only Read, Write and Close methods. So why can't gnet provide **abstraction** over these 2 thin interfaces to make it a pluggable replacement for http and other widely used packages?

**Comment by panjf2000** [comment]
Go allows users to write asynchronous network applications under a synchronous programming model while `gnet` is designed as an asynchronous at the time of its creation, thus there is no way to make them compatible.

**Comment by ivanjaros** [comment]
can you elaborate on that? iirc the listener just runs loop and spins up goroutine for each connection and each connection then has its own loop that spins new goroutine to handle the message(request->response). what is gnet doing differently(as you say, async vs sync)?
