### ISSUE TITLE
gnet 和 gev 的压测结果不一致问题

### ISSUE THREAD

**Issue by yale8848** [panjf2000/gnet#17]
[gev](https://github.com/Allenxuxu/gev)，gnet都很优秀，感谢你们开源付出。但是目前看你两出的基准测试结果还是有差异的，这样让使用者比较困惑，建议你两能否商量一下拿出一个统一的基准测试。

**Comment by yale8848** [comment]
https://github.com/Allenxuxu/gev/issues/6 我也再这边提了，你也可以看看

**Comment by panjf2000** [comment]
@yale8848 
导致结果不同的原因挺复杂的，首先机器参数就不同，两边设置的压测参数也不太一样，另外就是这种压测的不稳定性，有时候这个表现好一点，有时候又变成另一个表现更好了，`gev` 的吞吐量测试显示它更高，不过我也用过 `gev` 的吞吐量测试在我的机器上测过，结果是 `gnet` 也有表现更好的时候：
<img width="644" alt="WechatIMG981" src="https://user-images.githubusercontent.com/7496278/65810665-a8f38900-e1df-11e9-9faf-e04984662c02.png">
<img width="663" alt="WechatIMG986" src="https://user-images.githubusercontent.com/7496278/65810666-aabd4c80-e1df-11e9-9dab-0efa1134c02d.png">
<img width="531" alt="WechatIMG979" src="https://user-images.githubusercontent.com/7496278/65810670-b1e45a80-e1df-11e9-8dd2-af6c53407223.png">
<img width="545" alt="WechatIMG980" src="https://user-images.githubusercontent.com/7496278/65810671-b3ae1e00-e1df-11e9-885a-461aaaa7e26d.png">

**Comment by Allenxuxu** [comment]
@yale8848 建议自己机器多跑几次看看，[gev](https://github.com/Allenxuxu/gev) 和 gnet 都是从我的另一个项目 [eviop](https://github.com/Allenxuxu/eviop)  而来，所以理论上应该都差不多。.

**Comment by panjf2000** [comment]
所以，基于这种测试环境的不同以及压测结果的波动，有时候 `gnet` 表现好一点，有时候又是 `gev` 更好，我觉得不一致挺正常的，再加上这两个库使用的网络模型都用的经典的主从 Reactor 模型，所以原理基本是一致的，就看一些在模型里小的优化能提高多少性能了，但是两者总体来说都比 Go 的标准 net 包性能更好，所以和 net 对比的这个压测结果是确定的，`gnet` 是基于 `evio` 的代码进行重构和改造的，由于`evio` 的代码耦合性问题，重构优化比较麻烦一点，`gev` 是参考 `evio` 和 `muduo ` 之后全新写的，我想可能会更做一点。

**Comment by yale8848** [comment]
好的，谢谢2位的及时回复
