### ISSUE TITLE
使用gnet 做tcp 代理。无法收到mysql的数据包。

### ISSUE THREAD

**Issue by roverliang** [panjf2000/gnet#173]
近期在使用gnet 做 tcp代理的相关开发，感谢你开发这么好用的组件。

**问题：**
> 发现gnet server 无法收到mysql Client 的数据。显示连接已建立。

使用[官方提供的TCP来测试](https://github.com/gnet-io/gnet-examples/tree/master/examples/echo_tcp)， 但是`React`函数内并未收到任何数据。

经过检查，并不是codec 的问题。codec 内也并没有执行到。

我不确定这是个bug，还是我使用上有什么问题。

另外，使用原生的net包，可以代理mysql的请求。

期望得到你的回复。

**Comment by panjf2000** [comment]
Please switch to gnet v2 and try this again, if the issue still exists, feel free to reopen this issue.
