### ISSUE TITLE
UDP connections do not close the underlying file descriptor

### ISSUE THREAD

**Issue by ehsannm** [panjf2000/gnet#174]
**Describe the bug**
In udp connection case, after React callback has been finished, the udp connection does not close the 
underlying fd. This makes problem with too many open files error for long runs

**Comment by panjf2000** [comment]
Why would you expect `gnet` to close the underlying fd after `gnet.React` when the server is still running? I'm pretty sure that a UDP server doesn't create a fd every time it receives a packet from a client.

**Comment by ehsannm** [comment]
yes, sorry i had problem in our tcp connection which was on our client side not closing properly.
