### ISSUE TITLE
Handler to open/drop connection before OnOpened

### ISSUE THREAD

**Issue by o447** [panjf2000/gnet#176]
**Is your feature request related to a problem? Please describe.**
I would like to be able to decide wehther to accept/drop a connection based on remote address.
The "OnOpened" method is too slow in my benchmarks, because too much CPU time is spent opening and closing a connection which was known to be useless.

**Describe the solution you'd like**
Anything that would let me decide to open/drop a connection based on remote address.

**Describe alternatives you've considered**
The "OnOpened" method

**Comment by panjf2000** [comment]
You have to accept a client socket first to know its address.
As you can see:
https://github.com/panjf2000/gnet/blob/fee6aca01174a81ebd795a4f708781b921ba8ca1/eventloop_unix.go#L118-L132
The `OnOpened` doesn't do much, only a few logic which is lightweight, why would it slow down the performance?

**Comment by panjf2000** [comment]
Closing this issue cuz inactivity, feel free to reopen it if there is still a question.
