### ISSUE TITLE
v1.3.2版本发现连接建立后偶发没有触发OnOpened方法

### ISSUE THREAD

**Issue by Gitforxuyang** [panjf2000/gnet#179]
潘神，你好。
我们使用了gnet的1.3.2版本做IM的服务器，上线一段时候后，我们发现一个非常诡异的现象。

当我们的服务运行一段时间后，会莫名其妙的造成系统内存一直增加，而且用netstat命令查看，发现很多连接的Recv-Q有大量的堆积。然后通过查询日志发现这一类有Recv-Q堆积的连接都没有触发onOpend方法，也就是说我的程序根本就没有感知到这个连接的建立（是不是因此这个连接的接收数据会一直得不到接收，一直堆在接收缓冲区上？）

附上recv-q的图
![image](https://user-images.githubusercontent.com/16128584/106295364-4f93e200-628b-11eb-9f57-6cdf0b3007e6.png)

期待得到你的回复。十分感谢。

**Comment by panjf2000** [comment]
现在 `gnet` 才到 v1.3.2，哪来的 1.3.6？提供下正确的版本号，还有Go版本，OS类型。

**Comment by Gitforxuyang** [comment]
@panjf2000 不好意思，是我写错了。版本是v1.3.2。 

OS : Centos 7.4  Kernel: 3.10
Go version: Go-1.13
gnet version: v1.3.2

**Comment by panjf2000** [comment]
你们在 `OnOpened` 里做了什么？为什么能确定它没被调用？
可以在这里加几行日志，然后重新编译一下代码：
https://github.com/panjf2000/gnet/blob/v1.3.2/acceptor_unix.go#L49-L56
把 `Trigger` 方法返回的 error 记录一下，看看是不是这里有错误，还有在 `loopOpen` 方法前后加一下 log，是不是真的没有调用这个方法，调试一下看看。

**Comment by panjf2000** [comment]
还有，有没有试过调用 https://github.com/panjf2000/gnet/blob/v1.3.2/gnet.go#L76 这个方法，连接数是不是真的不符？

**Comment by panjf2000** [comment]
我试着修复了一下这个问题，你更新一下版本再试试，观察一下还有没有这个问题，如果还出现这种情况，你再打开这个 issue 我们继续定位。
@Gitforxuyang

**Comment by Gitforxuyang** [comment]
好的，我按照你的修改先改了试试。

**Comment by Gitforxuyang** [comment]
我使用CountConnections方法获取到的连接数比使用netstat命令获取到的要少不少。请问这种情况正常吗？ netstat命令如下。
netstat -an|grep ESTABLISHED |wc -l

**Comment by Gitforxuyang** [comment]
我放到线上试了一下效果发现还是会有大量的连接Recv-Q堆积的很厉害，而且基本上发生在同时有大量连接进入的时候（某个时间点发送推送给用户时）。

**Comment by Gitforxuyang** [comment]
@panjf2000 我没法重新打开这个issue

**Comment by panjf2000** [comment]
加 log 了吗？`Trigger` 的返回错误了吗？还有 `loopOpen` 前后有没有打印 log？

**Comment by panjf2000** [comment]
> 我使用CountConnections方法获取到的连接数比使用netstat命令获取到的要少不少。请问这种情况正常吗？ netstat命令如下。
> netstat -an|grep ESTABLISHED |wc -l

你这个是查所有已建立的连接，一般是会多的，所以我问为什么你们能确定 `OnOpened` 没有调用？

**Comment by Gitforxuyang** [comment]
@panjf2000 我们在OnOpened里打印了log，其中包含来源方的ip+port。目前为止我们发现比较明显的异常情况
当我们发送推送，用户大量进来时就会出现大量连接的Recv-Q堆积，而且这些连接在日志里都找不到（onopened方法没有被调用）

所以我们怀疑是不是在并发情况下有一些隐秘的bug造成了这种现象

**Comment by Gitforxuyang** [comment]
@panjf2000 如果可以的话我方便加你微信沟通吗？ 为了消息更及时。  我的微信xy981466324

**Comment by Gitforxuyang** [comment]
我们有一个场景，当用户上线时会获取自己未接收的所有消息，所以用户刚上线时发送的请求和接收的请求可能量会比较大。 如果这种场景的话会造成有些连接来不及处理onOpened方法不会被调用的情况吗？

**Comment by Gitforxuyang** [comment]
我做了一下实验，自己创建连接去并发连接server但是不收发消息,发现服务不会出现异常。  那很有可能就是我们业务上收发消息造成连接的onOpened函数不会处理，还有Recv-Q会堆积，我想问我们gnet在某个连接的收发消息量很大的时候会阻塞主进程造成其它连接无法正常处理吗？

**Comment by panjf2000** [comment]
你现在要确认的是这部分代码有没有执行：
https://github.com/panjf2000/gnet/blob/2aee5a9ea2d86d2eabf2964be96cbf8ce643bc48/acceptor_unix.go#L50-L56
如果这里没有执行的话，那么说明连接的 fd 没有成功放到 epoll 监听列表里，那肯定是会造成 recv-q 数据积压的，因为 gnet 就是依赖 epoll 去唤醒接收数据的。

所以现在我的建议是，你这这里加 log，把 error 打印一下看看是不是非空的错误，然后就是你自己计算客户端连过来的socket数量，最后和 `gnet.CountConnections` 作比较，如果前者多于后者，那证明有很多连接没有被添加到 gnet 的 epoll 实例里，那肯定是有问题的。

**Comment by panjf2000** [comment]
还有，我现在怀疑是你机器的 TCP 全连接队列溢出了，`netstat -s | egrep "overflowed"`  查一下，然后设置一下 `/proc/sys/net/ipv4/tcp_abort_on_overflow` 为 1，再跑一下，如果客户端收到大量的 `connection reset by peer` 错误，那就说明的确是这个问题，你把 backlog 调大一点应该就能解决问题了。不过因为 gnet 的 backlog 参数没有暴露出来，所以你调大内核参数 `/proc/sys/net/core/somaxconn` 即可。

**Comment by Gitforxuyang** [comment]
好的。非常感谢。我去试试

**Comment by Gitforxuyang** [comment]
我有一个疑问，我的全连接队列虽然只有128，但是我服务器的cpu 内存的占比都很低，这种情况下新建的连接理论上应该是会被快速accept，是并不应该会造成堆积超过128这种情况吧？

**Comment by Gitforxuyang** [comment]
改了参数后我试了一天，确实没有再出现这个情况了。 非常感谢！

**Comment by Gitforxuyang** [comment]
我修改了配置还是发现有些连接没有被gnet接收到。我现在在你说的地方加了日志。 还会有其它地方会造成这种连接丢失的情况吗？

**Comment by Gitforxuyang** [comment]
对了，我们在业务使用中发现Tick方法在某种情况下会不再继续执行。   在一种未知的前提条件下，Tick方法会永远不再执行。

**Comment by Gitforxuyang** [comment]
最新。。。。 设置了/proc/sys/net/core/somaxconn后问题还是出现了。 Recv-Q再次发生堆积

**Comment by Gitforxuyang** [comment]
我在gnet里加了这样的日志，但是看日志情况是没有触发
![image](https://user-images.githubusercontent.com/16128584/106562549-69704600-6565-11eb-9db1-b346288a839e.png)

**Comment by Gitforxuyang** [comment]
我们的现象是大量连接会突然发生断开连接。 然后大量新连接重试就会发生Revc-Q的堆积。   
所以其实是有2个问题
1.为啥莫名其妙会大量连接断开连接
2.为什么大量新连接会不被gnet感知到，在系统层面造成Recv-Q堆积。。。

我想问其它使用者有使用到线上并发现有类似问题的吗？

**Comment by panjf2000** [comment]
> 我在gnet里加了这样的日志，但是看日志情况是没有触发
> ![image](https://user-images.githubusercontent.com/16128584/106562549-69704600-6565-11eb-9db1-b346288a839e.png)

那你把 Trigger 返回的 error 打印一下呢？是什么错误？

**Comment by panjf2000** [comment]
> 我们的现象是大量连接会突然发生断开连接。 然后大量新连接重试就会发生Revc-Q的堆积。
> 所以其实是有2个问题
> 1.为啥莫名其妙会大量连接断开连接
> 2.为什么大量新连接会不被gnet感知到，在系统层面造成Recv-Q堆积。。。
> 
> 我想问其它使用者有使用到线上并发现有类似问题的吗？

连接断开是什么错误？socket如果没有被加进 epoll 监听的话，的确有可能出现这种积压的情况。

还有一个可能，是不是服务端的数据也一直没有写回到客户端？
https://github.com/panjf2000/gnet/blob/2aee5a9ea2d86d2eabf2964be96cbf8ce643bc48/reactor_linux.go#L66-L68
你在这里也加一下 log，看看是不是一直进入这个 `case`，但是又没有进入 `if` 里面。

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/106745307-de25ac00-665b-11eb-9e28-51a43ba82ffc.png)
我们在打印更详细的日志后发现红色的部分会打印出来，err为nil。 但是黄色部分的日志都没有打印。  正常状态下他们都会执行的。

**Comment by panjf2000** [comment]
你把 https://github.com/panjf2000/gnet/blob/master/internal/netpoll/epoll.go#L86 这一行的 `if` 去掉呢？就不要判断 ==1 之后才去调用 `unix.Write()`，改成：
```go
p.asyncJobQueue.Push(job)
_, err = unix.Write(p.wfd, b)
```
看看能不能解决你的问题？
@Gitforxuyang

**Comment by panjf2000** [comment]
黄色部分的逻辑不是在当前 goroutine 里执行的，会被添加到一个异步队列，后面才去执行，你是搜索了全部的日志之后确认没有这部分日志对吧？

**Comment by panjf2000** [comment]
黄色部分的日志不可能都没有打印吧？应该是指丢失的那部分连接才没有打印，大多数情况下还是会打印的，不然整个服务根本跑不起来。

**Comment by Gitforxuyang** [comment]
@panjf2000  请求正常时黄色部分是打印的。  当问题出现时，我查了一些有问题的连接的打印链路。黄色部分就没有打印。

**Comment by Gitforxuyang** [comment]
我改一下试试。 

> 你把 https://github.com/panjf2000/gnet/blob/master/internal/netpoll/epoll.go#L86 这一行的 `if` 去掉呢？就不要判断 ==1 之后才去调用 `unix.Write()`，改成：
> 
> ```go
> p.asyncJobQueue.Push(job)
> _, err = unix.Write(p.wfd, b)
> ```
> 
> 看看能不能解决你的问题？
> @Gitforxuyang

我改一下试试

**Comment by Gitforxuyang** [comment]
_, err = unix.Write(p.wfd, b)

这一行代码在gnet中起到什么作用啊？

**Comment by panjf2000** [comment]
> _, err = unix.Write(p.wfd, b)
> 
> 这一行代码在gnet中起到什么作用啊？

这里就是一个利用 linux 的 eventfd 进行一个事件通知，每次 accept 新连接之后会把添加新连接进 epoll 监听队列的操作放到异步队列里，然后触发一个事件通知 event-loop 线程去执行这个操作，因为 event-loop 处理异步队列的时候是一次性执行完整个队列里的操作的，所以这里之前是做了一个优化：多次添加任务进异步队列只有第一次去触发一个事件，避免多余的系统调用。
现在你反馈的这个问题，我猜可能是因为这个优化，某些地方的问题导致任务添加进异步队列之后没有触发事件通知 event-loop 去处理。不过只是个猜测，你先修改一下试试能不能解决。

**Comment by panjf2000** [comment]
还有，你们的并发连接数一般是多大？丢失的连接又有多少？

**Comment by Gitforxuyang** [comment]
并发连接数不大。不过万而已。  当有大量请求（每秒新建过1000？）进入时，会有一定概率（百分比未知）发生这种丢连接的状况。   按道理按我们的量是不会有什么压力跟问题的。但是就是很奇怪。。。。

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/106978513-5e9cf780-6797-11eb-9591-516224df1034.png)
![image](https://user-images.githubusercontent.com/16128584/106978523-6197e800-6797-11eb-9d80-558fe40fc324.png)

我在这里加了日志，发现有大量的push之后不等于1的情况

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/106978885-24802580-6798-11eb-90f0-5d1a405723e4.png)
我能不能将这个异步的操作改成同步直接执行？  按我的理解改为同步后，也就是接收连接会变成串行、速度可能会不那么及时，其它的应该没有什么影响吧？

**Comment by panjf2000** [comment]
> ![image](https://user-images.githubusercontent.com/16128584/106978513-5e9cf780-6797-11eb-9591-516224df1034.png)
> ![image](https://user-images.githubusercontent.com/16128584/106978523-6197e800-6797-11eb-9d80-558fe40fc324.png)
> 
> 我在这里加了日志，发现有大量的push之后不等于1的情况

这里是 unix.Write() 有错误？不等于 1 是正常的，主要是这个 unix.Write() 不能有错误。

**Comment by panjf2000** [comment]
> ![image](https://user-images.githubusercontent.com/16128584/106978885-24802580-6798-11eb-90f0-5d1a405723e4.png)
> 我能不能将这个异步的操作改成同步直接执行？ 按我的理解改为同步后，也就是接收连接会变成串行、速度可能会不那么及时，其它的应该没有什么影响吧？

不可以，这里只能是异步。

**Comment by panjf2000** [comment]
你按我昨天说的改了吗？或者拉取最新的 master 代码更新一下，效果应该是一样的。

**Comment by Gitforxuyang** [comment]
unix.Write()没有返回错误。但是日志显示就是Trigger进入的job没有被执行。。我们现在就是想说绕开这个job的异步执行逻辑，直接改成同步执行，是不是就能解决问题。

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/106980454-2dbec180-679b-11eb-8fd2-abf3236177e1.png)
改了。

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/106983733-5ea1f500-67a1-11eb-8686-1f607793152c.png)
这个ForEach里面如果执行Jobs时出错，后续的job是不是就不会再被执行了？  如果这样，是不是就会出现job永远不被执行的情况。 跟我们的连接不被响应是不是就一致了？

**Comment by Gitforxuyang** [comment]
这是我们的日志。 
![image](https://user-images.githubusercontent.com/16128584/106983936-aaed3500-67a1-11eb-90aa-86d056019c9b.png)

**Comment by panjf2000** [comment]
这个问题已经解决了，更新到最新 master 就行。

**Comment by Gitforxuyang** [comment]
那这个错误是不是就有可能导致我们出现的接收连接的job永远不被执行的情况？

**Comment by panjf2000** [comment]
如果后续没有再调用 Trigger 的话，的确会导致剩下任务没有被执行。

**Comment by Gitforxuyang** [comment]
我枯了。。。。。

**Comment by panjf2000** [comment]
不过我之前不是让你更新到 master 去测试下吗？https://github.com/panjf2000/gnet/issues/179#issuecomment-770185904，那时候的 master 已经是修复这个问题了？你当时拉取最新代码了？

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/106986046-81360d00-67a5-11eb-9269-7cefddd45848.png)
我看了一下你的修改，是将报错后未执行的job重新扔回队列。 这样就有一个问题，这些重新扔回去的job要等到下一次触发forEach才能得到执行。为啥不直接在forEach的报错时打个错误日志就跳过，不影响后续的执行不就好了？ 
![image](https://user-images.githubusercontent.com/16128584/106986149-bd696d80-67a5-11eb-9232-623df6838e0c.png)
我们现在是这么改的，你觉得有什么问题吗？

**Comment by Gitforxuyang** [comment]
我们是v1.3.2的，没有更新版本

**Comment by panjf2000** [comment]
我之所以那么实现主要是考虑有时候错误是主动触发的，比如 ErrServerShutdown，还有就是一些错误发生后也要退出整个进程，比如 ErrAcceptSocket，所以就先返回，交给调用方去判断，这样能保持 queue.go 的纯粹性：一个通用的异步队列，如果要在 queue 里判断，还要耦合这些 error 类型的判断，所以主要是基于代码边界和纯粹性，还有实现上的优雅性，这些方面考虑的。

还有一个考虑是，一般异步任务不应该出错，一旦出错，大多是和网络或者系统相关的问题，后面的任务出错的概率也比较大，所以就先放回队列下次执行，不要阻塞当前的读写操作，保持 epoll 实例的活性。

不过你可以先临时这么改试试吧。

**Comment by Gitforxuyang** [comment]
好的。 我先改成不return吧。。。

**Comment by Gitforxuyang** [comment]
改了不return之后，我所有的连接的onopen方法都调用了。 但是还是会有recv-q堆积的情况，然后有些消息会延迟很多才能收到。感觉整个程序进入了僵死了一样。。。。

**Comment by Gitforxuyang** [comment]
![image](https://user-images.githubusercontent.com/16128584/107052112-3c8f8d80-6808-11eb-8764-5193b59fb5ef.png)
这个loopReadh函数是对当前触发了事件的所有文件句柄，一个个去读取他们的消息，然后串行处理。 如果中间有一个或多个用户发送的消息很多，在react处理时比较耗时，那么他后面的n个连接的消息就会阻塞在这儿。整个程序就会呈现出消息延迟的状态。 我的理解没错吧？

**Comment by Gitforxuyang** [comment]
gnet的SubReactor的Polling是不是不是很合理，如果有一个连接它有大量的收发数据，那么单它一个人的收发消耗就会很大。 会阻塞后面的其它用户的收发数据。 这样连接之间没有隔离，一个人造成全线雪崩的现象就会发生。 
是不是改成每个人的数据隔离，或者单个连接单次的处理有个 耗时/收发数据包大小 的限制会好一点？

**Comment by panjf2000** [comment]
> gnet的SubReactor的Polling是不是不是很合理，如果有一个连接它有大量的收发数据，那么单它一个人的收发消耗就会很大。 会阻塞后面的其它用户的收发数据。 这样连接之间没有隔离，一个人造成全线雪崩的现象就会发生。
> 是不是改成每个人的数据隔离，或者单个连接单次的处理有个 耗时/收发数据包大小 的限制会好一点？

不会发生"饿死"其他连接的状况，因为 loopRead 一次最多读 64KB 的数据，处理完了就处理下一个连接。

**Comment by Gitforxuyang** [comment]
我们在polling里加了耗时日志，发现有时候一次Polling会耗时超过500ms。 loopRead虽然一次只读64KB的数据，但是这64KB的数据可能包含了N次请求，那么这N次请求都会在这一次polling中执行完毕。 这样不就是阻塞?

**Comment by yxrobert** [comment]
net stat 不是时时准确的数据，换成ss命令试下

发自我的iPhone

**Comment by panjf2000** [comment]
> 我们在polling里加了耗时日志，发现有时候一次Polling会耗时超过500ms。 loopRead虽然一次只读64KB的数据，但是这64KB的数据可能包含了N次请求，那么这N次请求都会在这一次polling中执行完毕。 这样不就是阻塞?

缓冲区总要有个大小，I/O多路复用因为复用线程，就算每次只处理一次请求，一样会"阻塞"后面其他的请求，不要抬杠。

**Comment by Gitforxuyang** [comment]
> > 我们在polling里加了耗时日志，发现有时候一次Polling会耗时超过500ms。 loopRead虽然一次只读64KB的数据，但是这64KB的数据可能包含了N次请求，那么这N次请求都会在这一次polling中执行完毕。 这样不就是阻塞?
> 
> 缓冲区总要有个大小，I/O多路复用因为复用线程，就算每次只处理一次请求，一样会"阻塞"后面其他的请求，不要抠字眼和抬杠。

请不要误会，不是抬杠，是因为我们现在遇到了这种问题且急切的想解决这个问题。目前我们看起来的状况就是一次polling中执行的用时太长了，然后就会造成后续的请求全部延迟，然后继续延迟叠加，最后雪崩。 所以想给每个用户加一个资源限制，就算有个别用户行为异常，也可以将问题隔离在它自己身上，而不是因为一个用户影响所有用户。

**Comment by panjf2000** [comment]
如果你不想一次 loopRead 处理太多请求的话，目前是 64KB，可以修改一下这里的值：https://github.com/panjf2000/gnet/blob/v1.3.2/server_unix.go#L119，看看有没有效果吧，如果的确有这种类似的需求，我后面考虑把这个值的配置暴露出来，让用户自己设置。

**Comment by lesismal** [comment]
看下这里
https://github.com/panjf2000/gnet/blob/master/internal/netpoll/epoll.go#L104

试试这个改，把这几行

```golang
if n == 0 || (n < 0 && err == unix.EINTR) {
	msec = -1
	runtime.Gosched()
	continue
} else if err != nil {
	logging.DefaultLogger.Warnf("Error occurs in epoll: %v", os.NewSyscallError("epoll_wait", err))
	return err
}
msec = 0
```

改成

```golang
if err != nil && err != unix.EINTR {
	return err
}
```
看看有没有效果。我前阵子看到字节第二次分享他们的 KRPC，说是 msec 这里像当前这样用性能更高，但是我自己的网络库实测了下似乎会导致事件不被触发，并且性能也没见到提升。我只是在ubuntu虚拟机压测发现的这个问题，不确定是否所有环境都会有相同情况，楼主可以试试看
因为第一次看到字节分享他们内部RPC时，是有说因为go协程不是系统现成，亲和性、调度相关的性能损失不划算，并且可能导致cpu尖刺，所以字节的内核部门为他们的RPC专门打了补丁，所以我不确定是不是因为他们的内核补丁导致这样用法提高了性能

**Comment by lesismal** [comment]
另外，epoll的操作在相对较新的版本都是线程安全的，所以epoll事件的修改，应该是可以不使用trigger的方式的，直接在其他并行流调用就行，triger的方式虽然是传统，但带来一定的性能损失

**Comment by Gitforxuyang** [comment]
这个issues我先关掉吧，onOpened不调用的问题应该就是job执行的问题，你应该会在1.3.3上发布吧？  其它的目前看起来跟gnet本事并没有太大关系。

**Comment by panjf2000** [comment]
gnet v1.4.0 已经发布了，你可以更新到最新的版本试用。

**Comment by Gitforxuyang** [comment]
好的。非常感谢。
