### ISSUE TITLE
能添加一个websocket的示例代码吗

### ISSUE THREAD

**Issue by lchjczw** [panjf2000/gnet#18]

**Comment by panjf2000** [comment]
抱歉，`gnet` 是一个传输层的网络框架，应用层的开发得靠业务方自己开发，你可以参考一下这个项目：[ws](https://github.com/gobwas/ws)，或者看一下一些例子: https://github.com/golang-samples/websocket。

我现在主要在优化 `gnet` 的性能，没太多时间加更多应用层协议的示例代码，等后面有时间我再考虑多加几个吧。

**Comment by lchjczw** [comment]
OK，谢谢你提供的参考项目
