### ISSUE TITLE
OnOpened 事件函数没有应用编解码器

### ISSUE THREAD

**Issue by QbCheng** [panjf2000/gnet#180]
在 OnOpened 事件中.  out []byte 返回值 在发送数据时. 并没有通过注册的编码器进行编码. 和 React事件有点不一致.  

文档没有特殊说明。 容易导致新手出现问题.
不知道是不是有意这样做的.  希望能解答下

**Comment by panjf2000** [comment]
这里的确是这样，因为在 OnOpened 里返回数据给客户端一般来说只是一些简单的数据包，解析包不一定要和主逻辑上的编解码器一致。

**Comment by QbCheng** [comment]
这里可能出现这些问题

```go
// 假设. 我使用了编码器(LengthFieldBasedFrameCodec).
func (cs *codecServer) OnOpened(conn gnet.Conn) (out []byte, action gnet.Action) {
	fmt.Printf("服务器 接收到一个新的连接. 并且已经打开的回调. addr : %v  \n", conn.RemoteAddr())
	message := []byte("收到新的连接~~~")
	// 服务器 并未封包.
	// message, _ =  cs.codec.Encode(conn, message)
	return message, 0
}
```
意味着客户端方面需要对收到第一个包 和 服务器方面进行额外约定. 来解析第一个包. 
当客户端如果未和服务器方面 对一个包进行特殊约定. 还是按照通用的 编码解码器来解包. 则会导致错误. 因为读取包头时. 服务器端未设立包头. 长度是个不可控的值.
统一下操作. 感觉能减少歧义. 消耗应该也不会有太大的差别.

**Comment by panjf2000** [comment]
也有道理，这里我再思考下吧。

**Comment by panjf2000** [comment]
考虑了一下，`OnOpened` 这个事件函数一开始支持直接写回数据的初衷只是为了让服务端可以用一点数据通知到客户端连接已成功建立，所以也会发送几个字节的一个小数据包，没有必要去编解码，如果业务的编解码协议非常复杂的话，就有点得不偿失了，如果一定要应用编解码器在这个小包上的话，也可以调用 `c.AsyncWrite()` 方法，这个方法是会进行编码的。

另外，另一个理由是，如果修改了这部分，那就是 breaking change，会对用户更新 gnet 造成影响，所以我决定还是只修改 doc 说明一下，等到了 2.x 版本了可以再继续讨论这个有没有必要的修改理由，谢谢你提出了这个点。

谢谢你提出了这个点。@QbCheng
