### ISSUE TITLE
建议去掉TechEmpower测试结论

### ISSUE THREAD

**Issue by lesismal** [panjf2000/gnet#182]
**What is your question about gnet?**
Please describe your question meticulously.

用不完整的http功能测试代码跟其他完整http功能的框架对比性能是不合适的，抛开网络的4层部分，7层的部分只做了别人的 1/N，这样的测试容易误导，不够严谨

应该对标的是其他4层网络库或者标准库net包

除非把http支持得更完善，才应该用TechEmpower来修饰本库的性能

**Comment by panjf2000** [comment]
这里直接比较的确是不合适的，事实上我在加入这个排行榜的时候还专门发文章澄清过这个问题，明确指出过 `gnet` 的 HTTP 解析器是残缺的，所以在这方面占了便宜。

但是，首先第一点，techempower 这个排行榜现在名列前茅的那些库，很多都没有达到 in-production 标准，比如 ulib 也是和 gnet 一样的思路：残缺的 HTTP Parser，还有里面好几个 C/C++ 框架，实际上都不具备完整的 HTTP 解析功能，还有排名靠前的几个 java 框架，更是直接利用 JNI 搞成 java + native epoll，包括现在上面的 actix-raw 也是不完整的，事实上排名靠前的大多数都是基于这个测试做了针对性优化的，总之我想说就是现在这个榜单仅仅只能作为一种框架极致性能的参考，是不能作为生产级别参考的，技术选型还是要根据自己的业务需求。gnet 对标的的确是 go 的 net 库，我当初加入这个榜也仅仅只是想测试它的性能极限，但是没有找到基于第四层网络的相关的权威榜单，所以才放到 techempower 里。

第二，当初 gnet 加入这个测试榜单，合入代码的时候也是和 maintainer 讨论过以及最终取得同意的。

最后，谢谢你的提醒，但我决定暂时保留这个榜单。

**Comment by lesismal** [comment]
> 框架，实际上都不具备完整的 HTTP 解析功能，还有排名靠前的几个 java 框架，更是直接利用 JNI 搞成 java + native epoll，包括现在上面的 actix-raw 也是不完整的，事实上排名靠前的大多数都是基于这个测试做了针对性优化的，总之我想说就是现在这个榜单仅仅只能作为一种框架极致性能的参考，是不能作为生产级别参考的，技术选型还是要根据自己的业务需求。gnet 对标的的确是 go 的 net 库，我当初加入这个榜也仅仅只是想测试它的性能极限，但是没有找到基于第四层网络的相关的权威榜单，所以才放到 techempo

ok
