### ISSUE TITLE
建议实现 net.Conn

### ISSUE THREAD

**Issue by lesismal** [panjf2000/gnet#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lesismal** [comment]
抱歉之前在你的项目中提到我的项目，我只是执着于coding和交流，无意冒犯。

这两周又撸了个http parser来支持non-blocking http server，兼容标准库 http，实现net.Conn有较大便利，所以仍然建议 gnet 也实现 net.Conn

后续我还计划支持 websocket 和 http 2.0，之前魔改的tls虽然功能可用但我不太喜欢标准库的那份代码，所以也想有档期重写，都是体力活，希望能与开源的小伙伴多多交流

再请见谅，多多交流，good luck！

**Comment by lesismal** [comment]
兄弟，之前在你项目里提到我自己的项目，确实是抱歉、不够礼貌，但是我没有恶意，只是想多交流和回馈社区，请多多见谅！
nbio现在的tls/http 1.x/websocket支持已经比较完善了、并且基本兼容标准库，这些都是依赖于对 net.Conn 的实现，所以虽然关闭了这个issue，我还是建议 gnet 也考虑实现 net.Conn，会有更多便利去支持业务层的扩展

**Comment by lesismal** [comment]
fasthttp等项目开了个pool的好头，但是对于异步网络库高度定制内存管理等场景，不够通用。

标准库方案的那种一个连接一个协程，就单个连接而言，在内存管理、pool定制上比异步库更方便，buffer多是在单个协程内、处理完一个消息后才会进行下一轮ReadMessage，所以内存管理更可控，异步库内存生命周期管理起来比一个连接一个协程麻烦太多了。

简单定制的tcp、固定header 那种要省力得多，http/websocket解析起来太麻烦了，如果是慢连接，尤其是测试粘包时候一个字节一个字节发送，跨协程的buffer生命周期管理，2^N的方式大部分性能都消耗在内存的重复分配释放上了，反倒性能不好。所以最近把http/websocket的内存池改了，之前用的2^N对齐的buffer，换成无固定长度buffer的方式了，不保证一对一的分配和释放，只是尽量在各个协议层复用pool中的buffer

**Comment by panjf2000** [comment]
关于实现 `net.Conn` 标准接口，目前来看至少在 gnet 的 v1.x 版本中是不可能了，因为现在 `gnet.Conn` 已经和 `neg.Conn` 不兼容了，现在看来实现标准的 `net.Conn` 对 gnet 来说的确可能有潜在的好处，我会在 gnet 的下个主版本(v2.x)中实现。

**另外，对于你给 gnet 提的改进建议我个人表示感谢，做开源、技术交流和回馈社区都是好事情，我也很欢迎，但是做事还是得有一定的规则，不管是明面上的还是不成文的，开源社区也是有规则的，之前你在 gnet 的多个 issue 里推销自己的开源库，至少在我看来是非常没有分寸的行为，我倒是愿意去相信你当初并没有恶意，大家都是做技术的，我相信在这方面都还是比较纯粹的，至少在技术领域，我个人一般不会首先去揣度别人怀有恶意，还是更愿意相信技术人的纯粹，既然你现在也承认了自己的错误，这个事儿就算过去了，以后就不必再提了**。

做开源和回馈社区是好事，我个人也祝你顺利！

**Comment by lesismal** [comment]
多交流些吧，其他几个点或许也可以优化的

1. 定时器，虽然没必要epoll级的定时器，但自带一个、支持SetDeadline这些还是有必要
2. 我在nbio里epoll没有用trigger的方式，而是直接写，写失败才去addWrite、等待可写flush。这样的好处是减少了一些trigger的syscall，而且直接写时的buffer不跨协程，多数时候写是成功的、这个buffer不需要拷贝、缓存
3. 对于ringbuffer，我觉得其实带来的好处可能不影响，单个Conn读写的并发竞争很少、几乎可以忽略不计，无竞争时mutex也只是简单atomic一下而且内联的: https://github.com/golang/go/blob/master/src/sync/mutex.go#L74 ，当然，用了稳定、内存可控也ok
4. 协程池，ants跟当前版本的go相比好像没有优势，或者跟一些其他的协程池比，性能要慢一些，这个可以确认下是否需要继续优化

**Comment by lesismal** [comment]
> **另外，对于你给 gnet 提的改进建议我个人表示感谢，做开源、技术交流和回馈社区都是好事情，我也很欢迎，但是做事还是得有一定的规则，不管是明面上的还是不成文的，开源社区也是有规则的，之前你在 gnet 的多个 issue 里推销自己的开源库，至少在我看来是非常没有分寸的行为，我倒是愿意去相信你当初并没有恶意，大家都是做技术的，我相信在这方面都还是比较纯粹的，至少在技术领域，我个人一般不会首先去揣度别人怀有恶意，还是更愿意相信技术人的纯粹，既然你现在也承认了自己的错误，这个事儿就算过去了，以后就不必再提了**。

我这个人不擅长礼貌，聊到技术来电了就不考虑太多，确实不妥，但是过后反思，也知道不妥。
但是性格是比较难改的，而且我出发点相对比较单纯，我自己的主业已经不是写代码，闲了写nbio这些也基本是纯为爱发电，兴致来了肝几夜。所以我是喜欢更纯的技术氛围之类的、大家都可以畅所欲言。
github或者说技术社区、圈子有些风气其实也是不太好的，彼此照顾面子倒还好，太多小白开发者不懂技术乱起哄，有的问题讨论，小白乱支持让错误的观点反倒被抬高。
最近两三年，在不少群里闲了“审稿”，也得罪了一些人，最近也去给这几个知名项目说过异步网络库的问题：
https://github.com/eranyanay/1m-go-websockets
https://github.comgobwas/ws
https://github.com/gorilla/websocket
但1m-go-websockets的作者甚至都没意识到有问题，gobwas/ws的作者我估计是能懂问题但故意搪塞、直接close了。之前在你这说到我自己项目我知道不好，所以刚开始没打算在他们那说，但是解释了很多，甚至没人肯承认他们自己的问题
搞技术的事情、尤其是开源社区却不能坦坦荡荡地聊这些问题、承认和改进问题，也是很郁闷，或许我的沟通方式是真的不好，但确实难改，而且如果让我直接去PR他们的项目，也实在是需要改太多、浪费自己时间

**Comment by lesismal** [comment]
现在的技术圈子也太浮躁了，太多逻辑程序员，不像十几年前，论坛里聊技术，遇到好玩的问题，大家可以争论得你死我活、面红耳赤，但是争论过后问题搞清楚了，皆大欢喜、大伙感情更进一步
那时候还没有github，也没有现在这么多的流量经济，也没有现今这么庞大的程序员群体，没有这么浮躁的技术社区和迅速迭代的各种技术栈，很多程序问题都可以聊到哲学高度或者至少工程哲学的高度，可能比现在有趣多了

**Comment by lesismal** [comment]
单就网络库性能，nbio压测数据跟gnet差不多，多测几轮可能由于系统波动互有高低上下差不了百分之几，但nbio实现了net.Conn、使用方式可能更方便，tls/http 1x/websocket支持比较完善了，而且也是使用起来方便。最近对tls/http/websocket和nbio.Conn整个流程的内存池也做了较多的优化、基本打通1对1的分配释放，内存和性能都更稳定平衡了。

早期计划还有支持http 2.0，但http2.0做资源服务器不友好，做动态协议交互也不如websocket更方便，所以不打算做了

**Comment by lesismal** [comment]
最近字节的异步网络库和RPC也开源出来了：
https://github.com/cloudwego/netpoll

去年和今年各看到过他们的文章介绍，说是优化了很多、性能非常强，他们文档里benchmark的图展示的数据要比gnet高出一截，但是我简单跑了下压测，性能应该只能算一般、比gnet要低很多，不知道你有没有关注到
我不确定自己写的他们这个网络库的echo server的代码是否准确，有兴趣的话也去瞧瞧？

**Comment by panjf2000** [comment]
字节跳动的 netpoll 没开源之前他们团队就发过文章介绍过，我也是这两天才知道已经开源了，昨天粗略地扫了一下源码，架构方面就不用说了，还是经典的 reactor 模型，第一印象里主要的优化点就是号称 zero copy 的 linked buffer 以及 epoll 方面抛弃 Go 封装好的 sys/unix 包，自己改造 epoll_event 支持保存用户数据的指针，然后裸调 epoll 的 API，不需要通过 fd 找 conn，还有就是支持了像 `MSG_ZEROCOPY` 这样的零拷贝技术。

Linked buffer 虽然号称 zero copy，但是在数据包跨 node 的情况下一样需要拷贝拼接，大概只对网络小包的场景比较友好，还有就是封装的功能更多了吧；至于 epoll 调用的优化部分，由于需要使用 `unsafe.Pointer` 传入用户态指针入内核，由于 Go 的 GC 存在，会有潜在的内存问题而且 Go 编译器会检测这一类万能指针误用的问题，很难编译通过，编译过了也可能会在运行时出问题，这一块我很早之前也曾尝试过和他们一样的实现，做了一版代码，但是因为上述原因最终没有合入主干，不过最近又重新开始搞这一块。

至于说性能压测的结果，他们自己也说了，netpoll 主要是为了 RPC 场景构建和优化的，gnet 这一类框架考虑的场景更像 redis server、haproxy 这些，而且他们的 benchmark code 也还没放出来，我个人其实不太在意他们那个压测结果，因为 netpoll 的基本架构和 gnet 是一样的，但是加了更多复杂的逻辑和功能，netpoll 虽然做了不少优化，但是对比 gnet 还是比较重的，gnet 更加轻量，因此 netpoll 不太可能性能比 gnet 高出这么多，等他们把测试代码放出来再看看吧。

**Comment by panjf2000** [comment]
> > **另外，对于你给 gnet 提的改进建议我个人表示感谢，做开源、技术交流和回馈社区都是好事情，我也很欢迎，但是做事还是得有一定的规则，不管是明面上的还是不成文的，开源社区也是有规则的，之前你在 gnet 的多个 issue 里推销自己的开源库，至少在我看来是非常没有分寸的行为，我倒是愿意去相信你当初并没有恶意，大家都是做技术的，我相信在这方面都还是比较纯粹的，至少在技术领域，我个人一般不会首先去揣度别人怀有恶意，还是更愿意相信技术人的纯粹，既然你现在也承认了自己的错误，这个事儿就算过去了，以后就不必再提了**。
> 
> 我这个人不擅长礼貌，聊到技术来电了就不考虑太多，确实不妥，但是过后反思，也知道不妥。
> 但是性格是比较难改的，而且我出发点相对比较单纯，我自己的主业已经不是写代码，闲了写nbio这些也基本是纯为爱发电，兴致来了肝几夜。所以我是喜欢更纯的技术氛围之类的、大家都可以畅所欲言。
> github或者说技术社区、圈子有些风气其实也是不太好的，彼此照顾面子倒还好，太多小白开发者不懂技术乱起哄，有的问题讨论，小白乱支持让错误的观点反倒被抬高。
> 最近两三年，在不少群里闲了“审稿”，也得罪了一些人，最近也去给这几个知名项目说过异步网络库的问题：
> https://github.com/eranyanay/1m-go-websockets
> https://github.comgobwas/ws
> https://github.com/gorilla/websocket
> 但1m-go-websockets的作者甚至都没意识到他的方案有问题，gobwas/ws的作者我估计是能懂问题但是短期无力解决所以故意搪塞、直接close了，因为我已经给他解释了好几轮了。之前在你这说到我自己项目我知道不好，所以刚开始没打算在他们那说，但是解释了很多，甚至没人肯承认他们自己的问题，很无奈。很多不明所以的用户，用了他们的方案，就面临着服务慢、甚至服务不可用的风险
> 搞技术的事情、尤其是开源社区却不能坦坦荡荡地聊这些问题、承认和改进问题，也是很郁闷，或许我的沟通方式是真的不好，但确实难改，而且如果让我直接去PR他们的项目，也实在是需要改太多、浪费自己时间

既然说到这里了，我就再多嘴两句，我猜你大概是那种比较典型的技术人了，涉及到技术话题可能就比较投入，这一点其实没问题，技术就该是纯粹的，就事论事。

但是我认为技术是纯粹和理性的，但是做技术的人则未必，每个人都会有自己的情感和脾性，所以技术交流的时候技术固然是最重要的，但是交流的方式和态度也非常重要；我做开源也有一段时间了，也碰到过一些上来一副颐指气使的态度的人，上来就一副大爷模样，态度恶劣地说你这个东西哪里哪里差，或者是直接就开喷说你这东西没什么了不起的，或者是过来碰瓷儿的，我个人也自认为是一个脾气好的人而且在技术方面能做到就事论事，但就像我之前说的，做任何事都需要有规则和方式，如果是这种态度，那么就算是他说的是对的，我一样不买账，骂回去都算是轻的。

所以，我相信你是一个有技术热情的人，而且也欣赏这种热情，但我的建议还是说技术交流理当是纯粹的，但是规则和方式不能就此抛弃，只是一点点个人的建议，我也不是想对你说教什么，毕竟我俩也只是萍水相逢，我只是个人感觉还是挺有用的，不管是在工作上的还是社区中的技术交流，希望你一切顺利！

**Comment by lesismal** [comment]
> 字节跳动的 netpoll 没开源之前他们团队就发过文章介绍过，我也是这两天才知道已经开源了，昨天粗略地扫了一下源码，架构方面就不用说了，还是经典的 reactor 模型，第一印象里主要的优化点就是号称 zero copy 的 linked buffer 以及 epoll 方面抛弃 Go 封装好的 sys/unix 包，自己改造 epoll_event 支持保存用户数据的指针，然后裸调 epoll 的 API，不需要通过 fd 找 conn，还有就是支持了像 `MSG_ZEROCOPY` 这样的零拷贝技术。
> 
> Linked buffer 虽然号称 zero copy，但是在数据包跨 node 的情况下一样需要拷贝拼接，大概只对网络小包的场景比较友好，还有就是封装的功能更多了吧；至于 epoll 调用的优化部分，由于需要使用 `unsafe.Pointer` 传入用户态指针入内核，由于 Go 的 GC 存在，会有潜在的内存问题而且 Go 编译器会检测这一类万能指针误用的问题，很难编译通过，编译过了也可能会在运行时出问题，这一块我很早之前也曾尝试过和他们一样的实现，做了一版代码，但是因为上述原因最终没有合入主干，不过最近又重新开始搞这一块。
> 
> 至于说性能压测的结果，他们自己也说了，netpoll 主要是为了 RPC 场景构建和优化的，gnet 这一类框架考虑的场景更像 redis server、haproxy 这些，而且他们的 benchmark code 也还没放出来，我个人其实不太在意他们那个压测结果，因为 netpoll 的基本架构和 gnet 是一样的，但是加了更多复杂的逻辑和功能，netpoll 虽然做了不少优化，但是对比 gnet 还是比较重的，gnet 更加轻量，因此 netpoll 不太可能性能比 gnet 高出这么多，等他们把测试代码放出来再看看吧。

`MSG_ZEROCOPY` 大包友好，但是通用场景未必划算，所以没太大必要支持。
昨天晚上开始简单跑他们的测试，感觉不太对，给他们开了几个issue，然后review了一点代码，单凭下面这一句，从我的角度够给 netpoll 判死刑了：
https://github.com/cloudwego/netpoll/blob/main/connection_impl.go#L327

issue 13 有描述，而且关键不是实际场景中这里是不是会频繁触发，而是这样设计就说明不是奔着纯异步库来的，给应用层提供了 Peek Next 这些方法、每个都暴露出触发这种情况的可能性，如果 Peek Next 的 size 不当，慢连接就会占用协程。

还有像这种地方：
https://github.com/cloudwego/netpoll/blob/main/connection_reactor.go#L135

异步库要解决的主要问题是协程数量巨大所带来的巨大内存和调度消耗，他们的这些设计，可能并不是真正解决了问题，而只是运气好的时候解决了问题。

那个LinkBuffer的实现也是有点虐心，zero copy这算偷换概念了，通常是内核和应用层这样说。勉强认同他们框架和业务之间也这样叫吧，但是单就数据收发来讲，nbio的 OnData 中收到的数据也可以用来直接回写，我上面说过，nbio.Conn是直接写，不跨协程，所以直接写也相当于zero copy，写失败nbio.Conn会copy缓存等待flush。而且LinkBuffer的用法、尤其是zero copy继承，应用层太不友好了，这是又要写c/c++感觉
而且治愈LinkBuffer节约内存、高性能，至少我跑30s压测，他内存就2-3G了，不确定我的测试代码错误还是他们实现有bug，也是需要等他们放出来完整的benchmark用例

**Comment by lesismal** [comment]
> 自己的情感和脾性，所以技术交流的时候技术固然是最重要的，但是交流的方式和态度也非常重要；我做开源也有一段时间了，也碰到过一些上来一副颐指气使的态度的人，上来就一副大爷模样，态度恶劣地说你这个东西哪里哪里差，或者是直接就开喷说你这东西没什么了不起的，或者是过来碰瓷儿的，我个人也自认为是一个脾气好的人而且在技术方面能做到就事论事，但就像我之前说的，做任何事都需要有规则和方式，如果是这种态度，那么就算是他说的是对的，我一样不买账，骂回去都算是轻的。
> 
> 所以，我相信你是一个有技术热情的人，而且也欣赏这种热情，但我的建议

你说得很对，尤其是开源社区，人和人之间具有相对平等的交流自由权，开源还得考虑说话技巧，即使linus暴脾气都要被社区反对甚至制裁
所以这么一琢磨，公司里上班虽然存在各种条条框框、不自由，但却有它的好，公司团队内的技术研判，直接技术压制决定话语权就可以了，单纯省力

我还是要努力改改交流方式

**Comment by lesismal** [comment]
我以前所在的团队的研发节奏太快，技术氛围也更浓些，大家沟通也简单粗暴，方案直接互相喷到清楚，大家不会因为喷得狠而伤感情，所以做事非常高效，这么多年习惯了这种方式，再到开源社区沟通，我这种就不恰当了，应该算是我的一种职业病了:joy:

**Comment by panjf2000** [comment]
> > 字节跳动的 netpoll 没开源之前他们团队就发过文章介绍过，我也是这两天才知道已经开源了，昨天粗略地扫了一下源码，架构方面就不用说了，还是经典的 reactor 模型，第一印象里主要的优化点就是号称 zero copy 的 linked buffer 以及 epoll 方面抛弃 Go 封装好的 sys/unix 包，自己改造 epoll_event 支持保存用户数据的指针，然后裸调 epoll 的 API，不需要通过 fd 找 conn，还有就是支持了像 `MSG_ZEROCOPY` 这样的零拷贝技术。
> > Linked buffer 虽然号称 zero copy，但是在数据包跨 node 的情况下一样需要拷贝拼接，大概只对网络小包的场景比较友好，还有就是封装的功能更多了吧；至于 epoll 调用的优化部分，由于需要使用 `unsafe.Pointer` 传入用户态指针入内核，由于 Go 的 GC 存在，会有潜在的内存问题而且 Go 编译器会检测这一类万能指针误用的问题，很难编译通过，编译过了也可能会在运行时出问题，这一块我很早之前也曾尝试过和他们一样的实现，做了一版代码，但是因为上述原因最终没有合入主干，不过最近又重新开始搞这一块。
> > 至于说性能压测的结果，他们自己也说了，netpoll 主要是为了 RPC 场景构建和优化的，gnet 这一类框架考虑的场景更像 redis server、haproxy 这些，而且他们的 benchmark code 也还没放出来，我个人其实不太在意他们那个压测结果，因为 netpoll 的基本架构和 gnet 是一样的，但是加了更多复杂的逻辑和功能，netpoll 虽然做了不少优化，但是对比 gnet 还是比较重的，gnet 更加轻量，因此 netpoll 不太可能性能比 gnet 高出这么多，等他们把测试代码放出来再看看吧。
> 
> `MSG_ZEROCOPY` 大包友好，但是通用场景未必划算，所以没太大必要支持。
> 昨天晚上开始简单跑他们的测试，感觉不太对，给他们开了几个issue，然后review了一点代码，单凭下面这一句，从我的角度够给 netpoll 判死刑了：
> https://github.com/cloudwego/netpoll/blob/main/connection_impl.go#L327
> 
> issue 13 有描述，而且关键不是实际场景中这里是不是会频繁触发，而是这样设计就说明不是奔着纯异步库来的，给应用层提供了 Peek Next 这些方法、每个都暴露出触发这种情况的可能性，如果 Peek Next 的 size 不当，慢连接就会占用协程。
> 
> 还有像这种地方：
> https://github.com/cloudwego/netpoll/blob/main/connection_reactor.go#L135
> 
> 异步库要解决的主要问题是协程数量巨大所带来的巨大内存和调度消耗，他们的这些设计，可能并不是真正解决了问题，而只是运气好的时候解决了问题。
> 
> 那个LinkBuffer的实现也是有点虐心，zero copy这算偷换概念了，通常是内核和应用层这样说。勉强认同他们框架和业务之间也这样叫吧，但是单就数据收发来讲，nbio的 OnData 中收到的数据也可以用来直接回写，我上面说过，nbio.Conn是直接写，不跨协程，所以直接写也相当于zero copy，写失败nbio.Conn会copy缓存等待flush。而且LinkBuffer的用法、尤其是zero copy继承，应用层太不友好了，这是又要写c/c++感觉
> 而且治愈LinkBuffer节约内存、高性能，至少我跑30s压测，他内存就2-3G了，不确定我的测试代码错误还是他们实现有bug，也是需要等他们放出来完整的benchmark用例

嗯，他们的 linked buffer 的 zero copy 就是说的框架和业务之间，以前看他们团队的文章介绍 netpoll 我就是这么想的，这一点其实有点过度 PR 的嫌疑，因为如果这是这个定义其实不难实现。至于使用成本你也说的不错，linked buffer 功能看起来丰富，但这算优势也算劣势，使用成本高的话也有可能劝退一些人。

至于 `MSG_ZEROCOPY `，其实最核心的还不是大包小包的问题，主要还是调用 sendmsg 之后用户内存不能立刻释放或者复用，因为这个 zero copy 接口是异步写，数据不会立刻被读取并写到网络，需要等内核发送出去之后通知用户，才能释放内存，所以不太好支持，所以现在 netpoll 虽然通过 `MSG_ZEROCOPY` 可能避免了一些拷贝，但是又多监听了一个 MSG_ERRQUEUE，相当于每次写数据都需要多一次系统调用，也不知道到底划不划算。

**Comment by panjf2000** [comment]
> > 自己的情感和脾性，所以技术交流的时候技术固然是最重要的，但是交流的方式和态度也非常重要；我做开源也有一段时间了，也碰到过一些上来一副颐指气使的态度的人，上来就一副大爷模样，态度恶劣地说你这个东西哪里哪里差，或者是直接就开喷说你这东西没什么了不起的，或者是过来碰瓷儿的，我个人也自认为是一个脾气好的人而且在技术方面能做到就事论事，但就像我之前说的，做任何事都需要有规则和方式，如果是这种态度，那么就算是他说的是对的，我一样不买账，骂回去都算是轻的。
> > 所以，我相信你是一个有技术热情的人，而且也欣赏这种热情，但我的建议
> 
> 你说得很对，尤其是开源社区，人和人之间具有相对平等的交流自由权，开源还得考虑说话技巧，即使linus暴脾气都要被社区反对甚至制裁
> 所以这么一琢磨，公司里上班虽然存在各种条条框框、不自由，但却有它的好，公司团队内的技术研判，直接技术压制决定话语权就可以了，单纯省力
> 
> 我还是要努力改改交流方式

我觉得其实也不用强迫自己去做什么大改变，毕竟性格这种东西基本都定了，讨论问题的时候有分歧和争论，这再正常不过了，我认为除非对面沟通的那个人是个混蛋，否则的话每个人沟通的时候态度不要恶劣，不咄咄逼人，不要让对方下不来台就够了，能做到这几点就完全 OK 了。

**Comment by lesismal** [comment]
> 至于 `MSG_ZEROCOPY `，其实最核心的还不是大包小包的问题，主要还是调用 sendmsg 之后用户内存不能立刻释放或者复用，因为这个 zero copy 接口是异步写，数据不会立刻被读取并写到网络，需要等内核发送出去之后通知用户，才能释放内存，所以不太好支持，所以现在 netpoll 虽然通过 `MSG_ZEROCOPY` 可能避免了一些拷贝，但是又多监听了一个 MSG_ERRQUEUE，相当于每次写数据都需要多一次系统调用，也不知道到底划不划算。

小包的映射、锁等操作，可能比copy更费事，而且框架层实现`MSG_ZEROCOPY`又需要两步，所以通用场景，这个性能未必划算。除非是确定全大包场景定制

**Comment by lesismal** [comment]
> 我觉得其实也不用强迫自己去做什么大改变，毕竟性格这种东西基本都定了，讨论问题的时候有分歧和争论，这再正常不过了，我认为除非对面沟通的那个人是个混蛋，否则的话每个人沟通的时候态度不要恶劣，不咄咄逼人，不要让对方下不来台就够了，能做到这几点就完全 OK 了。

最难的地方在于，即使自己没想咄咄逼人，但如果面对的人根本get不到问题的点，就需要去解释更多，解释得越多，越会被认为咄咄逼人，但其实只是想把事情的解释清楚
换位想一下，如果是我自己面对更高层次的大牛，也一样会有类似的心理体验

或许减少这种交流、不去管这些闲事算是个方法吧

**Comment by lesismal** [comment]
nbio发了个新版本，HTTP client，Websocket dialer/client 也都支持了。tls/http1.x/websocket c/s都通畅了，HTTP client应该比标准库性能高比较多，我后面再多测测。因为是异步，不好做更完善的参数支持比如MaxIdleConns、MaxIdleConnsPerHost，够用了，反正也都是需要应用层保证。

**Comment by hellodudu** [comment]
> 关于实现 `net.Conn` 标准接口，目前来看至少在 gnet 的 v1.x 版本中是不可能了，因为现在 `gnet.Conn` 已经和 `net.Conn` 不兼容了，现在看来实现标准的 `net.Conn` 对 gnet 来说的确可能有潜在的好处，我会在 gnet 的下个主版本(v2.x)中实现。
> 
> **另外，对于你给 gnet 提的改进建议我个人表示感谢，做开源、技术交流和回馈社区都是好事情，我也很欢迎，但是做事还是得有一定的规则，不管是明面上的还是不成文的，开源社区也是有规则的，之前你在 gnet 的多个 issue 里推销自己的开源库，至少在我看来是非常没有分寸的行为，我倒是愿意去相信你当初并没有恶意，大家都是做技术的，我相信在这方面都还是比较纯粹的，至少在技术领域，我个人一般不会首先去揣度别人怀有恶意，还是更愿意相信技术人的纯粹，既然你现在也承认了自己的错误，这个事儿就算过去了，以后就不必再提了**。
> 
> 做开源和回馈社区是好事，我个人也祝你顺利！

gnet用户之一，确实非常希望能够实现net.Conn。期待v2版本
