### ISSUE TITLE
如何获取客户端连接描述符

### ISSUE THREAD

**Issue by cham-pin** [panjf2000/gnet#186]
接口中缺少获取连接描述符的方法, 导致多个客户端无法区分

**Comment by panjf2000** [comment]
区分客户端连接用 `RemoteAddr()` 就行了。

**Comment by cham-pin** [comment]
可我通过打印发现RemoteAddr()没内容
我在gnet.Conn添加了Fd()方法， 并在connect_unix.go中实现了它， 解决了问题


RemoteAddr方法明天我再看看， 多谢指导
| |
chenbin200818
|
|
chenbin200818@126.com
|
签名由网易邮箱大师定制
在2021年2月23日 22:26，Andy Pan<notifications@github.com> 写道：

区分客户端连接用 RemoteAddr() 就行了。

**Comment by panjf2000** [comment]
`c.RemoteAddr()` 返回为空确认了吗？TCP 协议下？

**Comment by cham-pin** [comment]
客户端与服务端在同一台服务器, 采用unix域通信, 返回 @


| |
chenbin200818
|
|
chenbin200818@126.com
|
签名由网易邮箱大师定制
在2021年2月26日 22:11，Andy Pan<notifications@github.com> 写道：

c.RemoteAddr() 返回为空确认了吗？TCP 协议下？

**Comment by zhuiyi9009** [comment]
区分客户端，可以用SetContext(ctx interface{}) 来定制业务吧
