### ISSUE TITLE
How to implement IP blacklist？

### ISSUE THREAD

**Issue by vvhh2002** [panjf2000/gnet#187]
**What is your question about gnet?**
How to implement IP blacklist？
I want to ban specific IP connections

**Comment by panjf2000** [comment]
You can do that via iptables: https://www.e2enetworks.com/help/knowledge-base/how-to-block-ip-address-on-linux-server/

If you must do it in gnet, use `c.RemoteAddr()` to get the client's address and block it.

**Comment by jonsen** [comment]
I 

> **What is your question about gnet?**
> How to implement IP blacklist？
> I want to ban specific IP connections

I did like this:

```go
var (
        clientBlock   = sync.Map{}
)

func init() {
    clientBlock.Store(`10.10.0.1`, 0)
}

func (cs *server) OnOpened(c gnet.Conn) (out []byte, action gnet.Action) {
    ip, port, err := net.SplitHostPort(c.RemoteAddr().String())
    if err != nil {
        log.Error(err)
        action = gnet.Close
        return
    }

    num, ok := clientBlock.Load(ip)
    if ok {
        action = gnet.Close
        clientBlock.Store(ip, num.(int)+1)
        return
    }

    // ...
}
```

**Comment by panjf2000** [comment]
So are there any questions?
