### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jingchuang** [panjf2000/gnet#19]
# github.com/panjf2000/gnet
..\..\go\pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:129:4: undefined: sniffError
..\..\go\pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:159:14: too many arguments in call to serve
	have (Events, []*listener, bool)
	want (Events, []*listener)

**Comment by panjf2000** [comment]
@jingchuang 
Windows 里用的是 IOCP，它是异步的，和同步的 epoll 还是有一点区别，如果要支持 Windows 的话可能会有一些兼容的修改，而且说实话我对 Windows 下的网络编程和 IOCP 都不甚了解，还在调研学习中。

`gnet` 未来可能会支持 Windows，但是我近期可能还没时间精力和足够的知识储备做，
可以持续关注 `gnet`，或者欢迎 Windows 网络编程和 IOCP 的高手给我提 PR 😁，另外，你下载的 `gnet` 版本太老了，现在已经更新到 v1.0.0-beta.3 了，如果要试用，可以下载这个版本，感谢对 `gnet` 的关注😀

**Comment by jingchuang** [comment]
thanks, How to get the latest version of your package in mod mode?
I use mod mode, the version that is automatically pulled down is v0.1.3

**Comment by jingchuang** [comment]
> @jingchuang
> Windows 里用的是 IOCP，它是异步的，和同步的 epoll 还是有一点区别，如果要支持 Windows 的话可能会有一些兼容的修改，而且说实话我对 Windows 下的网络编程和 IOCP 都不甚了解，还在调研学习中。
> 
> `gnet` 未来可能会支持 Windows，但是我近期可能还没时间精力和足够的知识储备做，
> 可以持续关注 `gnet`，或者欢迎 Windows 网络编程和 IOCP 的高手给我提 PR 😁，另外，你下载的 `gnet` 版本太老了，现在已经更新到 v1.0.0-beta.3 了，如果要试用，可以下载这个版本，感谢对 `gnet` 的关注😀

thanks, How to get the latest version of your package in mod mode?
I use mod mode, the version that is automatically pulled down is v0.1.3

**Comment by panjf2000** [comment]
@jingchuang 
一般来说，在目录下执行 `go get -u github.com/panjf2000/gnet` 之后，go.mod 应该会自动更新到最新的 release，如果没有的话，那就直接用 `go mod edit` 编辑 go.mod，手动把版本改成最新版本（当前是v1.0.0-rc.3），然后 `go mod tidy` 应该就行了。

**Comment by jingchuang** [comment]
> @jingchuang
> 一般来说，在目录下执行 `go get -u github.com/panjf2000/gnet` 之后，go.mod 应该会自动更新到最新的 release，如果没有的话，那就直接用 `go mod edit` 编辑 go.mod，手动把版本改成最新版本（当前是v1.0.0-rc.3），然后 `go mod tidy` 应该就行了。

i konw how to pull latest version, with eg:
require github.com/panjf2000/gnet master,

Can you add windows std usage? Like evio std, because I can debug directly on windows pc, and finally run in linux docker, I prefer to be in windows coding. thanks
