### ISSUE TITLE
关于连接消息接收和onOpen方法调用顺序问题

### ISSUE THREAD

**Issue by Gitforxuyang** [panjf2000/gnet#191]
go-version: 1.13  os: linux  gnet-version: 1.4.1

你好，我们在onOpen中去初始化连接的基本配置，但是在处理消息的时候发现有的时候会有基本配置没有被初始化的情况，查看代码之后感觉这一块有问题。代码如下：

![image](https://user-images.githubusercontent.com/16128584/111126403-a0e30100-85ad-11eb-8807-c31e987c52fb.png)

我想问一下按照现在的代码，消息的接收有可能会在onOpen方法之前被执行吧？

**Comment by panjf2000** [comment]
你是说有时候 React() 比 OnOpened() 先调用？这个基本不可能，上面的代码也没有问题。

**Comment by Gitforxuyang** [comment]
我在React中打印，发现有些conn的RemoteAddr()返回值为nil。为什么会有这种情况?

**Comment by panjf2000** [comment]
> mainLoop跟eventLoops是两个协程，上面的代码先addRead，此时eventLoops就可以在循环中读取到这个连接的消息了，而onOpen还没有被调用。 会不会这样执行取决于服务器的调度，在代码层面理论上是可能的吧?

你的理解是错误的，el.poller.Trigger 方法会把待执行的函数通过 epoll 发到 event-loop 的 goroutine 里去执行，不是在 main-loop 这里执行的。

**Comment by panjf2000** [comment]
> 我在React中打印，发现有些conn的RemoteAddr()返回值为nil。为什么会有这种情况?

TCP 连接吗？

**Comment by Gitforxuyang** [comment]
我加了些日志，初步判断是因为我们在React里异步去执行造成的。   按照同步打印没有出现这种情况。   这个问题我先close吧，如果后期再发现这种情况，我再打开
