### ISSUE TITLE
请问gnet需要修改linux内核参数来提高连接数限制吗？

### ISSUE THREAD

**Issue by hjes** [panjf2000/gnet#192]
请问gnet需要修改linux内核参数来提高连接数限制吗？
目前默认的是1024 openfiles 需要修改吗？

**Comment by panjf2000** [comment]
根据你的业务场景调整，如果是需要建立大量连接的话则可以考虑调高一下参数，不过最好还是实际测试一下你们业务的连接数高峰是多少再决定。

**Comment by hjes** [comment]
感谢。大于1024链接，还是修改了内核参数，可以关闭了
