### ISSUE TITLE
有待测试，不知道在各种苛刻的条件下，能否稳定运行

### ISSUE THREAD

**Issue by felix0080** [panjf2000/gnet#2]

**Comment by panjf2000** [comment]
欢迎试用，反馈问题~~😋

**Comment by choleraehyq** [comment]
目前这个库是用在什么地方的？之前踩 ants 的坑踩的有点多

**Comment by panjf2000** [comment]
老哥，不用对我这么没信心吧😓。
其实就是个TCP/UDP网络框架，需要开发网络应用的地方都可以用的，不过针对一些总连接量大而活跃连接少的场景可能会有更好的表现，用reactor模式就是为了用极少量的goroutines管理大量连接嘛，相比较标准的net包那种一条连接一个goroutine的模式，也能节省不少资源。

**Comment by choleraehyq** [comment]
@panjf2000 老哥我也不是针对你，一个库在没有上过线上服务之前，大家肯定是会持保留态度的呀，更何况是网络库这种偏底层的库。这个库是公司里在用，还是纯粹的个人项目呢。

**Comment by panjf2000** [comment]
个人业余项目啦，目前没有线上业务在用，而且说实话现在我也不推荐在线上用这个，因为我还没release出一个稳定的版本呢，现在我还在疯狂迭代。。。
