### ISSUE TITLE
Only binding to IPv4 addresses on Linux

### ISSUE THREAD

**Issue by OrfeasZ** [panjf2000/gnet#201]
The documentation states that scheme prefixes `udp` and `tcp` will result in the server listening on both IPv4 and IPv6 addresses, and while that works on Windows, it doesn't seem to be the case on Linux.

For example, doing this:

```go
net.Serve(listener, "udp://:1234",
	gnet.WithMulticore(true),
	gnet.WithReusePort(true),
)
```

We would expect the server to listen on all interfaces and all available addresses (both v4 and v6), but on Linux a netstat indicates it only listens on IPv4 addresses:

```
udp        0      0 0.0.0.0:1234              0.0.0.0:*
```

If it was listening on IPv6 as well, we would expect to see another line like this one:

```
udp6       0      0 :::1234                   :::*
```

This issue is also present with TCP servers. The current workaround is to set up two servers, one with the `udp4/tcp4` prefix and one with the `udp6/tcp6` one.

**Comment by panjf2000** [comment]
Will take some time to look into this.
