### ISSUE TITLE
panic when calling CountConnections

### ISSUE THREAD

**Issue by li-ma** [panjf2000/gnet#204]
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb1e5b1]

goroutine 92 [running]:
github.com/panjf2000/gnet.Server.CountConnections(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0004b1c80)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.4.3/gnet.go:78 +0x71
github.com/panjf2000/gnet.(*eventloop).loopTicker.func1(0xc0004e2168, 0xc0004cd400)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.4.3/eventloop_unix.go:266 +0x3c
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling(0xc0001183c0, 0xc00043ef68, 0x0, 0xc0004147c0)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.4.3/internal/netpoll/epoll.go:136 +0x50e
github.com/panjf2000/gnet.(*server).activateSubReactor(0xc000134090, 0xc0000e6600, 0x1)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.4.3/reactor_linux.go:52 +0xb2
github.com/panjf2000/gnet.(*server).startSubReactors.func1.1(0xc000134090, 0xc0000e6600)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.4.3/server_unix.go:96 +0x45
created by github.com/panjf2000/gnet.(*server).startSubReactors.func1
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.4.3/server_unix.go:95 +0x6a

**To Reproduce**
1. OnInitComplete Event: store Server object as srv
2. Tick Event: print out the value returned by srv.CountConnections()

**System Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Go version: 1.16
 - gnet version: 1.4.2 & 1.4.3

**Comment by panjf2000** [comment]
Please show me your example code here.

**Comment by li-ma** [comment]
Sorry for late reply. I run the same application for both TCP and UDP. I think it was a mistake. UDP doesn't have "Connection".

**Comment by panjf2000** [comment]
OK, then I'm about to close this issue, feel free to reopen it in case there is something else.
