### ISSUE TITLE
Provide an example by converting redis server for evio to use gnet?

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/gnet#205]
since gnet is derived from evio, possible to convert this for testing performance?
https://github.com/tidwall/evio/blob/master/examples/redis-server/main.go

thx in advance

**Comment by panjf2000** [comment]
Kind of busy these days，I'll look into it when I got some time.

**Comment by panjf2000** [comment]
Try this one: https://github.com/IceFireDB/redhub
