### ISSUE TITLE
关于定时器的问题

### ISSUE THREAD

**Issue by Txhua** [panjf2000/gnet#206]
为什么不考虑用timerfd作为定时器触发，而是用简单的sleep作为延时触发，以及为什么不是在mainReactor中设置触发tick，反而在idx为0的subReactor中设置

**Comment by panjf2000** [comment]
现在是遇到什么具体问题了吗？

**Comment by lesismal** [comment]
> 我的业务逻辑需要用到定时器，我写定时相关逻辑卡住了，阅读源码发现tick回调中还需要在处理一次数据同步，逻辑层面还需要自己实现一个TimerQueue管理定时器任务，如果说在底层就能提供epoll层级的定时器并且提供TimerQueue，提供RunAt(),RunAfter(), RunEvery()这些暴露给逻辑层的接口，且在本协程处理超时回调，逻辑层面就更简单了。

相比于应用层自己实现一个TimerQueue，epoll的timeout做定时器是不划算的：trigger syscall或者时间轮空转的代价都更高
