### ISSUE TITLE
用gnet实现一个redis server，自己实现codec，可能带来性能损耗

### ISSUE THREAD

**Issue by foxhunter72143** [panjf2000/gnet#208]
**What is your question about gnet?**
Please describe your question meticulously.
用gnet实现一个redis server，利用协程池异步回写。如果某个命令很大，react函数的接受数据可能不是一个完整的redis命令，因此要实现codec解决tcp拆包问题，但是decode要每一次判断一个redis协议是否完整，由于要解析redis协议带来性能的损耗，有更好的方法吗？

**Comment by panjf2000** [comment]
使用上的问题请到 [IM](https://gitter.im/gnet-io/gnet) 上沟通，GitHub issue 主要是用来提 bug 和新功能，以及解答一些架构设计上的问题等等，谢谢。
