### ISSUE TITLE
Conn为何没有像原生的net里的Conn有Deadline的属性呢

### ISSUE THREAD

**Issue by zjj9850** [panjf2000/gnet#209]
Conn里为何不加入ReadDeadLine和WriteDeadLine的属性呢，这样可以在一定时间内，将无任何消息的链接进行关闭，减少资源占用。。。。逻辑层也可以不用再去实现一个超时的处理

**Comment by panjf2000** [comment]
#83 

业务层可以自己实现，框架原生支持这个需要再考虑。
