### ISSUE TITLE
都没详细点的文档

### ISSUE THREAD

**Issue by hongbaotong** [panjf2000/gnet#21]

**Comment by panjf2000** [comment]
`gnet` 本身是一个轻量级的网络框架，使用方法是很简单的，基本上只要注册几个所需的函数即可，README 已经有介绍了，或者想看具体的示例可以看 `gnet` 的 [examples](https://github.com/panjf2000/gnet/tree/master/examples)，最后 `gnet` 的所有可用的 API 也可以相应的文档：[APIs](https://gowalker.org/github.com/panjf2000/gnet)
