### ISSUE TITLE
Proposal: cap the memory usage and allocation caused by AsyncWrite

### ISSUE THREAD

**Issue by lming** [panjf2000/gnet#214]
First of all - thank you @panjf2000 for the excellent library!

I found several memory related issues when I tested sending high load of data from gnet server to many connected tcp clients:
1. The lock free queue grows unbounded when CPU is the bottleneck to process the pending queue tasks (while producer can still calls `AsyncWrite` at a high speed)
2. Each invokation of `AsyncWrite` creates a func closure, which invovles a memory allocation.
3. Each `queue.Enqueue` creates a new `node`
4. Above 2 and 3 triggers gabage collection frequently when server sends out data a high rate.

The proposed solution involves following changes:
1. Adding an option to set a cap of the task queue
2. Adding an option to cap the send buffer of each connection
3. Eliminate the memory allocation in `AsyncWrite` and `Enqueue`

I've made above changes in [this branch](https://github.com/lming/gnet/tree/memory-cap) and the result looks promising:

<img width="1248" alt="Screen Shot 2021-05-29 at 9 57 32 PM" src="https://user-images.githubusercontent.com/618857/120093082-ab049e00-c0cc-11eb-8da4-e967c12ab3e2.png">

However I don't have thorough knowledge about gnet to create a polished PR. I'd suggest @panjf2000 to incorporate the change if you like the direction.

Thanks!

**Comment by panjf2000** [comment]
I think you should reopen #213 and we can go through the code review and test.

**Comment by lming** [comment]
Sounds good. I'll reopen it.

**Comment by Devying** [comment]
@lming How was this monitoring picture generated？

**Comment by lming** [comment]
It was monitoring graph from newrelic

**Comment by panjf2000** [comment]
Hi @lming, could you run your test code on [this branch](https://github.com/panjf2000/gnet/tree/reduce-gc) to verify whether it eases GC when `AsyncWrite` being called in high frequency? thanks~

**Comment by lming** [comment]
Thank you @panjf2000 for making the change. It allivate the issue a lot because we no longer create callback func inside `AsyncWrite`:

![image](https://user-images.githubusercontent.com/618857/124839570-de451300-df3d-11eb-9f89-74e818acde17.png)

If you want to further improve it, ideally we can also eliminate the creation of a node in `Enqueue` call

![image](https://user-images.githubusercontent.com/618857/124839776-4ac01200-df3e-11eb-8fb7-eee136c66c42.png)

**Comment by panjf2000** [comment]
The pprof of `Conn.AsyncWrite` is from the old version of gnet, could you also show the new one on the latest commit, so that we can have a more intuitive sense of the comparison, thanks~
@lming

**Comment by lming** [comment]
Here is the latest one. Please ignore the absolute number as it depends on how long the test code runs. But it shows that all the memory allocation in the `AsyncWrite` call chain is from the `node` in `lockFreeQueue`

![image](https://user-images.githubusercontent.com/618857/124856358-34767e00-df5f-11eb-80c6-53e546c952c2.png)
