### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by huzhao37** [panjf2000/gnet#216]
var packet [0x10000]  客户端连接关闭后，该内存并没有释放

**Comment by huzhao37** [comment]
最近跑长稳，发现客户端连接已经关闭很久了，没有任何连接的情况下,go tool pprof监视heap使用分配，发现packet数组使用的内存没有释放，且一直不会释放

**Comment by huzhao37** [comment]
已解决。。

**Comment by panjf2000** [comment]
下次记得按 issue 模板填内容。
