### ISSUE TITLE
更新gnet 1.4.5报verifying module: checksum mismatch

### ISSUE THREAD

**Issue by jkingben** [panjf2000/gnet#219]
![image](https://user-images.githubusercontent.com/5220242/124723188-5b23bd00-df3d-11eb-98ea-0b49abdab6c2.png)

无论是单独在非工程文件夹下清掉modecache用go get下，还是在mod下用mod clean方式后用go mod tidy 都是报这个错，1.4.5无法更新下来，只能更新到1.4.4。

工程里用的是ants v2.4.4版本

**Comment by panjf2000** [comment]
v1.4.5 在 go modules 服务器中的缓存有问题，直接更新到 v1.4.6 即可。
