### ISSUE TITLE
如何做到 tcp 连接验证

### ISSUE THREAD

**Issue by jol5** [panjf2000/gnet#220]
**What is your question about gnet?**
Please describe your question meticulously.
 我想在 acept 前后可以立马能够做连接认证，比如简单的用户名密码。通过以后再建立连接

**Comment by panjf2000** [comment]
accept 前后？建连接之前？连接都还没建立，客户端鉴权信息从哪里来？

**Comment by jol5** [comment]
> accept 前后？建连接之前？连接都还没建立，客户端鉴权信息从哪里来？

那对于客户端，他可以做到  只建立连接，不发送数据，那岂不是不会触发验证？这样岂不是可以一直消耗资源？

**Comment by jol5** [comment]
> accept 前后？建连接之前？连接都还没建立，客户端鉴权信息从哪里来？

而对于MQTT这种，大部分的做法是 在 Accept 之后，起一个协程 去处理收发，而在协程开始就起一个定时器去搞的，建立通道后，5s内没有接收到数据，就关闭通道了。
如下：
![image](https://user-images.githubusercontent.com/28615922/124852742-5875a600-dfd7-11eb-9cad-c51e0171ce98.png)

**Comment by panjf2000** [comment]
你在 `gnet.OnOpened()` 里做不就好了吗？
https://pkg.go.dev/github.com/panjf2000/gnet#EventServer.OnOpened

**Comment by panjf2000** [comment]
Close this issue for inactivity.
