### ISSUE TITLE
没有详细的开发技术文档吗，搭建 跑demo 快速上手？？？

### ISSUE THREAD

**Issue by danielesk** [panjf2000/gnet#223]
**What is your question about gnet?**
Please describe your question meticulously.

**Comment by panjf2000** [comment]
`gnet` 本身足够简单，核心 API 只有那几个，官网 https://gnet.host 上的博客已经做了详细的说明，其他 API 的使用看 https://pkg.go.dev/github.com/panjf2000/gnet 就可以了。

至于使用示例：https://github.com/gnet-io/gnet-examples

**Comment by tokingHong** [comment]
> `gnet` 本身足够简单，核心 API 只有那几个，官网 https://gnet.host 上的博客已经做了详细的说明，其他 API 的使用看 https://pkg.go.dev/github.com/panjf2000/gnet 就可以了。
> 
> 至于使用示例：https://github.com/gnet-io/gnet-examples

放到readme呗
