### ISSUE TITLE
在使用gnet时，linux有什么需要注意的地方吗？

### ISSUE THREAD

**Issue by sinwa1121** [panjf2000/gnet#225]
我的程序在windows下运行良好，但是在linux上总是莫名崩溃，用go 原生的net库没有问题

每次奔溃的地方都不一样

goroutine 54 [running]:
GoServer/Core/NetWork.(*TCPServer).PreWrite(0xc0003482a0)
        <autogenerated>:1 +0x2f
github.com/panjf2000/gnet.(*eventloop).loopWrite(0xc00021e400, 0xc0004b4d20, 0xf, 0xc00032a0d8)
        /home/apple/Source/mygo/pkg/mod/github.com/panjf2000/gnet@v1.5.0/eventloop_unix.go:197 +0x49
github.com/panjf2000/gnet.(*server).activateSubReactor.func2(0xf, 0xc000000019, 0x40, 0x40)
        /home/apple/Source/mygo/pkg/mod/github.com/panjf2000/gnet@v1.5.0/reactor_linux.go:71 +0xe5
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling(0xc0000200a0, 0xc000316f68, 0x3, 0xc0003a86f6)
        /home/apple/Source/mygo/pkg/mod/github.com/panjf2000/gnet@v1.5.0/internal/netpoll/epoll.go:140 +0x127
github.com/panjf2000/gnet.(*server).activateSubReactor(0xc0004cc3f0, 0xc00021e400, 0xc000136300)
        /home/apple/Source/mygo/pkg/mod/github.com/panjf2000/gnet@v1.5.0/reactor_linux.go:57 +0xb8
github.com/panjf2000/gnet.(*server).startSubReactors.func1.1(0xc0004cc3f0, 0xc00021e400)
        /home/apple/Source/mygo/pkg/mod/github.com/panjf2000/gnet@v1.5.0/server_unix.go:93 +0x45
created by github.com/panjf2000/gnet.(*server).startSubReactors.func1
        /home/apple/Source/mygo/pkg/mod/github.com/panjf2000/gnet@v1.5.0/server_unix.go:92 +0x6a

**Comment by sinwa1121** [comment]
解包代码如下
func (p *MsgParser) Decode(c gnet.Conn) (data []byte, err error) {

	if c.BufferLength() > 0 {
		data = c.Read()
		if len(data) < TCPHeaderSize {
			return nil, nil
		}
		headFlag, _, _, bufferSize, _, msgSize := DealRecvTcpHeaderData(data)
		BufAllSize := TCPHeaderSize + int(bufferSize) + int(msgSize) + 1 // 整个数据包长度，末尾有标示位
		if headFlag != uint8(254) {
			zLog.ErrorLog("数据包头部标识不正确 %x", data)
			return nil,errors.New("数据包头部标识不正确") // 数据包格式校验不正确
		}
		if len(data) < BufAllSize {
			return nil, nil //int(bufferSize) + offset
		}
		endData := DealRecvTcpEndData(data[BufAllSize-1 : BufAllSize])
		if endData != uint8(TCPEnd) { // EE
			zLog.ErrorLog("数据包尾部判断不正确 %x ", data)
			return  nil,errors.New("数据包尾部判断不正确")
		}
		c.ShiftN(TCPHeaderSize +int(bufferSize) + 1)
		finalBuffer := data[ : TCPHeaderSize+int(bufferSize) + 1]
		return finalBuffer, nil
	}
	return nil, nil
}
react函数直接把数据加锁拷走，没有多余的逻辑

**Comment by panjf2000** [comment]
按模板填 issue，为什么要删掉模板？

**Comment by panjf2000** [comment]
还有，崩溃的错误是什么？

**Comment by sinwa1121** [comment]
奔溃的地方每次都不一样，看起来要么是多线程问题，要么是内存写越界了，还有大量的protobuf解包失败，是不是我的decode函数写的有问题？我费解的是windows下跑了一晚上都没有问题。
