### ISSUE TITLE
about ring buffer expand and shrink 

### ISSUE THREAD

**Issue by firedtoad** [panjf2000/gnet#226]
**What is your question about gnet?**
目前1.50 版本的ringbuffer 使用的扩容和缩容策略过于激进，每次扩容翻倍，每次缩容一半。
而且每次扩容/缩容都会导致重新分配内存，带来的内存开销非常大，目前的golang内存管理机制会导致
占用内存非常大，并且不能及时归还操作系统。
希望能改成平滑策略，比如内置slice实现，每次扩容一倍达到某个值(1024)后开始线性增长,缩容最好不要频繁进行
目前的缩容策略过于激进。

**Comment by panjf2000** [comment]
提个 PR？

**Comment by panjf2000** [comment]
暂时把 Reset() 的 shrink 操作移掉了，现在想想这个逻辑的确有点粗暴，而且突然发现还会影响到 ringbuffer pool.

至于扩容，ring buffer 的扩容其实不是容量翻倍，而是计算现有容量+需要新增的容量最近的一个 2^n 的数作为新容量。

**Comment by firedtoad** [comment]
实际结果就是每次扩容都会是上次容量的两倍，这在缓存区很小的时候没问题, 但是当缓冲区大了以后就成了灾难,
比如当前缓存区是1G下次扩容就是2G，再扩容几次就oom了
我是有一个业务，客户端发送的请求很小，服务端返回的数据很大，造成缓冲区堆积，压测的时候发现这个问题的
目前系统函数growslice采用的策略是容量小于1024时翻倍增长，大于1024 线性增长(每次至少增长新容量的25%)，我觉得可以参考一下
给ringbuffer 提供一个可以设置增长率的参数。
这个问题在c++中也存在，默认的std::vector 也是采用每次扩容翻倍的策略，后来facebook
做folly框架的时候就自己实现了vector采用1.5作为扩容参数
参考链接 https://github.com/facebook/folly/blob/master/folly/FBVector.h#L1133

Andy Pan ***@***.***> 于2021年7月18日周日 下午12:37写道：

**Comment by panjf2000** [comment]
你说的系统函数说的是 Go 的 `bytes.Buffer`? 它是每次两倍+新容量。

**Comment by firedtoad** [comment]
append函数 也就是 growslice函数
参考slice.go:144-163(go1.16.3)

Andy Pan ***@***.***> 于2021年7月18日周日 下午9:04写道：

**Comment by panjf2000** [comment]
哦，你说的是 slice，它的确是如此。

关于 ring buffer 的扩容策略我这阵子再参考下其他主流开源库。

**Comment by panjf2000** [comment]
你要有兴趣也可以提个 PR 一起研究下。

**Comment by firedtoad** [comment]
我还遇到一个问题 就是关于编码解码器的设计问题,目前的 LengthFieldBasedFrameCodec encode方法里进行了内存分配
我觉得犯不着为添加几个字节包头进行一次分配和内存拷贝,太浪费了,有开源库采用的方法是把连接对象传进encode函数
先写包头再写包体的，这样做改动会很大。我希望最好能避免在编码器内做内存分配

Andy Pan ***@***.***> 于2021年7月18日周日 下午9:14写道：
