### ISSUE TITLE
主动推送问题

### ISSUE THREAD

**Issue by zhuiyi9009** [panjf2000/gnet#227]
目前的接口都是通过out返回给前端，服务器如果需要一个请求返回多个包，要怎么处理？
看了下push的例子， 里面引入了ants包做协程池， 会不会有死锁的问题？
eventHandler处理完前端包, 然后提交多个包如下面：
`
pool.Submit( func() {
    conn.asyncWrite()
})
`
`
pool.Submit( func() {
    conn.asyncWrite()
})
`
那么eventHandler =》 pool => eventHandler的方式是不是有死锁风险。

**Comment by panjf2000** [comment]
1. 多个包你拼成一整个 []byte 就行了
2. 不明白你提到的所谓的死锁，gnet 整个框架是无锁的。
