### ISSUE TITLE
Why is Gnet splitting requests when a request is split over multiple packets

### ISSUE THREAD

**Issue by tilmanrpk** [panjf2000/gnet#241]
not always but only at random times, react is triggered two times with the first frame containing the first 1024 bytes of the request and the second the rest of the request, which obviously leads to errors.  I never had this problem when using http.Serve. Wireshark tells me that the request is split into two packets, but I don't see why that would be a problem, seems like pretty normal behaviour.  Is this a bug, wrong configuration or am I meant to handle this myself? Where/how would be the best way to do it?

**Comment by panjf2000** [comment]
The `React()` will be triggered every time one complete pakcet is decoded by your codec of gnet, so you might want to take a look at your codec you passed into gnet.

**Comment by panjf2000** [comment]
Close this issue for inactivity.
