### ISSUE TITLE
Get Eventloop

### ISSUE THREAD

**Issue by azzahrah** [panjf2000/gnet#244]
**What is your question about gnet?**
in netty we can get eventlop from context/channel and execute, schedule same task inside eventloop, how to do that in gnet?

**Comment by panjf2000** [comment]
`gnet` is the Golang clone of netty, it doesn't provide all features that netty has. 

If you want to run some tasks, just do it in `React()`, and please note that you should run non-blocking tasks in the current goroutine and blocking tasks in the new goroutines.

**Comment by panjf2000** [comment]
Closed this issue for inactivity.
