### ISSUE TITLE
如何处理有首尾分隔符的包

### ISSUE THREAD

**Issue by kaytiondev** [panjf2000/gnet#246]
**What is your question about gnet?**

你好，请问一下如果协议设计上包含首位分隔符的，这种需要自己特殊处理吗，还是gnet可直接处理掉，我看文档上delimiter都是对应单个。包数据组成 

`0xee abcdefg 0xee`，其中oxee是分隔符

感谢

**Comment by panjf2000** [comment]
用内置的 `DelimiterBasedFrameCodec` 也没问题，只不过第一个解码出来的包会是分隔符 `0xee`，你可以自己实际再测一下
