### ISSUE TITLE
gnet借鉴了netty，但是并没有看到客户端booststrap代码，大部分都是作为服务端

### ISSUE THREAD

**Issue by xj524598** [panjf2000/gnet#248]
**What is your question about gnet?**
gnet借鉴了netty，但是并没有看到客户端booststrap代码，大部分都是作为服务端

**Comment by panjf2000** [comment]
gnet Client 最近会发布。

**Comment by xj524598** [comment]
目前公司内部想做service mesh 底层的网络库在考虑gnet，后期可能会有更多机会求教



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Andy Pan ***@***.***&gt;
发送时间: 2021年9月29日 18:31
收件人: panjf2000/gnet ***@***.***&gt;
抄送: xj524598 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[panjf2000/gnet] gnet借鉴了netty，但是并没有看到客户端booststrap代码，大部分都是作为服务端 (#248)

**Comment by zyc801208** [comment]
> gnet Client 最近会发布。

Is the release date confirmed of gnet Client?
