### ISSUE TITLE
gnet server在返回client数据包时，Encode接口效率低下

### ISSUE THREAD

**Issue by liujiangang01** [panjf2000/gnet#249]
背景：应用server在返回数据包给client时往往会携带header、body、attachment（二进制数据），这些在应用层往往是不连续内存，如果按照现有Encode接口（返回的是[]byte），无法支持多路内存聚合io，会带来额外的拷贝开销
建议：Encode的返回值是[][]byte，这样也能兼容字节传输的应用

**Comment by panjf2000** [comment]
gnet v2 已经移除 codec 机制，详情见 https://github.com/panjf2000/gnet/issues/263#issuecomment-1004164099
