### ISSUE TITLE
How to implement a push server with gnet

### ISSUE THREAD

**Issue by itlabers** [panjf2000/gnet#25]
作为一个服务端框架如何实现推送的?

**Comment by panjf2000** [comment]
你说的是服务端定时推送吧，这个还没有加上，正在做。

**Comment by panjf2000** [comment]
推送服务器示例已添加：[push server](https://github.com/panjf2000/gnet/blob/master/examples/push-server/main.go)

**Comment by itlabers** [comment]
这样也可以实现,但是不好控制tick event频度,最好能暴露api出来主动发数据,做到基于事件驱动给客户端下发数据

**Comment by panjf2000** [comment]
基于事件驱动主动推送？你是有什么具体的应用场景？

**Comment by javarobot234** [comment]
@panjf2000 借道问一下, 这样是不是相当于两个协程向同一个连接写入数据 会和正常事务里的 AsyncWrite 冲突吗
