### ISSUE TITLE
请问下有中文文档么

### ISSUE THREAD

**Issue by ayamzh** [panjf2000/gnet#250]
**What is your question about gnet?**
Please describe your question meticulously.
请问下有中文文档么

**Comment by panjf2000** [comment]
`gnet` 本身的核心 API 并不多，可以参考这里 https://gnet.host/blog/presenting-gnet-cn/，基本讲得七七八八了，其他 API 可以再看这里 https://pkg.go.dev/github.com/panjf2000/gnet
