### ISSUE TITLE
不懂为什么gnet会比官方net库快很多?

### ISSUE THREAD

**Issue by joshua86z** [panjf2000/gnet#252]
官方net库不也是调epoll吗
能不能简洁说下用了什么设计让性能大幅上升?

**Comment by mikeqoo1** [comment]
這篇文章 不知道有沒有解答你問題 

- http://xiaorui.cc/archives/6758

結論:作者設計的pool比較優

**Comment by zhongweikang** [comment]
https://strikefreedom.top/go-netpoll-io-multiplexing-reactor

**Comment by zhongweikang** [comment]
这篇比较详细
