### ISSUE TITLE
有没有阻塞的方法？

### ISSUE THREAD

**Issue by zgcbj** [panjf2000/gnet#255]
比如说链接刚建立的时候，我在onopen里面来回交互几次，认证完后再切换成非阻塞模式?写mysql服务端的时候，链接上来就要认证下，认证逻辑和正常的业务逻辑没在一起，如果能先阻塞的处理完认证逻辑，后面的业务数据再异步处理，能省点事儿。

**Comment by panjf2000** [comment]
OnOpened 不就是干这事儿的吗？这个 OnOpened 这个回调执行完之后才会开始处理业务消息的读写。
