### ISSUE TITLE
请问下怎么知道是客户端关闭的链接还是服务端关闭的链接

### ISSUE THREAD

**Issue by cxjhk** [panjf2000/gnet#256]
**What is your question about gnet?**
Please describe your question meticulously.

**Comment by panjf2000** [comment]
服务端一般不会主动关闭socket（除非你自己关闭），只会在读写socket失败的时候关闭，调用 OnClosed 回调，所以一般可以认为是客户端关闭，或者socket出错了。

**Comment by cxjhk** [comment]
我们有业务场景需要知道是服务端关闭还是客户端自己关闭 用swoole的话会返回一个reactorId 我能知道是不是客户端断开的

**Comment by panjf2000** [comment]
除了你自己调用 c.Close() 之外，gnet server 不会主动关闭 socket。
