### ISSUE TITLE
关于Accept()的疑问

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#259]
问题：在其他地方看到在调用net.Accept()后会判断返回的err!=nil且错误类型是Temporary()就进入一个time.Sleep()或time.After()的处理，而gnet里看到的则是直接return掉。想请教下这两种方式的区别，如何选择

**Comment by zhu121** [comment]
> gnet 在 accept 之后判断是 `EAGAIN` 是 return nil，后面会再重试的。

acceptor_windows.go/L48是判断err != nil 就 return 结束 listenerRun 的 goroutine 了？

**Comment by panjf2000** [comment]
gnet 在 Unix-like 系统下是裸调系统调用，所以需要自己处理这些具体的错误，而在 Windows 平台则是直接用的 Go 的标准库  net，它在底层已经处理好了这些细节，这种临时性的错误已经处理了，返回到用户态的错误一般是不可恢复的，所以就直接退出了，可以看下 net 的源码了解下。

**Comment by zhu121** [comment]
> gnet 在 Unix-like 系统下是裸调系统调用，所以需要自己处理这些具体的错误，而在 Windows 平台则是直接用的 Go 的标准库 net，它在底层已经处理好了这些细节，这种临时性的错误已经处理了，返回到用户态的错误一般是不可恢复的，所以就直接退出了，可以看下 net 的源码了解下。

请教下，在一些源码看到都会在调用net库的accept()后做类似以下代码的判断处理，这种会是多余的吗
`
if ne, ok := err.(net.Error); ok && ne.Temporary() {
	time.Sleep(tempErrDelay)
	continue
}
`
