### ISSUE TITLE
Support Least-Connections load-balancing algorithm

### ISSUE THREAD

**Issue by lonerwolf** [panjf2000/gnet#26]
RT，连接频繁，导致很多连接都归到一个EPOLL下，其他EPOLL上的连接比较少

**Comment by panjf2000** [comment]
@lonerwolf 
现在是用 round-robin 轮询分配的，怎么会导致连接都分配到一个 poller 里？

**Comment by lonerwolf** [comment]
> @lonerwolf
> 现在是用 round-robin 轮询分配的，怎么会导致连接都分配到一个 poller 里？

因为轮询，所有有问题，比如2个EPOLL,进来2个连接，两个都是一个，然后2号EPOLL里的这个连接断开了，他重新连接就到1号上去了，不断累积就不平衡了

**Comment by panjf2000** [comment]
客户端连接是长连接和短连接混合的时候，Round-Robin 负载均衡的确会出现你说的这种问题，这是算法决定的，所以我建议你复用连接或者用 `gnet` 的 `SO_REUSEPORT` 模式，让内核来做负载均衡。

**Comment by luyu6056** [comment]
我建议以fd来分配loop，取得连接fd分配之后，将fd分配到 idx为nfd%svr.subLoopGroup.len()的loop里。
那么我们来复现疑问场景。
loop总数为2，fd为1分配到loop1，fd为2分配到loop0。fd2断开，重新再连，获得的fd还是2，2%2=0，这时候分配到loop0，实现均衡:smile:
