### ISSUE TITLE
gnet里面怎么处理粘包

### ISSUE THREAD

**Issue by cxjhk** [panjf2000/gnet#261]
**What is your question about gnet?**
Please describe your question meticulously.
刚使用go写
没搞明白在gnet中怎么处理tcp的粘包问题

**Comment by mikeqoo1** [comment]
粘包问题 一般不是都是開發人員自行處理嗎?

**Comment by panjf2000** [comment]
业务协议分包需要自己实现 gnet.ICodec 去做。
