### ISSUE TITLE
执行顺序方面

### ISSUE THREAD

**Issue by push-and-pop** [panjf2000/gnet#262]
**What is your question about gnet?**
Please describe your question meticulously.
我想问一下函数执行顺序的问题
我这边测试出来好像先是执行react，然后才是Decode、Encode
![image](https://user-images.githubusercontent.com/80676432/139566173-3b3154c8-1bd7-4b1b-89dd-99a4cbc1c19f.png)
想问一下上面compute的部分具体是在哪里执行呢

测试：
代码：
![image](https://user-images.githubusercontent.com/80676432/139566205-fdc7ebd2-5ca1-4b89-851b-78ac911c97ab.png)
![image](https://user-images.githubusercontent.com/80676432/139566213-5feb4fd5-19a9-49d6-bf6e-a08ffb4458f5.png)
结果：
![image](https://user-images.githubusercontent.com/80676432/139566222-11eed686-e5f5-4c4b-b520-90bcb9bd1994.png)

**Comment by panjf2000** [comment]
compute 部分就是 React() 回调里的逻辑。

**Comment by push-and-pop** [comment]
好的谢谢
