### ISSUE TITLE
Decode(c Conn) ([]byte, error) 返回类型

### ISSUE THREAD

**Issue by mylxy** [panjf2000/gnet#263]
Decode 返回byte[]， 这个返回类型为什么不能是interface{}类型呢？一般数据都会解析成struct类型，比如MQTT协议解析，这个方法只用于分包吗？我的理解是 Decode 方法用作协议解析，得到用户想要的任务对象，React方法得到这个对象，作业务处理，但是[]byte 作为React，还要数据解析吗？？不太理解

**Comment by panjf2000** [comment]
目前的 `gnet.ICodec` 的确只能做分包，最后一步根据二进制数据还原成对象目前只能在 `React()` 里做，gnet v2 会考虑加上这一步。

**Comment by zhongweikang** [comment]
这个功能还是很实用的（我项目中基于 1.5.3 fork了一份代码，魔改实现了这个功能，避免 React 二次解析）

请问一下 v2 有发版计划么，期待尽快用上 😄

**Comment by taozix** [comment]
为啥Decode的时候总会有size为0的frame，是姿势没对？

**Comment by zhongweikang** [comment]
> 为啥Decode的时候总会有size为0的frame，是姿势没对？

正常的，Decode 入口处，用类似下边的代码判断一下就行
```
	buf := c.Read()
	if len(buf) == 0 {
		return nil, gerrors.ErrIncompletePacket
	}
```

**Comment by panjf2000** [comment]
gnet v2 已经初步完成开发，这个版本做了很多重大改变，移除 codec 是其中之一；codec 对于 gnet 的架构设计来说反而有所限制：gnet v1 里每次读取数据都需要循环调用 codec.Decode()，直到所有数据处理完才结束，现在移除 codec，让使用者自己在 `EventHandler.OnTraffic()` 灵活处理，也克服了 codec API 不灵活的缺点：比如本 issue 描述的问题，还有无法返回 [][]byte 离散数据。
