### ISSUE TITLE
go get github.com/panjf2000/gnet occur error

### ISSUE THREAD

**Issue by betNevS** [panjf2000/gnet#264]
**What is your question about gnet?**
Please describe your question meticulously.

go: downloading github.com/panjf2000/gnet v1.5.3
go get: github.com/panjf2000/gnet@v1.0.0-rc.4 updating to
        github.com/panjf2000/gnet@v1.5.3 requires
        gopkg.in/natefinch/lumberjack.v2@v2.0.0: reading gopkg.in/natefinch/lumberjack.v2/go.mod at revision v2.0.0: unknown revision v2.0.0

**Comment by panjf2000** [comment]
你运行的命令是什么？

**Comment by betNevS** [comment]
找到问题了，打扰了哈~

**Comment by panjf2000** [comment]
如果问题解决，麻烦关闭这个 issue。
