### ISSUE TITLE
Persistent UDP connection

### ISSUE THREAD

**Issue by PZRdUqv15P** [panjf2000/gnet#265]
**Is your feature request related to a problem? Please describe.**
After reading and parsing UDP incoming data, I want to reuse the connection to send response back to the client asynchronously. But in [eventloop_unix.go:304 and eventloop_windows.go:267] where c.releaseUDP() is immediately called after React(), which will make the connection unavailable.

**Describe the solution you'd like**
In [eventloop_unix.go:304]
```go
c := newUDPConn(fd, el, el.ln.lnaddr, sa)
	out, action := el.eventHandler.React(el.buffer[:n], c)
	if out != nil {
		_ = c.sendTo(out)
	}
	if action == Shutdown {
		return gerrors.ErrServerShutdown
	}
	if action == Close {
		c.releaseUDP()
	}
```

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by panjf2000** [comment]
I believe that TCP is a connection-oriented protocol, whereas UDP is a connectionless protocol. Therefore, you are able to send data back to the client as long as you still have the peer socket address under UDP, c.releaseUDP neither close the socket nor erase the UDP socket address, thus you can just call c.SendTo() after the React().

**Comment by PZRdUqv15P** [comment]
> 
> 
> I believe that TCP is a connection-oriented protocol, whereas UDP is a connectionless protocol. Therefore, you are able to send data back to the client as long as you still have the peer socket address under UDP, c.releaseUDP neither close the socket nor erase the UDP socket address, thus you can just call c.SendTo() after the React().

Thanks for the reply. Did not fix my problem here but I'll figure something out.
