### ISSUE TITLE
请问，gnet相比thrift的网络框架和gprc的网络框架，优势在哪？如果有，优势的逻辑是什么？

### ISSUE THREAD

**Issue by liujiangang01** [panjf2000/gnet#268]
看了下实现逻辑，和libevent、netty （其实主流rpc像 thrift和grpc底层都利用了这些框架）类似，我想知道gnet的相比他们的优势在哪？为什么要重新做一个网络框架，麻烦解惑

**Comment by panjf2000** [comment]
这些都是 Reactor 模式的网络框架，使用的开发语言不同，而且gnet相比来说定位是轻量且高性能，不会像 netty 这一类做得很重。

**Comment by liujiangang01** [comment]
性能高于golang版grpc或者thrift的技术点体现在哪呢？看了下thrift是基于libevent，实现原理和我们gnet类似



---原始邮件---
发件人: "Andy ***@***.***&gt;
发送时间: 2021年11月8日(周一) 晚上10:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [panjf2000/gnet] 请问，gnet相比thrift的网络框架和gprc的网络框架，优势在哪？如果有，优势的逻辑是什么？ (Issue #268)




 
这些都是 Reactor 模式的网络框架，使用的开发语言不同，而且gnet相比来说定位是轻量且高性能，不会像 netty 这一类做得很重。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
