### ISSUE TITLE
epollWait的疑问

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#269]
syscall_epoll_generic_linux.go/L26的epollWait函数
问题1：RawSyscall调用本身是可能会阻塞的，所以对底层epoll_wait调用的超时传0是为了使其不会阻塞立即返回吗
问题2：Syscall函数受调度器控制，不会造成系统堵塞，但是对底层epoll_wait调用的超时传-1，反而会处于阻塞状态？

**Comment by panjf2000** [comment]
Go 调度器对于陷入系统调用的 goroutine 会进行抢占，不会阻塞其他 goroutine。
