### ISSUE TITLE
ReadSplit Support

### ISSUE THREAD

**Issue by zhongweikang** [panjf2000/gnet#271]
在应用层协议设计的过程中，经常需要以分隔符比如 \n 来解析报文，能否提供一个 ReadSplit 方法，使得我可以读取缓冲区数据中的一行（从第一个字节开始，直接碰到第一个 \n 结束）。

例如报文 aaa\nbbb\n，当调用 readSplit 时，返回 aaa，而无需像 ReadN 一样指定读取长度。

当然我可以通过 Read 或者 ReadN 二次封装来实现 ReadSplit 方法，但对于报文解析而言，这应该是一个较为通用的功能，如果官方库直接实现应该会方便很多用户。

**Comment by panjf2000** [comment]
https://pkg.go.dev/github.com/panjf2000/gnet#LineBasedFrameCodec

**Comment by zhongweikang** [comment]
好的谢谢
