### ISSUE TITLE
咨询http/http2问题？

### ISSUE THREAD

**Issue by liupeidong0620** [panjf2000/gnet#273]
**gnet只是一个四层传输库，如果用gnet做一个七层http服务，是否可以和fasthttp这样的库结合使用？**

1. gnet 提供的http例子过于简单，无法用于生产环境
2. 目前没有找到比较合适的http库可以和gnet结合使用

**Comment by panjf2000** [comment]
fasthttp 本身就已经是一个完整的 HTTP 层库了，它的网络库是 go net，不再需要 gnet 这样的网络库了，现有的没有什么现成的 HTTP 库可以和 gnet 结合使用，因为那些 HTTP 框架都是基于 net/http，如果要基于 gnet 就需要有人去自己去写。
