### ISSUE TITLE
 Is Gnet Framework capable of Multi Port Listen?

### ISSUE THREAD

**Issue by comwls** [panjf2000/gnet#274]
I am a user who is paying close attention to the Gnet framework.

We open two ports for security
one for external devices

One wants to use only the inside

Is there a way to listen to the two ports of Gnet?

**Comment by panjf2000** [comment]
Start two goroutines and call `gnet.Serve()` to listen on two ports.

**Comment by panjf2000** [comment]
Close this for inactivity.
