### ISSUE TITLE
errnoErr问题

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#276]
syscall_errors_linux.go里写errnoErr()是防止运行时分配几个常用的错误类型变量，
在epoll_optimized_poller.go/L123把epollWait()返回的err打印%v和&err，
当错误类型一样的，打印的值都在变化，并没有复用变量，没看懂是怎么防止运行时分配的，还是测试方式错了？

**Comment by panjf2000** [comment]
说详细点。

**Comment by zhu121** [comment]
> 说详细点。
在syscall_errors_linux.go里看到定义了errEAGAIN等变量，注释写为了防止在运行时分配，
然后想知道是怎么防止运行时分配的
然后在epoll_optimized_poller.go的123行把epollWait()返回的err添加打印fmt.Printf("%v, %t, %v, %t", err, err, &err, &err)
比如当err都是unix.EINTR时，打印的结果都不一样，没看懂是怎么防止运行时分配的
