### ISSUE TITLE
需要设置超时时间（DeadLine），是否可以把底层的 net.Conn 暴露出来？

### ISSUE THREAD

**Issue by ycyuxin** [panjf2000/gnet#277]
从 Issues 中发现类似的需求还不少：

- #43
- #83
- #170
- #209

如果把底层的 net.Conn 暴露出来，就可以使用下面的代码设置超时时间了：

```go
c.NetConn().SetReadDeadline(time.Now().Add(3 * time.Second))
```

不知道作者有没有考虑这么做呢？

**Comment by panjf2000** [comment]
gnet 底层没有使用 `net.Conn`，是自己实现的，之前没有做是考虑到应用层实现这个功能也不麻烦，不过这个功能会在 gnet v2 中实现，v2 应该会实现 `net.Conn` 这个接口的所有方法。
