### ISSUE TITLE
eventloop的false-sharing疑问

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#279]
请问下在0bfade3aea015a7932b0e45b646a6c85a620a205节点把eventloop结构体的prevents false-sharing相关的代码移除掉是出于什么考虑呢

**Comment by panjf2000** [comment]
目前 `eventloop` 的大小已经默认超过 64KB 了，早就远远超过 CPU cache line 了，而且 `eventloop` 现在也不是连续分配的，所以目前 false-sharing 已经没有必要了。
