### ISSUE TITLE
问题: address already in use #229

### ISSUE THREAD

**Issue by rizzi37** [panjf2000/gnet#281]
请问 `mac` 下遇到这个问题如何解决,

```
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
```
这个无法解决

**Comment by panjf2000** [comment]
拉最新的代码，设置 reuseaddr：
https://github.com/panjf2000/gnet/blob/f7a3adadd83bbc79803d8eb464cb0575fd355892/options.go#L166
