### ISSUE TITLE
gnet Client Tags版本大概什么时候会发布？

### ISSUE THREAD

**Issue by JoyZou** [panjf2000/gnet#282]

**Comment by panjf2000** [comment]
顺利的话下周，下个月肯定会发布。

**Comment by JoyZou** [comment]
3qu

**Comment by xj524598** [comment]
请问现在这个项目几个人维护，想引用该库到公司生产，但是担心panjf2000一个人经历不够，无法及时解决我们的issue

**Comment by k96331** [comment]
请问gnet Client 建立的gnet.Conn能否直接加入到某个gent.Server实例中套用现成的Reactor机制? 如果这样gnet就非常好用了.

**Comment by panjf2000** [comment]
> 请问gnet Client 建立的gnet.Conn能否直接加入到某个gent.Server实例中套用现成的Reactor机制? 如果这样gnet就非常好用了.

暂时没有这样计划。

**Comment by xj524598** [comment]
gnet是否有计划引入 http1和http2c的 codec？
