### ISSUE TITLE
'client.go' is ignored by the build tool because of the windows mismatch

### ISSUE THREAD

**Issue by tigerxuz** [panjf2000/gnet#285]

**Comment by panjf2000** [comment]
Sorry, gnet client is now only available on Liunx and BSD-like OS's, not supported on Windows yet.

**Comment by panjf2000** [comment]
I'm sorry to inform you that gnet v2 no longer supports Windows, see https://github.com/panjf2000/gnet/commit/a5621d66adc3dfee0a191e6a7533079d4f03e3ab, thus this issue should be closed.
