### ISSUE TITLE
ring_buffer_unix.go的问题

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#288]
**Describe the bug**
CopyFromSocket()函数内部在grow()后可能会把isEmpty错误的置为true，导致PeekAll()时认为是没数据的

**To Reproduce**
1. 把MaxStreamBufferCap先改为1024byte
2. Decode()改成需要读到1028byte才正常返回
3. 客户端一次发送1028byte
4. 服务端会调用两次CopyFromSocket()
5. 第一次读到1024byte，但是数据不足
6. 第二次读到4byte，但是调用到Reset()把isEmpty错误改为true

**System Info (please complete the following information):**
 - gnet version (e.g. v1.0.0): SHA-1: b8d571dd762cb79c2c685f16d36886f6edb40195

**Comment by panjf2000** [comment]
`CopyFromSocket` 哪有调用 Reset()？把你的代码贴出来我看下

**Comment by panjf2000** [comment]
更新到 v1.6.0 再重试一下，你现在应该不是最新的gnet。

**Comment by zhu121** [comment]
> `CopyFromSocket` 哪有调用 Reset()？把你的代码贴出来我看下
CopyFromSocket()函数会调用rb.grow()->rb.Read()->rb.Reset()

以下是自定义的一个ICodec
`type testCodec struct {
}

func (cc *testCodec) Encode(c gnet.Conn, buf []byte) (out []byte, err error) {
	return
}

func (cc *testCodec) Decode(c gnet.Conn) ([]byte, error) {
	var buf innerBuffer
	buf = c.Read()
	msg, _ := buf.readN(1028)
	if msg == nil {
		return nil, nil
	}
	c.ShiftN(1028)
	return msg, nil
}`

**Comment by panjf2000** [comment]
谢谢你发现这个bug。
@zhu121
