### ISSUE TITLE
大量连接断开nil错误

### ISSUE THREAD

**Issue by luyu6056** [panjf2000/gnet#29]
1. 监听tcp端口，使用多核，使用端口重用
2. 客户端打开1W个连接，并且等到1W个连接，连接成功
3. 关掉客户端
4. 服务器抛出一个nil错误，并且退出

![image](https://user-images.githubusercontent.com/30688922/67547355-7a5ec480-f731-11e9-9619-37f1aafbe40b.png)

**System Info (please complete the following information):**
 - OS (e.g. Linux):  ubuntu 19.10
 - Go Version (e.g. Go 1.13):  1.13.3
 - gnet Version (e.g. v1.0.0-beta.3):  v1.0.0-beta7

**Additional context**
客户端协议使用 github.com/gorilla/websocket 实现，服务端协议轻微修改

**Comment by panjf2000** [comment]
@luyu6056 
看这个报错，reuseport没有设置对，贴一下服务端代码我看下？

**Comment by luyu6056** [comment]
![image](https://user-images.githubusercontent.com/30688922/67550418-058f8880-f739-11e9-86af-738a0d6a3b84.png)
![image](https://user-images.githubusercontent.com/30688922/67550421-0cb69680-f739-11e9-9429-4a51424e1c3f.png)
这是服务器代码
并没有过多的设置什么

**Comment by luyu6056** [comment]
![image](https://user-images.githubusercontent.com/30688922/67550524-4ab3ba80-f739-11e9-999b-b9fbaf9e4ed0.png)
![image](https://user-images.githubusercontent.com/30688922/67550555-5bfcc700-f739-11e9-8012-7f60a3f60004.png)
客户端代码crtl+c退出

**Comment by panjf2000** [comment]
@luyu6056 
很奇怪，看你的设置好像没什么问题，但是最后并没有开启 reuseport 模式，server 的代码不完整，copy 一份完整的出来吧

**Comment by luyu6056** [comment]
package main

//2019-10-16 修改为gnet作为http服务器
import (
	"bbs/config"
	_ "bbs/controllers/admin"
	_ "bbs/controllers/web"
	"bbs/db"
	"bbs/db/mysql"
	"bbs/httpserver"
	"bbs/libraries"
	"bbs/models"
	"bbs/protocol"
	"fmt"
	"io/ioutil"
	"log"
	"math/rand"
	"os"
	"runtime/debug"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/panjf2000/ants"
	"github.com/panjf2000/gnet"
)

type httpServer struct {
	*gnet.EventServer
	addr string
	pool *ants.Pool
}

var context_pool = sync.Pool{New: func() interface{} {
	return &httpserver.ConnCtx{Out: new(protocol.MsgBuffer)}
}}

func (hs *httpServer) OnInitComplete(srv gnet.Server) (action gnet.Action) {
	log.Printf("http server started on %s (loops: %d)", hs.addr, srv.NumLoops)
	return
}
func (hs *httpServer) OnOpened(c gnet.Conn) (out []byte, action gnet.Action) {
	ctx := c.Context()
	if ctx == nil {
		ctx = context_pool.Get()
		c.SetContext(ctx)
	}
	return
}
func (hs *httpServer) OnClosed(c gnet.Conn, err error) (action gnet.Action) {
	if ctx := c.Context(); ctx != nil {
		if ctx.(*httpserver.ConnCtx).WSconn != nil {
			ctx.(*httpserver.ConnCtx).WSconn.Close = true
		}
		ctx.(*httpserver.ConnCtx).WSconn = nil
		context_pool.Put(ctx)
	}
	return
}
func (hs *httpServer) React(c gnet.Conn) (out []byte, action gnet.Action) {
	data := c.Read()

	// process the pipeline
	ctx := c.Context().(*httpserver.ConnCtx)

	if ctx.WSconn == nil {
		tmp_ctx := httpserver.Context_pool.Get().(*httpserver.Context)
		defer httpserver.Context_pool.Put(tmp_ctx)
		shift, err := parsereq(data, tmp_ctx.Request)

		if err != nil {
			out = libraries.Str2bytes("HTTP/1.1 500 Error\r\nContent-Length: " + strconv.Itoa(len(err.Error())) + "\r\n\r\n" + err.Error())
			action = gnet.Close
			return
		} else if shift == 0 {
			// request not ready, yet
			return
		}
		ctx.Out.Reset()
		tmp_ctx.Conn = ctx
		tmp_ctx.Request.RemoteAddr = c.RemoteAddr().String()
		defer func() {
			if err := recover(); err != nil {
				fmt.Println(err)
				debug.PrintStack()
			}
			tmp_ctx.Save_errlog()
			tmp_ctx.Recovery()
			c.ResetBuffer()
			out = ctx.Out.Bytes()
		}()
		// handle the request
		switch tmp_ctx.Request.Path {
		case "/a":
			tmp_ctx.BeginRequest("a")
			return
		case "/ws":
			err := tmp_ctx.Upgradews(c.AsyncWrite)
			if err != nil {
				libraries.DEBUG(err)
				action = gnet.Close
			}
			return
		}
		static(tmp_ctx)
		return
	} else {
		ws := ctx.WSconn
		ws.In.Write(data)
		for ws.In.Len() > 0 {
			msgtype, p, err := ws.ReadMessage()
			if msgtype == httpserver.WaitFrame {
				break
			}
			if err != nil {
				action = gnet.Close
				return
			}
			if msgtype == httpserver.CloseMessage {

				action = gnet.Close
				return
			}
			if len(p) < 4 { //"Error data len"
				break
			}
			tmpctx := httpserver.Context_pool.Get().(*httpserver.Context)
			tmpctx.Conn = ws.Conn
			tmpctx.Request.Body.SetBytes(p)

			hs.pool.Submit(func() {
				if ws.Close {
					httpserver.Context_pool.Put(tmpctx)
					return
				}
				tmpctx.Wshand()
				httpserver.Context_pool.Put(tmpctx)
			})
			ws.In.Shift(ws.ReadLength)
		}

		c.ResetBuffer()
	}
	return
}

func main() {
	mysql.Init_register_db = append(mysql.Init_register_db, db.DB_init)
	mysql.Init_register_db = append(mysql.Init_register_db, db.DBlog_init)
	mysql.Mysql_init()
	models.Model_init()
	pool, _ := ants.NewPool(500)
	http := &httpServer{addr: config.Server.Listen, pool: pool}
	defer http.pool.Release()
	// We at least want the single http address.
	//addr := fmt.Sprintf("unix"+"://:%d", port)
	os.Remove(config.Server.Listen)

	// Start serving!
	log.Fatal(gnet.Serve(http, config.Server.Listen, gnet.WithMulticore(true)), gnet.WithTCPKeepAlive(time.Second*600), gnet.WithReusePort(true))
}

func init() {

	rand.Seed(time.Now().UnixNano())
}

var static_patch = "./static"

func static(ctx *httpserver.Context) {
	b, err := ioutil.ReadFile(static_patch + ctx.Request.Path)
	if err != nil {
		libraries.Log("请求%s未找到", ctx.Request.Path)
		ctx.Conn.Out.WriteString("HTTP/1.1 404 Error\r\nContent-Length: 13\r\n\r\n404 Not Found")
	} else {
		ctx.Conn.Out.WriteString("HTTP/1.1 200 OK\r\nConnection: keep-alive\r\n")
		s := strings.Split(ctx.Request.Path, ".")
		name := s[len(s)-1]
		switch {
		case strings.Contains(name, "css"):
			ctx.Conn.Out.WriteString("Content-Type: text/css\r\n")
			b = libraries.DogzipCompress(b)
			ctx.Conn.Out.WriteString("Content-Encoding: gzip\r\n")
		case strings.Contains(name, "gif"):
			ctx.Conn.Out.WriteString("Content-Type: image/gif\r\n")
		case strings.Contains(name, "html"):
			ctx.Conn.Out.WriteString("Content-Type: text/html;charset=utf-8\r\n")
			b = libraries.DogzipCompress(b)
			ctx.Conn.Out.WriteString("Content-Encoding: gzip\r\n")
		case strings.Contains(name, ".js"):
			ctx.Conn.Out.WriteString("Content-Type: application/javascript\r\n")
			b = libraries.DogzipCompress(b)
			ctx.Conn.Out.WriteString("Content-Encoding: gzip\r\n")
		case strings.Contains(name, ".png"):
			ctx.Conn.Out.WriteString("Content-Type: image/png\r\n")
		case strings.Contains(name, ".swf"):
			ctx.Conn.Out.WriteString("Content-Type: application/x-shockwave-flash\r\n")
		}
		ctx.Conn.Out.WriteString("Content-Length: ")
		ctx.Conn.Out.WriteString(strconv.Itoa(len(b)))
		ctx.Conn.Out.WriteString("\r\n\r\n")
		ctx.Conn.Out.Write(b)

	}
}

func parsereq(data []byte, req *httpserver.Request) (shift int, err error) {
	sdata := libraries.Bytes2str(data)
	var i, s, top int

	//var top string
	var clen int
	var q = -1
	// method, path, proto line
	req.Proto = ""
	for ; i < len(sdata); i++ {
		if sdata[i] == ' ' {
			req.Method = sdata[s:i]
			for i, s = i+1, i+1; i < len(sdata); i++ {
				if sdata[i] == '?' && q == -1 {
					q = i
				} else if sdata[i] == ' ' {
					if q != -1 {
						req.Path = sdata[s:q]
						req.Query = sdata[q+1 : i]
					} else {
						req.Path = sdata[s:i]
					}
					for i, s = i+1, i+1; i < len(sdata); i++ {
						if sdata[i] == '\n' && sdata[i-1] == '\r' {
							req.Proto = sdata[s:i]
							i, s = i+1, i+1
							break
						}
					}
					break
				}
			}
			break
		}
	}

	if req.Proto == "" {
		return 0, fmt.Errorf("malformed request")
	}
	//top = sdata[:s]
	top = s
	for ; i < len(sdata); i++ {
		if i > 1 && sdata[i] == '\n' && sdata[i-1] == '\r' {
			line := sdata[s : i-1]
			s = i + 1
			if line == "" {
				req.Head = sdata[top : i+1]
				i++
				if clen > 0 {
					if len(sdata[i:]) < clen {
						break
					}
					req.Body.Reset()
					req.Body.Write(data[i : i+clen])
					i += clen
				}
				return i, nil
			}

			if len(line) > 15 && (line[:15] == "Content-Length:" || line[:15] == "Content-length:") {
				clen, err = strconv.Atoi(line[16:])
			}

		}
	}

	// not enough data
	return 0, nil
}

**Comment by panjf2000** [comment]
客户端还没写完数据你就 ctrl + c 退出？

**Comment by panjf2000** [comment]
@luyu6056 
另外，`gnet` 内部是有两个网络模型的，默认是主从 Reactors 模型，但是如果开启 reuseport 用的是多 Reactors 模型，我看你设置了 reuseport 最终却用的是第一种模型，说明没设置成功，很诡异，我自己试了一下是可以正常开启 reuseport 的，不知道你那边是怎么回事，你可以 debug 一下，关闭 go modules 然后直接用本地的 gnet 代码，加点 log 看看。

**Comment by panjf2000** [comment]
还有，不需要自己 import ants，gnet 已经把 ants 集成了，直接用内置的就可以了，
参考这个：https://github.com/panjf2000/gnet#echo-server-with-blocking-logic

**Comment by luyu6056** [comment]
> 还有，你说是大量连接才会出这个问题？如果是少量连接的情况下就不会有这个错误？

在浏览器一直刷新，不断进行断开重连，不会出现这个问题

**Comment by panjf2000** [comment]
不懂你的意思。。。
我是想知道重现这个错误的必要条件是不是：
1. 频繁新建大量连接
2. 客户端 ctrl+c 中断退出

**Comment by luyu6056** [comment]
> 不懂你的意思。。。
> 我是想知道重现这个错误的必要条件是不是：
> 
> 1. 频繁新建大量连接
> 2. 客户端 ctrl+c 中断退出

beta8 这个错误似乎是100%出现，与之前的版本不一样的是，似乎是waitForShutdown出问题
当不断的打开浏览器，关闭浏览器，让浏览器断开与新建连接，我发现OnClosed事件被一直执行，刷新pprof/goroutine，会看到有一条loop执行到gnet_server.go:37。
使用浏览器打开关闭网页，除了异常响应（可能是业务代码问题）之外并不会抛出错误。
使用客户端进行5000个连接，发送数据中，ctrl+c中断，再重连，就会报nil，并且在同样的位置

**Comment by luyu6056** [comment]
> 不懂你的意思。。。
> 我是想知道重现这个错误的必要条件是不是：
> 
> 1. 频繁新建大量连接
> 2. 客户端 ctrl+c 中断退出

我曾经用atomic.AddInt32去计算OnClosed调用次数，浏览器打开关闭几次（彻底关闭exe）出现异常后，onclosed会一直执行，似乎没有停止的打算，已经统计到十几万次，然后我手动ctrl+c关闭了。OnOpened是正常的，只调用了十几次。并且我发现客户端5000连接二次重连的时候，似乎调用了OnOpened之后在没有断开连接的情况下，调用了onclosed

**Comment by panjf2000** [comment]
应该和 waitForShutdown 没关系，gnet 启动之后就会停在 waitForShutdown 处，等待关闭 server 的信号。

**Comment by panjf2000** [comment]
至于 nil 错误和 onClosed 不停被调用的问题，初步怀疑是你用 AsyncWrite 的问题，因为是异步写，等到真正写数据的时候，连接已经关闭了，进而出现问题，明天再看看。

**Comment by luyu6056** [comment]
> 至于 nil 错误和 onClosed 不停被调用的问题，初步怀疑是你用 AsyncWrite 的问题，因为是异步写，等到真正写数据的时候，连接已经关闭了，进而出现问题，明天再看看。

我追查了一下，关闭了ReusePort，在我不断打开，关闭浏览器链接之后，会产生以下流程：
1.epoll.go第70行，从unix.EpollWait，不断产生n=1的事件
2.进入到reactor_linux.go判断outboundBuffer，由于浏览器已经彻底关闭，很明显outboundBuffer是空的。
3.eventloop.go的loopIn，由于浏览器关闭， unix.Read报错 bad file descriptor，进入loopCloseConn与OnClosed。
4.不断重复1-3过程，意思就是unix.EpollWait不断执行。


以下是我的OnClosed代码
	if ctx := c.Context(); ctx != nil {
		if ctx.(*httpserver.ConnCtx).WSconn != nil {
			ctx.(*httpserver.ConnCtx).WSconn.Close = true
		}
		ctx.(*httpserver.ConnCtx).WSconn = nil
		context_pool.Put(ctx)
	}
	return

**Comment by luyu6056** [comment]
> 至于 nil 错误和 onClosed 不停被调用的问题，初步怀疑是你用 AsyncWrite 的问题，因为是异步写，等到真正写数据的时候，连接已经关闭了，进而出现问题，明天再看看。

go 1.13.3版本
golang.org/x/sys的packed-refs是1.13版本
fde4db37ae7ad8191b03d30d27f258b5291ae4e3 refs/remotes/origin/release-branch.go1.13

**Comment by panjf2000** [comment]
我大概理解你说的导致问题的步骤，但是我不太理解为什么会不断重复，按理说应该把连接关闭一次就完了，怎么会不断重复呢？

**Comment by luyu6056** [comment]
> 我大概理解你说的导致问题的步骤，但是我不太理解为什么会不断重复，按理说应该把连接关闭一次就完了，怎么会不断重复呢？

我大概知道什么原因，上面说了，我统计过OnClosed与OnOpened，然后我发现OnClosed的执行次数比OnOpened要多，这就导致了lp.svr.connPool.Put重复的把一个conn，Put进去2次，然后前面池子Get包含了两个同样的conn。
也因为这样，我两个链接，拿到同一个conn，其中一个链接关闭掉，执行delete(lp.connections, c.fd)，把lp.connections[c.fd]删掉。而另一个链接使用同一个conn，执行到上面报nil的地方，取lp.connections[c.fd]肯定是nil了。
解决方法
1.查看为何多执行了loopCloseConn，保证同一个conn不被put两次
2.不用lp.svr.connPool池，没任何问题，这个你肯定不采用。
3.对loopCloseConn加锁，当lp.connections[c.fd]为空的时候,就不要再put了,还是会影响性能.

我再看看是否能找到一个链接loopCloseConn被执行两次的问题,这个是根源

**Comment by luyu6056** [comment]
> 我大概理解你说的导致问题的步骤，但是我不太理解为什么会不断重复，按理说应该把连接关闭一次就完了，怎么会不断重复呢？

我发现,,某些链接在执行了lp.poller.Delete之后,还会触发一次lp.poller.Delete,问题就在这,第一次delete成功之后,把conn Put到池子去,第二次delete报err,但是你没对err处理,又二次put到池子去,所以现在最快的解决方法,二选一
1.
	if err := lp.poller.Delete(c.fd); err == nil {
		delete(lp.connections, c.fd)
		_ = unix.Close(c.fd)
		
	} else {
		return err
	}
2.
	if err == nil {
		c.reset()
		lp.svr.connPool.Put(c)
	}

**Comment by luyu6056** [comment]
> 我大概理解你说的导致问题的步骤，但是我不太理解为什么会不断重复，按理说应该把连接关闭一次就完了，怎么会不断重复呢？

我对lp.poller.Delete(c.fd)产生的err进行 return,就不会产生问题了,你确认一下,应该可以关掉这个issue,读写冲突的问题应该与此有关,你再出个beta9,我测一下异步ayscwrite没问题,再关掉那个issue

**Comment by panjf2000** [comment]
> 也因为这样，我两个链接，拿到同一个conn，其中一个链接关闭掉，执行delete(lp.connections, c.fd)，把lp.connections[c.fd]删掉。而另一个链接使用同一个conn，执行到上面报nil的地方，取lp.connections[c.fd]肯定是nil了。

这个不对吧，就算是 pool 有两个指向同一个 conn 的引用被不同的连接拿到了，但是不同连接的 fd 是不同的，其中一个从 map 里删掉 conn 也是自己的 fd 作为 key，不会删掉另一个 fd，第二个来取的时候不会有 nil 问题的。

**Comment by luyu6056** [comment]
> > 也因为这样，我两个链接，拿到同一个conn，其中一个链接关闭掉，执行delete(lp.connections, c.fd)，把lp.connections[c.fd]删掉。而另一个链接使用同一个conn，执行到上面报nil的地方，取lp.connections[c.fd]肯定是nil了。
> 
> 这个不对吧，就算是 pool 有两个指向同一个 conn 的引用被不同的连接拿到了，但是不同连接的 fd 是不同的，其中一个从 map 里删掉 conn 也是自己的 fd 作为 key，不会删掉另一个 fd，第二个来取的时候不会有 nil 问题的。不过两个引用指向同一个 conn 的确是一个问题。

会的，同时并发时候，流程大概是这样
链接1拿到conn
链接2拿到conn
链接1赋予了c.fd=1
链接2紧接着赋予了c.fd=2
链接1存map，这时候c.fd已经是2
链接2存map，这时候c.fd还是2，
你看，这样子不但会报nil，还会可能产生读写冲突。

读写冲突的流程，大概是这个模型。
链接1拿了conn
链接2拿了conn
...
map都存了c.fd=2
然后链接1，并发了一个读取
在31行读取map[c.fd]
链接2，并发了一个delete，在close那里
delete(map,c.fd)
这样是不是map读写冲突也解决了？

**Comment by panjf2000** [comment]
你的理解是错的，accept 流程：
```go
	lp := svr.subLoopGroup.next()
	c := svr.connPool.Get().(*conn)
	c.fd = nfd
	c.loop = lp
	c.sa = sa
	_ = lp.loopOpen(c)
	_ = lp.poller.Trigger(func() (err error) {
		if err = lp.poller.AddRead(nfd); err == nil {
			lp.connections[nfd] = c
			return
		}
		return
	})
	return nil
```
这里往 map 里存 conn 的时候用的是 nfd，这是每个连接的唯一 fd，通过闭包引用传过去的，不会变化，而且这个操作是发到 eventloop 的那个 goroutine 里执行的，并不是在 accpter 这个 goroutine 执行的，读取 map 和 删除 map 的值，也是同理，全部都是在单 goroutine 里做的，你再仔细看看，不会导致 race 问题。

**Comment by luyu6056** [comment]
> > 也因为这样，我两个链接，拿到同一个conn，其中一个链接关闭掉，执行delete(lp.connections, c.fd)，把lp.connections[c.fd]删掉。而另一个链接使用同一个conn，执行到上面报nil的地方，取lp.connections[c.fd]肯定是nil了。
> 
> 这个不对吧，就算是 pool 有两个指向同一个 conn 的引用被不同的连接拿到了，但是不同连接的 fd 是不同的，其中一个从 map 里删掉 conn 也是自己的 fd 作为 key，不会删掉另一个 fd，第二个来取的时候不会有 nil 问题的。不过两个引用指向同一个 conn 的确是一个问题。

不对，读写冲突应该是这样
链接1拿了conn，nfd=1
链接2拿了conn，nfd=2
最后c.fd=2，
链接1经过了accept ，这时候准备close，delete(lp.connections,c.fd)，同时delete(map,2),和map[2]=c
链接2刚进入accept ，lp.connections[nfd] = c

**Comment by luyu6056** [comment]
不对，应该是accept的map[fd]=c与31行c=map[fd]，这两个位置------------------ 原始邮件 ------------------
发件人: "Andy Pan"<notifications@github.com>
发送时间: 2019年10月26日(星期六) 晚上6:11
收件人: "panjf2000/gnet"<gnet@noreply.github.com>;
抄送: "luyu6056"<343636111@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [panjf2000/gnet] 大量连接断开nil错误 (#29)



你的理解是错的，accept 流程：
 	lp := svr.subLoopGroup.next() 	c := svr.connPool.Get().(*conn) 	c.fd = nfd 	c.loop = lp 	c.sa = sa 	_ = lp.loopOpen(c) 	_ = lp.poller.Trigger(func() (err error) { 		if err = lp.poller.AddRead(nfd); err == nil { 			lp.connections[nfd] = c 			return 		} 		return 	}) 	return nil
 
这里往 map 里存 conn 的时候用的是 nfd，这是每个连接的唯一 fd，通过闭包引用传过去的，不会变化，而且这个操作是发到 eventloop 的那个 goroutine 里执行的，并不是在 accpter 这个 goroutine 执行的，读取 map 和 删除 map 的值，也是同理，全部都是在单 goroutine 里做的，你再仔细看看，不会导致 race 问题。
 
&mdash;

**Comment by panjf2000** [comment]
你说的这个是导致 nil 的原因，这的确是可能的。
至于 race 问题，你还是没理解的 gnet 的架构，我刚才说了， acceptor 没有执行 `lp.connections[nfd] = c` 这个操作，它是发到 eventloop 所在的 goroutine 去执行的。

**Comment by panjf2000** [comment]
要不你方便的话加我微信聊吧：panjf2000，这样效率高一点。

**Comment by luyu6056** [comment]
我明白了，这里改了，所以不会出现读写冲突，这几天我怎么测都不会，那就是delete的时候，链接1把链接2的c.fd删除了，链接2就出现nil------------------ 原始邮件 ------------------
发件人: "Andy Pan"<notifications@github.com>
发送时间: 2019年10月26日(星期六) 晚上6:11
收件人: "panjf2000/gnet"<gnet@noreply.github.com>;
抄送: "luyu6056"<343636111@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [panjf2000/gnet] 大量连接断开nil错误 (#29)



你的理解是错的，accept 流程：
 	lp := svr.subLoopGroup.next() 	c := svr.connPool.Get().(*conn) 	c.fd = nfd 	c.loop = lp 	c.sa = sa 	_ = lp.loopOpen(c) 	_ = lp.poller.Trigger(func() (err error) { 		if err = lp.poller.AddRead(nfd); err == nil { 			lp.connections[nfd] = c 			return 		} 		return 	}) 	return nil
 
这里往 map 里存 conn 的时候用的是 nfd，这是每个连接的唯一 fd，通过闭包引用传过去的，不会变化，而且这个操作是发到 eventloop 的那个 goroutine 里执行的，并不是在 accpter 这个 goroutine 执行的，读取 map 和 删除 map 的值，也是同理，全部都是在单 goroutine 里做的，你再仔细看看，不会导致 race 问题。
 
&mdash;

**Comment by panjf2000** [comment]
对，如果按照你说的 OnClosed 意外地多次执行，delete 那个操作的确会导致问题。

**Comment by panjf2000** [comment]
@luyu6056 
Hello, 我大概知道了问题出在哪了，`loopCloseConn` 之所以被触发多次，我想是因为你调用了多次 `AsyncWrite`，然后 gnet 会异步调用 `conn.write()`:
```
func (c *conn) write(buf []byte) {
	if !c.outboundBuffer.IsEmpty() {
		_, _ = c.outboundBuffer.Write(buf)
		return
	}
	n, err := unix.Write(c.fd, buf)
	if err != nil {
		if err == unix.EAGAIN {
			_, _ = c.outboundBuffer.Write(buf)
			_ = c.loop.poller.ModReadWrite(c.fd)
			return
		}
		_ = c.loop.loopCloseConn(c, err)
		return
	}
	if n < len(buf) {
		_, _ = c.outboundBuffer.Write(buf[n:])
		_ = c.loop.poller.ModReadWrite(c.fd)
	}
}
```
然后你在客户端还在发数据的时候就中断进程，所有连接被动关闭，会触发 `loopCloseConn`，接着 `conn.write()` 被真正执行，试图往当前已经关闭了的连接写数据，结果导致再一次触发 `loopCloseConn`，这就是为什么这个函数会被多次触发。然后因为之前 gnet 里没有处理这种情况导致了这个返回 nil 的这个 bug，我已经 push 了一个修复，你在 go.mod 把更新到 gnet 更新成 master 然后再测试一下吧，如果没有问题我就 push 一个新的 release了，谢谢。

**Comment by panjf2000** [comment]
最新的 release：v1.0.0-beta.10

**Comment by luyu6056** [comment]
> @luyu6056
> Hello, 我大概知道了问题出在哪了，`loopCloseConn` 之所以被触发多次，我想是因为你调用了多次 `AsyncWrite`，然后 gnet 会异步调用 `conn.write()`:
> 
> ```
> func (c *conn) write(buf []byte) {
> 	if !c.outboundBuffer.IsEmpty() {
> 		_, _ = c.outboundBuffer.Write(buf)
> 		return
> 	}
> 	n, err := unix.Write(c.fd, buf)
> 	if err != nil {
> 		if err == unix.EAGAIN {
> 			_, _ = c.outboundBuffer.Write(buf)
> 			_ = c.loop.poller.ModReadWrite(c.fd)
> 			return
> 		}
> 		_ = c.loop.loopCloseConn(c, err)
> 		return
> 	}
> 	if n < len(buf) {
> 		_, _ = c.outboundBuffer.Write(buf[n:])
> 		_ = c.loop.poller.ModReadWrite(c.fd)
> 	}
> }
> ```
> 
> 然后你在客户端还在发数据的时候就中断进程，所有连接被动关闭，会触发 `loopCloseConn`，等到 `conn.write()` 被真正执行的时候，它试图往当前这个已经关闭的连接写数据，结果导致再一次触发 `loopCloseConn`，这就是为什么这个函数会被多次触发。然后因为之前 gnet 里没有处理这种情况导致了这个返回 nil 的 bug，我已经 push 了一个修复，你在 go.mod 把更新到 gnet 更新成 master 然后再测试一下吧，如果没有问题我就 push 一个新的 release了，谢谢。

我测了一下暂时没问题，但是我给你带来一个新问题，问题出现在conn的回收与AsyncWrite，并且这个问题。我大概告诉你一下问题所在，就如你例子里面带阻塞的。
1.连接1，取了一个conn，异步处理阻塞了几秒，但是连接在1秒后就中断了
2.连接2，把上述回收的conn取出来了，收到了连接1后面发送的AsyncWrite数据，因为连接1异步goroutine 里面，最后对这个conn进行了AsyncWrite

我觉得你有必要让用户重视这个问题，避免异步处理，或者对OnClosed 进行阻塞，建议使用chan控制异步 goroutine 的数量，并且OnClosed 一直阻塞到len(chan)==0。
或者你看看怎么对AsyncWrite改造，conn使用sync池的时候无法避免

**Comment by panjf2000** [comment]
@luyu6056 
> 1.连接1，取了一个conn，异步处理阻塞了几秒，但是连接在1秒后就中断了
2.连接2，把上述回收的conn取出来了，收到了连接1后面发送的AsyncWrite数据，因为连接1异步goroutine 里面，最后对这个conn进行了AsyncWrite

> 我觉得你有必要让用户重视这个问题，避免异步处理，或者对OnClosed 进行阻塞，建议使用chan控制异步 goroutine 的数量，并且OnClosed 一直阻塞到len(chan)==0。
或者你看看怎么对AsyncWrite改造，conn使用sync池的时候无法避免

你说的没错，这里的确还有这个问题，不过我不想用阻塞或者加锁的方式来解决，我现在用了一种类似 CAS 的机制来解决：如果是需要调用 `AsyncWrite` 的业务，每次在 `React` 的入口处获取当前连接的 fd，然后最后调用 `AsyncWrite` 把 fd 传参进去，最后往客户端写数据之前判断一下当前 conn 的 fd 是不是和当时的 fd 一致，一致就写，不一致就说明 conn 已经变了，则不写。

代码在这里：https://github.com/panjf2000/gnet/commit/db0018d98e6bf6e4c620b33837a271e30d525d42

你可以看看，可以继续讨论一下，看看有没有更好的方式。

**Comment by panjf2000** [comment]
经过一番思考，我还是决定去掉 connection pool，为了复用 `conn` 对象而引入这个 connection pool，导致了很多同步问题，改完一个又发现一个可能的 race 隐患，所以还是决定暂时去掉 connection pool 这个特性，这样 `AsyncWrite` 也可以保持原状了，我等下提交下代码。

**Comment by panjf2000** [comment]
@luyu6056 
最新 release：v1.0.0-rc.1，这一版应该把我们之前讨论的所有 bugs 都解决了，你有空可以测一下。

**Comment by luyu6056** [comment]
> @luyu6056
> 最新 release：v1.0.0-rc.1，这一版应该把我们之前讨论的所有 bugs 都解决了，你有空可以测一下。

好的，我抽空测一下，关于你提的

> @luyu6056
> 
> > 1.连接1，取了一个conn，异步处理阻塞了几秒，但是连接在1秒后就中断了
> > 2.连接2，把上述回收的conn取出来了，收到了连接1后面发送的AsyncWrite数据，因为连接1异步goroutine 里面，最后对这个conn进行了AsyncWrite
> 
> > 我觉得你有必要让用户重视这个问题，避免异步处理，或者对OnClosed 进行阻塞，建议使用chan控制异步 goroutine 的数量，并且OnClosed 一直阻塞到len(chan)==0。
> > 或者你看看怎么对AsyncWrite改造，conn使用sync池的时候无法避免
> 
> 你说的没错，这里的确还有这个问题，不过我不想用阻塞或者加锁的方式来解决，我现在用了一种类似 CAS 的机制来解决：如果是需要调用 `AsyncWrite` 的业务，每次在 `React` 的入口处获取当前连接的 fd，然后最后调用 `AsyncWrite` 把 fd 传参进去，`AsyncWrite` 在最后往客户端写数据之前会判断一下当前 conn 的 fd 是不是与一开始获取的 fd 一致，一致就写，不一致就说明 conn 已经变了，则不写。
> 
> 代码已经提交到 master，测试的时候直接 `go get github.com/panjf2000/gnet@master` 使用最新的 commit。
> 
> 这种方式会导致的 `AsyncWrite` 无法向后兼容，不过我暂时也没想到更好的方式，你看下，可以继续讨论一下有没有更好的方式。

好的，有空我测一下最新版，关于这条你说的传fd进去，我有打印过，可能与WithReusePort有关，同一个ip打开关闭，再打开，得到的fd号是一样的。
conn的pool可以复用，但是你得多封装一个struct，就像我的代码一样，最外层一个ConnCtx，React里面还调用了一个Context，封装了两层ctx。
我的意思是大的conn里面，在封装多一层包含write的struct，这层不用pool，loopAccept的时候new一个，并且传到asyncwrite里面去，这样asyncwrite就不可能重复调用同一个包含write的结构体。
当然不用pool能省很多事是的

**Comment by panjf2000** [comment]
我之前已经移除了 connection pool 了，改成了 bytes pool，因为其实最开始用 connection pool 就是为了减少内存分配，但是复用 conn 会出现太多同步问题，修完一个又会发现一个，所以就移除了，现在在之前 connection pool 的实现上做了一点修改，变成 bytes pool，是一样的。

**Comment by luyu6056** [comment]
新版的测试完了
1.用于asyncwrite阻塞的例子中，只打开一个链接，在阻塞过程中进行断开，重连测试，fd值是增长的，这个避免了fd污染
2.asyncwrite阻塞完毕之后，再重连，fd会重复调用，没问题。
3.万个go写的socket链接没发生nil与map冲突，我对结果进行验证，没发现输出数据被污染
4.用firefox，opera，Chrome测试都没问题，之前用conn池的时候，firefox连网页基础数据都加载不完

结论,是可以作为rc用了

**Comment by panjf2000** [comment]
@luyu6056 
感谢你的测试！😋

不过你的描述里我有些地方没太懂，望解答：
> 1.用于asyncwrite阻塞的例子中，只打开一个链接，在阻塞过程中进行断开，重连测试，fd值是增长的，这个避免了fd污染
2.asyncwrite阻塞完毕之后，再重连，fd会重复调用，没问题。

这里面的 AsyncWrite 阻塞是什么意思？还有 fd 重复调用，也不太明白。

**Comment by luyu6056** [comment]
就是你例子里面，带阻塞的服务
_ = es.pool.Submit(func() {
		time.Sleep(1 * time.Second)
		c.AsyncWrite(data)
	})

加大一点time.Sleep时间，在该时间内，就可以看到断开再连，fd值会递增。例如，1,2,3,4
等time.sleep过了之后，再连，fd值会恢复第一个拿到的数值。
至少单机连接的时候是如此，大量连接暂时没那个心情打log出来观察。

**Comment by panjf2000** [comment]
那行，这个 issue 我先关掉了，万一后续还有问题的话，你再重新打开或者新开一个 issue， 感谢你为 gnet 找到的这个 bug，挺关键的一个问题👍
