### ISSUE TITLE
Gnet cannot support large value(>10K) redis benchmark test

### ISSUE THREAD

**Issue by slow-zhang** [panjf2000/gnet#290]
**Describe the bug**
I try to implement a redis-server by gnet,  but I cannot test by redis-benchmark 

cmd: `redis-benchmark -h <host> -p<port> -t set,get -n 1000000 -d 1000000 -r 1000000`

how I implement it in React:
1. read cmd in frame
// async
2. using immemeory map set/get
3. return value
![image](https://user-images.githubusercontent.com/24769636/145325838-1141ced4-7010-417e-a14d-d3046fa26744.png)

React: `React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) `
**To Reproduce**
just run bench

**Expected behavior**
it can test and show the result

**Screenshots**
the Screenshot shows only when -d (data size) is small it can run
![image](https://user-images.githubusercontent.com/24769636/145326359-7714e489-f864-4154-9655-2ad4883bec07.png)

**System Info (please complete the following information):**
 - OS (e.g. Ubuntu 16.04 & osx1.15): 
 - Go version (e.g. Go 1.16): 
 - gnet version (e.g. v1.6.1): 

**Additional context**
the code is simple, if you need, I can upload later

**Comment by slow-zhang** [comment]
how i start gnet: `log.Fatal(gnet.Serve(echo, dir, gnet.WithMulticore(true), gnet.WithReadBufferCap(8*1024*1024)))`

**Comment by panjf2000** [comment]
I don't think you have a full understanding of `gnet`, I'd recommend you to use `gnet.ICodec` to implement your redis server, parse and process the redis packets one by one, instead of returning `gnet.Close` when there is an incomplete packet.

**Comment by slow-zhang** [comment]
can i pass the connection reader to  the goredis.NewRespReader?

**Comment by slow-zhang** [comment]
i see the http example  here: 
![image](https://user-images.githubusercontent.com/24769636/145346003-ab5ec209-2703-450a-96ef-782d7a80f837.png)

will the buf := c.Read() read a complete request? if it's incomplete what will happen?

**Comment by slow-zhang** [comment]
![image](https://user-images.githubusercontent.com/24769636/145358864-e7edecc8-4770-46c0-894b-b6cc389ba7fd.png)
i find that the example of http is like redis. but I am confused because line 61 returns directly if there are some incomplete requests, will this cause the next error 
for example, take ABC as a complete req
user: send ABC
Decode: A: invalid
Decode: BC: invalid

**Comment by slow-zhang** [comment]
another question:
i want an inmemory redis-server using map, it will have a lock on the map. what will I do the map operator?
in React? but it don't know how the decode str to react
in Decode? 
could you provide some examples for it?

**Comment by panjf2000** [comment]
When you find there is an incomplete packet, you should return it without any error, in that case, gnet will buffer these data and continue to read data from socket, if you return gnet.Close like you did in your example, the connection will be closed, so take more time to understand gnet before you develop anything on top of it.

**Comment by panjf2000** [comment]
If you are trying to develop a redis server with gnet, take a reference from https://github.com/IceFireDB/redhub.

**Comment by slow-zhang** [comment]
how gnet know it needs to handle a req instead of read it the next time?
the interface decode/encode is hard to use? for decode read data and write to out, it seems all work will be done in encode
.
form your reply I assume if out is empty the encode will be ignore and data will be send to buffer again?

**Comment by slow-zhang** [comment]
i find that the reference you provided is not used `gnet.ICodec`. Do you know why?

**Comment by panjf2000** [comment]
> how gnet know it needs to handle a req instead of read it the next time?

If the Decode() returns a nil []byte, gnet will continue to read data from socket.

**Comment by panjf2000** [comment]
> i find that the reference you provided is not used `gnet.ICodec`. Do you know why?

gnet.ICode is just a recommended way to do it, you can also put all your code in React(), as long as you ensure you're doing it correctly.

**Comment by slow-zhang** [comment]
> If the Decode() returns a nil []byte, gnet will continue to read data from socket.
but since we read the data and reset the buf before, will some data lost?

**Comment by slow-zhang** [comment]
will this possible: 
take ABC as a complete req
user: send ABC
1. Decode: A: invalid, return nil
2. Decode: BC: invalid

will the 1. write A back to socket to make the 2. be a complete request ?

**Comment by slow-zhang** [comment]
![image](https://user-images.githubusercontent.com/24769636/145518596-6b2ad7e4-3906-4065-96cc-6a28faa5ee93.png)
this http example will discard incomplete req for it reset buffers

I find if we discard only when we handled data it will be fine

**Comment by slow-zhang** [comment]
but it still cannot pass the large value benchmark
![image](https://user-images.githubusercontent.com/24769636/145519014-1269a06d-a0ad-4d91-93c3-85e3dd592039.png)
the cmd `/usr/local/opt/redis@3.2/bin/redis-benchmark -t set,get -n 3 -d 100000 -r 100000 -c 1 -p <port>` will be slow.
by debug i found there are always some incomplete req to the decode so it hangs for a long time

**Comment by slow-zhang** [comment]
create other issue about this https://github.com/panjf2000/gnet/issues/297
