### ISSUE TITLE
Will gnet support long connection?

### ISSUE THREAD

**Issue by slow-zhang** [panjf2000/gnet#291]
**What is your question about gnet?**

i want to hold a var for a connection for such as auth and some client related info? is it possible?

**Comment by panjf2000** [comment]
Not so sure what you meant about long connection, gnet doesn't close any connection unless there is an error or the user calls Conn.Close().

**Comment by slow-zhang** [comment]
i mean in each React, we can get some var such as ConnInfo holds authed, DB choosed, cursor... 
this var is connection related infos

**Comment by slow-zhang** [comment]
i see there is a set/get Context in gnet, can I use the context to keep a pointer to struct to hold some info about this connection

**Comment by panjf2000** [comment]
yes
