### ISSUE TITLE
Gnet hangs on receive incomplete request

### ISSUE THREAD

**Issue by slow-zhang** [panjf2000/gnet#297]
**What is your question about gnet?**
i implement a redis server using gnet, but it can only pass the benchmark when one client send one request (-c 1, -n 1)
this is `/usr/local/opt/redis@3.2/bin/redis-benchmark -t set,get -n 1 -d 100000 -r 100000 -c 1 -p <port>`

when set multi request (-c 1, -n 10)
this is `/usr/local/opt/redis@3.2/bin/redis-benchmark -t set,get -n 10 -d 100000 -r 100000 -c 1 -p <port>`

here is my impl https://github.com/slow-zhang/gnet-test, am I use gnet by the error way?

**Comment by panjf2000** [comment]
Use `dlv` to find out why.

**Comment by slow-zhang** [comment]
i have using dlv and find the reason just like the title: Gnet hangs on receive incomplete request

**Comment by panjf2000** [comment]
Share more details with me?

**Comment by slow-zhang** [comment]
the redis-bench is hung and for the example the buf is always nil.

you can try the cmd by you self: `/usr/local/opt/redis@3.2/bin/redis-benchmark -t set,get -n 10 -d 100000 -r 100000 -c 1 -p <port>`
![image](https://user-images.githubusercontent.com/24769636/146518177-43d924e5-b6f2-4b87-b2bf-c66601d1464f.png)

**Comment by Spongecaptain** [comment]
@slow-zhang @panjf2000 
`if len(buf) == 0` is true, we should `return nil,gerrors.ErrIncompletePacket`instead of just `return`.

Please see this example of using client in gnet: https://github.com/Spongecaptain/gnet-examples/blob/master/examples/custom_codec/protocol/pb.go#L95, it may help.

**Comment by slow-zhang** [comment]
thanks for helping! i will fix it later

**Comment by slow-zhang** [comment]
after I fixed this error , the code can not even pass the benchmark when one client send one request (-c 1, -n 1)

here is the code after fixed: https://github.com/slow-zhang/gnet-test/blob/main/main.go#L142

![image](https://user-images.githubusercontent.com/24769636/147535214-1350e419-580f-4132-bb3d-247dc08d8b63.png)

**Comment by panjf2000** [comment]
Please upgrade to gnet v1.6.4 and try again.

**Comment by slow-zhang** [comment]
so can i assume that there is a bug fix for it?
