### ISSUE TITLE
无法编译运行 example codec/server

### ISSUE THREAD

**Issue by diamond0209** [panjf2000/gnet#298]
go get github.com/panjf2000/gnet/pool/goroutine: module github.com/panjf2000/gnet@upgrade found (v1.6.3), but does not contain package github.com/panjf2000/gnet/pool/goroutine

环境：WSL ubuntu20.04 
go version：go version go1.13.8 linux/amd64
golang 使用apt 安装

**Comment by diamond0209** [comment]
go env:
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/snk/.cache/go-build"
GOENV="/home/snk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/snk/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build968110613=/tmp/go-build -gno-record-gcc-switches"

**Comment by panjf2000** [comment]
不要重复开 issue: https://github.com/gnet-io/gnet-examples/issues/9
