### ISSUE TITLE
ants异步处理

### ISSUE THREAD

**Issue by taozix** [panjf2000/gnet#299]
有个疑问：当一个客户端通过一个conn不断发消息，reactor将消息异步处理，最后进行AsyncWrite时，因为都是write到同一个conn，需自行加锁吗，还是gnet或者ants已经做了？谢谢。

**Comment by mikeqoo1** [comment]
我的理解是不需要, 除非你的資料是有順序性的

**Comment by taozix** [comment]
只要保证消息完整、单个消息没有顺序要求。

**Comment by panjf2000** [comment]
`AsyncWrite()` 是并发安全的，不需要用户加锁。
