### ISSUE TITLE
大量连接发送与接收消息中，再断开导致map读写冲突

### ISSUE THREAD

**Issue by luyu6056** [panjf2000/gnet#30]
1. 服务端监听tcp，使用多核端口复用
2. 客户端2W连接（足够多可能就会触发）
3. cpu是6核12线，发送与接收数据，客户端接收速度约5万qps
4. 数据未发送与接收完毕时，关闭客户端
![image](https://user-images.githubusercontent.com/30688922/67547883-d2e29180-f732-11e9-8555-ccdcff5865cf.png)

**System Info (please complete the following information):**
 - OS (e.g. Linux): ubuntu 19.10
 - Go Version (e.g. Go 1.13):  1.13.3
 - gnet Version (e.g. v1.0.0-beta.3): v1.0.0-beta.7 

**Additional context**
附加一个建议，AsyncWrite是异步写出，导致我的写出消息[]bye，需要一直make 和 copy，我修改AsyncWrite为同步写出，不需要copy一份数据就能输出无错误，所以我需要一个直接输出消息的Write接口

**Comment by panjf2000** [comment]
需要同步写出，就直接赋值给 `out` 返回值就行了，AsyncWrite 一般是在业务 goroutine 里调用的。

**Comment by panjf2000** [comment]
这个我看也是没有设置 reuseport，是不是设置错了，还有贴一下具体服务端代码和客户端代码。

**Comment by luyu6056** [comment]
上一个 issue我贴出了服务器main.go的代码，在ReadMessage之后，调用pool.Submit不断去并发业务流程写出AsyncWrite，如果不开多个goroutine，由于业务代码轻微阻塞，cpu占用只能达到200-300%的调用。

**Comment by luyu6056** [comment]
我还做了另一个处理模型，就是一个conn只产生一个goroutine去处理的模型，这个就是只有一个goroutine去处理业务和写出，之前的消息缓冲有问题，进来的消息得不到及时处理，占用多了几个G的内存，我再试试用另一种方法处理，看看能不能降低内存占用

**Comment by panjf2000** [comment]
这和你是不是多个 goroutine 没关系，调用 AsyncWrite 最后也是在同一个 eventloop 里执行的，肯定不会导致 race，我现在还是不懂为什么你会遇到这个问题，你把错误输出里说的哪些地方导致 race 贴出来我看下。

**Comment by luyu6056** [comment]
我现在无法重现，但是又出现另一个问题，客户端断开后，二次连接，就会收到一些莫名其妙的数据，并且确定是与WithReusePort有关，关掉这个选项，是可以不断的进行断开，重连的操作。
客户端与服务器都是在同一台hyper虚拟机上运行，是否与ubuntu 19.10有关？

**Comment by luyu6056** [comment]
代码还是之前那份，对hs.pool.Submit进行屏蔽，也就是没有进行异步AsyncWrite 处理，客户端连接设置是1万个

**Comment by panjf2000** [comment]
不是，我是说，终端上不是有错误输出错误信息吗，那里会说哪些地方的读写导致冲突，你复制一下我看下是哪里的问题。

**Comment by luyu6056** [comment]
上面贴有一个截图，我反复重试才截到的，reactor_linux.go第30行

**Comment by luyu6056** [comment]
@panjf2000 回到上面那个建议啊，由于粘包，一个React里面可能粘了几百上千条消息，按你说的不用AsyncWrite，我把需要回的消息都写入一个buf，最后再汇总到out里面，以上面1万客户端的测试条件，内存占用快多了10G，虽然是buf没及时释放，但是我还是希望有一个直接调用c.write(buf)的Write，而不是AsyncWrite，以节约缓冲内存

**Comment by luyu6056** [comment]
> > 上面贴有一个截图，我反复重试才截到的，reactor_linux.go第30行
> 
> 这个是 race 读的，肯定有另一个地方尝试写才会冲突，就是想看看是哪里在写。

现在没了，下次再出现我看看能不能找到，之前测试由于ants的pool开启了上万个，等终端打印完，都找不到头了

**Comment by panjf2000** [comment]
基于之前我的解释，gnet 对 eventloop 里的 connections map 的读写都是在同一个 goroutine 里执行的，所以不会出现 race 问题，大概是你使用的问题，我看到你前面说你把 AsyncWrite 改成同步写的了，我猜大概是你改成同步写之后又在独立的 goroutine 里调用了这个方法才会导致这个问题。

我的建议：
gnet 内置了输入输出的两个 buffers，业务方不需要自己维护一个 buffer，读取的时候在 `React` 注册方法里直接调用 `Read()` 或者 `ReadN()` 直接读取就行（注意 ReadN() 会真正把数据从 buffer 里读出来，和 Read() 是不一样的）。写出数据的时候，如果业务逻辑非阻塞，把你的响应数据直接赋值 out 返回即可，gnet 会先尝试把数据写回客户端，没写完就会存到 buffer 里，下次继续写。如果是阻塞的业务逻辑，可以把任务提交到 goroutine pool，最后调用 `AsyncWrite()` 写出响应数据到客户端。

既然不是 gnet 本身的 bug，那这个 issue 我先关掉，如果后续你按照我的方法去做还出现类似的问题你再重新打开吧，谢谢。
