### ISSUE TITLE
gnet client 丢失报文

### ISSUE THREAD

**Issue by zhongweikang** [panjf2000/gnet#302]
**描述问题**
这是一个很容易复现的问题
问题的表象大约是：使用 `gnet client` 向 `redis server` 写入了 100 条报文，但是 `redis server` 只回应了 99（或更少） 条消息

**复现步骤**
1. 使用 `cli.Dial` 获得一个 `Conn`
2. 立即调用 `AsyncWrite` 方法写入报文
3. 多重复几次上诉步骤即可

**尝试排查问题**
问题大致出在了这行代码，调用 `AsyncWrite` 时，代码判断 `conn.opened` 尚未开启，消息直接被丢弃了，并且没有打印任何日志
https://github.com/panjf2000/gnet/blob/dev/connection_unix.go#L229
> 建议这行代码修改为：return errors.New("conn not open")

**尝试解释问题**
`cli.Dial` 方法的最后，会注册一个事件
https://github.com/panjf2000/gnet/blob/dev/client.go#L203

`AsyncWrite` 方法的最后，也会注册一个事件
https://github.com/panjf2000/gnet/blob/dev/connection_unix.go#L313

当 `write` 事件比 `register` 事件更早的被调用时，就会出现没有 `conn.opened` 尚未开启的情况，消息直接被丢弃了

**System Info (please complete the following information):**
 - 操作系统版本 `Linux` version 3.10.0-1160.11.1.el7.x86_64 (mockbuild@kbuilder.bsys.`centos`.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) SMP Fri Dec 18 16:34:56 UTC 2020。`mac`上也可以复现。
 - Go version `1.14` 
 - gnet version `1.6.1`

**Additional context**
这个报错，是我将这行代码修改后的结果 https://github.com/panjf2000/gnet/blob/dev/connection_unix.go#L229
将 return nil 改为 return errors.New("conn not open")
> 在 `NewClient` 时，我注入了新的 `Logger`，下面的报错，并不是使用我注入的 `Logger` 打印出来的，或许也是一个潜在问题
```
2021-12-14T18:08:40.32433425+08:00	WARN	logging/logger.go:187	error occurs in user-defined function, conn not open
github.com/panjf2000/gnet/pkg/logging.Warnf
	/home/sftcwl/croot/redis/redis-proxy-go-reactor/vendor/github.com/panjf2000/gnet/pkg/logging/logger.go:187
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling
	/home/sftcwl/croot/redis/redis-proxy-go-reactor/vendor/github.com/panjf2000/gnet/internal/netpoll/epoll_default_poller.go:171
github.com/panjf2000/gnet.(*eventloop).loopRun
	/home/sftcwl/croot/redis/redis-proxy-go-reactor/vendor/github.com/panjf2000/gnet/reactor_default_linux.go:104
github.com/panjf2000/gnet.(*Client).Start.func1
	/home/sftcwl/croot/redis/redis-proxy-go-reactor/vendor/github.com/panjf2000/gnet/client.go:100
```

**Comment by panjf2000** [comment]
register 任务优先级比 write 更高，一定会更先执行的，所以问题应该不在这里。

**Comment by panjf2000** [comment]
监听一下 OnOpened 事件，打印一下 log，看看有没有调用。

**Comment by zhongweikang** [comment]
应该是我使用姿势有问题，排查到了两点问题
1、`codec` 解报文时，没有正确使用 `gerrors.ErrIncompletePacket`
2、我构建了一个`cli.Dial`连接池，当某个 conn 被意外关闭时，我连接池里对应的 conn  没有及时释放

打扰了，感谢
