### ISSUE TITLE
在React函数里面启动协程池的问题,报文乱序的问题

### ISSUE THREAD

**Issue by czxfreedom** [panjf2000/gnet#304]
我开启一个客户端 发送 hello world 俩条报文   如果我在React函数将数据提交到协程池,协程池不保证任务执行的顺序吧? 那客户端会不会就接收到 乱序的报文 world hello?

**Comment by czxfreedom** [comment]
![image](https://user-images.githubusercontent.com/18362511/146483463-99e2d08b-7c52-4317-b794-64fb4e4ebe74.png)
我稍微测试了下 服务端开启协程池的情况下 客户端接收到的报文确实是乱序的

**Comment by panjf2000** [comment]
设计如此，这是预期行为，这种场景要自己保证顺序。

**Comment by czxfreedom** [comment]
您好，你的来件已收到，谢谢！

**Comment by mikeqoo1** [comment]
如果你對資料的順序很重要 建議你送msg的地方 可能用同步阻塞的方式 比較直覺

**Comment by czxfreedom** [comment]
好的 感谢
