### ISSUE TITLE
gnet最新的版本占用了大量的内存

### ISSUE THREAD

**Issue by vxzhong** [panjf2000/gnet#306]
**Describe the bug**
升级到1.6.3，启动后虚拟内存和实际内存飞涨，切换回1.5.3后，内存就降下来了。不知道是不是用法有问题，像1.6和1.5的codec的写法就是不一样的。

**To Reproduce**
升级到1.6.3，重启，大量报文连接上来

**Expected behavior**
内存占用和1.5.3一样

**Screenshots**
1.5.3
![image](https://user-images.githubusercontent.com/86217/147328048-ec1127f1-f47b-46b2-ac0e-18a3e8607bea.png)
1.6.3
![image](https://user-images.githubusercontent.com/86217/147328439-b8d4fc1a-e695-48f6-b4e9-0b8d8e020347.png)
![image](https://user-images.githubusercontent.com/86217/147328479-d129cf4a-7296-476c-8deb-f727979b4580.png)

**System Info (please complete the following information):**
 - OS (e.g. Ubuntu 18.04):  CentOS7
 - Go version (e.g. Go 1.13):  1.7.1
 - gnet version (e.g. v1.0.0):  1.6.3

**Additional context**

**Comment by panjf2000** [comment]
大量 TCP 连接？v1.6 现在是每个连接预分配固定大小的 buffer，所以如果上来就有大量连接是会这样的，有监控两个版本的最终的内存占用量，应该差不太多？

**Comment by vxzhong** [comment]
是的，大量TCP连接，启动一会儿内存占用已经接近跑很久的峰值了，1.5.3版本RES峰值就9G左右。测试时同时在线12万左右，高峰在线数翻倍，还没跑。客户端连服务端，几秒后空闲就关闭连接，不会一直保持连接，实际连接数2-3万。

**Comment by panjf2000** [comment]
如果只是建连接不操作的话那肯定是 v1.5.3 的内存占用要低很多了，我意思是连接建立之后还要大量收发消息，1.6 的内存占用应该和 v1.5.3 差不太多，你们有测对比吗？

**Comment by vxzhong** [comment]
比较糙，升级了版本，直接上去跑业务了的，有大量消息收发的，不仅仅是连接，但只跑了十几分钟，看内存占用比较大，就回退了。

**Comment by vxzhong** [comment]
这是1.5.3，跑了几小时的内存占用：
![image](https://user-images.githubusercontent.com/86217/147335285-ebea510a-4f1c-4bec-ab8f-f4ad16b0d3e0.png)
1.6.3，RSS上来就是9G，但后面会缓慢下降。但应该不会降到1.5.3的水平。

**Comment by vxzhong** [comment]
内存一直涨，下不去，先回退了：
![image](https://user-images.githubusercontent.com/86217/147348025-904ce57f-49c0-4a00-859b-01ea034f2ab2.png)
![image](https://user-images.githubusercontent.com/86217/147348048-979bd403-bd53-4d5d-8f22-f85198e8499d.png)
![image](https://user-images.githubusercontent.com/86217/147348076-ed8ef162-4fa0-4444-a3a9-599e966ce77a.png)

**Comment by panjf2000** [comment]
怎么会一直涨？一直在新建连接吗？

**Comment by vxzhong** [comment]
嗯，客户端发完就关掉连接，然后需要过一会要发包的时候再连上来。

**Comment by panjf2000** [comment]
这几天我优化一下这个问题，到时候麻烦你再验证下。

**Comment by panjf2000** [comment]
请拉取 `dev` 分支的最新代码再测试一下，如果还有问题就重新打开 issue。
@vxzhong

**Comment by panjf2000** [comment]
@vxzhong 
有验证过吗？

**Comment by vxzhong** [comment]
验证过了，好了。
