### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by LLHFWT** [panjf2000/gnet#31]
![SharedScreenshot](https://user-images.githubusercontent.com/25070621/67666272-6f609a00-f9a6-11e9-8869-4866d0ab0bec.jpg)

**Comment by panjf2000** [comment]
下次麻烦填一下 template。。。。
你是什么系统？哪个版本？

**Comment by LLHFWT** [comment]
centOS7.2, 就只是运行了以下你写的gnet_test

**Comment by panjf2000** [comment]
可能是之前提交的某一个 commit 有问题，麻烦更新到最新的 code 再试一次。

**Comment by panjf2000** [comment]
我已经试过了，最新的代码，在 mac 和 linux 都没问题，你可以更新到最新的代码应该就没问题了。
