### ISSUE TITLE
请问能否提供一个gnet 客户端的示例

### ISSUE THREAD

**Issue by iwaters-yyj** [panjf2000/gnet#310]
请问能否提供一个gnet 客户端的示例呢？

**Comment by panjf2000** [comment]
https://github.com/gnet-io/gnet-examples/blob/master/examples/custom_codec/client/client.go

**Comment by taozix** [comment]
gnet client是不是不支持windows呢?

**Comment by panjf2000** [comment]
> gnet client是不是不支持windows呢?

暂时不支持

**Comment by taozix** [comment]
貌似在服务端关闭后，客户端AsyncWrite也没报错。

**Comment by ssrlxl** [comment]
> > gnet client是不是不支持windows呢?
> 
> 暂时不支持

有计划支持吗，大概什么时候呢

**Comment by UniKylin** [comment]
> > > gnet client是不是不支持windows呢?
> > 
> > 
> > 暂时不支持
> 
> 有计划支持吗，大概什么时候呢

`gnet client` 支持 `windows` 意义不太大
