### ISSUE TITLE
Topics about the http/http2/rpc server corresponding to gnet

### ISSUE THREAD

**Issue by srvlibs** [panjf2000/gnet#311]
It feels quite complicated to manually implement a http/http2/rpc server corresponding to gnet. I would like to know if you have any plans, and when will it start?

**Comment by someview** [comment]
这个问题还没关闭啊，我们也有这个需求，采用gnet来作为quic协议的底层连接驱动库。不匹配的地方是quic没有提供asyncwrite，这和gnet当前的方式不太匹配。另外一点是，gnet是把addr 绑定在conn上面的， 而quic协议addr本身是可变的，这要求把addr从conn中解放出来
