### ISSUE TITLE
gnet调用 (*eventloop).write 时发生Panic

### ISSUE THREAD

**Issue by leogwy** [panjf2000/gnet#316]
**Describe the bug**
gnet框架内部调用 (*eventloop).write 时发生Panic，详情如下，在代码中看起来是由于没有判断  len(iov)=0 的情况，导致Panic

- func (el *eventloop) write(c *conn) error {
	el.eventHandler.PreWrite(c)

	iov := c.outboundBuffer.Peek()
	var (
		n   int
		err error
	)
	if len(iov) > 1 {
		n, err = io.Writev(c.fd, iov)
	} else {
		n, err = unix.Write(c.fd, iov[0])
	}
	c.outboundBuffer.Discard(n)
	switch err {
	case nil:
	case unix.EAGAIN:
		return nil
	default:
		return el.closeConn(c, os.NewSyscallError("write", err))
	}

	// All data have been drained, it's no need to monitor the writable events,
	// remove the writable event from poller to help the future event-loops.
	if c.outboundBuffer.IsEmpty() {
		_ = el.poller.ModRead(c.pollAttachment)
	}

	return nil
}

Panic信息：
panic: runtime error: index out of range [0] with length 0
goroutine 339 [running]:
github.com/panjf2000/gnet.(*eventloop).write(0xc0036008a0, 0xc021b4e460, 0x168e, 0xc054c65cc8)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.6.3/eventloop_unix.go:167 +0x245
github.com/panjf2000/gnet.(*eventloop).run.func2(0x168e, 0xc000000019, 0x20, 0x20)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.6.3/reactor_default_linux.go:118 +0xa5
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling(0xc00001f220, 0xc06af23f78, 0x0, 0x0)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.6.3/internal/netpoll/epoll_default_poller.go:136 +0x143
github.com/panjf2000/gnet.(*eventloop).run(0xc0036008a0, 0x0)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.6.3/reactor_default_linux.go:104 +0xa5
github.com/panjf2000/gnet.(*server).startEventLoops.func1.1(0xc0036008a0, 0xc00740a400)
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.6.3/server_unix.go:69 +0x3c
created by github.com/panjf2000/gnet.(*server).startEventLoops.func1
	/home/vagrant/go/pkg/mod/github.com/panjf2000/gnet@v1.6.3/server_unix.go:68 +0x6a

**System Info (please complete the following information):**
 - OS ( Ubuntu 18.04): 
 - Go version ( Go 1.15): 
 - gnet version (  v1.6.3): 

**Additional context**

**Comment by panjf2000** [comment]
请升级到 v1.6.4，已经修复了。

**Comment by leogwy** [comment]
好的，非常感谢回复
