### ISSUE TITLE
跨语言 udp client 如何实现呢？

### ISSUE THREAD

**Issue by symsimmy** [panjf2000/gnet#317]
**What is your question about gnet?**
Please describe your question meticulously.
我现在用 gent 实现了一个 udp 的 server，使用 gnet 提供的 client 确实是可以跑通clinet-server 通信的。
但我的clinet 也有 java 语言的，如果使用java 提供的原生 udp 接口，如何发送消息使得 gnet udp-server 能接收消息呢？
请问需要做哪些改造工作呢？

**Comment by panjf2000** [comment]
这个和你使用什么框架去实现没关系，只和你自己的协议有关。
