### ISSUE TITLE
IPv4 in IPv6 地址格式问题

### ISSUE THREAD

**Issue by Ricardo-Evans** [panjf2000/gnet#319]
master分支，位于internal/socket/socktoaddr.go中line 60
func sockaddrInet4ToIP(sa *unix.SockaddrInet4) net.IP
由于bsPool中获得的内存内容可能并不全为0（归还时没有重置），此处应该对ipv4 in ipv6地址前10byte置0

**Comment by panjf2000** [comment]
提个 PR？
