### ISSUE TITLE
发布 gnet v2 有没有个发布计划表？

### ISSUE THREAD

**Issue by ycyuxin** [panjf2000/gnet#325]
对 gnet v2 很感兴趣，看到默认分支 dev 已经是 v2 了，想了解一下：
1. 目前进度如何
2. 有没有发布计划
谢谢。

**Comment by panjf2000** [comment]
v2 已经基本开发完成了，预计本月底发布。

**Comment by Nyx2022** [comment]
> v2 已经基本开发完成了，预计本月底发布。

建议在v2中考虑支持Windows

**Comment by panjf2000** [comment]
> > v2 已经基本开发完成了，预计本月底发布。
> 
> 建议在v2中考虑支持Windows

暂时不支持。

**Comment by skyw4code** [comment]
> > > v2 已经基本开发完成了，预计本月底发布。
> > 
> > 
> > 建议在v2中考虑支持Windows
> 
> 暂时不支持。

那么，window下使用gnet开发，有没有比较好的解决方案？不然调试会蛋疼死的...

**Comment by skyw4code** [comment]
> 用 [WLS](https://docs.microsoft.com/zh-cn/windows/wsl/) 试试？

用WLS解决不了根本问题，目前看，想方便，只能在linux或macOS上做开发...

**Comment by panjf2000** [comment]
gnet v2 今天正式发布：https://github.com/panjf2000/gnet/releases/tag/v2.0.0
