### ISSUE TITLE
Plan to support io_uring or XDP backend?

### ISSUE THREAD

**Issue by fly3366** [panjf2000/gnet#327]
**Is your feature request related to a problem? Please describe.**
Custom OVS or Proxy running on limited hardware.

**Describe the solution you'd like**
Add build flag for diff kernel. use syscall or iouring. XDP support like bryandmc/glommio in Rust.

**Comment by panjf2000** [comment]
Not yet.

**Comment by mstrYoda** [comment]
> Not yet.

Hi, what is the current state of this issue? Is there anyone working on io_uring support or do you accept PR for this?

**Comment by panjf2000** [comment]
> Hi, what is the current state of this issue?

I haven't started it yet.

> do you accept PR for this?

PR is always welcome.
