### ISSUE TITLE
AsyncWrite需要等待数据被完全写出去

### ISSUE THREAD

**Issue by MoonShining** [panjf2000/gnet#328]
**Describe the bug**

AsyncWrite接受一个callback， 看上去可以用来做这次AsyncWrite完成的通知。 

但其实，需要写出去的数据在callback完成时可能还被buffer在内存里。

考虑流式写数据的场景，会循环调AsyncWrite，然后等AsyncWrite完成，伪代码如下
```
for {
   buf := make([]byte, 1024)
   reader.Read(buf)
   AsyncWrite(buf, callback)
  // 此时希望等待buf被全部写出去，然后再读下一块数据
}
```

如果往外写数据比较慢，就会导致内存一直增长,  需要有一种手段等待buf写真正完成

**Comment by panjf2000** [comment]
可以调用 `Conn.Flush()`

**Comment by JuniaWonter** [comment]
callback 为什么不把写错误也搞出来 ,`func(cc gnet.Conn,err error) error`像这样。
