### ISSUE TITLE
对比Go官方库改进点的疑问

### ISSUE THREAD

**Issue by victory460** [panjf2000/gnet#329]
Great project！

[Go官方库 也有epoll kqueue的支持](https://go.dev/src/runtime/netpoll_epoll.go)

我不太清楚这个项目对比官方库的改进点；比如udp read这块，对比go官方库，主要改进了哪些方面哇？

**Comment by panjf2000** [comment]
可以参考 https://strikefreedom.top/archives/go-netpoll-io-multiplexing-reactor
