### ISSUE TITLE
Connection migration to other server seemlessly.

### ISSUE THREAD

**Issue by chikilov** [panjf2000/gnet#330]
**Is your feature request related to a problem? Please describe.**
I am using gnet framework with 30k clients.
And use aws codedeploy (blue/green).
When I deploy new version of source all connection close and reconnect to new server at once.
It might be cause a kind of performance issue. So I try to use onShutdown event, Unfortunately, it fires after all connection closed.

**Describe the solution you'd like**
Can you make a new event type just before start shut down?

**Describe alternatives you've considered**

**Additional context**

**Comment by panjf2000** [comment]
Sorry, still not so clear about your requirement here, could you describe it step by step and share more details?

**Comment by chikilov** [comment]
Just I want another event which is fire when server shutdown.(before client connections close)

**Comment by panjf2000** [comment]
Let me see what I can do.
