### ISSUE TITLE
用作tcp server时close_wait比较多

### ISSUE THREAD

**Issue by phoenixxliu** [panjf2000/gnet#335]
**What is your question about gnet?**
 使用gnet用作codec tcp server，开启了multicore，运行一段时间后发现cpu占用很高，close_wait逐渐变多，open files也不断上涨（基本都是socket）,看起来像socket未正常关闭。
 问下可能是什么原因导致的呢？或者我的使用方法不对？
 
我的理解：
1. gnet自己本身不会主动断链接，除非有问题或者主动调用 `Conn.Close()`; （我在Onclose里return了 gnet.Close的action）
2. CLOSE_WAIT只出现在被动关闭链接一端，也就是说server收到了客户端发来的FIN后还没回复ACK；
3. 从`loopCloseConn()`代码看会调用`unix.Close(fd)`来关闭fd;

求解。

**Comment by panjf2000** [comment]
有没有错误日志？

**Comment by phoenixxliu** [comment]
> 有没有错误日志？

没有，server一切正常

**Comment by panjf2000** [comment]
> 提供一下基本信息，什么操作系统，gnet 版本，代码贴一下。

**Comment by phoenixxliu** [comment]
> 提供一下基本信息，什么操作系统，gnet 版本，代码贴一下。
Linux (tlinux3-0020)
gnet1.5.3
已私下沟通

**Comment by phoenixxliu** [comment]
排查后发现是业务的codec.Decode()在部分case下可能会阻塞gnet的subReactor的eventloop 而导致的。
并非框架问题。

close 本 issue，如果遇到类似问题的优先排查业务逻辑。
