### ISSUE TITLE
go get Error

### ISSUE THREAD

**Issue by centratelemedia** [panjf2000/gnet#336]
PS D:\projects\goproject\server> go mod init servergps
go: creating new go.mod: module servergps
PS D:\projects\goproject\server> go get -u github.com/panjf2000/gnet/v2
go: downloading golang.org/x/sys v0.0.0-20220307203707-22a9840ba4d7
# github.com/panjf2000/gnet/v2
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:49:7: undefined: engine
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:55:18: el.loadConn undefined (type *eventloop has no field or method loadConn)
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:384:27: cannot use options (type *Options) as type bool in argument to initListener     
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:389:14: too many arguments in call to serve
        have (EventHandler, *listener, *Options, string)
        want (EventHandler, *listener, *Options)
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:402:11: undefined: engine
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:404:13: undefined: engine
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\load_balancer.go:71:4: el.idx undefined (type *eventloop has no field or method idx)
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\load_balancer.go:101:12: el.loadConn undefined (type *eventloop has no field or method loadConn)
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\load_balancer.go:103:12: v.loadConn undefined (type *eventloop has no field or method loadConn) 
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\load_balancer.go:112:4: el.idx undefined (type *eventloop has no field or method idx)
..\..\golang\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\load_balancer.go:112:4: too many errors
PS D:\projects\goproject\server> 

how to solve this problem?

**Comment by panjf2000** [comment]
Sorry, gnet v2 is not available on Windows for the moment.
