### ISSUE TITLE
asyncWrite 中内存泄露？

### ISSUE THREAD

**Issue by ycyuxin** [panjf2000/gnet#337]
**问题**

服务程序长时间运行后，显示内存一直在增长，使用 go tool pprof 查看，发现下面两个函数占用了大量内存：

- `github.com/panjf2000/gnet/v2/pkg/buffer/linkedlist.(*Buffer).PushBack`
-  `github.com/panjf2000/gnet/v2/pkg/pool/byteslice.(*Pool).Get`

感觉应该是内存泄露

**运行环境**

- ubuntu20.04
- go1.17.7
- gnet/v2

**go tool pprof .../heap 的截图** 

![image](https://user-images.githubusercontent.com/32991951/157160386-3141c73a-b622-466e-850a-cdd587b02c77.png)

**Comment by ycyuxin** [comment]
运行时打开了 -race，我关掉再试试

**Comment by panjf2000** [comment]
看起来像是 outbound buffer 堆积了很多数据，是有大量的数据写出吗？客户端有没有及时接收？

**Comment by ycyuxin** [comment]
有大量的数据写出，目前没出现这种情况，我再监视一下。

为避免客户端没有接收的情况，是不是可以在写入前用下面的代码检查？

```go
if c.OutboundBuffered() < maxOutBuffered {
  c.AsyncWrite(...)
} else {
  _ = c.Close()
}
```

**Comment by panjf2000** [comment]
`OutboundBuffered()` 只能在那几个事件回调里调用，比如 `OnTraffic()`，它不是线程安全的，所以不能在其他的 goroutine 里调用。

**Comment by ycyuxin** [comment]
如果出现客户端长时间不接收数据的情况，内存会不会一直增长？有没有方法避免呢？

**Comment by panjf2000** [comment]
客户端不接收只发送数据？这也说明有bug吧，还有你的逻辑是写在哪里？你是在 `OntTraffic()` 里又启动了新的 goroutine，然后在这个新的 goroutine 里调用 `AsyncWrite()` 吗？如果只是在 `OntTraffic()` 里直接用 `c.Write()` 就行了，而且可以 `OutboundBuffered()`，如果的确是在新 goroutine 里，`AsyncWrite()` 可以传一个回调函数进去的，可以在这个回调函数里调用 `c.OutboundBuffered()` 再判断，堆积太多可以 close 掉。

**Comment by ycyuxin** [comment]
好的，明白了，多谢! 

Write() 里可以直接检测 OutboundBuffered，AsyncWrite 里需要通过 callback。

还应该把连接超时机制也加上去
