### ISSUE TITLE
gnet v2 supports Windows

### ISSUE THREAD

**Issue by amos-lsl** [panjf2000/gnet#339]
![image](https://user-images.githubusercontent.com/32168345/157409947-824a9877-16fc-44f4-9ea3-46c15ade10e7.png)

**Comment by panjf2000** [comment]
看起来像是环境配置的问题，go test 能跑吗？

**Comment by amos-lsl** [comment]
不行，我用的ide是vscode
![image](https://user-images.githubusercontent.com/32168345/157420590-b59ad85c-eca1-48b0-af66-4d24c6285ec4.png)

**Comment by amos-lsl** [comment]
gnet包中，定义了两个eventloop struct ??
![image](https://user-images.githubusercontent.com/32168345/157421664-5e854407-9a10-48da-bb52-d05028b0772b.png)
![image](https://user-images.githubusercontent.com/32168345/157421758-403b6ea6-0e78-4ed2-88b6-1d18d97d6451.png)

**Comment by panjf2000** [comment]
你是什么操作系统？

**Comment by jkingben** [comment]
应该是windows系统下的开发

**Comment by bagualing** [comment]
一样一样的问题，
Windows 7、vscode下，编译github.com/gnet-io/gnet-examples下的示例程序，提示：
![图片](https://user-images.githubusercontent.com/5525630/161918299-9ef4f4a9-7b48-4211-86f8-aa32d1a3baa0.png)

**Comment by jkingben** [comment]
2.0现在不支持win，我是win下用v1，linux下用v2 这样分开的，搞得挺麻烦

**Comment by gcggcg** [comment]
v2好像不支持win，运行报错一样的问题。大佬有解决方法吗。
![image](https://user-images.githubusercontent.com/56147091/164235381-7cc55781-c6f4-4249-8224-9b68391fccda.png)

**Comment by mikeqoo1** [comment]
@gcggcg  win只能用v1.x.x的版本 2.0以後就不支援win了

**Comment by josejuanmontiel** [comment]
github.com\panjf2000\gnet\v2@v2.0.3\engine.go

//go:build linux || freebsd || dragonfly || darwin
// +build linux freebsd dragonfly darwin

To be notice "this is the problem" :) i'm not expert... by i'll read about it https://www.sobyte.net/post/2021-09/golang-netpoll/ and understand why...

**Comment by ivanjaros** [comment]
oh 💩 i just noticed this is not working on windows. just wasted hour of my time setting up a new project. @panjf2000 you should at least implement workable windows version for basic development. it does not have to provide the same performance, obviously, but it should at least work.

**Comment by ivanjaros** [comment]
I noticed entire code base is windows-free so it's not just the netpoll library. This really sucks.

**Comment by maxbad** [comment]
围观一下, 期待早日支持windows

**Comment by maxbad** [comment]
2023新期待支持一下windows

**Comment by gedw99** [comment]
+1 windows support for V2

**Comment by TrungKenbi** [comment]
I'm waiting
