### ISSUE TITLE
Add encoder and decoder for network messages like netty

### ISSUE THREAD

**Issue by lhjw9810** [panjf2000/gnet#34]
粘包、拆包能像netty一样提供一些内置方法使用吗？

**Comment by panjf2000** [comment]
你是想说提供类似 netty 里的那几个内置解码器对吧？这几个：
- LineBasedFrameDecoder
- DelimiterBasedFrameDecoder（添加特殊分隔符报文来分包）
- FixedLengthFrameDecoder（使用定长的报文来分包）
- LengthFieldBasedFrameDecoder

这个可以做，我等下拉个分支实现一下。
