### ISSUE TITLE
Error go get

### ISSUE THREAD

**Issue by centratelemedia** [panjf2000/gnet#340]
PS D:\projects\golang\servergps> go get -u github.com/panjf2000/gnet/v2
go: downloading golang.org/x/sys v0.0.0-20220310020820-b874c991c1a5
# github.com/panjf2000/gnet/v2
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:87:6: el.run undefined (type *eventloop has no field or method run)
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:96:9: el.poller undefined (type *eventloop has no field or method poller)
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:105:6: el.activateSubReactor undefined (type *eventloop has no field or method activateSubRea
ctor)
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:113:44: eng.ln.address undefined (type *listener has no field or method address)
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:120:51: cannot use eng.opts (type *Options) as type bool in argument to initListener
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:124:10: undefined: netpoll
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:125:15: undefined: netpoll
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:127:6: el.ln undefined (type *eventloop has no field or method ln)
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:128:6: el.engine undefined (type *eventloop has no field or method engine)
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:255:6: serve redeclared in this block
        C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\engine_stub.go:51:53: previous declaration
C:\Users\Admin\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.0.0\gnet.go:128:6: too many errors
PS D:\projects\golang\servergps> 

howto solve this problem?

**Comment by panjf2000** [comment]
gnet v2 is not available on Windows.
