### ISSUE TITLE
关闭链接时，如果 outboundBuffer 非空回陷入死循环

### ISSUE THREAD

**Issue by ycyuxin** [panjf2000/gnet#341]
操作系统：Ubuntu 20.04
Go 版本: 1.17.7
gnet 版本：v2.0

场景：物联网设备服务器，设备建立 TCP 连接后断电。服务器端向该连接发送数据，导致 outboundBuffer 非空，此时尝试关闭连接。发现服务不在响应任何和数据。

经过跟踪，发现进入下面的死循环：

```go
// eventloop.go
func (el *eventloop) closeConn(c *conn, err error) (rerr error) {
	...
	if !c.outboundBuffer.IsEmpty() {
		for !c.outboundBuffer.IsEmpty() {
			iov := c.outboundBuffer.Peek(0)
			if len(iov) > iovMax {
				iov = iov[:iovMax]
			}
			n, err := io.Writev(c.fd, iov)    // 返回: n: -1, err: unix.EWOULDBLOCK
			if err != nil && err != unix.EAGAIN {  // 说明：unix.EAGAIN == unix.EWOULDBLOCK == 11
				el.getLogger().Warnf("closeConn: error occurs when sending data back to peer, %v", err)
				break
			}
			_, _ = c.outboundBuffer.Discard(n)  // outboundBuffer 内容不变，死循环
		}
	}
	...
}
```

此时，io.Writev 写入错误，但无法恢复，outboundBuffer 也一直不变, 导致整个 eventloop 无法工作，希望能尽快修复。

**Comment by ycyuxin** [comment]
或者，有没有一个函数，放弃所有未发送出去的数据，直接关闭连接？

**Comment by panjf2000** [comment]
对端设备断电，那 TCP 连接应该就断掉了，这时候往 socket 写数据应该是 Connection reset by peer 或者是 Broken pipe，怎么会返回 EWOULDBLOCK？

**Comment by ycyuxin** [comment]
手持设备通过无线通信模块上网，断电时没有机会发送任何数据。服务器端只能靠超时检测连接是否断开，从服务器端看 TCP 连接一直是 ESTABLISHED ，然后转成 FIN_WAIT1。

**Comment by panjf2000** [comment]
你这里是服务端主动调用 `c.Close()` 的？

**Comment by ycyuxin** [comment]
是，服务器长时间没收到响应会调用 c.Close()。

是不是可以增加一个 ForceClose()? 或者增加一个 ForceClose Action 直接关闭连接?

**Comment by panjf2000** [comment]
对端进程如果异常退出，本端还是可以往 socket 写数据的，直到写满 socket buffer，然后阻塞（blocking mode）或者返回 EAGAIN（non-blocking mode），直到超时返回 Connection reset by peer 或者是 Broken pipe 错误，应该不会无限失败下去的，你有记录这个过程持续了多长时间吗？

**Comment by ycyuxin** [comment]
确实，刚开始时 socket 写缓冲增加，然后关闭时陷入死循环，持续会有十几分钟，在此期间服务器不能响应任何连接，收到的数据都堆积在 socket 读缓冲区。

**Comment by ycyuxin** [comment]
确实，刚开始时 socket 写缓冲增加，然后关闭时陷入死循环，持续会有十几分钟，在此期间服务器不能响应任何连接，收到的数据都堆积在 socket 读缓冲区。

**Comment by ycyuxin** [comment]
确实，刚开始时 socket 写缓冲增加，然后关闭时陷入死循环，持续会有十几分钟，在此期间服务器不能响应任何连接，收到的数据都堆积在 socket 读缓冲区。

**Comment by panjf2000** [comment]
这个地方的确需要优化，我等会儿修复一下
