### ISSUE TITLE
Failed to awake poller

### ISSUE THREAD

**Issue by zhyq132** [panjf2000/gnet#342]
gnet@v1.3.0/eventloop_unix.go:266       Failed to awake poller in event-loop(0), error:write: bad file descriptor, stopping ticker

ubuntu1804,偶尔会爆出来一个这种导致的panic

**Comment by panjf2000** [comment]
是不是在停止进程的时候，这种情况是有可能打印这个日志的，但是不会有 panic 的。

**Comment by zhyq132** [comment]
升级了1.6.4 继续观察一下
