### ISSUE TITLE
conn.WriteTo(w io.Writer) 返回值问题

### ISSUE THREAD

**Issue by JemmyH** [panjf2000/gnet#343]
**Describe the bug**
这里的返回值应该是 n + int64(m) ？
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/38834787/158068063-2ad4178c-ea93-479a-9ca8-5e060d0e37fc.png">

**To Reproduce**
None

**Expected behavior**
应该返回 n + int64(m)
```go
func (c *conn) WriteTo(w io.Writer) (n int64, err error) {
	if c.inboundBuffer.IsEmpty() {
		var m int
		m, err = w.Write(c.buffer)
		c.buffer = c.buffer[m:]
		return int64(m), err
	}
	n, err = c.inboundBuffer.WriteTo(w)
	if err != nil {
		return
	}
	var m int
	m, err = w.Write(c.buffer)
	c.buffer = c.buffer[m:]
	return n + int64(m), err
}
```

**Screenshots**

**System Info (please fill out the following information):**
 - OS (e.g. Ubuntu 18.04):  macOS 12.2.1
 - Go version (e.g. Go 1.13):  go1.17.5 darwin/amd64
 - gnet version (e.g. v1.0.0):  v2

**Additional context**

**Comment by panjf2000** [comment]
这里的确有问题，我晚点改一下。

**Comment by panjf2000** [comment]
或者你有时间的话也可以提一个 PR。
