### ISSUE TITLE
关于错误处理

### ISSUE THREAD

**Issue by liu-jiangyuan** [panjf2000/gnet#346]
想问下有用来捕获全局异常的中间件吗？

**Comment by panjf2000** [comment]
能说具体点吗？

**Comment by liu-jiangyuan** [comment]
例如，我现在启动服务正常，但是在执行段代码或者哪里panic了，能否同意用个中间件捕捉到，但是不影响整个服务运行

**Comment by panjf2000** [comment]
你自己的业务代码用 recover 捕获不就行了？https://go.dev/blog/defer-panic-and-recover

**Comment by liu-jiangyuan** [comment]
行也行，主要是用了你们的框架想问下你们有没有配套的处理

**Comment by panjf2000** [comment]
目前还没有提供这种功能。

**Comment by liu-jiangyuan** [comment]
好的

**Comment by jkingben** [comment]
这应该不需要框架进行提供，消息处理主入口那自己加上就行，也没两句话
