### ISSUE TITLE
我们的服务都是运行在windows上啊，2.0不支持有点麻烦。

### ISSUE THREAD

**Issue by zhuqiyun** [panjf2000/gnet#347]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04):
 - Go version (e.g. Go 1.13):
 - gnet version (e.g. v1.0.0):

**What is your question about gnet?**
Please describe your question meticulously.

**Comment by panjf2000** [comment]
Windows 只作为开发调试使用，如果生产环境是 Windows 则直接用 go 标准库 net 实现就可以了。

**Comment by zhuqiyun** [comment]
> gnet v1.x 中的 Windows 版本只作为开发调试使用，如果生产环境是 Windows 则直接用 go 标准库 net 实现就可以了。

没事  我们是小项目   gnet现在在windows上也能用。

**Comment by panjf2000** [comment]
gnet 会在 v2.1 或者 v2.2 再次支持 Windows，这个 issue 和 #339 ，暂时关闭。
