### ISSUE TITLE
如果建立连接后，发送的给服务器的数据是不符合FrameCodec解码器规则的字节流，react就一直不会被触发，这时ringbuf会无线增大吗？

### ISSUE THREAD

**Issue by zhyq132** [panjf2000/gnet#350]
**What is your question about gnet?**
Please describe your question meticulously.

有碰到未知的ip连进来后一直恶意发送字节流.或者如果达到WithSocketRecvBuffer 设置的上限后，会不会主动关闭掉该connection，感谢

**Comment by panjf2000** [comment]
可以主动丢弃已读取的数据，这样就不会堆积了。
