### ISSUE TITLE
gnet v2编译时总提示engine找不到是什么原因呢

### ISSUE THREAD

**Issue by DIERWENMANG** [panjf2000/gnet#353]
诸如此类的编译错误——

# github.com/panjf2000/gnet/v2
github.com\panjf2000\gnet\v2@v2.0.2\gnet.go:49:7: undefined: engine
github.com\panjf2000\gnet\v2@v2.0.2\gnet.go:55:18: el.loadConn undefined (type *eventloop has no field or method loadConn)
github.com\panjf2000\gnet\v2@v2.0.2\gnet.go:384:27: cannot use options (type *Options) as type bool in argument to initListener
github.com\panjf2000\gnet\v2@v2.0.2\gnet.go:389:14: too many arguments in call to serve
	have (EventHandler, *listener, *Options, string)
	want (EventHandler, *listener, *Options)
github.com\panjf2000\gnet\v2@v2.0.2\gnet.go:402:11: undefined: engine
github.com\panjf2000\gnet\v2@v2.0.2\gnet.go:404:13: undefined: engine
github.com\panjf2000\gnet\v2@v2.0.2\load_balancer.go:71:4: el.idx undefined (type *eventloop has no field or method idx)
github.com\panjf2000\gnet\v2@v2.0.2\load_balancer.go:101:12: el.loadConn undefined (type *eventloop has no field or method loadConn)
github.com\panjf2000\gnet\v2@v2.0.2\load_balancer.go:103:12: v.loadConn undefined (type *eventloop has no field or method loadConn)
github.com\panjf2000\gnet\v2@v2.0.2\load_balancer.go:112:4: el.idx undefined (type *eventloop has no field or method idx)
github.com\panjf2000\gnet\v2@v2.0.2\load_balancer.go:112:4: too many errors

**Comment by panjf2000** [comment]
按 issue 模板填，现在 OS 是啥都不知道，干嘛要删掉模板？

**Comment by DIERWENMANG** [comment]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04): Windows 10
 - Go version (e.g. Go 1.13): go1.16.5 windows/amd64
 - gnet version (e.g. v1.0.0): v2.0.2

**What is your question about gnet?**
Please describe your question meticulously.

编译的时候提示
gnet.go:49:7: undefined: engine
gnet.go:55:18: el.loadConn undefined (type *eventloop has no field or method loadConn)
gnet.go:384:27: cannot use options (type *Options) as type bool in argument to initListener
gnet.go:389:14: too many arguments in call to serve
        have (EventHandler, *listener, *Options, string)
	want (EventHandler, *listener, *Options)
…………

**Comment by DIERWENMANG** [comment]
关了，v2应该是只能在Unix环境下编译
