### ISSUE TITLE
V2版部署linux阿里云或实体机上，消息接受延迟严重，用V1版正常，是哪里没用对？

### ISSUE THREAD

**Issue by jkingben** [panjf2000/gnet#354]
**Describe the bug**
v2版分别部署到linux实体机(10核32G内存)和阿里云测试机器(2核4G内存)，两台机器接受消息都延迟非常严重，10几秒才收到一个消息。
换成V1版，问题消失

**To Reproduce**

**Expected behavior**
代码片段：

svr.addr = fmt.Sprintf("tcp://:%d", port)
v1和v2的numEventLoop都设置为50，multicore都是true，v2版也去试过去掉numEventLoop设置
v1：
```go
gnet.Serve(svr, svr.addr, gnet.WithMulticore(opts.multicore), gnet.WithNumEventLoop(opts.numEventLoop), gnet.WithCodec(opts.codec.(*ProtobufCodec)), gnet.WithTCPNoDelay(gnet.TCPNoDelay), gnet.WithReuseAddr(true))
// Decode
func (cc *ProtobufCodec) Decode(c gnet.Conn) ([]byte, error) {
	if size, header := c.ReadN(msgLenHeadLength); size == msgLenHeadLength {
		msgLen := binary.BigEndian.Uint16(header)
		if msgLen > cc.BodyMaxSize { // 超出最大接收长度，断开连接
			client := c.Context().(*TcpConnect)
			_ = client.conn.Close()
			return nil, body_limit_error
		}
		protocolLen := defaultHeadLength + int(msgLen)
		if dataSize, data := c.ReadN(protocolLen); dataSize == protocolLen {
			c.ShiftN(protocolLen)
			return data[msgLenHeadLength:], nil
		}
	}
	return nil, nil
}
```

v2：
```go
gnet.Run(svr, svr.addr, gnet.WithMulticore(opts.multicore), gnet.WithNumEventLoop(opts.numEventLoop), gnet.WithTCPNoDelay(gnet.TCPNoDelay), gnet.WithReuseAddr(true))
// Decode
func (cc ProtobufCodec) Decode(c gnet.Conn) ([]byte, error) {
	ibLen := c.InboundBuffered()
	if ibLen > cc.maxSize {
		return nil, body_limit_error   // 这里返还后，OnTraffic会直接返回gnet.Close，也没有进入这里
	}
	if header, _ := c.Peek(msgLenHeadLength); len(header) == msgLenHeadLength {
		msgLen := binary.BigEndian.Uint16(header)
		if msgLen > cc.BodyMaxSize {
			return nil, body_limit_error   // OnTraffic一样处理
		}
		protocolLen := defaultHeadLength + int(msgLen) // 完整数据段
		if ibLen < protocolLen {
                        这里打印过信息，并没有进入
			return nil, gn_errors.ErrIncompletePacket
		}
		body, _ := c.Peek(protocolLen)
		_, _ = c.Discard(protocolLen)
		return body[msgLenHeadLength:], nil
	}
        这里打印过信息，并没有进入
	return nil, gn_errors.ErrIncompletePacket
}
```
v2版本是不是客户端请求消息体小了，gnet读取的长度达不到处理的要求而进行等待了？如果对这请求重复发送几次，能很快收到，但最后一个请求还是会有10几秒样子的延迟
v2版还有啥需要特别进行设置的？

**Screenshots**

**System Info (please fill out the following information):**
10核32G内存linux实体机
2核4G内存linux实体机

**Additional context**

**Comment by jkingben** [comment]
编译用了-tags="poll_opt"
实体机：rocky linux 8.5
阿里云：Alibaba Cloud Linux 3.2104 LTS 64位 快速启动版
GO：1.17
gnet v1：v1.6.4
gent v2：v2.0.2

v1：
func (svr *tcpSvr) React(frame []byte, conn gnet.Conn) (out []byte, action gnet.Action) {
	if graceful.IsShutdown(graceful.ShutdownTypeShutdown) {
		return nil, gnet.Shutdown
	}
	client := conn.Context().(*TcpConnect)
	msgId, msg := Decode(frame)
	reqSeq, single, multis, broadcast, isLog := svr.myDispatch(client, msgId, msg)
	if reqSeq > 0 {
		if multis != nil {
			if single != nil {
				multis = append(multis[:1], multis[0:]...) // insert
				multis[0] = MultiResponse{MsgId: msgId, Msg: single, SvrRetType: 1}
			}
			client.sendQueue.Store(reqSeq, multis)
		} else {
			client.sendQueue.Store(reqSeq, MultiResponse{MsgId: msgId, Msg: single, SvrRetType: 1})
		}
		checkSend(client)
	} else {
		var buf = bytebufferpool.Get()
		if single != nil {
			msg, _ = proto.Marshal(single)
			Encode(msgId, msg, buf)
			if isLog {
				mylog.Infof("服务器返回[%s(%s)], [size]: %d, [msgId]: %d, [msg]: %s", client.LoginUser, client.Address, len(msg), msgId, toString(single))
			}
		}
		if multis != nil {
			for _, response := range multis {
				msg, _ = proto.Marshal(response.Msg)
				Encode(response.MsgId, msg, buf)
				if isLog {
					mylog.Infof("服务器返回Multi[%s(%s)], [size]: %d, [msgId]: %d, [msg]: %s", client.LoginUser, client.Address, len(msg), response.MsgId, toString(response.Msg))
				}
			}
		}
		if buf.Len() > 0 {
			// mylog.Debugf("send bytes:  % X", buf.Bytes())
			if reqSeq == -1 {
				action = gnet.Close
			}
			out = client.directWrite(buf.Bytes())
		}
		bytebufferpool.Put(buf)
	}
	svr.broadcastSignle(broadcast)
	return
}

v2：
func (svr *tcpSvr) OnTraffic(c gnet.Conn) (action gnet.Action) {
	if graceful.IsShutdown(graceful.ShutdownTypeShutdown) {
		return gnet.Shutdown
	}
	frame, err := codec.Decode(c)
	if err == gn_errors.ErrIncompletePacket {
		return
	} else if err != nil {
		mylog.Warn(err.Error())
		return gnet.Close
	}
	client := c.Context().(*TcpConnect)
	msgId, msg := Decode(frame)
	reqSeq, single, multis, broadcast, isLog := svr.myDispatch(client, msgId, msg)
	if reqSeq > 0 {
		if multis != nil {
			if single != nil {
				multis = append(multis[:1], multis[0:]...) // insert
				multis[0] = MultiResponse{MsgId: msgId, Msg: single, SvrRetType: 1}
			}
			client.lock.Lock()
			client.sendQueue[reqSeq] = multis
			client.lock.Unlock()
		} else {
			client.lock.Lock()
			client.sendQueue[reqSeq] = MultiResponse{MsgId: msgId, Msg: single, SvrRetType: 1}
			client.lock.Unlock()
		}
		checkSend(client)
	} else {
		var buf = bytebufferpool.Get()
		if single != nil {
			msg, _ = proto.Marshal(single)
			Encode(msgId, msg, buf)
			if isLog {
				mylog.Infof("服务器返回[%s(%s)], [size]: %d, [msgId]: %d, [msg]: %s", client.LoginUser, client.Address, len(msg), msgId, toString(single))
			}
		}
		if multis != nil {
			for _, response := range multis {
				msg, _ = proto.Marshal(response.Msg)
				Encode(response.MsgId, msg, buf)
				if isLog {
					mylog.Infof("服务器返回Multi[%s(%s)], [size]: %d, [msgId]: %d, [msg]: %s", client.LoginUser, client.Address, len(msg), response.MsgId, toString(response.Msg))
				}
			}
		}
		if buf.Len() > 0 {
			// mylog.Debugf("send bytes:  % X", buf.Bytes())
			if reqSeq == -1 {
				action = gnet.Close
			}
			_, _ = c.Write(client.directWrite(buf.Bytes()))
		}
		bytebufferpool.Put(buf)
	}
	svr.broadcastSignle(broadcast)
	return
}

**Comment by jkingben** [comment]
v1和v2里的大部分代码都是一样的，里面调用的其他方法也是同一份

**Comment by jkingben** [comment]
再细点的区别就是sendQueue 一个是syncMap，一个是普通map加lock，checkSend里的区别也是两个变量获取方式不同

**Comment by panjf2000** [comment]
OnTraffic() 你的逻辑应该是一个 for 去不断处理消息，v1 里面是在框架内部帮你做了循环，不断处理消息直到 inbound buffer 的数据都处理完，你现在不做循环就可能会出现这种现象。
@jkingben

**Comment by panjf2000** [comment]
可以参考：https://github.com/gnet-io/gnet-examples/blob/v2/simple_protocol/server/server.go

**Comment by jkingben** [comment]
OK，已解决，加了for就没问题了
