### ISSUE TITLE
请教一下gnet.Conn的Read读取错误的问题

### ISSUE THREAD

**Issue by haliary** [panjf2000/gnet#355]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04):
 - Go version (e.g. Go 1.13):Go 1.13.4
 - gnet version (e.g. v1.0.0): v2.0.2

**What is your question about gnet?**
Please describe your question meticulously.
服务器分两次接收数据 OnTraffic触发了两次  只是第一次没有处理 第二次调用Read读取接收到的数据，但是Read的数据和Peek看到的数据不一样，中间跳过了几个byte，想请教一下这是为什么呀
我的OnTraffic代码：
![image](https://user-images.githubusercontent.com/23043407/163535190-54ffbd24-d625-4078-a001-aa2de66432c2.png)
调试信息：
![image](https://user-images.githubusercontent.com/23043407/163535367-9fbe8f23-21f2-4efc-acd8-74019aab16f5.png)

**Comment by panjf2000** [comment]
是一个 bug，我修复一下。

**Comment by haliary** [comment]
好的

**Comment by panjf2000** [comment]
麻烦拉取一下 dev 分支的最新代码验证下，如果还有问题请再回复一下，谢谢！
@haliary

**Comment by haliary** [comment]
@panjf2000 我这边重新跑了一遍   没有问题  想问一下什么时候可以拉一下新的tag 感谢

之前还发现了有些注释还是之前的，可能会有点困扰
<img width="799" alt="企业微信截图_16500200893324" src="https://user-images.githubusercontent.com/23043407/163757439-a4f4ea26-7eb7-4621-b27f-35a044466237.png">

**Comment by panjf2000** [comment]
今天会 push 一个新 tag。

**Comment by haliary** [comment]
好的

**Comment by panjf2000** [comment]
v2.0.3 已发布：https://github.com/panjf2000/gnet/releases/tag/v2.0.3
@haliary
