### ISSUE TITLE
proxy function or proxy example

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/gnet#357]
possible to add a proxy feature to this? been waiting for it for more than 1 year.

**Comment by panjf2000** [comment]
What kind of proxy feature do you have in mind? please describe it in detail.

**Comment by panjf2000** [comment]
Sorry to keep you waiting so long but I didn't have a clear perspective about a built-in proxy feature of gnet, and had no idea what kind of proxy feature that users really want.

**Comment by lxzan** [comment]
I guess what he means is: the client establishes a connection to the remote service through a proxy server.

If gnet implements net.Conn, it's easy to support proxies.
