### ISSUE TITLE
请教一下高并发请求的时候缓冲区数据叠加和ant协程池包使用问题

### ISSUE THREAD

**Issue by gcggcg** [panjf2000/gnet#358]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04):
 - Go version (e.g. Go 1.13):
 - gnet version (e.g. v1.0.0):

**What is your question about gnet?**
Please describe your question meticulously.
```go
// React client响应时触发
func (ser *Server) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	if frame != nil {
		//buf := bbPool.Get()
		//_, _ = buf.Write(frame)
		buf := append([]byte{}, frame...)
		util.TraceInfo("客户端："+c.RemoteAddr().String()+" 请求的的数据：", string(frame))
		if len(buf) != 0 {
			task := model.Task{
				Conn: c,
				Buf:  buf,
			}
			buf = nil
			if err := ser.Pool.Invoke(task); err != nil {
				util.Error("注入请求数据异常" + err.Error())
			}
		}
	}

	return
}
```
问题： 
1.  当压测200连接并发请求100次，发现打印的frame请求数据会叠加，造成数据处理失败，请问如何处理该问题。
2.  当前使用的是异步响应所以使用了ant包但是ant包该如何设置大小还是直接每次请求开启一个协程不适用ant有没有建议可以达到最大的性能。

**Comment by panjf2000** [comment]
叠加是什么意思？

**Comment by gcggcg** [comment]
这个解决了就是一次读取的是多个请求包，现在自定义解码器解决了那个问题。
关于第二个问题，有没有建议。当前使用的是异步响应所以使用了ant包但是ant包该如何设置大小还是直接每次请求开启一个协程去请求，但是ant的配置如果是非阻塞，那么没有获取到的协程是不是就丢失了，所以这个不确定是设置阻塞还是非阻塞，然后大小设置多少有没有建议可以达到最大的性能。

**Comment by panjf2000** [comment]
你可以尝试设置 ants pool 的 capacity 是无限的，这样 ants 就不会限制 worker 数量，只对 goroutine 进行复用。

**Comment by gcggcg** [comment]
可是我线上服务已经使用了 ants.NewPoolWithFunc，有没有方法可以让这个和ants pool 实现同样的效果。或者如果迁移过去需要怎么改动最小，有没有相关实例。


***@***.***
 
发件人： Andy Pan
发送时间： 2022-08-31 13:32
收件人： panjf2000/gnet
抄送： gcggcg; Author
主题： Re: [panjf2000/gnet] 请教一下高并发请求的时候缓冲区数据叠加和ant协程池包使用问题 (Issue #358)
你可以尝试设置 ants pool 的 capacity 是无限的，这样 ants 就不会限制 worker 数量，只对 goroutine 进行复用。

**Comment by panjf2000** [comment]
这里 https://pkg.go.dev/github.com/panjf2000/ants/v2#NewPoolWithFunc，size 传入 -1 即可。
