### ISSUE TITLE
请教一下gnet有MainReactor和SubReacter，那么一个服务启动后SubReacter的数量是如何确定的。

### ISSUE THREAD

**Issue by gcggcg** [panjf2000/gnet#359]
![image](https://user-images.githubusercontent.com/56147091/164954888-1da68c1e-13a0-49b5-9ee9-0d608a538c9e.png)
问题：
1. 关于SubReactor的数量是动态自己启动的吗（自动扩最大多少），数量是自动扩的还是需要设置。

**Comment by panjf2000** [comment]
默认是只有一个，可以开启多核，设置 [WithMulticore](https://pkg.go.dev/github.com/panjf2000/gnet/v2#WithMulticore) 开启，sub reactors 数量等于 CPU 核心数，也可以自定义这个数量，通过 [WithNumEventLoop](https://pkg.go.dev/github.com/panjf2000/gnet/v2#WithNumEventLoop) 设置。
