### ISSUE TITLE
go mod时源码下载不全是什么问题？

### ISSUE THREAD

**Issue by lijunfeng** [panjf2000/gnet#36]
github.com/panjf2000/gnet v0.1.3 下载的版本，但是我比对源码好多都没有download下来，不是网络的问题，其它的都可以。

**Comment by panjf2000** [comment]
现在最新的已经是 v1.0.0-rc.3了，你试试 `go get github.com/panjf2000/gnet@master` 拉取最新的代码。

**Comment by lijunfeng** [comment]
好的，谢谢。
