### ISSUE TITLE
Question：使用 gent 的goroutine pool，异步转发tcp 消息，会乱序么？

### ISSUE THREAD

**Issue by symsimmy** [panjf2000/gnet#361]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04): MacOS 12.3.1
 - Go version (e.g. Go 1.13): Go 1.17
 - gnet version (e.g. v1.0.0): V2.0.0

**What is your question about gnet?**
Please describe your question meticulously.

我这边使用gent 作为 tcp 的 gateway 网关转发数据。为了防止阻塞 eventloop，我将接收到的tcp 消息，使用 gnet 提供的 goroutine pool 提交，异步处理。

初始化：
```
tcpRoutinePool := goroutine.Default()
```

OnTraffic逻辑：,转发的逻辑在HandleFrameTask里面做，想问下这样发出去的消息，会乱序么？
```
func (es *TcpServer) OnTraffic(c gnet.Conn) gnet.Action {
	// Note that the []byte buf returned by Next() is not allowed to be passed to a new goroutine,
	// as this []byte will be reused within event-loop.
	// If you have to use buf in a new goroutine, then you need to make a copy of buf and pass this copy
	// to that new goroutine.
	buf, _ := c.Next(-1)
	if len(buf) < 9 {
		applog.Main.Errorf(context.Background(), "invalid TCP data packet.packet length:%+v", len(buf))
		return gnet.None
	}

	// make a copy of buf
	frame := append([]byte{}, buf...)

	// Use ants pool to unblock the event-loop.
	_ = es.Pool.Submit(func() {
		es.HandleFrameTask(c, frame)
	})

	return gnet.None
}
```

<img width="864" alt="image" src="https://user-images.githubusercontent.com/10104473/164982450-33c7b778-b07b-4ead-8053-b7be06725020.png">

**Comment by symsimmy** [comment]
如果为了达到转发消息有序的目的，且不阻塞 OnTraffic，这边有什么最佳实践么

**Comment by panjf2000** [comment]
异步处理消息是有可能乱序的，这种场景下要保证有序只能由业务侧自己去保证，比如业务方自己设置序列号。
