### ISSUE TITLE
请教LockOSThread和NumEventLoop数量的问题

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#363]
- OS: win11
- Go version: 1.18.1
- gnet version: v2.0.3

gnet.go的代码`options.LockOSThread && options.NumEventLoop > 10000`的注释提到“Go 程序可以使用的最大操作系统线程数最初设置为10000”，请问下10000可以修改吗，在文档里没找到相关的。能不能提供一点帮助信息。

**Comment by panjf2000** [comment]
https://pkg.go.dev/runtime/debug#SetMaxThreads

**Comment by zhu121** [comment]
> https://pkg.go.dev/runtime/debug#SetMaxThreads

谢谢！
