### ISSUE TITLE
关于byteslice.Get()的使用想法

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#365]
**Is your feature request related to a problem? Please describe.**
使用byteslice.Get()时得留意是否要自己做置零等初始化操作，不然底层数组可能遗留着上次的数据内容。
像socktoaddr.go的sockaddrInet4ToIP()函数中，就定义了一个合法的默认值pv4InIPv6Prefix，再做copy。

**Describe the solution you'd like**
byteslice.Get()时，能否对从池子的取出来的slice做reset，和make得到的slice保持一致的返回情况。

**Describe alternatives you've considered**
没有找到什么比较好的方式可以清空底层数组

**Additional context**
无

**Comment by panjf2000** [comment]
并不需要置零，调用方要根据自己的数据大小指定期望的 []byte 长度，拿到之后理论上是刚好能覆盖的，所以是不需要做置零的。
