### ISSUE TITLE
请教SockaddrToTCPOrUnixAddr()对IP的处理方式

### ISSUE THREAD

**Issue by zhu121** [panjf2000/gnet#366]
**Please fill out the following system information before opening an issue:**
 - OS: win11
 - Go version: 1.81.1
 - gnet version: v2.0.3

**What is your question about gnet?**
* gnet的socktoaddr.go文件中，`SockaddrToTCPOrUnixAddr()`函数在处理时，会调用`sockaddrInet4ToIP`或`sockaddrInet6ToIPAndZone`再处理一下IP
* 请问为什么没考虑直接返回`&net.TCPAddr{IP: sa.Addr[0:], Port: sa.Port}`（官方net包的tcpsock_posix.go文件中，`sockaddrToTCP()`函数是直接用sa.Addr[0:]）

**Comment by panjf2000** [comment]
这里的代码太久了，有点不太记得了，我有空再看看。
