### ISSUE TITLE
gnet.Conn.Close()问题

### ISSUE THREAD

**Issue by concn** [panjf2000/gnet#368]
版本 v1.6.4
在React调用close正常关闭socket链接
然后保存gnet.Conn，在其它方法里调用defer gnet.Conn.Close()；一般正常可以关闭，即调用后马上会执行到OnClosed方法里；
但偶尔有时候关闭不了，即执行不到OnClosed方法；

后来经常大概3－5分钟后，从日志看到执行到OnClosed方法，；

例如：209号客户端是17:14:53连接的；

17:15:50分在其它方法里调用gnet.Conn.close，并未马上执行；

17:17:48看日志才发现执行到OnClose方法里；随后出现了很多客户端被关闭，可以这些客户端并未执行gnet.Conn.close去关闭
![微信图片_20220511173332](https://user-images.githubusercontent.com/50606635/167818451-8e694a99-d17b-464f-a546-cef741d99aa6.png)

**Comment by concn** [comment]
大概率是十次出现一次这种关闭不了的情况

**Comment by concn** [comment]
目前在windows上测试没有出现这个问题，只有linux上测试出现这个问题！不知道是怎么回事呢？

**Comment by mikeqoo1** [comment]
有沒有可能是Linux的 CLOSE_WAIT或  TIME_WAIT 的情況?

**Comment by panjf2000** [comment]
Close 方法是异步执行的，不过延迟这么久也很奇怪，方便贴一下代码吗？

**Comment by concn** [comment]
是版本的问题，找到问题的原因了，window执行gnet.Conn.close()的时候，调用的是c.conn.SetReadDeadline(time.Now())；所以后来都是因为read超时关闭掉了，是可以关闭的。
而linux执行gnet.Conn.close()的时候，执行到下面这段代码:
![微信图片_20220511173332](https://user-images.githubusercontent.com/50606635/168196341-d4dc0310-10b7-4c61-b2e7-36ca81dbc142.png)
实际执行n, err := io.Writev(c.fd, iov)的时候，err返回的是resource temporarily unavailable这个错误，导致err != nil；但也不是后面unix.EAGAIN的时候，就进不了if；此时n 返回－1；（有时候n返回65535）;当n=-1的时候，再执行c.outboundBuffer.Discard(n)，此时for循环的判断c.outboundBuffer.IsEmpty()就永远为false，就会一直for循环下去退不出来的。从而导致问题的出现。
我查看了一下代码，上面贴的是版本 v1.6.4的代码，而新版本2.0的已经变成下面的代码了：
			if n, e := io.Writev(c.fd, iov); e != nil {
				el.getLogger().Warnf("closeConn: error occurs when sending data back to peer, %v", e)
				break
			} else {
				c.outboundBuffer.Discard(n)
			}
这样e != nil直接break掉了就没有问题。

**Comment by concn** [comment]
因为2.0暂不支持windows，所以我们用的是1.6.4的版本。

**Comment by panjf2000** [comment]
resource temporarily unavailable 就是 `EAGAIN` 错误，你要说的应该是因为是这个错误所以进入不了分支去 `break` 掉这个 loop 吧，我等会儿修复下，出个 v1.6.5

**Comment by concn** [comment]
对，因为错误打印日志出来，是resource temporarily unavailable ，但是没有进入if；此时n为－1，就一直循环跳不出来了

**Comment by concn** [comment]
查了下日志，打印出来broken pipe这个错误可以进入if，说明是EAGAIN错误，打印err出来是resource temporarily unavailable就会进入不了；但我网上查了一下Resource temporarily unavailable也是EAGAIN，这个就不知道为什么不能进入if了。

**Comment by panjf2000** [comment]
v1.6.5 已修复
