### ISSUE TITLE
Example using ReadN

### ISSUE THREAD

**Issue by ezmicken** [panjf2000/gnet#37]
I'm trying to create a tcp protocol for my game using gnet. I put it under stress and received an incomplete message. The http example comes pretty close to my use case and does handle incomplete messages, but it's pretty complicated.

There is a large comment about the function `ReadN` that describes what it might be used for but not how. When should I use `Read` and when should I use `ReadN`? An example using `ReadN` as intended would help a great deal.

**Comment by panjf2000** [comment]
@ezmicken 
You invoke `Read()`, you get all data from the inbound buffer that might contain incomplete data from the last few requests and current request, besides it doesn't evict those data from the buffer, you have to invoke `ResetBuffer()` at the end of the `React` if you ensure that you've gotten the expected data from `Read()` while `ReadN(n int)`  gives you bytes with the given fixed length and it does evict those data from the buffer, hence you should use this function only if you know exactly the length of subsequent TCP stream based on the protocol, like the Content-Length attribute in an HTTP request which indicates you how much data you should read from inbound ring-buffer.

In fact, `ReadN()` could be replaced with the [FixedLengthFrameCodec](https://github.com/panjf2000/gnet/blob/master/codec.go#L96-L98) which is one of the [codecs](https://github.com/panjf2000/gnet#multiple-built-in-codecs-for-tcp-stream) of `gnet` with which you are able to make it easier to unpack and pack frames based on your protocol and you can find the examples in my [example](https://github.com/panjf2000/gnet/blob/master/examples/codec/server/server.go) or [test code](https://github.com/panjf2000/gnet/blob/master/gnet_test.go#L23-L271).

Thank you for your attention to `gnet` and please let me know if you still have any questions later.

**Comment by ezmicken** [comment]
Thanks, that's what I was looking for and I think I understand now.

**Comment by panjf2000** [comment]
I am closing this issue but feel free to open a new issue if you get new questions later.
