### ISSUE TITLE
新增"错误拦截器"功能，捕获系统错误，让业务方自行处理错误

### ISSUE THREAD

**Issue by gcggcg** [panjf2000/gnet#370]
使用的环境配置如下： 
- Go version (e.g. Go 1.17):
 - gnet version (e.g. v1.6.4):
 -咨询两个问题
1. 首先将基于gnet设计的tcp服务打包部署在微软电脑商城下载的unbutu，然后在里面部署正常可以运行，但是一旦发起客户端连接部署的tcp服务就会自动关闭服务进程。
打印错误日志如下：
`2022-05-18 20:51:12.999 ERROR   gnet@v1.6.4/reactor_default_linux.go:35 Accept() fails due to error: protocol not available
2022-05-18 20:51:13.000 ERROR   gnet@v1.6.4/server_unix.go:171  main reactor is exiting due to error: accept a new connection error`
这种具体是什么原因导致的，然后该如何解决。

2. 还发现了一个问题，那就是按照步骤1的方式部署在纯正的unbutu服务器中，可以正常运行，并且小并发请求没有问题。但是当我在linux本机服务下进行压测该服务，大致的配置是5000并发连续10次去压测该tcp服务，但是压到一半就会自动杀死服务进程，导致大量的请求失败，这种问题该如何解决。
错误代码如下：
`2022-05-18 21:16:42.463 ERROR  gnet@v1.6.4/reactor_default_linux.go:35 Accept() fails due to error: too many open files
2022-05-18 21:16:42.463 ERROR   gnet@v1.6.4/server_unix.go:171  main reactor is exiting due to error: accept a new connection error
`
（猜测是压测使用的套接字太多，但是才压测5000并发就异常大致进程退出吗）

**Comment by panjf2000** [comment]
第一个问题，你监听的 address 是什么？协议格式不对。第二个问题是系统的最大打开文件句柄数太小，修改一下系统配置就行了。

**Comment by gcggcg** [comment]
大佬，第一个问题监听的就是正常的端口号地址唯一不同的就是使用的linux服务不一样一个是正式的linux服务器，一个是windows商城下载的虚拟镜像。
第二个问题（比较关心这个问题）：
 通过修改linux的句柄数确实不会出现进程退出了，但是我发现用go的官方net包开发的在不修改句柄数的情况下进行压测不会导致进程退出，但是我们gnet会导致退出，这个是不是一个致病问题。（因为在线上的话我们不能保证会出现多少句柄数，如果超过了设置导致服务崩掉是不是后果太严重）

**Comment by gcggcg** [comment]
> 第一个问题，你监听的 address 是什么？协议格式不对。第二个问题是系统的最大打开文件句柄数太小，修改一下系统配置就行了。
大佬，第一个问题监听的就是正常的端口号地址唯一不同的就是使用的linux服务不一样一个是正式的linux服务器，一个是windows商城下载的虚拟镜像。
第二个问题（比较关心这个问题）：
通过修改linux的句柄数确实不会出现进程退出了，但是我发现用go的官方net包开发的在不修改句柄数的情况下进行压测不会导致进程退出，但是我们gnet会导致退出，这个是不是一个致病问题。（因为在线上的话我们不能保证会出现多少句柄数，如果超过了设置导致服务崩掉是不是后果太严重）

**Comment by panjf2000** [comment]
代码贴出来看看

**Comment by gcggcg** [comment]
> 代码贴出来看看
当前的gnet版本使用的是：1.6.4
代码如下： （和新的case问题是相同的代码）
`// NewTCPServer 启动新的TCP服务器
func NewTCPServer() { //
cCoroutinesPool, err := ants.NewPoolWithFunc(util.Config.WorkPool, logic.HandleTaskLogic)      // 当前配置文件一般设置500，1000
if err != nil {  
os.Exit(1)
}
server := &Server{
Pool: cCoroutinesPool,
}
go func() {
// 监听退出信号,关闭服务器
shutdown := make(chan os.Signal, 1)
signal.Notify(shutdown, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
defer close(shutdown)
if <-shutdown == nil {
return
}
util.Info("====================关闭服务=================")
// 关闭接入心跳 关闭服务器
if err := gnet.Stop(context.Background(), "tcp://"+util.Config.IP+":"+util.Config.Port); err != nil {
return
}

}()

util.Info("====================启动服务=================")
if err = gnet.Serve(server, "tcp://"+util.Config.IP+":"+util.Config.Port,
	gnet.WithMulticore(true),
	gnet.WithTCPKeepAlive(time.Duration(util.Config.TCPKeepAliveTime)*time.Second),
	gnet.WithCodec(NewBuiltInFrameCodec('}')),
	gnet.WithLogger(util.Logger)); err != nil {
	util.Error("启动服务器异常" + err.Error())
}
}
// React client响应时触发
func (ser *Server) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
if frame != nil {
//buf := bbPool.Get()
//_, _ = buf.Write(frame)
buf := append([]byte{}, frame...)
c.Read()
util.TraceInfo("客户端："+c.RemoteAddr().String()+" 请求的的数据：", string(frame))
if len(buf) != 0 {
task := model.Task{
Conn: c,
Buf: buf,
}
buf = nil
if err := ser.Pool.Invoke(task); err != nil {
util.Error("注入请求数据异常" + err.Error())
}
}
}

return
}`

**Comment by panjf2000** [comment]
你客户端也是用的tcp去连接的吗？

**Comment by panjf2000** [comment]
还有，贴源码用 md 语法修饰一下，不然太难看了。

<img width="99" alt="image" src="https://user-images.githubusercontent.com/7496278/169686181-ba847e24-67c4-42e9-b67c-0b7aae1bdb3d.png">

**Comment by gcggcg** [comment]
> 你客户端也是用的tcp去连接的吗？

代码已经修饰了，客户端是tcp的，问题就是：
句柄数不知道设置多少合适，在线上使用的话，因为发现句柄数设置太小，高并发测试下会导致句柄数不够而使得进程服务宕机。但是如果是官方net包只是会报错，但是不会进程服务宕机。

**Comment by panjf2000** [comment]
目前 gnet 的处理机制就是系统调用出现错误就结束整个服务，系统的最大句柄数你们可以尽量设置大一点，反正你们实际用的时候也不会用那么多。

**Comment by gcggcg** [comment]
> 目前 gnet 的处理机制就是系统调用出现错误就结束整个服务，系统的最大句柄数你们可以尽量设置大一点，反正你们实际用的时候也不会用那么多。

好的，那就可以理解了，后面这个触发机制会不会做修改，不让服务宕机，就像gnet那样。因为如果是k8s方式进行监控部署的话，确实是没问题的，一旦宕机，后面k8s会自动检测重启，但是如果是没有监控机制，那么宕机后就会风险很大。

**Comment by panjf2000** [comment]
> > 目前 gnet 的处理机制就是系统调用出现错误就结束整个服务，系统的最大句柄数你们可以尽量设置大一点，反正你们实际用的时候也不会用那么多。
> 
> 好的，那就可以理解了，后面这个触发机制会不会做修改，不让服务宕机，就像gnet那样。因为如果是k8s方式进行监控部署的话，确实是没问题的，一旦宕机，后面k8s会自动检测重启，但是如果是没有监控机制，那么宕机后就会风险很大。

可以增加一个新功能：服务启动前可以设置"错误捕获器": ErrorInterceptor，然后在发生系统错误的时候可以自行决定是要自己消化还是继续抛回到框架里使其退出服务。

**Comment by gcggcg** [comment]
> > > 目前 gnet 的处理机制就是系统调用出现错误就结束整个服务，系统的最大句柄数你们可以尽量设置大一点，反正你们实际用的时候也不会用那么多。
> > 
> > 
> > 好的，那就可以理解了，后面这个触发机制会不会做修改，不让服务宕机，就像gnet那样。因为如果是k8s方式进行监控部署的话，确实是没问题的，一旦宕机，后面k8s会自动检测重启，但是如果是没有监控机制，那么宕机后就会风险很大。
> 
> 可以增加一个新功能：服务启动前可以设置"错误捕获器": ErrorInterceptor，然后在发生系统错误的时候可以自行决定是要自己消化还是继续抛回到框架里使其退出服务。

好的，感谢大佬，后面期待，这个功能上线使用。
