### ISSUE TITLE
TCP服务在少量的连接进行无间断连续压测导致服务系统卡顿问题(Linux和Windows均存在该问题)

### ISSUE THREAD

**Issue by gcggcg** [panjf2000/gnet#372]
- OS (Linux和Windows均存在该问题):
 - Go version (Go 1.18):
 - gnet version (v1.6.4):

**What is your question about gnet?**
通过gnet开发的TCP服务，发现一个问题，那就是少量连接然后进行无间隔压测，导致服务卡顿，但是服务进程没有崩掉，问题是卡顿的服务再次请求服务的时候无法接收请求以及处理响应。
以下是压测的设置：
         并发连接数： 100
         无间断请求：1000/每个连接
测试结果是40%成功，60%超时，但是通用的压测在官方net包开发的服务就不会存在该问题，该问题该如何规避。初次怀疑是大量的数据到达连接上而不能及时处理导致的卡顿，但是这个卡断一直持续，后续再次请求也不能正常处理新的请求。还请给出一些建议方便正确我们的开发使用。

**Comment by panjf2000** [comment]
代码贴出来我看看，是不是 React() 里阻塞了？这里不能阻塞，否则就会影响后续的请求。

**Comment by gcggcg** [comment]
> 代码贴出来我看看，是不是 React() 里阻塞了？这里不能阻塞，否则就会影响后续的请求。

当前的gnet版本使用的是：1.6.4
代码如下：
`// NewTCPServer 启动新的TCP服务器
func NewTCPServer() { //
	cCoroutinesPool, err := ants.NewPoolWithFunc(util.Config.WorkPool, logic.HandleTaskLogic) 
	if err != nil {
		os.Exit(1)
	}
	server := &Server{
		Pool: cCoroutinesPool,
	}
	go func() {
		// 监听退出信号,关闭服务器
		shutdown := make(chan os.Signal, 1)
		signal.Notify(shutdown, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
		defer close(shutdown)
		if <-shutdown == nil {
			return
		}
		util.Info("====================关闭服务=================")
		// 关闭接入心跳  关闭服务器
		if err := gnet.Stop(context.Background(), "tcp://"+util.Config.IP+":"+util.Config.Port); err != nil {
			return
		}

	}()

	util.Info("====================启动服务=================")
	if err = gnet.Serve(server, "tcp://"+util.Config.IP+":"+util.Config.Port,
		gnet.WithMulticore(true),
		gnet.WithTCPKeepAlive(time.Duration(util.Config.TCPKeepAliveTime)*time.Second),
		gnet.WithCodec(NewBuiltInFrameCodec('}')),
		gnet.WithLogger(util.Logger)); err != nil {
		util.Error("启动服务器异常" + err.Error())
	}
}
// React client响应时触发
func (ser *Server) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	if frame != nil {
		//buf := bbPool.Get()
		//_, _ = buf.Write(frame)
		buf := append([]byte{}, frame...)
		c.Read()
		util.TraceInfo("客户端："+c.RemoteAddr().String()+" 请求的的数据：", string(frame))
		if len(buf) != 0 {
			task := model.Task{
				Conn: c,
				Buf:  buf,
			}
			buf = nil
			if err := ser.Pool.Invoke(task); err != nil {
				util.Error("注入请求数据异常" + err.Error())
			}
		}
	}

	return
}`

**Comment by panjf2000** [comment]
你在 React() 调用 c.Read() 干吗？做无用功，你都设置了 codec 了，直接拷贝 frame 之后用就行了。你说服务卡顿，是不是 pool 满了，所以卡住了，试试设置 pool 为非阻塞的，或者先不要用 goroutine pool.

**Comment by gcggcg** [comment]
> 你在 React() 调用 c.Read() 干吗？做无用功，你都设置了 codec 了，直接拷贝 frame 之后用就行了。你说服务卡顿，是不是 pool 满了，所以卡住了，试试设置 pool 为非阻塞的，或者先不要用 goroutine pool.

刚刚想问呢，大佬，如果设置的pool非阻塞，那效果是不是高并发请求下，如果设置pool太小，会导致有的请求没有拿到pool的协程，而丢失。这部分丢失的请求就没有了。还是说您有更好的建议，因为关于pool的设置，不知道设置多少合适。

**Comment by panjf2000** [comment]
设置 pool 为非阻塞，如果满了就先把任务存下来，然后定时去检查 pool 是否空闲了，是的话再塞进去执行，或者简单点你们就直接不要用 goroutine pool 了，直接无脑 go func() 就行了，现在你们的 goroutine 数量已经多到无法忍受了吗？

**Comment by gcggcg** [comment]
> 设置 pool 为非阻塞，如果满了就先把任务存下来，然后定时去检查 pool 是否空闲了，是的话再塞进去执行，或者简单点你们就直接不要用 goroutine pool 了，直接无脑 go func() 就行了，现在你们的 goroutine 数量已经多到无法忍受了吗？

哈哈，这个倒没有，服务里面用的的协程数主要就是gnet产生的协程，其他地方暂时没有产生协程数，这里用pool主要是配合你的ant协程管理，你上面说的设置非阻塞会定期执行好像和我测试的效果不太一样，因为设置非阻塞后直接报错：
`too many goroutines blocked on submit or Nonblocking is set`不会触发新的请求。

**Comment by panjf2000** [comment]
> 你上面说的设置非阻塞会定期执行好像和我测试的效果不太一样

。。。我的意思是你自己存下来去定期检查然后重新提交，不是说这个库有这样的功能。

> 而官方的net包就不会只是在连接的协程上进行for循环监听不会每次请求都创建新的协程。

官方的 net 标准库是一条连接一个 goroutine，所以 gnet 是针对大量连接使用少量 goroutine 来管理，先搞清楚自己的实际场景，如果没有很多连接那你直接用 net 就好了。

**Comment by gcggcg** [comment]
> > 你上面说的设置非阻塞会定期执行好像和我测试的效果不太一样
> 
> 。。。我的意思是你自己存下来去定期检查然后重新提交，不是说这个库有这样的功能。
> 
> > 而官方的net包就不会只是在连接的协程上进行for循环监听不会每次请求都创建新的协程。
> 
> 官方的 net 标准库是一条连接一个 goroutine，所以 gnet 是针对大量连接使用少量 goroutine 来管理，先搞清楚自己的实际场景，如果没有很多连接那你直接用 net 就好了。

感谢，大佬，现在清晰了。
