### ISSUE TITLE
gnet.Conn.Close() 未及时执行问题

### ISSUE THREAD

**Issue by JemmyH** [panjf2000/gnet#379]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04): Debian GNU/Linux 9
 - Go version (e.g. Go 1.13): go version go1.17.6 linux/amd64
 - gnet version (e.g. v1.0.0): v2.0.3

**What is your question about gnet?**
调用已经创建的的 gnet.Conn.Close() 方法后，未及时与远端断开连接

目的：调用 Close() 后，及时断开连接

看了代码，Close() 其实是往 Eventloop 的 poller 的事件队列中放入一个trigger事件，但是是一个普通的trigger，考虑到关闭事件的重要性，是否可以将 Close() 放到 UrgentTrigger 中呢？

**Comment by JemmyH** [comment]
实际使用中发现，调用 close 之后等了好久，OnClose 始终没被调用

**Comment by panjf2000** [comment]
最终应该还是有被调用的吧？不然就是bug了，是不是你的服务有很多其他异步任务？

**Comment by JemmyH** [comment]
确定最后没有被调用；
是有很多异步任务。

**Comment by panjf2000** [comment]
没有被执行？那这是 bug，麻烦提供复现的步骤，方便的话贴一下能复现出来的 demo 代码。

**Comment by JemmyH** [comment]
sorry，我的代码bug。非常抱歉
