### ISSUE TITLE
Expose the func in gnet.Conn for getting the index of poller

### ISSUE THREAD

**Issue by 6congyao** [panjf2000/gnet#38]
RT，非常容易实现，需要在Conn中有接口能获取其所属poller的index，以便在后续处理时直接使用这个index来为task queue做分片，免去计算开销

**Comment by panjf2000** [comment]
@6congyao 

分片我可以理解，不过是不是一定要用 event-loop index 来做我觉得有待商榷。
比如，对 connection 做 hash 是不是也可以？

**Comment by 6congyao** [comment]
是的，目前的做法就是为每个conn给一个ID然后根据ID做hash或者取模，这么来看并不是非要使用poller的index。

**Comment by panjf2000** [comment]
嗯，不是必须要用 event-loop index，而且其实也并不需要人为地给每个 conn 再分配 ID 了，直接取 `Conn.RemoteAddr()` 就行了。
