### ISSUE TITLE
是否有gnet-http http2 quic http3等子项目？

### ISSUE THREAD

**Issue by 2391003262** [panjf2000/gnet#381]
是否有gnet-http http2 quic http3等子项目？

**Comment by 2391003262** [comment]
> 个人暂时还没时间弄，欢迎贡献。

许多http quic等库是通过net.Conn建立起来的，如果能把gnet跟net.Conn  net.PackConn做适配，那么，基于gnet的相关库可以很快改出来。

**Comment by 2391003262** [comment]
> 个人暂时还没时间弄，欢迎贡献。

只是，我不清楚这样能不能做到。因为net.Conn是BIO，而gnet是事件驱动的。

**Comment by panjf2000** [comment]
Duplicate #311

**Comment by someview** [comment]
这个问题还没关闭啊，我们也有这个需求，采用gnet来作为quic协议的底层连接驱动库。不匹配的地方是quic没有提供asyncwrite，这和gnet当前的方式不太匹配。另外一点是，gnet是把addr 绑定在conn上面的， 而quic协议addr本身是可变的，这要求把addr从conn中解放出来
