### ISSUE TITLE
websocket demo 阻塞

### ISSUE THREAD

**Issue by suconghou** [panjf2000/gnet#384]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04): mac 
 - Go version (e.g. Go 1.13):  1.18.3
 - gnet version (e.g. v1.0.0):  2.1.0

根据demo代码

https://github.com/gnet-io/gnet-examples/blob/v2/websocket/server/websocket.go#L60

OnTraffic 内 `wsutil.ReadClientData(c)`  很大概率会阻塞， 我们保证不了客户端发送来的是一个完整的数据包

经过多个浏览器 不断刷新测试， 很容易就卡住了，一旦卡住EventLopp， 后续所有请求都无法处理。

所以这个demo 不是最佳实践， 最好说明一下

另外，此种情况下，我们有什么策略能够较好完成吗，非要每次读取都开一个协程读取吗，这不太好

另外， 如果客户端发送了多条websocket数据包， ReadClientData 只读取了一条，  OnTraffic 后续还会再触发吗，如果没有触发，就会出现漏数据的情况，我们要在一次回调里，都消费完所有的buffer, 我们要多次调用ReadClientData，但我们也不知道到底消费几次，消费多了，又会卡住，消费少了，漏数据， 请指教

**Comment by panjf2000** [comment]
每次你就一直读完整的包，然后处理，最后一个残包就留在 gnet 的内部 buffer 里，等待后面客户端发剩下的数据的时候你再接着读。

**Comment by suconghou** [comment]
没法保证每次读取时都是一个完整的包， 也无法知道读取一次后，后面还有多个包，还是一个半包

**Comment by suconghou** [comment]
没法做到流式处理,不能满足需求,已经换库了

**Comment by datafeng** [comment]
> 没法做到流式处理,不能满足需求,已经换库了

我貌似也有同样的需求，好奇后来换了什么库？

**Comment by suconghou** [comment]
@datafeng   https://github.com/lesismal/nbio  带有流式处理的websocket, 使用很方便
