### ISSUE TITLE
关于异步任务处理的疑问

### ISSUE THREAD

**Issue by yiippee** [panjf2000/gnet#39]
感谢潘少的项目 ∩＾∩
有个疑问啊，你在文中提到如果有大量的goroutine会给go的调度带来压力，我印象中go官方提到过不会带来压力。是我理解错了吗？谢谢。
```
type Poller struct {
	fd            int    // epoll fd
	wfd           int    // wake fd
	wfdBuf        []byte // wfd buffer to read packet
	asyncJobQueue internal.AsyncJobQueue
}
```
另外能大概解析一下上面 wfd 具体作用吗？谢谢。

在处理EpollWait返回事件有以下代码，请问wfd有什么作用呢？
```
	if fd := int(el.events[i].Fd); fd != p.wfd { // 为什么要做这个判断呢？
		if err = callback(fd, el.events[i].Events); err != nil {
			return
		}
	} else {
		wakenUp = true
		fmt.Println("wfdbuf: ", p.wfdBuf)
		_, _ = unix.Read(p.wfd, p.wfdBuf)
	}
```

-------------分割线  补上

了解了eventfd的用法，对应上面的wfd，为了让异步执行的任务也统一通过epollWait来处理，但有两个疑问：
1，为什么要统一通过epollWait来统一调度呢，不可以想写数据的时候直接就往connfd中write呢？这样会有什么问题呢？谢谢。
2，
```
func (q *AsyncJobQueue) ForEach() (err error) {
	q.mu.Lock()
	jobs := q.jobs
	q.jobs = nil
	q.mu.Unlock()
	for i := range jobs {
		if err = jobs[i](); err != nil {
			return err
		}
	}
	return
}
```
ForEach 这个函数会遍历所有的jobs并执行，那么只要一个jobs写入的eventfd被调度了，那么就会执行所有的jobs，而且定时器也会定时触发这个调度。这样感觉会导致一些异步任务的执行并不是由这个任务本身去触发的，而是由其他的任务触发的，而且还会有多次write（eventfd）后，多次read（eventfd）没必要的情况（因为jobs一次就已经全部执行完了）。 请问是我哪里理解错了吗？谢谢。

**Comment by panjf2000** [comment]
> 我印象中go官方提到过不会带来压力。是我理解错了吗？

"不会带来压力"这句话看在什么场景下说，如果 go 程数量没有达到一个过分夸张的程度，这句话的确是对的，毕竟 go 程很轻量，但是我假设的场景是海量 go 程，并不是说 go 调度不了这么多 go 程，而是系统资源被侵占从而间接影响了调度器的运行，这个肯定是不可避免地会给整个系统带来压力的。

> 为什么要统一通过epollWait来统一调度呢，不可以想写数据的时候直接就往connfd中write呢？

当然不能随心所欲想读就读想写就写啊，不然事件驱动技术是被开发出来干吗的？想读的时候未必能读（读缓冲区为空），想写的时候未必能写（写缓冲区满了），就是为了要在可读的时候读，可写的时候写才有的事件驱动技术啊！提高性能！

> ForEach 这个函数会遍历所有的jobs并执行，那么只要一个jobs写入的eventfd被调度了，那么就会执行所有的jobs，而且定时器也会定时触发这个调度。这样感觉会导致一些异步任务的执行并不是由这个任务本身去触发的，而是由其他的任务触发的，而且还会有多次write（eventfd）后，多次read（eventfd）没必要的情况（因为jobs一次就已经全部执行完了）。 请问是我哪里理解错了吗？

首先，定时器没有触发这个调度。其次，多次写 eventfd 这个你的确没理解错，这个也无法避免，如果本来就是有多个 eventfd 事件，我总不能全部收集起来之后才去写吧？我也不知道哪一个是最后一个啊，难不成一直等吗？要是只有一个呢？

**Comment by yiippee** [comment]
<< 首先，定时器没有触发这个调度
我看源码中是有的，如下：
```
func (lp *loop) loopTicker() {
	var (
		delay time.Duration
		open  bool
	)
	for {
		if err := lp.poller.Trigger(func() (err error) { // 调用Trigger，Trigger再调用unix.Write(p.wfd, b)
			delay, action := lp.svr.eventHandler.Tick()
			lp.svr.ticktock <- delay
			switch action {
			case None:
			case Shutdown:
				err = errShutdown
			}
			return
		}); err != nil {
			break
		}
		if delay, open = <-lp.svr.ticktock; open {
			time.Sleep(delay)
		} else {
			break
		}
	}
}
```

**Comment by panjf2000** [comment]
@yiippee 
关于定时触发的问题是我记错了，的确是会定时写 eventfd，不过这个也不是什么问题，相反，定时激活 event-loop 而不是让它一直阻塞等也不是一件坏事，让 server 保持活跃状态。

> 关于eventfd，是否可以不使用eventfd，而是异步事件处理完后要发送数据时，注册可写事件到epoll就可以了？

至于这个，我不太明白你想表达的具体是什么意思？能具体点吗？

**Comment by yiippee** [comment]
> @yiippee
> 关于定时触发的问题是我记错了，的确是会定时写 eventfd，不过这个也不是什么问题，相反，定时激活 event-loop 而不是让它一直阻塞等也不是一件坏事，让 server 保持活跃状态。
> 
> > 关于eventfd，是否可以不使用eventfd，而是异步事件处理完后要发送数据时，注册可写事件到epoll就可以了？
> 
> 至于这个，我不太明白你想表达的具体是什么意思？能具体点吗？

```
	_ = es.pool.Submit(func() {
		time.Sleep(3* time.Second) // 执行一些阻塞事情
		// c.AsyncWrite(data)  这里是调用write eventfd 来通知epoll_wait 来调度写数据的。去掉
               lp.poller.AddWrite(c.fd)  // 换成这里直接注册可写事件啊，也是由epoll_wait来调度的，在可 
                                                                                                    写事件回调里面进行写fd
	})
```
大概上面的方式

**Comment by yiippee** [comment]
```
		case !c.outboundBuffer.IsEmpty():
			if ev&netpoll.OutEvents != 0 {
				fmt.Println("write2...")
				return lp.loopOut(c)
			}
			return nil
```
loop_linux.go 文件中上面这块逻辑好像有点问题，如果可读事件来了，但是outbuffer中有数据，则会一直进这个条件，死循环。

**Comment by panjf2000** [comment]
不可以，使用 eventfd 是为了确保写操作最后是在 event-loop 的那个 goroutine 里执行的，不然多 goroutine 操作 ring-buffer 会有 race 问题。

**Comment by yiippee** [comment]
> 不可以，使用 eventfd 是为了确保写操作最后是在 event-loop 的那个 goroutine 里执行的，不然多 goroutine 操作 ring-buffer 会有 race 问题。

是的，这个我也看到了，ringbuffer可以加锁吧。我刚按我改的跑了echo，感觉是可行的。不知道会不会有其他问题？

**Comment by panjf2000** [comment]
为什么要按你这种方式改？有什么好处？

**Comment by panjf2000** [comment]
> 如果可读事件来了，但是outbuffer中有数据，则会一直进这个条件，死循环。

这里是为了优先处理写数据，等到数据写完了自然就可以读了。

**Comment by yiippee** [comment]
> 为什么要按你这种方式改？有什么好处？

如果按照你现在的方式，write eventfd 会导致所有的异步任务执行，总感觉这样有点奇怪。按道理来说，一个connfd应该由自己控制异步任务的读写，而不是由其他人来触发啊。还有，现在的方式会导致很多无意义的读写eventfd，也就是会触发很多无意义的epoll_wait系统调用。   而如果所有的读写事件注册只有自己来维护，感觉更合理一些。

**Comment by yiippee** [comment]
> > 如果可读事件来了，但是outbuffer中有数据，则会一直进这个条件，死循环。
> 
> 这里是为了优先处理写数据，等到数据写完了自然就可以读了。

这样会有问题的，如果可读事件来了，但是outbuffer中有数据，而又没法进入读的逻辑，则会一直进这个条件，死循环。我刚试了一下，会有死循环的。

**Comment by panjf2000** [comment]
你也知道那些是异步任务，既然是异步任务，业务方本来就只是负责注册回调就行了，至于异步任务什么时候被执行就和它没关系了，什么时候执行那些任务是由系统/框架来决定的，这才叫异步任务。

**Comment by panjf2000** [comment]
为什么会有死循环，你的 socket 难道一直没有可写事件发生？

**Comment by yiippee** [comment]
> 你也知道那些是异步任务，既然是异步任务，业务方本来就只是负责注册回调就行了，至于异步任务什么时候被执行就和它没关系了，什么时候执行那些任务是由系统/框架来决定的，这才叫异步任务。

我这样
```
	        c.outboundBuffer.Write(buf)  数据准备好
	        c.loop.poller.ModWrite(c.fd)  注册可写回调
```
也是只负责注册回调，执行让epoll_wait来调度啊

**Comment by yiippee** [comment]
> 为什么会有死循环，你的 socket 难道一直没有可写事件发生？

c.outboundBuffer.Write(buf) 
c.loop.poller.ModWrite(c.fd)  
我是改成上面这样执行异步任务，跑echo时发现会有死循环的。
有可写事件，但是可读事件先来了，同时异步任务提交数据到outbuffer了，就会这样。

**Comment by panjf2000** [comment]
可读事件先来也无所谓啊，反正是 LT 模式，这次没有读，下次还会不断提醒的，只要有可写事件到来，然后把 outboundbuffer 的数据都写回去了之后下次自然就会去读数据了，按你说的那种死循环应该是没有可写事件，一直都是可读，然后 outboundbuffer 里的数据一直没法写出去，这本身就不正常，应该是你改的有问题，你再检查一下。

**Comment by panjf2000** [comment]
@yiippee 
Hello，请问这里还有问题吗？或者其他新的问题？如果还有疑问，可以继续讨论，如果没有的话，麻烦关掉这个 issue，谢谢！
