### ISSUE TITLE
gnet@v1.6.5/acceptor_unix.go:38 Accept() fails due to error: too many open files

### ISSUE THREAD

**Issue by concn** [panjf2000/gnet#390]
不知道是使用不当，还是程序的bug，出现这个后，程序出现假死，收不到消息了，但程序并未退出，问题如下：
![image](https://user-images.githubusercontent.com/50606635/182798335-c4a78784-e645-4171-aead-07f54455a223.png)
即出现这几行错误日志后，程序不再接收消息。我查了一下代码，调用如下
1.start后，server_unix.go的171行开始调用
![image](https://user-images.githubusercontent.com/50606635/182798877-ff40c5d8-dfe9-4c57-937a-a405cb9531d3.png)
2.然后是reactor_default_linux.go的35行调用后，返回第一个错误
![image](https://user-images.githubusercontent.com/50606635/182799078-966a8fea-06b4-4911-b598-1a3ca04cdcbb.png)
3.调用的是acceptor_unix.go的这个方法，
![image](https://user-images.githubusercontent.com/50606635/182799603-74abea3f-fb08-4f96-a80f-228e5403bc68.png)

从以上看出返回的错误是3步的38行，打印出Accept() fails due to error: too many open files这行错误日志
然后走到2是39行打印出main reactor is exiting due to error: accept a new connection error这行日志错误后，程序不再接收消息
linux是默认1024个连接，表面上看是未关闭客户端连接造成的。

**Comment by concn** [comment]
不知道是什么原因造成的这个问题，很多客户端会自动检测断线重连，但我gnet服务器并未进行关闭处理，；gnet会自动关闭以前无效的连接，还是需要我手动关闭处理呢？谢谢

**Comment by panjf2000** [comment]
https://www.ibm.com/docs/en/sim/6.0.0.22?topic=problems-too-many-files-open-unix-linux

**Comment by concn** [comment]
![image](https://user-images.githubusercontent.com/50606635/183576921-8063c1a4-72df-4f82-8503-6677a45211df.png)
之前表达的问题不是很精确，我想表达的是，因为流程是走这个，所以才导致了客户端已经断开连接的但gnet没有关闭，从而导致连接数一直增加，无论这个linux设置多少连接限制，最后都会被占满；根本原因是gnet走这个流程的时候，没有把客户端关闭。 上图可以看到上午10点多的时候这个使用gnet库的程序连接数三百多，下午二点的时候，连接数已经是460，一直在增加，目前是1024可以使用2天，如果按上面链接设置成8000的话，大概估计可以使用半个月后仍然会出现这个问题，实际上我们只有几十个终端在连接，他们会有重连上来；我在windows上跑的这个程序不会有这个问题，说明是linux库和windows库的处理方式不一样.

**Comment by concn** [comment]
实际上客户端不会主动断开连接，他如果判断没有连接了会不关闭之前的连接直接发起重连，重而导致了连接数一直在增加。

**Comment by concn** [comment]
我明白了，问题主要不是出在这里，主要是出在没有close客户端上，这里只是问题的表现，表现出来的问题是没有close已经空闲的连接上，才导致了连接数一直增加。我找找代码看看如果客户端没有主动关闭服务器怎么能把它关闭掉。

**Comment by concn** [comment]
应该是acceptor_unix.go的56行和57行是关闭socket的吧？如果是这样的话，那问题就出在没有走到这一步，在上面就直接返回了，所以socket没有被关闭掉，然后一直增加？
请问linux的是这个走到56和和57行gnetServer才会主动关闭socket的吗？

**Comment by panjf2000** [comment]
gnet 不会主动去关闭 socket，你要自己调用 c.Close()

**Comment by concn** [comment]
请问大神三个小白问题，1、gnet.Serve(echo, fmt.Sprintf("tcp://:%d", port), gnet.WithMulticore(multicore), gnet.WithReusePort(reuseport), gnet.WithTCPKeepAlive(330)) 如果启动的时候加上gnet.WithTCPKeepAlive这个参数，会起作用330秒没有数据自动关闭连接吗？2、是不是需要自己保存socket，因为目前没有保存，不知道在哪调用 c.Close() 3、gnet的OnClosed方法，是自己手动调用c.Close()后才会执行到吧？

**Comment by panjf2000** [comment]
1. socket 的 keepalive 是由三个参数控制的，不是简单的一个数字，具体可以看：https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
2. 是的，如果你需要随时能关闭 socket，则需要把 gnet.Conn 保存起来
3. 不管是客户端关闭还是服务端关闭连接，OnClose 都会被回调。

**Comment by concn** [comment]
![image](https://user-images.githubusercontent.com/50606635/184306421-467e9e6c-a260-458e-993e-18b28bc07afa.png)

目前把server的OnClosed方法上来，然后在里面关闭，跑了二天看大概连接数一直稳定在130，解决问题。
所以可以这样理解，不管是客户端关闭还是服务端关闭连接，OnClose 都会被回调。但是必须还得自己手动调用一下c.Cloese()才可以？

**Comment by panjf2000** [comment]
> 但是必须还得自己手动调用一下c.Cloese()才可以？

不需要，服务端如果要主动关闭连接才需要调用 c.Close()

**Comment by concn** [comment]
windows不需要，实测linux是需要的，需要在OnClosed里调用 c.Close()；否则打开的文件数一直在增长，即socket没有关闭，1024个三天就占满了，导致服务不再接受新消息，实际上我只有70个终端。自从在OnClosed里手动调用c.Close()方法后，打开的fd稳定在130个左右，解决问题。

**Comment by concn** [comment]
应该是因为windows是设置deadlinetime，系统自动清理关闭的socket，linux的不明白原理

**Comment by JemmyH** [comment]
> gnet 不会主动去关闭 socket，你要自己调用 c.Close()

还有一种场景：write 异常后，会自己走到`conn.closeConn`：
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/38834787/188309685-f189b256-1aab-47bc-8e68-f44ca9c5d400.png">

**Comment by panjf2000** [comment]
那要看下 OnClose 传过来的 error 是什么。

**Comment by hk520570** [comment]
这个问题已经修复了么？

**Comment by panjf2000** [comment]
> 这个问题修复了么？

目前来看不太像是 gnet 的问题。

**Comment by panjf2000** [comment]
暂时评估这个不是 gnet 的问题，先关闭 issue，如果还有问题可以随时打开。

**Comment by hk520570** [comment]
我看了1.45的源码，当前keepalive不是应用层的是么？是通过修改内核参数来实现的？

**Comment by hk520570** [comment]
> 不知道是使用不当，还是程序的bug，出现这个后，程序出现假死，收不到消息了，但程序并未退出，问题如下： ![image](https://user-images.githubusercontent.com/50606635/182798335-c4a78784-e645-4171-aead-07f54455a223.png) 即出现这几行错误日志后，程序不再接收消息。我查了一下代码，调用如下 1.start后，server_unix.go的171行开始调用 ![image](https://user-images.githubusercontent.com/50606635/182798877-ff40c5d8-dfe9-4c57-937a-a405cb9531d3.png) 2.然后是reactor_default_linux.go的35行调用后，返回第一个错误 ![image](https://user-images.githubusercontent.com/50606635/182799078-966a8fea-06b4-4911-b598-1a3ca04cdcbb.png) 3.调用的是acceptor_unix.go的这个方法， ![image](https://user-images.githubusercontent.com/50606635/182799603-74abea3f-fb08-4f96-a80f-228e5403bc68.png)
> 
> 从以上看出返回的错误是3步的38行，打印出Accept() fails due to error: too many open files这行错误日志 然后走到2是39行打印出main reactor is exiting due to error: accept a new connection error这行日志错误后，程序不再接收消息 linux是默认1024个连接，表面上看是未关闭客户端连接造成的。

使用不当，你没有开启keepalive导致的，开启就行了
