### ISSUE TITLE
How to implement a broadcast server?

### ISSUE THREAD

**Issue by ccnlui** [panjf2000/gnet#395]
gnet version: v2.0.0

My use case is to build a broadcast server. The server will poll or listen from a data source, which is sending a stream of messages. I would like broadcast the messages to all connected clients with the lowest possible latency.

I imagine I can use `c.AsyncWrite()`, but I'm not sure if that's the best way of doing this because it is not running on the event loop. Another way I can think of is to add a custom broadcast event to the event loop, in that case I can just use `c.Write()`, but it doesn't seem like I can add a user defined custom event to the gnet event loop.

How would you implement such a broadcast server?

**Comment by panjf2000** [comment]
`c.AsyncWrite()` is thread-safe, so you can store your connections out of the event-loop and call it when you need it.

**Comment by ccnlui** [comment]
thanks!
