### ISSUE TITLE
Optimal way to listen to multiple ports

### ISSUE THREAD

**Issue by pagran** [panjf2000/gnet#397]
- OS: Ubuntu 20
 - Go version: 1.18
 - gnet version: v2.1.1

Hello, what is the correct way to listen to multiple ports (> 255, tcp)? Is it necessary to call `gnet.Run` with `multicore=false` or what is the correct way?

**Comment by panjf2000** [comment]
Run multiple processes or run multiple `gnet.Run()` in one process.

**Comment by pagran** [comment]
With default settings? Or is it better to change something?

**Comment by panjf2000** [comment]
Up to you, better to run some benchmark tests before you launch it to production.

**Comment by pagran** [comment]
For those who will solve a similar problem - I do not recommend creating a lot of listeners, it creates a lot of threads and it comes out not effective. I recommend redirecting everything to 1 port using iptables/redirect and fwmark
