### ISSUE TITLE
windows编译失败

### ISSUE THREAD

**Issue by icc99** [panjf2000/gnet#40]
**Describe the bug**
编译失败, 显示
C:\Users\Administrator\go\pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:129:4: undefined: sniffError
C:\Users\Administrator\go\pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:159:14: too many arguments in call to serve
	have (Events, []*listener, bool)
	want (Events, []*listener)

**To Reproduce**
执行的examples下的echo-server

**Expected behavior**
编译成功

**Screenshots**

**System Info (please complete the following information):**
 - OS (e.g. Ubuntu 18.04):  win10
 - Go version (e.g. Go 1.13):  go 1.13
 - gnet version (e.g. v1.0.0):  v0.1.3

**Additional context**

**Comment by panjf2000** [comment]
你这 gnet 版本太老了，那时候还不支持 Windows，更新到最新的 master

**Comment by icc99** [comment]
我是用go module的.   go buid 的时候 自动帮我用了 v0.1.3 这个版本. . 我要怎么才能用最新的呢??

**Comment by panjf2000** [comment]
go get github.com/panjf2000/gnet@master
