### ISSUE TITLE
Async gnet.Client.Dial

### ISSUE THREAD

**Issue by pagran** [panjf2000/gnet#400]
**Please fill out the following system information before opening an issue:**
 - OS: Ubuntu 20
 - Go version: 1.18
 - gnet version: v2.1.1

**What is your question about gnet?**
I am implementing a proxy server and it has the following pattern:

1. Accept the connection
2. Parse the request (http for example) to retrieve the address of the remote server
3. Establish a connection to a remote server using gnet.Client.Dial
4. Bidirectionally send traffic client<-> proxy<-> remote server

Step 3 (gnet.NewClient.Dial) causes problems. If the remote server takes a long time to respond or does not work at all, the current OnTraffic is blocked for quite a long time.

Question: Is it possible to establish a connection to a remote server asynchronously?  To get around the problem, I would have to do some rather complrex logic with gorutine running, buffering data (while the connection is being established), etc.

**Comment by panjf2000** [comment]
`gnet` doesn't have an asynchronous client yet, could you make it asynchronous by putting the dialing process into a goroutine?

**Comment by pagran** [comment]
Okay, thank you. I thought there were more elegant ways to do it.
