### ISSUE TITLE
Enroll + AsyncWrite` is not safe

### ISSUE THREAD

**Issue by pagran** [panjf2000/gnet#402]
**Describe the bug**
Combination of `client.Enroll` and `conn.AsyncWrite` is not safe.
The `Enroll` is not synchronous because the `UrgentTrigger` [link](https://github.com/panjf2000/gnet/blob/dev/client.go#L216) does not wait for the `opened=true` [link](https://github.com/panjf2000/gnet/blob/dev/eventloop.go#L98) flag to complete.

Under heavy load, this leads to a bug where `conn.AsyncWrite` does not call the callback and generally just exit - [link](https://github.com/panjf2000/gnet/blob/3c3c519b8c57e750231db3d191e7257b5a3cf51d/connection.go#L215) (in my case it hangs the connection)

**To Reproduce**
1. Fast `Enroll` many client connections (>100)
2. Instantly write async data to connection

**Expected behavior**
I think it would be useful to make `Enroll` synchronous or make a mechanism to wait when the connection is fully open

**System Info (please fill out the following information):**
 - OS: Ubuntu 20
 - Go version: Go 1.18
 - gnet version: v2.1.1

**Additional context**

Dirty fix: https://github.com/pagran/gnet/commit/65543c51ea72e80b686c2f7c446af2fd0b094c9c

**Comment by panjf2000** [comment]
You should wait for `OnOpen`, an example from the test code:

https://github.com/panjf2000/gnet/blob/c296922d171e64bcd0a97b1bf7eeb7adc747dad6/client_test.go#L43-L48

**Comment by pagran** [comment]
Now I see, thank you for detailed answer.
