### ISSUE TITLE
建议开放一些私有方法或变量

### ISSUE THREAD

**Issue by moqsien** [panjf2000/gnet#406]
A、建议以下私有方法提供一下public方案。
1、engine.go中的serve(eventHandler EventHandler, listener *listener, options *Options, protoAddr string) error；
2、listener.go中initListener(network, addr string, options *Options) (l *listener, err error)，

B、listener结构体提供一个获取fd的方法。
func  (ln *listener) GetFd() int {
    return ln.fd
}

主要原因是，有时候想要自定义或者获取listener，以便在框架外部使用。结果都是私有对象，除非自己修改源码或者用unsafe，体验不是很好。

**Comment by panjf2000** [comment]
> A、建议以下私有方法提供一下public方案。
1、engine.go中的serve(eventHandler EventHandler, listener *listener, options *Options, protoAddr string) error；
2、listener.go中initListener(network, addr string, options *Options) (l *listener, err error)，

initListener() 现在是可以通过 options 来加一些初始化配置的，这个配置还不够吗？你的需求是什么？能不能举几个例子？

> B、listener结构体提供一个获取fd的方法。
func (ln *listener) GetFd() int {
return ln.fd
}

你可以使用 gnet 的 [Dup()](https://pkg.go.dev/github.com/panjf2000/gnet/v2#Engine.Dup)
