### ISSUE TITLE
Connection-level codecs

### ISSUE THREAD

**Issue by ligser** [panjf2000/gnet#41]
**Is your feature request related to a problem? Please describe.**
When the gnet works with a protocols that has a connection-level configuration (like the websocket) we have a problem with the Codec abstraction. 
In the websocket protocol we have a connection-level negotiation about the „extensions“ that will be applied to the connection. That means the same websocket server can handle compressed and uncompressed connections.

**Describe the solution you'd like**
Simple but may be hacky way to do that — have the `gnet.Conn` in the `Encode` method. When we accept a connection we can write a negotiated extensions into the conn `ctx` and when we make decoding — we can read it from `conn.Context()`. To be clear the `ICodec` already aware about `gnet.Conn` in the `Decode` method, why not to do that in the `Encode` too?

**Describe alternatives you've considered**
Other way might be to have a multiple codecs in the server object. And when we create the `conn` we should assign one of them manually (store pointer or some synthetic ID of the codec in the `conn` struct) into `OnOpened` method.

**Additional context**
[WebSocket RFC](https://tools.ietf.org/html/rfc6455)
[WebSocket permessage-deflate RFC](https://tools.ietf.org/html/rfc7692)

**Comment by panjf2000** [comment]
@ligser 
> have the gnet.Conn in the Encode method. When we accept a connection we can write a negotiated extensions into the conn ctx and when we make decoding — we can read it from conn.Context(). 

I believe that you are able to write negotiated extensions into the conn ctx in every event-handler which has an argument of `gnet.Conn`, for example, `gnet.React()`, so why do you insist on `codec.Encode()`？

**Comment by ligser** [comment]
Yes, I can handle that without use a custom encoder at all via implementing same flow inside a `EventServer`. 
I only think that can be suitable to have that option into the `ICodec` because it looks like a right place to introduce a transport level framing.

The WebSocket flow looks like:
```
Client        Server
=============== HTTP Part
|----Upgrade--->|  
|<---Upgrade----| Accept connection and answer HTTP 101 Code
=============== WebSocket Part
|<--WS Frames-->| Here WebSocketCodec works
```

So I think a `ICodec` can automatically handle a frames by itself. There is no need to use the `ICodec` when a connection opened because we at HTTP Part now and should answer a not framed response. But as I see that also should be reflected in the WebSocket codec if we have one.

But when I see at the diagram above it looks like WebSocket as a stateful protocol cannot be implemented only on the `Codec` level (we do not know should we use framing or we still at the Upgrade part and should answer with plain HTTP).
Sorry for disturbing feel free to close the issue :)

**Comment by panjf2000** [comment]
> Sorry for disturbing feel free to close the issue :)

Don't be, I think you've made a proposal that is worth discussing about adding `gnet.Conn` as an argument of `codec.Encode()` to make the boundary of a codec more distinct, so I'm going to keep this issue and give a serious consideration to it.

Thanks for your suggestion about it.
