### ISSUE TITLE
Better to support bufio.SplitFunc to split packet automatically

### ISSUE THREAD

**Issue by fwang2002** [panjf2000/gnet#418]
It's better to add another method in EventHandler interface
```go
// data is a single packet data splitted from the recv buffer(it can be a slice from the original buffer)
OnPacket(c Conn, data []byte) (action Action)
```
and add an option when call gnet.Run
```go
func WithSplitFunc(splitFunc bufio.SplitFunc) Option
```
If splitFunc is set, then OnPacket will be called when each single complete packet is received.

SplitFunc is convenient for both splitting packet by length field and splitting packet by delimeters.

**Comment by panjf2000** [comment]
There were [codecs](https://gnet.host/docs/v1.x/doc-for-gnet-v1/#multiple-built-in-codecs-for-tcp-stream) in gnet v1, doing the exact same things you're talking about, however, those codecs are dropped in gnet v2, the reasons why I did that:
> The built-in codecs have been deprecated and removed, to reduce the complexity and keep gnet simple. From a lot of feedback we've received, this feature does not bring convenience and benefits to users, thus, I decided to take it off from gnet. Cutting those codecs off makes the code on top of gnet more holistic and straightforward.

quoted from https://gnet.host/blog/announcing-gnet-v2/

**Comment by fwang2002** [comment]
We can separate packet splitter and codec into two things. Here I just mean packet splitter to get a complete binary buffer of a packet, not the codec to convert binary buffer to something like protobuf defined messages. bufio.SplitFunc is implemented in application layer, and indicates the offset to split a packet. By this, gnet will not care about the format of the packet.
