### ISSUE TITLE
byteslice.Get 内存增长导致程序OOM

### ISSUE THREAD

**Issue by soukengo** [panjf2000/gnet#420]
**Describe the bug**

在阿里云k8s环境部署后，进行压测，向客户端写入数据时，内存持续快速增长，导致程序OOM

**Screenshots**
<img width="988" alt="image" src="https://user-images.githubusercontent.com/13197092/199662761-84984dc2-0dca-47d7-8224-fcca9d7878b6.png">

**System Info (please fill out the following information):**
 - OS : Docker（alpine  3.16.2 ）
 - Go version : go1.19.2
 - gnet version: v2.1.2

**Comment by soukengo** [comment]
会不会是因为我在其它goroutine中，调用Write导致的？

**Comment by panjf2000** [comment]
看起来像是服务端一直写而客户端没有去读，导致数据积压。

**Comment by soukengo** [comment]
客户端是一直在读取，不过施压的客户端机器cpu占用将近100%了，但是换成golang原生的tcp，同样的业务没有出现服务器内存明显增长。我再对比压测一下看看

**Comment by panjf2000** [comment]
是不是 server 端写得太快了，客户端读取速度跟不上，你试试能不能加快一下客户端的读取速度。

**Comment by panjf2000** [comment]
> > 是不是 server 端写得太快了，客户端读取速度跟不上，你试试能不能加快一下客户端的读取速度。
> 
> 有这个可能，我再定位一下 另外 潘少 是不是只要不在OnTraffic当前的goroutine里，就必须调用AsyncWrite而不是Write

是的，只有在 OnTraffic() 的 goroutine 中才能用 Write，否则都应该使用 AsyncWrite，因为 Write 是非线程安全的。

**Comment by lesismal** [comment]
应该加配置项来限制写缓冲、最大读写缓存size的，否则就存在这些问题。
对于读写缓存的buffer，不管是用link list还是ring buffer，可能会存在这种情况：当某次读写使这些buffer size扩张后，后续即使没有这种大buffer的需求，但这个活跃的Conn上面可能一直挂载着这1-N个buffer，直到Close才释放。这对于海量在线的场景，内存开销甚至比标准库方案更大。
低在线的场景poller并不比标准库性能更好，poller的优势就在于节约的协程、内存、gc这些，如果按gnet现在的方式，在实际的项目实战中可能连poller的优势也不存在了。
字节的netpoll我测试时也是占用内存很高，但几次交流下来，似乎他们对它的定位就是在线量不高的 RPC 场景、更偏向于空间换时间来提高响应，而且毕竟自成一套7层体系，也可以理解。
我在自己库里的策略是单个Conn需要缓存的时候才有，用完就释放了，用户可以根据自己实际业务来定制zero copy，而且buffer pool也是可以用户自定义的，极端场景用户可以自己用chan令牌来限流分配进而实现自动平衡。如果用户不限制分配，除了极端场景每个Conn都是大包、缓冲区都拥堵了，也都是非常可控的。

**Comment by panjf2000** [comment]
> 应该加配置项来限制写缓冲、最大读写缓存size的，否则就存在这些问题。 对于读写缓存的buffer，不管是用link list还是ring buffer，可能会存在这种情况：当某次读写使这些buffer size扩张后，后续即使没有这种大buffer的需求，但这个活跃的Conn上面可能一直挂载着这1-N个buffer，直到Close才释放。这对于海量在线的场景，内存开销甚至比标准库方案更大。 低在线的场景poller并不比标准库性能更好，poller的优势就在于节约的协程、内存、gc这些，如果按gnet现在的方式，在实际的项目实战中可能连poller的优势也不存在了。 字节的netpoll我测试时也是占用内存很高，但几次交流下来，似乎他们对它的定位就是在线量不高的 RPC 场景、更偏向于空间换时间来提高响应，而且毕竟自成一套7层体系，也可以理解。 我在自己库里的策略是单个Conn需要缓存的时候才有，用完就释放了，用户可以根据自己实际业务来定制zero copy，而且buffer pool也是可以用户自定义的，极端场景用户可以自己用chan令牌来限流分配进而实现自动平衡。如果用户不限制分配，除了极端场景每个Conn都是大包、缓冲区都拥堵了，也都是非常可控的。

gnet 的 buffer 是弹性伸缩的，在数据被业务层读取之后或者是写入底层 socket buffer 之后就会回收内存，不存在说因为某一个读写数据量大而导致该 conn 上会一直占据扩容之后的内存。

**Comment by lesismal** [comment]
> gnet 的 buffer 是弹性伸缩的，在数据被业务层读取之后或者是写入底层 socket buffer 之后就会回收内存，不存在说因为某一个读写数据量大而导致该 conn 上会一直占据 buffer 扩容之后的内存。

那还好，只要加上size限制就好了，如果业务层不需要这么大的缓冲size，或者说已经缓冲这么大了说明这个Conn不健康了就Close，由7层去重连逻辑来保证业务

**Comment by soukengo** [comment]
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/13197092/200291821-d90df7d7-7776-4573-bb86-2a8ea9146a83.png">
发现内存增长的时候，会遇到这个错误

**Comment by panjf2000** [comment]
这是在连接被关闭的时候尝试把 buffer 中残留的数据写回对端，如果对端已经把连接关闭了则会看到这个日志，应该没有什么相关性。

**Comment by panjf2000** [comment]
这是在连接被关闭的时候尝试把 buffer 中残留的数据写回对端，如果对端已经把连接关闭了则会看到这个日志，应该没有什么相关性。

**Comment by panjf2000** [comment]
> 客户端 建立连接->接收消息->再断开连接->建立连接，反复这样操作，就会遇到这样的情况。另外，客户端断开连接（结束进程）后（甚至物理关机），gnet.Engine.CountConnections()返回的数量只会减少一部分（比如1000个连接还剩700多）。我的业务层给连接设置了超时时间，超时后主动关闭连接，发现即使主动关闭未正常退出的连接（gnet.Engine.CountConnections()=0），通过pprof仍然显示byteslice.(*Pool).Get占用的资源没有回收。还有gnet.Engine.CountConnections()数量可能为负数。 对面是python客户端，我用golang写的客户端还没有复现这个问题。

你描述的这个现象有点奇怪，方便提供下你的代码吗？

**Comment by soukengo** [comment]
内存增长的问题可以通过这个测试代码复现
服务端：https://github.com/soukengo/gnettest/blob/main/cmd/comet/server/main.go
客户端：https://github.com/soukengo/gnettest/blob/main/cmd/comet/client/main.go

复现步骤如下
1. 在一个4c8g的阿里云服务器上部署服务端，带宽100M
2. 同时用多个客户端连接服务器（6000+）
3. 服务端将这些连接加入到一个组里
4. 服务端每秒向这个组里的连接推送2k的数据（这样会把带宽打满）
5. 客户端连接一段时间后，断开重连，反复操作几次
6. 通过pprof查看，即使所有客户端都断开了，而服务端byteslice.(*Pool).Get 分配的内存有部分不会回收

**Comment by panjf2000** [comment]
![pprof_top10](https://user-images.githubusercontent.com/7496278/202884741-3c10ecab-652a-4f54-b3e9-8a135f0ce356.png)
![pprof_inuse_objects](https://user-images.githubusercontent.com/7496278/202884787-33bb1a47-0fc3-4ccf-9591-83e72c21db20.png)

我按照你的程序和步骤跑了一下，没能复现你说的这个问题，通过 pprof 分析更像是你业务层的 socketchannel 对象泄露导致的内存占用，而且我也切换了你代码里的另一个网络库，发现也是一样的，不过我是在 mac 上跑的，但是在 linux 上我估计也是一样的，有时间的话我到 linux 跑一下看看。

**Comment by soukengo** [comment]
我之前在mac上也没有复现，这个是在linux复现的

**Comment by panjf2000** [comment]
![linux-test](https://user-images.githubusercontent.com/7496278/205436802-97d606c2-f2b2-4c06-8371-0f7fa0a36ba9.png)

我在 linux/x86_64 也没有复现

**Comment by soukengo** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/13197092/205837109-d089ced5-03cc-4962-8cf9-4cbf404ca123.png">
具体的操作是施压客户端机器或者服务端机器带宽被打满了之后，kill掉客户端，再次启动客户端，操作两三次之后就会出现。
是不是我的压测场景不太合理。

**Comment by panjf2000** [comment]
> 内存增长的问题可以通过这个测试代码复现 服务端：https://github.com/soukengo/gnettest/blob/main/cmd/comet/server/main.go 客户端：https://github.com/soukengo/gnettest/blob/main/cmd/comet/client/main.go
> 
> 复现步骤如下
> 
> 1. 在一个4c8g的阿里云服务器上部署服务端，带宽100M
> 2. 同时用多个客户端连接服务器（6000+）
> 3. 服务端将这些连接加入到一个组里
> 4. 服务端每秒向这个组里的连接推送2k的数据（这样会把带宽打满）
> 5. 客户端连接一段时间后，断开重连，反复操作几次
> 6. 通过pprof查看，即使所有客户端都断开了，而服务端byteslice.(*Pool).Get 分配的内存有部分不会回收

我就是按照你这里的代码和步骤进行复现的，但是在 macOS 和 Linux 上都没有复现出来。

不过你刚刚说 kill 掉客户端指的是正常 ctrl+C 退出客户端吗？我是这么操作的。还是说你是通过 kill -9 强杀客户端的？

**Comment by soukengo** [comment]
我是直接ctrl+C的

**Comment by qinguoyi** [comment]
> 这个是我本地跑客户端的截图（带宽较少） <img alt="image" width="921" src="https://user-images.githubusercontent.com/13197092/205837109-d089ced5-03cc-4962-8cf9-4cbf404ca123.png"> 这个是在单独在另外一个服务器上跑的客户端（带宽100M） <img alt="image" width="941" src="https://user-images.githubusercontent.com/13197092/205837664-486f022c-cf93-414d-b807-c7add846bf0e.png"> 客户端停止一个小时之后服务端内存也没有降下去 <img alt="image" width="1045" src="https://user-images.githubusercontent.com/13197092/205853067-f40cd80f-c3fb-426f-8495-ede4eb6aeaa6.png">
> 
> 具体的操作是施压客户端机器或者服务端机器带宽被打满了之后，kill掉客户端，再次启动客户端，操作两三次之后就会出现。 是不是我的压测场景不太合理。

tks

**Comment by qinguoyi** [comment]
> > 这个是我本地跑客户端的截图（带宽较少） <img alt="image" width="921" src="https://user-images.githubusercontent.com/13197092/205837109-d089ced5-03cc-4962-8cf9-4cbf404ca123.png"> 这个是在单独在另外一个服务器上跑的客户端（带宽100M） <img alt="image" width="941" src="https://user-images.githubusercontent.com/13197092/205837664-486f022c-cf93-414d-b807-c7add846bf0e.png"> 客户端停止一个小时之后服务端内存也没有降下去 <img alt="image" width="1045" src="https://user-images.githubusercontent.com/13197092/205853067-f40cd80f-c3fb-426f-8495-ede4eb6aeaa6.png">
> > 具体的操作是施压客户端机器或者服务端机器带宽被打满了之后，kill掉客户端，再次启动客户端，操作两三次之后就会出现。 是不是我的压测场景不太合理。
> 
> tks
test
