### ISSUE TITLE
V2.0相对于V1.0的优势是什么？2.0解决了什么问题？另外v2.0的windows支持进度如何了？谢谢解答。

### ISSUE THREAD

**Issue by im-pingo** [panjf2000/gnet#421]
V2.0相对于V1.0的优势是什么？2.0解决了什么问题？另外v2.0的windows支持进度如何了？谢谢解答。

**Comment by panjf2000** [comment]
> V2.0相对于V1.0的优势是什么？2.0解决了什么问题？

https://gnet.host/blog/announcing-gnet-v2/

> 另外v2.0的windows支持进度如何了？谢谢解答。

暂时还没有时间继续推进。
