### ISSUE TITLE
想确定真实写入的数据

### ISSUE THREAD

**Issue by JemmyH** [panjf2000/gnet#425]
> Please read [<u>*How To Ask Questions The Smart Way*</u>](http://www.catb.org/~esr/faqs/smart-questions.html) ( Chinese translation: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)) before you file an issue formally.
>
> Furthermore, please comply with the issue template instead of just filling it out yourself, otherwise your issue may not be accepted or may even be closed outright.

**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04): Darwin(22.1.0)
 - Go version (e.g. Go 1.13):  go1.18.5 darwin/amd64
 - gnet version (e.g. v1.0.0): v2.1.2

**What is your question about gnet?**
- 我的场景是客户端，长连接服务。
- 诉求：能有一个回调函数，将 data、writeError 同时传给这个回调。

发送的时候使用的是 `AsyncWrite`，这个函数调用成功只能说明“放到发送队列成功”，并不是真正的 **系统调用write** 成功。在 QPS 较高的前提下，发送队列一定会有任务堆积，如果此时 socket 出现异常(对端断开连接或其他原因)，那么队列中的这些任务就全部丢了。但是对应用层来说，结果却是调用成功，这对定位问题会造成一定的困扰。
虽然有 `AsyncCallback` (dev 分支似乎已经修改了这个函数签名，加上了 error，但是还没发布新版本)，但是还是不能知道在 write 失败时的具体 data 是什么。对业务来说，顶多打个日志或报警，实际去定位还是不能知道哪个 data 写失败了。
<img width="569" alt="image" src="https://user-images.githubusercontent.com/38834787/203324337-0b4ee106-c095-4070-96c8-57a7f7ec7ddb.png">

另外，在一些 tob 的业务场景，想把真实发送给客户的流量(真正 write 成功)记录下来，似乎只能在 `AsyncCallback` 这里实现。

可能的方案：
`AsyncCallback` 定义成：
```go
type AsyncCallback(c Conn, err error, data []byte) error
```

希望考虑下这个 case，谢谢~

**Comment by panjf2000** [comment]
我理解在设置 AsyncCallback 的时候通过闭包的方式就可以实现吧？

**Comment by JemmyH** [comment]
> 我理解在设置 AsyncCallback 的时候通过闭包的方式就可以实现吧？

谢谢回复。目前就是通过这种方式实现的，似乎就能解决问题(这个 issue 没啥意义，我稍后关掉)。另外请问下 `AsyncCallback` 携带 error 的修改有新版本发布计划吗？

**Comment by panjf2000** [comment]
> > 我理解在设置 AsyncCallback 的时候通过闭包的方式就可以实现吧？
> 
> 谢谢回复。目前就是通过这种方式实现的，似乎就能解决问题(这个 issue 没啥意义，我稍后关掉)。另外请问下 `AsyncCallback` 携带 error 的修改有新版本发布计划吗？

应该这周末我会发一个新的 release
