### ISSUE TITLE
[Question]:  同一个包中的变量无法引用

### ISSUE THREAD

**Issue by youjile** [panjf2000/gnet#429]
### Questions with details

潘少，我复制官方版本2的示例到goland中，启动就报错。我查了下源码是在gnet.go文件中引用了engine.go文件中定义的engine结构体，但是engine.go文件中的engine结构体是非导出的，goland编辑器一直无法识别。

gnet版本v2
操作系统windows

错误日志：

# github.com/panjf2000/gnet/v2
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:49:7: undefined: engine
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:54:14: invalid operation: s.eng == nil (operator == not defined on untyped nil)
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:59:19: el.loadConn undefined (type *eventloop has no field or method loadConn)
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:69:14: invalid operation: s.eng == nil (operator == not defined on untyped nil)
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:84:14: invalid operation: s.eng == nil (operator == not defined on untyped nil)
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:421:43: cannot use options (variable of type *Options) as type bool in argument to initListener
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:426:9: undefined: run
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:440:11: undefined: engine
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\gnet.go:442:13: undefined: engine
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\load_balancer.go:71:5: el.idx undefined (type *eventloop has no field or method idx)
E:\work\go\pkg\mod\github.com\panjf2000\gnet\v2@v2.2.0\load_balancer.go:71:5: too many errors

**Comment by panjf2000** [comment]
v2 暂时不支持 Windows

**Comment by panjf2000** [comment]
#339
