### ISSUE TITLE
Support connection-level TTL timeout

### ISSUE THREAD

**Issue by 6congyao** [panjf2000/gnet#43]
作为长连接服务端，gnet能否在connection级别设置timeout?即在指定时间内没有读到报文就断开连接

**Comment by panjf2000** [comment]
先确认一下，这个功能目前来说在业务端也是可以实现的对吧？

**Comment by 6congyao** [comment]
可以的，用一个带ttl的缓存来monitor所有的长连接，一旦到期主动关闭它们，有数据到来就更新ttl

**Comment by panjf2000** [comment]
嗯，我一开始也是类似的思路，如果要把这个功能集成进 network framework 可能会对框架的性能有所影响（要一直追踪所有 connections TTL），我再考虑一下这个功能有没有比较优雅的实现。

**Comment by 6congyao** [comment]
👌
