### ISSUE TITLE
[Question]: AsyncWrite how to guarantee write order?

### ISSUE THREAD

**Issue by pagran** [panjf2000/gnet#431]
### Questions with details

Based on fact that AsyncWrite only [add](https://github.com/panjf2000/gnet/blob/dev/connection.go#L446) a write call to the queue and if >1 poller is running then actual write order can be random. 

How to ensure that a serial call `AsyncWrite(a)->AsyncWrite(b)->AsyncWrite(c)` writes to socket `a->b->c` ?

**Comment by panjf2000** [comment]
You have to deal with the sequence yourself, if you do nothing about it, then the sequence of messages being sent back to the peer is the sequence of `AsyncWrite()` being called.

**Comment by pagran** [comment]
Strange, under heavy load I have seen more than once that traffic came to client in the wrong order (socks proxy broke tls). 
But, ok, got it. No such mechanism and I myself need to manage the sequence, thanks for the answer.
