### ISSUE TITLE
[Bug]: Compilation error on bsd 32 bit (kqueue)

### ISSUE THREAD

**Issue by pnx** [panjf2000/gnet#432]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the current list of Github issues but didn't find any duplicate issues that have been solved.
- [X] I've searched the internet with this issue, but haven't found anything helpful.

### What happened?

Compilation fails when building kqueue on 32 bit. Only tested while cross-compiling for freebsd-arm.

Look like `unix.Kevent_t.Ident` is `uint32` on 32 bit and therefore the cast fails.

### Major version of gnet

v2

### Specific version of gnet

2.2.2

### Operating system

BSD

### Relevant log output

```shell
go version: go1.17 linux/amd64

# github.com/panjf2000/gnet/v2/internal/netpoll
internal/netpoll/kqueue_default_poller.go:197:4: cannot use uint64(pa.FD) (type uint64) as type uint32 in field value
internal/netpoll/kqueue_default_poller.go:198:4: cannot use uint64(pa.FD) (type uint64) as type uint32 in field value
internal/netpoll/kqueue_default_poller.go:206:4: cannot use uint64(pa.FD) (type uint64) as type uint32 in field value
internal/netpoll/kqueue_default_poller.go:214:4: cannot use uint64(pa.FD) (type uint64) as type uint32 in field value
internal/netpoll/kqueue_default_poller.go:222:4: cannot use uint64(pa.FD) (type uint64) as type uint32 in field value
internal/netpoll/kqueue_default_poller.go:230:4: cannot use uint64(pa.FD) (type uint64) as type uint32 in field value
```

### How to Reproduce

1. run `GOOS=freebsd GOARCH=arm go1.17 test -c`

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
Thanks for the bug report.
