### ISSUE TITLE
用taskset把程序绑定到多核心以后，性能不如taskset绑定到单核心

### ISSUE THREAD

**Issue by huangmingyou** [panjf2000/gnet#433]
### Questions with details

本来的计划是在机器上隔离出单独的cpu给应用使用。  但是用taskset绑定多核心以后，性能反而不如在单核心上面好。multicore 这个参数有什么设置技巧吗?

**Comment by panjf2000** [comment]
你的业务场景是不是单核心就足够了，设置多核心反而因为上下文切换而降低了性能？

**Comment by huangmingyou** [comment]
单核心不太够用，还是希望能多核心运行。同样的配置，如果不使用 cpuset或者taskset做cpu绑定，性能会比作了cpu绑定好。是否是cpu绑定会影响到gnet的性能。

**Comment by huangmingyou** [comment]
通过cgroup方式绑定到了两颗cpu , 对，把multicore=false,性能更好。

**Comment by panjf2000** [comment]
你能提供一下复现步骤吗？最好是有 demo 代码可以测试。
