### ISSUE TITLE
[Feature]: Improve performance by using io_uring api

### ISSUE THREAD

**Issue by misterquestions** [panjf2000/gnet#438]
### Description of new feature

Seems like this API performs better than the standard epoll, some interesting resources can be found here.

https://betterprogramming.pub/gain-the-new-fastest-go-tcp-framework-40ec111d40e6

Also something interesting is that windows native support could be added by using IoRing 

Another resource for it: https://windows-internals.com/one-year-to-i-o-ring-what-changed/

### Scenarios for new feature

High-concurrent networked servers, such as game servers or any other networked application.

### Breaking changes or not?

Yes

### Code snippets (optional)

```go
This will happen in the background so nothing of the current API (v2) must be changed at all.
```

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
io_uring is in the [roadmap of gnet](https://github.com/panjf2000/gnet#-features).

**Comment by panjf2000** [comment]
Duplicate #327
