### ISSUE TITLE
[Bug]: 接收数据时下标越界

### ISSUE THREAD

**Issue by concn** [panjf2000/gnet#439]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the current list of Github issues but didn't find any duplicate issues that have been solved.
- [X] I've searched the internet with this issue, but haven't found anything helpful.

### What happened?

![1676517386623](https://user-images.githubusercontent.com/50606635/219260065-07d55305-d93c-409e-b2aa-230cbeee5e12.jpg)

### Major version of gnet

v1

### Specific version of gnet

v1.6.6

### Operating system

Windows

### Relevant log output

```shell
程序接收时，出现接收的数据下标越界的情况，没有找到哪一行，最大设置为1408的；但是接收的数据是1601字节。不知道这个需要怎么处理，谢谢！
```

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Does this issue reproduce with the latest release?

It gets fixed in the latest release

**Comment by panjf2000** [comment]
麻烦提供一下复现问题的代码。

**Comment by concn** [comment]
func StartManageServer(Conf *restgo.Config) {
	Cfg = Conf
	var port string
	var multicore, reusePort bool

	// Example command: go run echo.go --port 9000 --multicore=true --reuseport=true
	flag.StringVar(&port, "port", Conf.App["tcpManageServerPort"], "--port 9011")
	flag.BoolVar(&multicore, "multicore", true, "--multicore true")
	flag.BoolVar(&reusePort, "reuseport", false, "--reuseport true")
	flag.Parse()
	echo := new(echoServer)
	err := gnet.Serve(echo, fmt.Sprintf("tcp://:%s", port), gnet.WithMulticore(multicore), gnet.WithReusePort(reusePort))
	if err != nil {
		panic(err)
	}
}
上面是启动Server代码。程序大概2－3天停止一次。
![20230220161058](https://user-images.githubusercontent.com/50606635/220050936-42e6d949-0c3c-47c3-bce7-fe85d0846249.jpg)

每次停止的话，这个下标越界这个出现。说是capacity的问题，只有1408，但是启动的时候没有设置过限制呀，应该是默认65535这个64K默认值，不知道如何用户自己设置，是在哪里设置这个capacity呢？

**Comment by panjf2000** [comment]
你这是业务代码出问题了，是因为你自己的数组读越界了吧。

**Comment by panjf2000** [comment]
> ```go
> func StartManageServer(Conf *restgo.Config) {
> 	Cfg = Conf
> 	var port string
> 	var multicore, reusePort bool
> 
> 	// Example command: go run echo.go --port 9000 --multicore=true --reuseport=true
> 	flag.StringVar(&port, "port", Conf.App["tcpManageServerPort"], "--port 9011")
> 	flag.BoolVar(&multicore, "multicore", true, "--multicore true")
> 	flag.BoolVar(&reusePort, "reuseport", false, "--reuseport true")
> 	flag.Parse()
> 	echo := new(echoServer)
> 	err := gnet.Serve(echo, fmt.Sprintf("tcp://:%s", port), gnet.WithMulticore(multicore), gnet.WithReusePort(reusePort))
> 	if err != nil {
> 		panic(err)
> 	}
> }
> ```
> 
> 上面是启动Server代码。程序大概2－3天停止一次。 ![20230220161058](https://user-images.githubusercontent.com/50606635/220050936-42e6d949-0c3c-47c3-bce7-fe85d0846249.jpg)
> 
> 每次停止的话，这个下标越界这个出现。说是capacity的问题，只有1408，但是启动的时候没有设置过限制呀，应该是默认65535这个64K默认值，不知道如何用户自己设置，是在哪里设置这个capacity呢？

你给我这一点启动的代码没用啊，主要得排查一下你自己的业务代码，是不是解包的逻辑有问题。
