### ISSUE TITLE
[Question]: 请问潘少是否知道有比较好点的七层的golangcodec库，因为gnet貌似并没有像netty一样提供丰富的七层handler

### ISSUE THREAD

**Issue by xj524598** [panjf2000/gnet#441]
### Questions with details

[Question]: 请问潘少是否知道有比较好点的七层的golangcodec库，因为gnet貌似并没有像netty一样提供丰富的七层handler

**Comment by lesismal** [comment]
:eyes::yum:

**Comment by panjf2000** [comment]
https://awesome-go.com/serialization/
