### ISSUE TITLE
[Feature]: 为什么v2版本没有内置codec了, v1的codec适用v2吗

### ISSUE THREAD

**Issue by LeftH0ok** [panjf2000/gnet#448]
### Description of new feature

[Feature]: 为什么v2版本没有内置codec了, v1的codec适用v2吗

### Scenarios for new feature

[Feature]: 为什么v2版本没有内置codec了, v1的codec适用v2吗

### Breaking changes or not?

No

### Code snippets (optional)

```go
[Feature]: 为什么v2版本没有内置codec了, v1的codec适用v2吗
```

### Alternatives for new feature

[Feature]: 为什么v2版本没有内置codec了, v1的codec适用v2吗

### Additional context (optional)

[Feature]: 为什么v2版本没有内置codec了, v1的codec适用v2吗

**Comment by panjf2000** [comment]
> 为什么v2版本没有内置codec了?

请看 v2 版本的发布[博客](https://gnet.host/blog/announcing-gnet-v2/#features)

> v1的codec适用v2吗

v2 已经不支持设置 codec 了，所以你无法将 v1 的 codec 设置到 v2 版本，但是编解码器的逻辑是通用的，你可以把你需要的 codec 写在 v2 的 `OnTraffic` 事件函数里。
