### ISSUE TITLE
2.0什么时候可以支持Windows

### ISSUE THREAD

**Issue by 1185497683** [panjf2000/gnet#449]
### Questions with details

我想问的是GNet 2.0什么时候支持Windows，我觉得这是非常必要的。

**Comment by panjf2000** [comment]
Duplicate #339

**Comment by panjf2000** [comment]
近期会开始开发 Windows 支持

**Comment by zhuqiyun** [comment]
期待

**Comment by ayamzh** [comment]
支持！！！

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
support! ! !
