### ISSUE TITLE
[Question]: logging.Debugf要打印出来只能设置环境变量吗? 

### ISSUE THREAD

**Issue by maxbad** [panjf2000/gnet#455]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

在 gnet.Run 的 Option 增加了 gnet.WithLogLevel(logging.DebugLevel) ,gnet.WithLogPath("aaa.log")  也打印不出来debug日志,

logging.LogLevel() 获取到的还是 info

**Comment by maxbad** [comment]
还有就是 logging.Errorf 不打印堆栈信息要怎么设置呢?

**Comment by panjf2000** [comment]
> 在 gnet.Run 的 Option 增加了 gnet.WithLogLevel(logging.DebugLevel) ,gnet.WithLogPath("aaa.log") 也打印不出来debug日志

你怎么加的？这两个选项是没问题的，设置 WithLogLevel 之后，gnet 内部如果有优先级等于或者高于你设置的 level 的日志就肯定会打印到你指定的文件里。

用这个例子：
```go
package main

import (
	"fmt"
	"net"
	"os"
	"time"

	"github.com/panjf2000/gnet/v2"
	"github.com/panjf2000/gnet/v2/pkg/logging"
)

type testWakeConnServer struct {
	*gnet.BuiltinEventEngine
	network string
	addr    string
	conn    chan gnet.Conn
	c       gnet.Conn
	wake    bool
}

func (t *testWakeConnServer) OnOpen(c gnet.Conn) (out []byte, action gnet.Action) {
	t.conn <- c
	return
}

func (t *testWakeConnServer) OnClose(c gnet.Conn, err error) (action gnet.Action) {
	action = gnet.Shutdown
	return
}

func (t *testWakeConnServer) OnTraffic(c gnet.Conn) (action gnet.Action) {
	_, _ = c.Write([]byte("Waking up."))
	action = -1
	return
}

func (t *testWakeConnServer) OnTick() (delay time.Duration, action gnet.Action) {
	if !t.wake {
		t.wake = true
		delay = time.Millisecond * 100
		go func() {
			conn, _ := net.Dial(t.network, t.addr)
			defer conn.Close()
			r := make([]byte, 10)
			conn.Read(r)
		}()
		return
	}
	t.c = <-t.conn
	_ = t.c.Wake(func(c gnet.Conn, err error) error {
		logging.Debugf("conn=%s done wake: %v", c.RemoteAddr().String(), err)
		return nil
	})
	delay = time.Millisecond * 100
	return
}

func main() {
	svr := &testWakeConnServer{network: "tcp", addr: ":9000", conn: make(chan gnet.Conn, 1)}
	err := gnet.Run(svr, "tcp://:9000",
		gnet.WithTicker(true),
		gnet.WithLogLevel(logging.DebugLevel),
		gnet.WithLogPath("aaa.log"))
	if err != nil {
		panic(err)
	}
	b, _ := os.ReadFile("aaa.log")
	fmt.Println(string(b))
}
```

打印：
```
2023-04-16T11:17:13.407975+08:00	DEBUG	v2@v2.2.6/reactor_default_bsd.go:73	event-loop(0) is exiting in terms of the demand from user, server is going to be shutdown
2023-04-16T11:17:13.40895+08:00	DEBUG	v2@v2.2.6/reactor_default_bsd.go:40	main reactor is exiting in terms of the demand from user, server is going to be shutdown
2023-04-16T11:17:13.409053+08:00	DEBUG	v2@v2.2.6/eventloop.go:273	stopping ticker in event-loop(-1) from Engine, error:context canceled
2023-04-16T11:17:41.46316+08:00	DEBUG	v2@v2.2.6/reactor_default_bsd.go:73	event-loop(0) is exiting in terms of the demand from user, server is going to be shutdown
2023-04-16T11:17:41.463764+08:00	DEBUG	v2@v2.2.6/reactor_default_bsd.go:40	main reactor is exiting in terms of the demand from user, server is going to be shutdown
```

> logging.LogLevel() 获取到的还是 info

通过 options 设置的 logger 和默认的 logger 不是一回事，前者是 gnet 内部用的 logger，后者是全局的默认的 logger，只能通过环境变量设置：

https://github.com/panjf2000/gnet/blob/2e95df16bad4326365e5773bcbcafaa44dcabc65/pkg/logging/logger.go#L90-L97

> 还有就是 logging.Errorf 不打印堆栈信息要怎么设置呢?

你可以通过设置自定义的 logger 实现，参考[文档](https://pkg.go.dev/github.com/panjf2000/gnet/v2#WithLogger)。文档里说得很清楚了，gnet 用的 logger 是 [zap](https://github.com/uber-go/zap)，而 zap 是支持控制打印堆栈的，有两种方式：
1. 通过设置 [zap.Config.DisableStacktrace](https://github.com/uber-go/zap/blob/v1.24.0/config.go#L69-L72)
2. 通过设置 [zap.AddStacktrace](https://github.com/uber-go/zap/blob/v1.24.0/options.go#L116)

这些东西明明都在文档里有写明的，完全可以通过查阅文档自己解决，下次有问题先自己仔细看一下文档，以及多用 google，而不是一遇到问题就迫不及待地开一个 issue，开 issue 的前置条件要求每个人仔细看相关的文档以及先在互联网上搜索相关信息之后再进行，而非只是形式化地把 checkbox 点一下就算了。
