### ISSUE TITLE
[Question]: Does gnet support the tls?

### ISSUE THREAD

**Issue by AngelBoby** [panjf2000/gnet#457]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

Implement the TLS protocol handshake yourself ?

**Comment by kolinfluence** [comment]
pls support tls soonest possible. thx

**Comment by panjf2000** [comment]
#16 #435

**Comment by ouvaa** [comment]
@panjf2000 can you pls make this tls possible?

i think there is one bug with the connection, 
https://github.com/0-haha/gnet_tls_examples/issues/2

can you help incorporate into gnet asap? like by mid of april? this shld be top priority.
