### ISSUE TITLE
[Question]: Buffer的使用是否可以优化 

### ISSUE THREAD

**Issue by xsean2020** [panjf2000/gnet#458]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

在使用的buff 的时候，看到好多都是 c.buffer = c.buffer[m:]这种重头部截取的方式，这个回导致内存重新分配， 为啥不直接用copy 移动一下，直接压缩buff ,   n =  copy(c.buffer, c.buffer[m:]),  c.buffer = c.buffer[:n]，这样可以有效的避免重复分配内存?  

### Code snippets (optional)

```go
func (c *conn) Next(n int) (buf []byte, err error) {
	inBufferLen := c.inboundBuffer.Buffered()
	if totalLen := inBufferLen + len(c.buffer); n > totalLen {
		return nil, io.ErrShortBuffer
	} else if n <= 0 {
		n = totalLen
	}
	if c.inboundBuffer.IsEmpty() {
		buf = c.buffer[:n]
		c.buffer = c.buffer[n:]
		return
	}
	head, tail := c.inboundBuffer.Peek(n)
	defer c.inboundBuffer.Discard(n) //nolint:errcheck
	if len(head) >= n {
		return head[:n], err
	}
	c.loop.cache.Reset()
	c.loop.cache.Write(head)
	c.loop.cache.Write(tail)
	if inBufferLen >= n {
		return c.loop.cache.Bytes(), err
	}

	remaining := n - inBufferLen
	c.loop.cache.Write(c.buffer[:remaining])
	c.buffer = c.buffer[remaining:]
	return c.loop.cache.Bytes(), err
}
```

**Comment by panjf2000** [comment]
`c.buffer` 实际上是 `eventloop.buffer` 的切片，每次只是做 re-slice 而不分配新内存，使用 copy 是多余的。
