### ISSUE TITLE
[Question]: gnetv2 client的问题

### ISSUE THREAD

**Issue by liaogang** [panjf2000/gnet#459]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

	var cli, _ = gnet.NewClient(
		slf,
		gnet.WithLogLevel(logging.ErrorLevel),
		//gnet.WithCodec(codec),
		gnet.WithReadBufferCap(8*1024),
		//gnet.WithLockOSThread(true),
		//gnet.WithTCPNoDelay(TCPNoDelay),
		gnet.WithTCPKeepAlive(time.Minute),
		gnet.WithSocketRecvBuffer(8*1024),
		gnet.WithSocketSendBuffer(8*1024),
		//gnet.WithTicker(true),
	)
	
	slf.cli = cli
	var conn, err = slf.cli.Enroll(rawConn)
	if err != nil {
		return nil, fmt.Errorf("gnet cli enroll, %w", err)
	}

var err = slf.cli.Start()

一个rawconn的流程是上面这样，如果我有二个连接rawconn

是用如下的流程吗
var cli, _ = gnet.NewClient
var err = slf.cli.Start()

var conn, err = slf.cli.Enroll(rawConn1)
var conn, err = slf.cli.Enroll(rawConn2)
还是需要二个gnet的client

**Comment by panjf2000** [comment]
不需要一个新的 Client，Client 和 Conn 是一对多的关系，一个 Client 管理多个 Conn，所以直接 `cli.Dial()` 就行了。
