### ISSUE TITLE
[Feature]: v2 版本能否支持下 服务热重启？？ 复用之前的 fd 文件描述符

### ISSUE THREAD

**Issue by caohao-go** [panjf2000/gnet#462]
### Description of new feature

v2 版本能否支持下优雅重启，支持下暴露 fd 和 SetFD 功能，复用之前的 listener fd 句柄。

### Scenarios for new feature

v2 版本能否支持下优雅重启，支持下暴露 fd 和 SetFD 功能，复用之前的 listener fd 句柄。

### Breaking changes or not?

Yes

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
listener 的 fd 你可以通过 [API](https://pkg.go.dev/github.com/panjf2000/gnet/v2#Engine.Dup) 来 dup 一个，至于你说的 SetFD 具体是要做什么？

**Comment by caohao-go** [comment]
没事，这个问题已经解决了， 出现了一个问题，在 http 请求里面， c.Next(-1) 并没有拉到整个请求信息，而是只读取了 header 信息， body 信息没有读取，这种情况应该怎么处理？
func (hs *httpServer) OnTraffic(c gnet.Conn) gnet.Action {
	hc := c.Context().(*httpCodec)
	buf, _ := c.Next(-1)
}
