### ISSUE TITLE
[Question]: About func (el *eventloop) read(c *conn)

### ISSUE THREAD

**Issue by EddieChan1993** [panjf2000/gnet#473]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

Why do we still need to write the buffer into inboundBuffer after the data has been processed in the OnTraffic function?

### Code snippets (optional)

```go
c.buffer = el.buffer[:n]
	action := el.eventHandler.OnTraffic(c)
....    
	_, _ = c.inboundBuffer.Write(c.buffer)
```

**Comment by panjf2000** [comment]
If you've already consumed all data, then `c.buffer` will be empty.

**Comment by EddieChan1993** [comment]
> If you've already consumed all data, then `c.buffer` will be empty.

Thanks for your reply.
