### ISSUE TITLE
[Question]: React里回写到buffer或粘包？

### ISSUE THREAD

**Issue by concn** [panjf2000/gnet#475]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

![188ee15854022383ee9f8e804975834](https://github.com/panjf2000/gnet/assets/50606635/9073c691-a290-41f7-8bd2-381a31b1f56f)
因为不知道为什么我这个包分了二个，在React里读出来后第一次长度不够，需要回写到Buffer，等长度够了再一次性读出，不知道需要怎么做？以下是我React的代码，如果长度不够直接Return了，但是下次就没有之前的了，请问不知道需要用什么方法可以实现呢？
![88b1dec8c82d742deb551f65ecc74a4](https://github.com/panjf2000/gnet/assets/50606635/63eb66a9-1f3e-41fc-b394-7490df18e7f6)

**Comment by panjf2000** [comment]
TCP 是流协议，业务的数据被分包是正常的，这种情况有两种方法处理：
1. 实现 [ICodec](https://pkg.go.dev/github.com/panjf2000/gnet#ICodec) 进行解包，通过使用 `c.ReadN` 方法，如果数据残缺则不调用 `c.ShiftN` 让数据暂时存在内部 buffer 中，等到剩余的数据到来时再解包；
2. 你自己持有一个 buffer，每次都把数据写入你的 buffer 之后再处理，有完整包就执行业务逻辑，否则就跳过等剩余的数据。

**Comment by concn** [comment]
谢谢潘少，按如上方法已解决！
