### ISSUE TITLE
[Bug]: connMap cause fatal error: concurrent map writes

### ISSUE THREAD

**Issue by whiliang** [panjf2000/gnet#479]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

启动一个tcp server，当客户端频繁断连时，conn_map.go connMap由于fatal error:  concurrent map writes导致程序崩溃

### Major version of gnet

v2

### Specific version of gnet

v2.3.0-rc.6

### Operating system

Linux

### Relevant log output

```shell
fatal error: concurrent map writes

goroutine 335 [running]:
github.com/panjf2000/gnet/v2.(*connMatrix).delConn(0xc002768260, 0xc004752000)
        /data/workspace-iot/iot.svc/vendor/github.com/panjf2000/gnet/v2/conn_map.go:61 +0x49
github.com/panjf2000/gnet/v2.(*eventloop).close(0xc002768200, 0xc004752000, {0x35ef6a0, 0xc003e74440})
        /data/workspace-iot/iot.svc/vendor/github.com/panjf2000/gnet/v2/eventloop_unix.go:207 +0xacc
github.com/panjf2000/gnet/v2.(*eventloop).read(0xc002768200, 0xc004752000)
        /data/workspace-iot/iot.svc/vendor/github.com/panjf2000/gnet/v2/eventloop_unix.go:108 +0x1b6
github.com/panjf2000/gnet/v2.(*eventloop).run.func1(0x84, 0x1)
        /data/workspace-iot/iot.svc/vendor/github.com/panjf2000/gnet/v2/reactor_default_linux.go:116 +0x105
github.com/panjf2000/gnet/v2/internal/netpoll.(*Poller).Polling(0xc00275a320, 0xc002a5de58)
        /data/workspace-iot/iot.svc/vendor/github.com/panjf2000/gnet/v2/internal/netpoll/epoll_default_poller.go:138 +0x38d
github.com/panjf2000/gnet/v2.(*eventloop).run(0xc002768200)
        /data/workspace-iot/iot.svc/vendor/github.com/panjf2000/gnet/v2/reactor_default_linux.go:97 +0x106
golang.org/x/sync/errgroup.(*Group).Go.func1()
```

### How to Reproduce

1. 利用gnet启动一个Tcp server, eg  127.0.0.1:19000
2. 测试代码如下：
```golang
package main

import (
	"fmt"
	"net"
)

func main() {
	for i := 0; i < 10000; i++ {
		fmt.Println(i)
		err := connectAndDisconnect()
		if err != nil {
			fmt.Println("Error:", err)
		}
	}
}

func connectAndDisconnect() error {
	conn, err := net.Dial("tcp", "127.0.0.1:19000")
	if err != nil {
		return err
	}
	defer conn.Close()
	return nil
}

```

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
1. v2.2.x 的版本会有这个问题吗？
2. 服务端加 -race  编译之后再跑一下，看看具体是哪些并发写导致的。

**Comment by panjf2000** [comment]
服务端的代码也给一下

**Comment by panjf2000** [comment]
我用以下的代码在 Linux 和 macOS 上都没能复现你提的这个现象：

客户端代码：
```go
package main

import (
	"log"
	"net"
)

func main() {
	for i := 0; i < 10000; i++ {
		log.Println("conn:", i+1)
		err := connectAndDisconnect()
		if err != nil {
			log.Fatalln("Error:", err)
		}
	}
}

func connectAndDisconnect() error {
	conn, err := net.Dial("tcp", "127.0.0.1:19000")
	if err != nil {
		return err
	}
	return conn.Close()
}
```

服务端代码：[TCP echo example](https://github.com/gnet-io/gnet-examples/blob/v2/echo_tcp/echo.go)

**所以请提供你当时测试时的服务端环境，包括但不限于：完整的服务端代码、Linux 内核版本以及Go 版本**。

**Comment by panjf2000** [comment]
可能有关联的 issue：#463

**Comment by whiliang** [comment]
抱歉，服务端代码掺杂了太多业务的东西，不好拆，用提供的代码加了个我们这边的逻辑可以复现：
```golang
package main

import (
	"flag"
	"fmt"
	"github.com/panjf2000/gnet/v2"
	"log"
)

type echoServer struct {
	gnet.BuiltinEventEngine

	eng       gnet.Engine
	addr      string
	multicore bool
}

func (es *echoServer) OnBoot(eng gnet.Engine) gnet.Action {
	es.eng = eng
	log.Printf("echo server with multi-core=%t is listening on %s\n", es.multicore, es.addr)
	return gnet.None
}

func (es *echoServer) OnTraffic(c gnet.Conn) gnet.Action {
	buf, _ := c.Next(-1)
	c.Write(buf)
	return gnet.None
}

func (es *echoServer) OnOpen(c gnet.Conn) (out []byte, action gnet.Action) {
	if c == nil || c.RemoteAddr() == nil || c.LocalAddr() == nil {
		return
	}
	go func() {
               defer func() {
			if err := recover(); err != nil {
				log.Printf("panic: %+v", err)
			}
		}()
		c := c
		if c == nil || c.RemoteAddr() == nil || c.LocalAddr() == nil {
			return
		}
		//log.Printf("[tcpServer] OnClose remoteAddr:%s localAddr:%s", c.RemoteAddr().String(), c.LocalAddr().String())
		c.Write([]byte("hello\r\n"))
	}()
	return
}

func (es *echoServer) OnClose(c gnet.Conn, err error) (action gnet.Action) {
	if c == nil || c.RemoteAddr() == nil || c.LocalAddr() == nil {
		return
	}
	//log.Printf("[tcpServer] OnClose remoteAddr:%s localAddr:%s", c.RemoteAddr().String(), c.LocalAddr().String())
	//
	//log.Printf("[tcpServer] OnClose remoteAddr:%s localAddr:%s", c.RemoteAddr().String(), c.LocalAddr().String())

	return
}

func main() {
	var port int
	var multicore bool

	// Example command: go run echo.go --port 9000 --multicore=true
	flag.IntVar(&port, "port", 19000, "--port 19000")
	//flag.BoolVar(&multicore, "multicore", false, "--multicore true")
	flag.Parse()
	echo := &echoServer{addr: fmt.Sprintf("tcp://:%d", port), multicore: multicore}
	log.Fatal(gnet.Run(echo, echo.addr, gnet.WithMulticore(multicore)))
}

```

**操作系统**：ubuntu22.04  （Linux version 5.19.0-45-generic (buildd@lcy02-amd64-117) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20
）
**Go版本**：go version go1.19.7 linux/amd64
**gnet版本**：github.com/panjf2000/gnet/v2 v2.2.9

**Comment by whiliang** [comment]
错误信息：
fatal error: concurrent map writes

goroutine 794 [running]:
github.com/panjf2000/gnet/v2.(*eventloop).closeConn(0xc0001521b0, 0xc0002627e0, {0x7151e0, 0xc00031ab20})
        /home/whiliang/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.2.9/eventloop.go:224 +0xab0
github.com/panjf2000/gnet/v2.(*conn).write(0xc0002627e0, {0xc0000247c7, 0x7, 0x7})
        /home/whiliang/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.2.9/connection.go:148 +0x276
github.com/panjf2000/gnet/v2.(*conn).Write(0xc0002627e0, {0xc0000247c7, 0x7, 0x7})
        /home/whiliang/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.2.9/connection.go:366 +0x118

涉及代码：
eventloop.go 
func (el *eventloop) closeConn(c *conn, err error) (rerr error)

delete(el.connections, c.fd)
	el.addConn(-1)
	if el.eventHandler.OnClose(c, err) == Shutdown {
		rerr = gerrors.ErrEngineShutdown
	}
	c.releaseTCP()

**Comment by panjf2000** [comment]
看了代码我大概知道问题所在了，主要问题在于 `OnOpen` 里的 `go func()` 里，[gnet.Conn](https://pkg.go.dev/github.com/panjf2000/gnet/v2@v2.3.0-rc.6#Conn) 不是所有方法都是线程安全的，基本上就只有以 Async 开头的那些方法以及 `gnet.Socket` 接口里的方法是线程安全的，所以你只要把 `OnOpen` 里的 `go func()` 去掉就行了，直接执行那些逻辑即可。

**Comment by panjf2000** [comment]
问题已经定位到，出现这种现象是因为使用不当而非框架本身的 bug，issue 先关闭了，有问题再回复。

**Comment by whiliang** [comment]
ok,多谢
