### ISSUE TITLE
win system go module 

### ISSUE THREAD

**Issue by TOBEMINE** [panjf2000/gnet#48]
# github.com/panjf2000/gnet
D:\GoWorks\pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:129:4: undefined: sniffError
D:\GoWorks\pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:159:14: too many arguments in call to serve
	have (Events, []*listener, bool)
	want (Events, []*listener)

**Comment by panjf2000** [comment]
You should get the latest version of gnet: `go get -u github.com/panjf2000/gnet`

**Comment by TOBEMINE** [comment]
D:\GoWorks>go get -u github.com/panjf2000/gnet
go: finding github.com/smartystreets-prototypes/go-disruptor latest
go: finding golang.org/x/sys latest
# github.com/panjf2000/gnet
pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:129:4: undefined: sniffError
pkg\mod\github.com\panjf2000\gnet@v0.1.3\gnet.go:159:14: too many arguments in call to serve
        have (Events, []*listener, bool)
        want (Events, []*listener)

D:\GoWorks>

**Comment by panjf2000** [comment]
That is odd, try: go get -u

**Comment by TOBEMINE** [comment]
I try it ,by now,the same problem

**Comment by panjf2000** [comment]
What about `go get -u github.com/panjf2000/gnet@v1.0.0-rc.4`?

**Comment by TOBEMINE** [comment]
It works,thanks
