### ISSUE TITLE
[Question]: streaming large response in TCP

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [panjf2000/gnet#483]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

Use case: building an http server and need to serve a large file.

In the example in gnet-examples, the response is returned in a byte array, which requires loading the whole file in memory first. Is there a way to stream/chunk the file out in response?

Thanks!

**Comment by panjf2000** [comment]
Try zero copy system call `sendfile` with non-blocking mode.

**Comment by mohamed--abdel-maksoud** [comment]
@panjf2000 Thanks for the insight!

how would you replace a call to `gnet.Conn.Write` with sendfile?

**Comment by panjf2000** [comment]
> @panjf2000 Thanks for the insight!
> 
> how would you replace a call to `gnet.Conn.Write` with sendfile?

Zero-copy is a restricted technique that can only be used in some specific scenarios, thus we can't just ***replace*** the generic I/O methods with zero-copy system calls.

If all you want is a simple file server, you don't have to build it on top of `gnet`, go with `http.FileServer`.

**Comment by mohamed--abdel-maksoud** [comment]
I'm implementing a subset of the functionality of a server like `nginx` using gnet, hence I wanted to handle large files efficiently.

I'll read up further about that, thanks for the response!
