### ISSUE TITLE
UDP fd什么时候调用close？

### ISSUE THREAD

**Issue by iqinlongfei** [panjf2000/gnet#484]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

发现TCP连接在创建和关闭时会调用OnOpen/OnClose，但对于UDP，OnOpen/OnClose没有被调用。我想知道UDP连接什么是否会被释放。我的应用场景是使用gnet实现一个UDP server，请求都是ping-pong模式，因此在大并发情况下，担心fd不够用。

**Comment by panjf2000** [comment]
UDP 是不可靠协议，通信前不需要建立连接。
