### ISSUE TITLE
[Question]: compatibility, gnet 2.x Client  request gnet 1.5.3 Server

### ISSUE THREAD

**Issue by maggieWmj** [panjf2000/gnet#490]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

    Can gnet 2.x client correctly request  gnet 1.5.3 server? We are exploring the use of a gnet 2.x client for improved functionality, but need to ensure compatibility with our current gnet 1.5.3 server.

such as:
    client: gnet 2.3.0
    server: gnet 1.5.3 
    golang: go1.19.12

**Comment by panjf2000** [comment]
I believe there are no compatibility problems between a `gnet` server and any client working with TCP protocol.

**Comment by maggieWmj** [comment]
Thanks for your answer, and it's been verified
