### ISSUE TITLE
[Question]: 应该如何支持 tls

### ISSUE THREAD

**Issue by 451008604** [panjf2000/gnet#496]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

gnet currently does not support TLS, does it? What I currently need to do is build the wss service, which has been implemented using gnet. However, when supporting the tls certificate, I found that there seems to be no interface support. Currently, I only see that PR that supports tls is still in the open state
gnet 目前还未支持 tls 是吗？我目前要做的是搭建 wss 服务，已经使用 gnet 实现 ws 服务，但是在支持 tls 证书时，发现好像没有接口支持。目前只看到有支持 tls 的 PR 还处在 open 状态中

\------------------------------------------------------------------
Do I need to implement the support for TLS certificates myself? Can you provide some implementation ideas?
对于 tls 证书的支持，需要自己去实现吗？是否可以提供一下实现思路？

\------------------------------------------------------------------
The framework version has been upgraded from v1 to v2, and currently there is no support for tls in either version🙂
（框架版本已从 v1 升级到 v2 ，目前这两个版本中都没有看到有 tls 支持🙂）

**Comment by panjf2000** [comment]
`gnet` 目前还不支持 tls，如果你需要的话可以通过 proxy 来引入 tls，可以用 [caddy](https://github.com/caddyserver/caddy), [traefik](https://github.com/traefik/traefik) 或者 [envoy](https://github.com/envoyproxy/envoy).

**Comment by 451008604** [comment]
哦哦，好的感谢。

其实有考虑过代理的方案，最开始的想法是通过 nginx 做代理后再访问 app 

有点担忧的是采用代理之后，是不是会对 gnet 的性能产生影响。有点吕布骑驴的感觉了。。。

（对系统底层的调用了解不深😂）

**Comment by 451008604** [comment]
哈哈哈哈，好的好的。
确认 gnet 现在不支持 tls 就 ok 。这样就直接采用代理服务方案了👍
