### ISSUE TITLE
[Feature]: 使用Engine.Stop退出时，会通过DefaultLogger输出很多错误日志

### ISSUE THREAD

**Issue by amwfhv** [panjf2000/gnet#497]
### Description of new feature

我有一个应用需要先调用Engine.Stop()，停止对外进行服务，然后再处理后续关闭任务，
但是当调用Engine.Stop()关闭网络时，会通过DefaultLogger输出很多错误日志如下
希望在相应的函数处能够处理关闭状态，关闭时真正的错误由Engine.Stop()函数返回，
[gnet] 2023-09-01T16:35:42.2013511+08:00        INFO    v2@v2.3.1/engine_windows.go:94  engine is being shutdown...
[gnet] 2023-09-01T16:35:42.2164331+08:00        ERROR   v2@v2.3.1/acceptor_windows.go:49        Accept() fails due to error: accept tcp [::]:8081: use of closed network connection
github.com/panjf2000/gnet/v2.(*engine).listen
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/acceptor_windows.go:49
golang.org/x/sync/errgroup.(*Group).Go.func1
        C:/Users/flash/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75
[gnet] 2023-09-01T16:35:42.2169447+08:00        ERROR   v2@v2.3.1/engine_windows.go:54  engine is being shutdown with error: accept tcp [::]:8081: use of closed network connection
github.com/panjf2000/gnet/v2.(*engine).shutdown
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/engine_windows.go:54
github.com/panjf2000/gnet/v2.(*engine).listen.func1
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/acceptor_windows.go:28
github.com/panjf2000/gnet/v2.(*engine).listen
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/acceptor_windows.go:50
golang.org/x/sync/errgroup.(*Group).Go.func1
        C:/Users/flash/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75
[gnet] 2023-09-01T16:35:42.2170447+08:00        ERROR   v2@v2.3.1/engine_windows.go:104 engine shutdown error: accept tcp [::]:8081: use of closed network connection
github.com/panjf2000/gnet/v2.(*engine).stop
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/engine_windows.go:104
github.com/panjf2000/gnet/v2.run
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/engine_windows.go:163
github.com/panjf2000/gnet/v2.Run
        C:/Users/flash/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.1/gnet.go:489
main.main
        C:/Users/flash/GolandProjects/awesomeProject/main.go:42
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:250

### Scenarios for new feature

在通过日志对服务器进行监控告警时，这里输出的信息会导致错误的告警

### Breaking changes or not?

Yes

### Code snippets (optional)

```go
package main

import (
	"context"
	"fmt"
	"github.com/panjf2000/gnet/v2"
	"log"
	"time"
)

var EchoServer *echoServer

type echoServer struct {
	gnet.BuiltinEventEngine
	eng gnet.Engine
}

func (es *echoServer) OnBoot(eng gnet.Engine) (action gnet.Action) {
	fmt.Printf("start echoServer")
	es.eng = eng
	return
}

func (es *echoServer) OnOpen(c gnet.Conn) (out []byte, action gnet.Action) {
	fmt.Printf("client connection:%s", c.RemoteAddr().String())
	return nil, gnet.None
}

func (es *echoServer) OnClose(c gnet.Conn, err error) (action gnet.Action) {
	if err != nil {
		log.Printf("error occurred on connection=%s, %v", c.RemoteAddr().String(), err)
	}
	return
}

func main() {
	EchoServer = &echoServer{}
	time.AfterFunc(time.Second*5, func() {
		EchoServer.eng.Stop(context.Background())
	})

	gnet.Run(EchoServer, "tcp://:8081", gnet.WithMulticore(true))
}
```

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
主动退出时内部涉及多个错误，这些错误和意外退出的错误的处理有重叠，比较难分开，你说的 `希望在相应的函数处能够处理关闭状态，关闭时真正的错误由Engine.Stop()函数返回` 我不是很理解，能具体一点吗？或者用代码展示你想要的最终效果是什么。

**Comment by amwfhv** [comment]
就是说，能否在调用Stop函数时通过一个atomic.bool标记是正常调用关闭接口，这样在内部涉及的多个错误可以检测这个标记，比如Accept函数此时返回的错误能够知道是因为调用Stop函数时触发，就无需输出错误

**Comment by amwfhv** [comment]
我在Windows平台下面，尝试加入以下代码后主动退出就输出错误了，不确认内部还有多少涉及的地方，望评估该功能
1、engine_windows.go
engine结构加入
`isStop       atomic.Bool`
2、engine_windows.go
start函数加入
`eng.isStop.Store(false)`
3、engine_windows.go
stop函数加入
`eng.isStop.Store(true)`
4、acceptor_windows.go
listen函数在accept后处理err时进行判断
`
			tc, e := eng.ln.ln.Accept()
			if e != nil {
				if eng.isStop.Load() {
					return nil
				}
				err = e
				eng.opts.Logger.Errorf("Accept() fails due to error: %v", err)
				return
			}
`
