### ISSUE TITLE
[Bug]: bind: address already in use when using without reuseAddr parameter

### ISSUE THREAD

**Issue by gohryt** [panjf2000/gnet#503]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

I've made a simple server
```
Server struct {
	Engine gnet.Engine
}
server := &server.Server{}
```
which implements gnet.EventHandler interface and run it with gnet
```
err := gnet.Run(server, "tcp://0.0.0.0:3000",
	gnet.WithMulticore(true), gnet.WithTCPKeepAlive(alive), gnet.WithTCPNoDelay(gnet.TCPNoDelay))
```
on the ctrl+c i'm stopping this server with
```
err := server.Engine.Stop(background)
```
All this scheme works ok, but only if not send requests to server.
When i open the 0.0.0.0:3000 page in browser it works correctly and closes gnet server correctly, but it gives "bind: address already in use" on the every next start of program 

### Major version of gnet

v2

### Specific version of gnet

v2.3.2

### Operating system

Linux

### OS version

Linux 6.5.3-arch1-1 x86_64

### Go version

go version go1.21.0 linux/amd64

### Relevant log output

```shell
[gohryt@gohrytpc Go]$ go build && ./go
{"trace_id":"00000000000000000000000000000000","timestamp":"14-09-2023 17:46:25","level":"DEBUG","message":"boot"}
{"trace_id":"5a975d1e75b7498aa52f305845e21a78","timestamp":"14-09-2023 17:46:36","level":"DEBUG","message":"open"}
{"trace_id":"18ee031ccbae4f0290807bf83bc87a0d","timestamp":"14-09-2023 17:46:36","level":"DEBUG","message":"open"}
{"trace_id":"5a975d1e75b7498aa52f305845e21a78","timestamp":"14-09-2023 17:46:36","level":"DEBUG","message":"traffic"}
{"trace_id":"5a975d1e75b7498aa52f305845e21a78","timestamp":"14-09-2023 17:46:36","level":"DEBUG","URI":"/"}
{"trace_id":"5a975d1e75b7498aa52f305845e21a78","timestamp":"14-09-2023 17:46:36","level":"DEBUG","message":"traffic"}
{"trace_id":"5a975d1e75b7498aa52f305845e21a78","timestamp":"14-09-2023 17:46:36","level":"DEBUG","URI":"/favicon.ico"}
^C{"trace_id":"00000000000000000000000000000000","timestamp":"14-09-2023 17:46:38","level":"DEBUG","message":"shutdown"}
{"trace_id":"18ee031ccbae4f0290807bf83bc87a0d","timestamp":"14-09-2023 17:46:38","level":"DEBUG","message":"close"}
{"trace_id":"5a975d1e75b7498aa52f305845e21a78","timestamp":"14-09-2023 17:46:38","level":"DEBUG","message":"close"}
[gohryt@gohrytpc Go]$ go build && ./go
{"trace_id":"00000000000000000000000000000000","timestamp":"14-09-2023 17:46:50","level":"ERROR","error":"bind: address already in use"}
{"trace_id":"00000000000000000000000000000000","timestamp":"14-09-2023 17:46:50","level":"ERROR","error":"the internal engine is empty"}
```

### How to Reproduce

1. start http example from https://github.com/gnet-io/gnet-examples
2. open it's main page in browser
3. stop http example
4. start it again

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
This is not a bug, it's intended for TCP, see https://github.com/panjf2000/gnet/issues/485#issuecomment-1645166204.

**Comment by gohryt** [comment]
Maybe describe this behavior in Engine.Stop comment?
