### ISSUE TITLE
UDP resets Context and creates new gnet.Conn OnTraffic()

### ISSUE THREAD

**Issue by BatikanHyt** [panjf2000/gnet#506]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

For the UDP server, I attempted to use SetContext on the UDP gnet.Conn in OnTraffic(). However, gnet creates a new gnet.Conn with each OnTraffic call, and the context becomes nil.

### Major version of gnet

v2

### Specific version of gnet

v2.3.0

### Operating system

Linux

### OS version

Linux 4.19.0-24-amd64 x86_64

### Go version

1.20

### Relevant log output

```shell
-
```

### How to Reproduce

1. Start the gnet UDP server.
2. Set the gnet.Conn ctx in the OnTraffic() function.
3. Use netcat to connect to the UDP server and send a couple of messages.

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
Unlike TCP is a connection-based protocol, UDP is connectionless.

UDP does not establish a connection when sending data. It sends data without confirming receipt or checking for errors, thus there is actually no such **connection** between the endpoints under the UDP protocol. 

As for gnet, the gnet.Conn for UDP doesn't really represent a connection as it does for TCP, it's just an interface providing some useful APIs, so a gnet.Conn is constructed and destructed along with each data transfer while you're working with UDP.
