### ISSUE TITLE
[Feature]: 实现异步非阻塞的PacketConn接口,从而支持quic协议

### ISSUE THREAD

**Issue by someview** [panjf2000/gnet#508]
### Description of new feature

quic或http3协议，当前go语言里quic-go实现上使用的的是net.PacketConn接口, 如果gnet也实现PacketConn接口，那么久可以无缝对接quic-go这个库，使用http3或者quic协议 了.

### Scenarios for new feature

quic类似于websocket这样的长连接，但是本身是通过connection id作为标识，不是通过四元组来作为标识，gnet实现PacketConn接口，也可以在更高的层次上统一udp，tcp这样的协议.

### Breaking changes or not?

Yes

### Alternatives for new feature

最近正在探索将event io和quic结合起来使用的可能，理论上是完全可行的

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
我没深入看过 quic-go 的源码，不过我有点怀疑它能和 gnet 结合起来，因为它 go net 是同步编程模式，而 gnet 是异步编程模式 (非异步 I/O)，感觉应该无法兼容。

**Comment by someview** [comment]
> 我没深入看过 quic-go 的源码，不过我有点怀疑它能和 gnet 结合起来，因为它 go net 是同步编程模式，而 gnet 是异步编程模式 (非异步 I/O)，感觉应该无法兼容。

比较难，最底层直接就是go标准库的事件循环,上面实现跨多个连接的stream manager，如果是异步模式，数据缓存太难做了。实现肯定是可以实现的。
