### ISSUE TITLE
[Question]: Does gnet support a websocket server that can handle different URL patterns

### ISSUE THREAD

**Issue by rockflying** [panjf2000/gnet#511]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

Like `http.HandleFunc`, it can handle multiple patterns. How to implement such a serve using gnet?

**Comment by panjf2000** [comment]
`gnet` is a network framework that works on the transport layer, you can implement your own protocols (HTTP/WebSocket/...) with any features you want on top of it.
