### ISSUE TITLE
[Question]: 请问 多网卡情况下,在 udp 的 OnTraffic 事件里面,怎么得到接收数据的网络接口呢

### ISSUE THREAD

**Issue by maxbad** [panjf2000/gnet#513]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

比如收到UDP广播消息后,得到对方IP是0.0.0.0, 需要回复广播消息. 应该怎么回复呢.

**Comment by panjf2000** [comment]
接收 UDP 广播消息之后获取对端地址然后直接回复不就行了，这和 gnet 有什么关系？
