### ISSUE TITLE
[Question]: 数据超过65535时多次触发OnTraffic如何处理数据？

### ISSUE THREAD

**Issue by wadeLouis** [panjf2000/gnet#515]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

数据如果大于65535，这个时候，read方法读取是不完整的，同时通过InboundBuffered也无法判断是否接收完全。数据被切分后，每个切片都会出发一次OnTraffic，这个动作又是异步的。如何保证上一个数据和下一个数据能够拼接一起。

**Comment by panjf2000** [comment]
如果是 UDP，你可以尝试增加 [ReadBufferCap](https://pkg.go.dev/github.com/panjf2000/gnet/v2#WithReadBufferCap)，这样每次读取的包就可以更大，如果是 TCP，因为其本身就是流式协议，分包的逻辑你需要自己完成，尝试增加 `ReadBufferCap` 也只是治标不治本，因为每次 TCP 读取不能保证读出来的数据大小，你只能按照你自己的应用层协议进行分包，每次都尝试读一个完整的包，不完整就不消费数据即可，参考这个[例子](https://github.com/gnet-io/gnet-examples/tree/v2/simple_protocol).

**Comment by wadeLouis** [comment]
我使用的是tcp，进行文件的传输。我在v2版本的时候，第一个版本拆解包没问题了，通过OnTraffic触发时取数据长度如果超长，缓存这次的数据，下次数据触发OnTraffic的时候补齐，这里很丑陋，要自己缓存一下。第二版本，我一次性的调用conn的read方法，读取所有的数据，但是即使我只发送一个文件，读取到完整文件数据后，后面仍然出发OnTraffic方法，让我没办法判断是否有新数据。然后我回到V1版本去使用，但是发送大文件时，服务端很久很久才会触发OnTraffic，也会卡住后面的消息处理。我不是很清楚这方面的逻辑，golang也用的不是很熟悉，帮忙解答下。
