### ISSUE TITLE
[Question]: 重启gnet.server需要如何做？

### ISSUE THREAD

**Issue by concn** [panjf2000/gnet#516]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

因为程序有时候会假死状态，gnet.server的端口是9011；但是有时候程序看着假死了，telnet 127.0.0.1 9011的时候连接不上，判断gnet.server内部停止了。 
这时候我想重启gnet.Serve，需要怎么做呢？有以下3点问题请教咨询：
1. React() 方法返回 return nil, gnet.Shutdown 这样是不是会关闭gnet.Serve启动的server?
2. 第二调用gnet.Stop(ctx, fmt.Sprintf("tcp://:%d", port))是不是也会关闭gnet.Serve启动的fmt.Sprintf("tcp://:%d", port)这个端口的监听server呢？
3. 以上二种方法有什么区别吗，另外还有没有其它方法关闭gnet.Serve启动的server呢？然后再重新启动一个监听9011端口的Serve，需要怎么处理，谢谢！

### Code snippets (optional)

```go
flag.IntVar(&port, "port", Conf.DataServer.Port, "--port 9011")
	flag.BoolVar(&multicore, "multicore", true, "--multicore true")
	flag.BoolVar(&reuseport, "reuseport", false, "--reuseport true")
	flag.Parse()
	echo := new(echoServer)
	err := gnet.Serve(echo, fmt.Sprintf("tcp://:%d", port), gnet.WithMulticore(multicore), gnet.WithCodec(echo), gnet.WithReusePort(reuseport), gnet.WithTCPKeepAlive(330*time.Second))
	if err != nil {
		panic(err)
	}
```

**Comment by concn** [comment]
go版本1.18
windows server2008R2
gnet v1.6.5版本

**Comment by panjf2000** [comment]
两种关闭 `gnet` server 的方法都可以使用，没有本质区别，重新启动的逻辑需要你自己控制。

**Comment by concn** [comment]
目前升级到gnet V2.3.3版本
go版本1.18
windows server2008R2

![image](https://github.com/panjf2000/gnet/assets/50606635/0b2a2b78-3d5a-4bfb-80b2-04ffc0014059)


func (es *echoServer) OnShutdown(srv gnet.Engine) {
	ZapLogger.Info("Echo server is shutdown")
	go RunGNetServer(5016, true, false)
}

在OnTraffice里返回gnet.Shutdown会触发关闭 OnShutdown方法， 在OnShutdown方法里再调用RunGNetServer(5016, true, false)后，启动不了，显示错误：
panic: listen tcp :5016: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

是之前的启动RunGNetServer的Server没有关闭吗？ 需要怎么关闭上次的这个5016端口的gnet监听的server呢？

**Comment by panjf2000** [comment]
`OnShutdown` 的时候整个流程还没走完，还有你为什么非要在代码里控制重启的流程，一般不建议这么搞(不限于 gnet server)，直接退出进程然后重启不就行了。

**Comment by concn** [comment]
![image](https://github.com/panjf2000/gnet/assets/50606635/8c712317-aae6-41dc-b9f3-954229173a46)
因为我们程序没有主动闭连接，客户端也没有主动关闭socket；但是可能是网络不稳定或什么原因，导致了连接客户端又直接发起了新的连接，老的连接关闭触发了OnClose，这样一般跑一二个小时，客户端有1600个；有时候跑一二天，就会出现出问题。如上图，这时候没有新连接上来，因为telnet ip 5016端口是不通的；端口已经不通了；在服务器主机telnet 127.0.0.1 5016也是不通的。也没什么错误输出，程序停在那里，。重启程序后，又马上可以用了，这样不断的重启这个问题。所以就需要判断是出现这个情况的时候，就需要关掉之前的gnet.Run，重新gnet.Run一下这个端口监听；。
有三个问题请教：
1.用在React() 方法返回 return nil, gnet.Shutdown ，如何判断之前的gnet.Run的server（监听5016）彻底关掉了，好重新gnet.Run一下5016
2.如果用第二种方法gnet.Stop(ctx context.Context, protoAddr string) ,就是var ctx context.Context  然后和gnet.Run中参数protoAddr传进来调用gnet.Stop就可以了是吗？ 另外我看Stop不推荐使用了。
3.gnet.Run(gnet.WithTCPKeepAlive(12*time.Minute)) 这个KeepAlive参数，是tcp本身的机制时间呢，还是客户端发数据心跳即OnTraffic里收到数据的时间呢？ 我们是5分钟一个客户端数据心跳。
问的问题有点多，因为对这些稍微有些深度的东西不太懂，感谢回答！

**Comment by panjf2000** [comment]
这种端口不通的问题我建议你在服务端排查一下，看看你的网络进程还有没有在正常监听端口，或者分析一下是不是进程因为某种原因卡死了，可以用 [go-delve](https://github.com/go-delve/delve) 进入进程调试一下。

另外，`gnet` 的 Windows 版本只是为了方便[开发调试](https://github.com/panjf2000/gnet/blob/dev/README_ZH.md#-%E5%8A%9F%E8%83%BD)，所以这个版本没有做很细致的优化，性能方面没有保证，通常不建议用在生产环境；鉴于你也不是很了解底层，我建议你不要用 `gnet` 这种底层的网络框架，直接用 Go 的 [net](https://pkg.go.dev/net) 标准网络库，代码会更好写一点，而且你写业务代码出 bug 的概率也更低一点。
