### ISSUE TITLE
[Question]: 请问作者是否有异步读取的最佳实践示例呢？ 

### ISSUE THREAD

**Issue by xiatianqiuyu** [panjf2000/gnet#518]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

请问作者是否有异步读取的最佳时间示例呢？ 当前我在创建100个连接的情况下压测，从OnTraffic总读取数据，然后异步处理，发现qps还不如直接使用原生的net库高， 请问这是否因为使用方式不当，异步使用应该怎样使用呢？

**Comment by panjf2000** [comment]
是否要异步处理取决于你的场景，如果读取数据之后的处理逻辑有可能阻塞 (比如涉及网络 I/O: 数据库读写等)，则使用异步，如果处理逻辑不会阻塞，则不需要异步处理，直接在 `OnTraffic` 的 event-loop 中完成即可。
