### ISSUE TITLE
[Question]:自定义codec中是否会存在接受header失败导致后续数据都无法正确获取的情况

### ISSUE THREAD

**Issue by leeeo2** [panjf2000/gnet#519]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

你好，请教一下，我自定以了一个codec，先接收header，header接收完成之后解析出payload长度，再接收payload
是否存在接受header失败或错误的情况，导致无法正确解析出payload长度而读取了错误的长度，进而导致后续header都解析错误

**Comment by panjf2000** [comment]
使用任何网络框架都有可能出现自定义协议解析错误，这个只和你的业务代码有关，和框架无关。至于解析出错之后如何处理也取决于开发者自己的需求。

总之，这个问题和框架无关。
