### ISSUE TITLE
Shutting down the listener.

### ISSUE THREAD

**Issue by iwasaki-kenta** [panjf2000/gnet#52]
Hello,

I would like to request if it is possible for lifecycle methods to be exposed to synchronously/asynchronously shutdown the listener, and to have another method/channel exposed to block the current goroutine until the listener has completed.

I'm currently doing a hack for it using the Ticker of the event loop to periodically see if an atomic integer has been set to a certain value, and if so, shut down the event loop.

**Comment by iwasaki-kenta** [comment]
Using the hack for shutting down the ticker, it appears to also log:

```
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
2020/01/25 23:37:35 server is going to be shutdown
```
There should be a way to turn off logs in this case.

**Comment by panjf2000** [comment]
Why do you need to shut listeners down? What's your scenario?

 > and to have another method/channel exposed to block the current goroutine until the listener has completed.

I don't quite get it, what's the "until the listener has completed" supposed to mean? Besides, not blocking eventloop is one of the tenets in `gnet` and why would you try to block a eventloop goroutine? And again, what's your scenario for that?
