### ISSUE TITLE
[Question]: IO Wait如何解决

### ISSUE THREAD

**Issue by Fgaoxing** [panjf2000/gnet#524]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

这是基于gnet的一个http框架https://github.com/fast-response/fast-response
我在使用如下代码测试时，到打一定数量时日志不再输出，但结束时出现服务端出现IO Wait
```go
package main

import (
    "github.com/panjf2000/ants/v2"
    "net/http"
)

func main() {
    // 创建一个协程池，最大协程数10000
    p, _ := ants.NewPool(1000000)  // 并发数
    for i := 0; i < 1000000; i++ { // 执行个数
        p.Submit(func() {
            for {
                http.Get("目标")
            }
        })
    }
}
```
其中输出日志，使用go关键字了，是否和这个有关

**Comment by panjf2000** [comment]
有没有服务端的具体堆栈信息或者日志？还有，有没有尝试查看进程的 TCP 连接是否全都销毁了，或者还有残存？

**Comment by Fgaoxing** [comment]
@panjf2000 应该是都没有，目前我怀疑是我写的日志输出，创建了新的goroutines，由于fmt.Println造成阻塞导致超出上限，不过现在我这里没有可以提供给你的日志，所以需要等后天，（最后，谢谢大佬的回复）

**Comment by Fgaoxing** [comment]
另外TLS功能什么时候能够使用，我希望是我的框架支持HTTPS和2/3
