### ISSUE TITLE
[Question]: 可疑的CPU占用

### ISSUE THREAD

**Issue by PotatoCloud** [panjf2000/gnet#526]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

pprof profile火焰图
![662ebbdfde8f5eefadf2cee6cbfc6ecd](https://github.com/panjf2000/gnet/assets/60210021/8190d91e-0d12-4e4c-afad-48a302452140)

- 有规律的CPU使用率增长，每次增长都会使CPU使用率增加100%
- 无规律的增长时间
- 最终CPU使用率停留在 200%
- 使用 `-tags=gc_opt` 进行编译
- 使用`gnet.WithMulticore(true), gnet.WithReuseAddr(true), gnet.WithReusePort(true)`启动gnet
- gnet `v2.3.4`, ` golang.org/x/sys v0.16.0`, `golang.org/x/sync v0.6.0`

**Comment by PotatoCloud** [comment]
该问题百分百复现

**Comment by panjf2000** [comment]
看你这 profiling 结果，你的服务器一直在接收新连接吧？是不是你的客户端使用的是短连接，用完就丢？而且在频率很高。

**Comment by PotatoCloud** [comment]
没有，websocket业务，看了下服务器上的连接数，就几百个，而且重启完不会出现CPU占用率很高的情况。这种情况是保持了大量的连接后出现的...

**Comment by panjf2000** [comment]
所以复现的步骤是：
1. 先发起大量的连接，然后 CPU 占用飙升；
2. 客户端关闭大部分连接之后，CPU 占用率没有下降。
这样？

有没有试过不要用 gnet.WithReuseAddr(true), gnet.WithReusePort(true) ？

**Comment by panjf2000** [comment]
还有，能不能详细描述复现这个问题的步骤，以及能够稳定复现的客户端和服务端代码？

**Comment by PotatoCloud** [comment]
1. 发起大量的连接后，CPU占用一开始不会飙升，而是过一段时间后才会飙升
2. 是的
3. 没试过不使用 gnet.WithReuseAddr(true), gnet.WithReusePort(true)

**Comment by panjf2000** [comment]
如果可以的话，请用 bug report 的[模板](https://github.com/panjf2000/gnet/issues/new?assignees=panjf2000&labels=bug&projects=&template=bug-report.yaml&title=%5BBug%5D%3A+)重新建一个 issue，填上所有必要的信息。

**Comment by PotatoCloud** [comment]
每次CPU飙升都是 +100% +100% 这样🤔
