### ISSUE TITLE
[Question]: gnet打印很多error occurs in user-defined function, use of closed network connection

### ISSUE THREAD

**Issue by bryanchen463** [panjf2000/gnet#527]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

客户端与服务端建立长连接，服务端调用writeAsync将数据写到客户端，在客户端频繁断开重连的情况下会频繁打印。

**Comment by panjf2000** [comment]
这个 issue 模板是用于通用问题的，你的问题请用[这个模板](https://github.com/panjf2000/gnet/issues/new?assignees=panjf2000&labels=bug&projects=&template=bug-report.yaml&title=%5BBug%5D%3A+)创建 issue，并填写必要的信息。
