### ISSUE TITLE
哥 client 的使用好复杂啊

### ISSUE THREAD

**Issue by tangjiemian** [panjf2000/gnet#528]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

哥 client 的使用好复杂啊

**Comment by panjf2000** [comment]
哥，说说具体是哪里复杂呗

**Comment by someview** [comment]
> 哥，说说具体是哪里复杂呗

有微信交流群吗，哥们。如果程序里面同时用gnetserver和gnetclient ，两者之间在gnet库里面有没有全局共享的资源啊

**Comment by panjf2000** [comment]
> > 哥，说说具体是哪里复杂呗
> 
> 有微信交流群吗，哥们。如果程序里面同时用gnetserver和gnetclient ，两者之间在gnet库里面有没有全局共享的资源啊

没有，最近蛮多人在问，我看看啥时候抽空搞一个
