### ISSUE TITLE
关于React中阻塞逻辑的疑问

### ISSUE THREAD

**Issue by capric98** [panjf2000/gnet#53]
在Readme中给出的样例代码中，带有阻塞逻辑的部分都有一个
```golang
data := append([]byte{}, frame...)
```
请问这是不是意味着如果frame所带的数据如果没有被及时处理，可能会被回收或者复用覆盖？

另外如果处理的速度跟不上网络的速度，上述的这种方法似乎会导致内存占用不断上升，有没有什么办法可以限制网络的吞吐量？

**Comment by panjf2000** [comment]
> 请问这是不是意味着如果frame所带的数据如果没有被及时处理，可能会被回收或者复用覆盖？

对，这部分内存在`React()`事件函数返回之后是会被复用的，因此一般是要求这个数据在`React()`的作用域之内消化完。

> 另外如果处理的速度跟不上网络的速度，上述的这种方法似乎会导致内存占用不断上升，有没有什么办法可以限制网络的吞吐量？

目前`gnet`还不支持网络限流，所以可能得从 client 端着手来做。

**Comment by capric98** [comment]
请问一下gnet的Conn接口将来会不会支持同步写方法？
在使用异步写的时候由于没有回调，无法知道何时网络写入完成，因此若是使用如下方式：
```Golang
func (c gnet.Conn) Write(b []byte) (int, error) {
    c.AsyncWrite(b)
    c.Wake()
}
```
在使用io.Copy的时候由于io包内部buffer或者生命周期的原因（没有细看），会造成写入问题

只好改成：
```Golang
func (c gnet.Conn) Write(b []byte) (int, error) {
    c.AsyncWrite(append([]byte{}, b...))
    c.Wake()
}
```
虽然简单测试了下没有什么问题，但是总感觉随手append可能会有大量内存分配的overhead（

如果gnet.Conn接口能实现同步写或者给AsyncWrite加一个回调，感觉就可以自己维护一个buffer或者free list……

**Comment by panjf2000** [comment]
> 请问一下gnet的Conn接口将来会不会支持同步写方法？

按照`gnet`目前的架构，无法支持这种同步写的方法。

至于给`AsyncWrite()`加一个回调功能，见 #55 

还有，你的代码：
```go
func (c gnet.Conn) Write(b []byte) (n int, e error) {
    c.AsyncWrite(append([]byte{}, b...))
    c.Wake()
    return len(b), nil
}
```
并不能达到你的要求，这么做并没有实现写数据的时候实时通知到业务方。

**Comment by capric98** [comment]
了解了，谢谢解释 : )
