### ISSUE TITLE
[Feature]: Support for SO_BINDTODEVICE?

### ISSUE THREAD

**Issue by shaunco** [panjf2000/gnet#532]
### Description of new feature

While listening for UDP packets, it is common to listen on "0.0.0.0:123" or just ":123", which allows for the receipt of both unicast and broadcast UDP packets, however there are times where an application might want to listen on just a single network interface. Obtaining that interface's IP and then listening on "1.2.3.4:123" will only receive unicast packets, and thus the preferred mechanism is to still listen on ":123" (for v4+v6) or "0.0.0.0:123" (for v4), but to use SO_BINDTODEVICE to bind the socket to a single interface.

Once bound, tools like `ss` show it as `0.0.0.0%eth0:123` rather than just `0.0.0.0:123`.

### Scenarios for new feature

On network appliances with multiple interfaces, those interfaces are often attached to different networks - such as a network gateway that is attached to a LAN network on eth0 and the WAN network on eth1. If that device wants to listen for unicast+broadcast UDP on just the LAN interface, there is currently no way to do this with gnet (at least not that I could find).

### Breaking changes or not?

No

### Code snippets (optional)

```go
For most linux/freebsd based systems:

unix.SetsockoptString(fd, unix.SOL_SOCKET, unix.SO_BINDTODEVICE, a.interfaceName)
```

For darwin:
```go
iface, _ := net.InterfaceByName(devName)
unix.SetsockoptInt(int(fd), unix.IPPROTO_IP, unix.IP_RECVIF, iface.Index)
unix.SetsockoptInt(int(fd), unix.IPPROTO_IP, unix.IP_BOUND_IF, iface.Index)
```

For windows, there is example calls at https://stackoverflow.com/a/73041705 , but they'd need to be converted to go.

### Alternatives for new feature

Could have separate listeners for unicast and broadcast traffic, but it gets messy.

Could listen to everything and then filter in `OnTraffic`, but it is much more efficient to have the kernel just bind to a single interface.

### Additional context (optional)

`WithMulticastInterfaceIndex()` does something similar for multicast traffic.

**Comment by panjf2000** [comment]
Sounds reasonable, I'll see what we can do here.

**Comment by panjf2000** [comment]
I've done some investigation on this. `SO_BINDTODEVICE` is linux-specific and it seems that there are no equivalents on other platforms. `IP_BOUND_IF` seems like an equivalent on macOS but it's osx-specific and it doesn't exist on other BSD-like systems.

As for `IP_RECVIF` on freebsd, it doesn't look like an equivalent to `SO_BINDTODEVICE`.

Therefore, if we're going to do this, it looks like we're only able to do it on linux and mac.

### References

- [SO_BINDTODEVICE undeclared on freebsd 12](https://forums.freebsd.org/threads/so_bindtodevice-undeclared-on-freebsd-12.73731/)
- [IP(4) for freebsd](https://man.freebsd.org/cgi/man.cgi?query=ip&apropos=0&sektion=4&manpath=FreeBSD+15.0-CURRENT&arch=default&format=html)
- [[OS X equivalent of SO_BINDTODEVICE](https://stackoverflow.com/questions/20616029/os-x-equivalent-of-so-bindtodevice)](https://stackoverflow.com/questions/20616029/os-x-equivalent-of-so-bindtodevice/57013928#57013928)
- [Use Linux SO_BINDTODEVICE and mac IP_BOUND_IF to bind socket to a network interface](https://djangocas.dev/blog/linux/linux-SO_BINDTODEVICE-and-mac-IP_BOUND_IF-to-bind-socket-to-a-network-interface/)
- [socket bind vs SO_BINDTODEVICE](https://github.com/nodejs/node/issues/35769)

**Comment by shaunco** [comment]
Thanks for digging into this. Would that make the functions just NOPs on other platforms or does it imply platform-specific APIs?

**Comment by panjf2000** [comment]
> Thanks for digging into this. Would that make the functions just NOPs on other platforms or does it imply platform-specific APIs?

If we're going to do this, API should be present on all platforms that `gnet` supports and returns an `ErrUnsupportedOp`.

**Comment by shaunco** [comment]
No more information to share, but still very interested in this functionality.

**Comment by panjf2000** [comment]
I plan on doing this next month if nothing else gets in the way.

**Comment by shaunco** [comment]
I am properly receiving broadcast packets on both Ubuntu 22 and balenaOS with the workaround I had added while waiting for this change:
```go
func controlHelper(interfaceName string, c syscall.RawConn) (err error) {
	controlErr := c.Control(func(fd uintptr) {
		err = unix.SetsockoptString(int(fd), unix.SOL_SOCKET, unix.SO_BINDTODEVICE, interfaceName)
		if err != nil {
			return
		}
	})
	if controlErr != nil {
		err = controlErr
	}
	return
}
```
which is used in:

```go
	var listenConfig = net.ListenConfig{
		Control: controlHelper,
	}

	// Must listen on `:port` to also receive broadcast packets...
	// ... we bind to a specific interface through control above
	packetConn, err := listenConfig.ListenPacket(context.Background(), "udp4", fmt.Sprintf(":%d", port))
	if err != nil {
		return nil, err
	}
```

I will give it a try in gnet with your change.

**Comment by shaunco** [comment]
Also, here is the Darwin equivalent:
```go
func bindToDevice(fd uintptr, devName string) error {
	iface, err := net.InterfaceByName(devName)
	if err != nil {
		return err
	}

	if err := unix.SetsockoptInt(int(fd), unix.IPPROTO_IP, unix.IP_RECVIF, iface.Index); err != nil {
		return fmt.Errorf("ipv4: Could not bind to an interface (receive path): %w", err)
	}

	if err := unix.SetsockoptInt(int(fd), unix.IPPROTO_IP, unix.IP_BOUND_IF, iface.Index); err != nil {
		return fmt.Errorf("ipv4: Could not bind to an interface (send path): %w", err)
	}

	return nil
}
```

**Comment by panjf2000** [comment]
> ```go
> IP_RECVIF
> ```

Are you sure this would work? I had tested it on my macOS and it doesn't even have `IP_RECVIF` anymore, the system call returned `EINVAL`. Besides, `IP_BOUND_IF` seemed to affect only outbound packets, not inbound packets.

**Comment by panjf2000** [comment]
> Also, here is the Darwin equivalent:
> 
> ```go
> func bindToDevice(fd uintptr, devName string) error {
> 	iface, err := net.InterfaceByName(devName)
> 	if err != nil {
> 		return err
> 	}
> 
> 	if err := unix.SetsockoptInt(int(fd), unix.IPPROTO_IP, unix.IP_RECVIF, iface.Index); err != nil {
> 		return fmt.Errorf("ipv4: Could not bind to an interface (receive path): %w", err)
> 	}
> 
> 	if err := unix.SetsockoptInt(int(fd), unix.IPPROTO_IP, unix.IP_BOUND_IF, iface.Index); err != nil {
> 		return fmt.Errorf("ipv4: Could not bind to an interface (send path): %w", err)
> 	}
> 
> 	return nil
> }
> ```

Are you sure this would work? I had tested it on my macOS and it doesn't even have `IP_RECVIF` anymore, the system call returned `EINVAL`. Besides, `IP_BOUND_IF` seemed to affect only outbound packets, not inbound packets.

**Comment by shaunco** [comment]
> Are you sure this would work? I had tested it on my macOS and it doesn't even have `IP_RECVIF` anymore, the system call returned `EINVAL`. Besides, `IP_BOUND_IF` seemed to affect only outbound packets, not inbound packets.

The engineers on our team that use macOS had been using this in dev, but we don't use macOS in prod so it is possible it doesn't work right.
