### ISSUE TITLE
一条链接往外写数据，内存增长很快。

### ISSUE THREAD

**Issue by eazon** [panjf2000/gnet#533]
![企业微信截图_17082368592691](https://github.com/panjf2000/gnet/assets/5153721/0a9863a2-63f6-44d8-8976-23204cf72efe)

**Comment by eazon** [comment]
@panjf2000 接收并发数大概10000，5000caps接收，然后一条链接往第三方发送，发送caps大概3000，内存增长很快。

**Comment by eazon** [comment]
没有下降，直至oom。

**Comment by eazon** [comment]
2月份的版本。

**Comment by panjf2000** [comment]
信息太少了，用这个[模板](https://github.com/panjf2000/gnet/issues/new?assignees=panjf2000&labels=bug&projects=&template=bug-report.yaml&title=%5BBug%5D%3A+)重开一个吧
