### ISSUE TITLE
[Feature]: 有没有详细的教程 新手根本不知道咋用

### ISSUE THREAD

**Issue by mynameiscuining** [panjf2000/gnet#537]
### Description of new feature

[Feature]: 有没有详细的教程 新手根本不知道咋用

### Scenarios for new feature

[Feature]: 有没有详细的教程 新手根本不知道咋用

### Breaking changes or not?

Yes

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by mynameiscuining** [comment]
参考下这个 https://github.com/aceld/zinx

**Comment by panjf2000** [comment]
https://gnet.host/docs/

`gnet` 本身是一个轻量级的框架，API 不多，也很精简，如果以前有过 `libevent`/`libuv`/`netty` 这一类网络框架的使用经验的话应该很容易上手。也可以参考我们的[示例程序](https://github.com/gnet-io/gnet-examples)。
