### ISSUE TITLE
[Question]: 请教一个问题：关于使用独立的 worker pool 处理阻塞的业务逻辑

### ISSUE THREAD

**Issue by dgqypl** [panjf2000/gnet#538]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

在官网 [doc](https://gnet.host/docs/about/overview-cn/) 中看到如下一段话：
<img width="815" alt="gnet 提问截图" src="https://github.com/panjf2000/gnet/assets/25171658/e01a68f8-46f4-4cb7-9c2d-60e5b3e4a3b4">

第一处画红线的地方，为何我在 `EventHandler` 这个 interface 中并没有搜到 React 这个方法，是更名为 OnTraffic 了吗？（我是在 v2.3.5 这个最新的 tag 下搜的）
第二处画红线的地方，点击 “这里” 这个超链接并没有跳转，是锚点失效了吗？能否给一个最新的该用法 example？

多谢

**Comment by panjf2000** [comment]
v1 版本是 `React`，v2 改成 `OnTraffic` 了，文档滞后了，我等会儿更新一下，多谢指出！

**Comment by panjf2000** [comment]
已更新：https://gnet.host/docs/
