### ISSUE TITLE
如何通知GNet关闭某个链接？[Question]: 

### ISSUE THREAD

**Issue by harry0059** [panjf2000/gnet#539]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

如何通知GNet关闭某个链接？gnet v2.3.1
场景：
一个用户开多客户端 重复链接服务器，要断开前一个链接，保持后一个链接
在收到一个后一个用户的链接数据登陆请求识别到用户id后，直接用前一个链接的gnet.Conn 的Close 关闭链接不行吧？

**Comment by panjf2000** [comment]
> 直接用前一个链接的gnet.Conn 的Close 关闭链接不行吧？

为什么不行？
