### ISSUE TITLE
codec模式使用asyncwrite数据不能自动编码吗？

### ISSUE THREAD

**Issue by shlande** [panjf2000/gnet#54]
作为一个小白来说看源代码有点难，，遇到了这个问题于是就来问问（反正我试了一下好像不行）。如果不能自动编码dalao有没有想法把这个加上去？

**Comment by panjf2000** [comment]
可以，我现在加一下这个功能。

**Comment by panjf2000** [comment]
我看了下代码，调用`AsyncWrite()`是会编码之后才写的，你是试了之后没有完成编码？

**Comment by shlande** [comment]
对不起，，我的问题，，打扰了
