### ISSUE TITLE
[Question]: remoteAddr为什么是空的

### ISSUE THREAD

**Issue by liuxm2239** [panjf2000/gnet#544]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

使用gnet v2时，在freebsd14系统上，使用udp协议时，如果同时有两个向服务端发送数据，服务端收到数据后用go-cache保存conn，然后遍历cache将数据转发给另外一个客户端，此时缓存中的另一个客户端的remoteAddr变成空值，这个问题只在freebsd14上发现，win上没有这个问题，linux没有测试，不清楚是否存在这个问题
![1b4dd2900be471121df60346370148b](https://github.com/panjf2000/gnet/assets/88423516/890ffc6c-53cf-4a28-b089-a5f3bd1450c4)
![Snipaste_2024-03-15_22-07-32](https://github.com/panjf2000/gnet/assets/88423516/b462fc0d-11a9-4608-89c2-251576fbea88)

### Code snippets (optional)

```go
package main

import (
	"fmt"
	"github.com/panjf2000/gnet/v2"
	"github.com/patrickmn/go-cache"
	"log"
	"time"
)

type TransportServer struct {
	gnet.EventHandler
	Remote *cache.Cache
}

func (ts *TransportServer) OnBoot(e gnet.Engine) (action gnet.Action) {
	log.Println("启动服务器....")
	return gnet.None
}

func (ts *TransportServer) OnShutdown(e gnet.Engine) {
	//ts.Netmap.Close()
	log.Println("网络传输服务器停止监听...")
}

func (ts *TransportServer) OnTraffic(conn gnet.Conn) (action gnet.Action) {
	ts.Remote.Set(conn.RemoteAddr().String(), conn, cache.DefaultExpiration)
	buf := make([]byte, 65535)
	n, err := conn.Read(buf)
	if err != nil {
		log.Println(err)
		return
	}
	fmt.Println(string(buf))

	for k, _ := range ts.Remote.Items() {
		connT, _ := ts.Remote.Get(k)
		conn1 := connT.(gnet.Conn)
		if conn1.RemoteAddr() == nil {
			conn1.Write([]byte(k + string(buf[:n]) + "空值"))
		} else {
			conn1.Write([]byte(k + string(buf[:n]) + conn1.RemoteAddr().String()))
		}

	}
	action = gnet.None
	return
}

var (
	tServer = TransportServer{}
)

func main() {
	tServer.Remote = cache.New(cache.DefaultExpiration, cache.NoExpiration)
	go printClient()
	err := gnet.Run(&tServer, "udp://192.168.44.13:33457", gnet.WithMulticore(true))
	if err != nil {
		panic(err)
	}
}

func printClient() {
	for {
		for k, _ := range tServer.Remote.Items() {
			connT, _ := tServer.Remote.Get(k)
			conn1 := connT.(gnet.Conn)
			log.Println("remote :", conn1.RemoteAddr()) //在freebsd14上，此处打印remoteAddr均为空值，在win上没有这个问题
		}
		time.Sleep(2 * time.Second)
	}

}
```

**Comment by panjf2000** [comment]
UDP 每次调用 `OnTraffic` 之后都会清理 c 里的相关资源，所以不要依赖于其中的数据。

**Comment by panjf2000** [comment]
至于 Windows 的实现的不一致，需要修正。

**Comment by panjf2000** [comment]
> 至于 Windows 的实现的不一致，需要修正。

仔细看了下代码，之所以会不一致是因为 Windows 的实现有点特殊，目前只能这样，所以暂时不会改这个。不过类 Unix 系统上还是保持原样，因为 `gnet` 需要回收 `localAddr` 和 `remoteAddr` 的内存，但是又因为用户可以异步操作，所以无法确定什么时候能回收，因此只能固定在每一轮 `OnTraffic` 过后强制释放资源。所以，目前来说，你需要自己维护这个数据。
