### ISSUE TITLE
[Feature]: enable `OnOpen` when UDP socket is connected

### ISSUE THREAD

**Issue by panjf2000** [panjf2000/gnet#549]
### Description of new feature

We currently circumvent the `OnOpen` callback on the server side, which is fine because UDP requires unconnected sockets on the server side. That being said, we use connected UDP sockets on the client side, and it's feasible to enable `OnOpen` on the client side.

### Scenarios for new feature

For connected UDP sockets.

### Breaking changes or not?

No

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by IrineSistiana** [comment]
FR: 希望 UDP 的 OnClose 也会被调用。这样UDP和 TCP 的行为统一。

**Comment by panjf2000** [comment]
> FR: 希望 UDP 的 OnClose 也会被调用。这样UDP和 TCP 的行为统一。

等一下，我记得现在已经是会调用 `OnClose` 的吧？
