### ISSUE TITLE
希望AsyncWrite添加一个回调

### ISSUE THREAD

**Issue by CyberBunker** [panjf2000/gnet#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by panjf2000** [comment]
```go
func (c *conn) write(buf []byte) {
	if !c.outboundBuffer.IsEmpty() {
		_, _ = c.outboundBuffer.Write(buf)
		return
	}
	n, err := unix.Write(c.fd, buf)
	if err != nil {
		if err == unix.EAGAIN {
			_, _ = c.outboundBuffer.Write(buf)
			_ = c.loop.poller.ModReadWrite(c.fd)
			return
		}
		_ = c.loop.loopCloseConn(c, err)
		return
	}
	if n < len(buf) {
		_, _ = c.outboundBuffer.Write(buf[n:])
		_ = c.loop.poller.ModReadWrite(c.fd)
	}
}
```
`AsyncWrite()` 最后会调用上面的方法写数据，可以看到`n, err := unix.Write(c.fd, buf)`写数据的回客户端的时候是有可能出现 temporary unavailable error 这种情况的，这时 `gnet` 会把数据先写入出站的 buffer，等到后续有 writable 事件来的的时候再尝试写，这样的话注册的回调函数就无法发挥作用了，因此目前无法加入这一功能。
