### ISSUE TITLE
[Feature]: how to disable logging? replace uber zap with zerolog too pls

### ISSUE THREAD

**Issue by kolinfluence** [panjf2000/gnet#555]
### Description of new feature

uber zap is giving a lot of mem alloc issues

under ddos load, it's generating a lot of garbage coz of gnet usage. the cpu load is higher than my tls.

1. how to disable logging completely?
2. pls change to something zero allocation like zerolog or something.

![Screenshot from 2024-03-23 00-06-49](https://github.com/panjf2000/gnet/assets/104323920/e80da78b-d64d-44c3-9eaa-31b4518b68e8)

![Screenshot from 2024-03-23 00-09-05](https://github.com/panjf2000/gnet/assets/104323920/f4ee4a2f-a8c2-4c36-8dae-716ddc0e1666)

### Scenarios for new feature

improve performance and mem use

### Breaking changes or not?

No

### Alternatives for new feature

i want to continue liking gnet

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
It should only print logs at `ERROR` and `WARN` levels by default, what logging outputs were you seeing?

**Comment by panjf2000** [comment]
The logging module of `gnet` is pluggable, which means that you are free to replace the default logger with your own [customized logger](https://pkg.go.dev/github.com/panjf2000/gnet/v2@v2.3.6#WithLogger). If you want to disable the default logger, you can set the environment variable [`GNET_LOGGING_LEVEL`](https://pkg.go.dev/github.com/panjf2000/gnet/v2@v2.3.6/pkg/logging) to the highest level `FatalLevel` (which is "5") before starting your `gnet` services.

**Comment by ouvaa** [comment]
it was under ddos attack, i'm using 
github.com/IceFireDB/redhub which uses gnet.

it doesnt show any logs output. do u think it's doing something without showing anything? i put icefiredb under ants.Submit "goroutine". just wondering if it's advisable to use ants on top of gnet services etc.

**Comment by kolinfluence** [comment]
@panjf2000 it was under ddos attack, i'm using 
github.com/IceFireDB/redhub which uses gnet.

it doesnt show any logs output. do u think it's doing something without showing anything? i put icefiredb under ants.Submit "goroutine". just wondering if it's advisable to use ants on top of gnet services etc.
