### ISSUE TITLE
[Question]: What is the maximum number of cores tested by anyone? I just tested 192 cores and it's better than evio etc but...

### ISSUE THREAD

**Issue by ouvaa** [panjf2000/gnet#558]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

anyone tested on 448 cores before? any experience with that against other rust based equivalents?

*update:*
i just tested a rust version of monoio on 192cores aws c6a 384gb ram and gnet is faster
gnet 5393926 req/s
monoio 4958282 req/s

**Comment by ouvaa** [comment]
actually i came across this issue too...
https://github.com/golang/go/issues/65064

**Comment by panjf2000** [comment]
I'm a little bit confused, you said that `gnet` worked great on the 192-cores machine before, but now it doesn't anymore?

**Comment by ouvaa** [comment]
@panjf2000 i saw the stats wrong, it wasnt fully utilizing the cores and it has the issues here:
https://github.com/golang/go/issues/65064

it worked better than the rest including evio etc.

**Comment by panjf2000** [comment]
Just out of curiosity, what networking frameworks did you test exactly?

**Comment by ouvaa** [comment]
@panjf2000 
gnet
https://github.com/IceFireDB/redhub
evio
https://github.com/tidwall/redcon

as mentioned, i'm looking at io_uring and maybe even af_xdp now because epoll cant take advantage of multi cores like 192 cores. it's really terrible the performance. and with more cores, the cpu will take up a 3-5% tested on aws c6a. 192 cores 384gb ram

now i'm hoping for tls and io_uring from gnet. pls look at the tls as top priority.

**Comment by ouvaa** [comment]
@panjf2000 my bad, i was testing redis and http at the same time.

http version is "perfect". (need tls and io_uring)

it's fastest than all others, able to take advantage of multiple cores even up to 192 cores effectively.

**Comment by ouvaa** [comment]
@panjf2000 my bad again, i tested one last time and found gnet is best used in 8 core - 12 core environments. "optimum" at 8 cores, anymore than that will have diminish return.

yes it is able to use up all 192 cores but the speed actually dropped greater than lower cores, around 16 cores i think (where it is peaked)

e.g. 8 cores at 530000 req/s
16 cores at 580000 req/s
192 cores at 530000 req/s 

1 core at 65000 req/s
