### ISSUE TITLE
支持从单个goroutine关闭连接，windows不起作用

### ISSUE THREAD

**Issue by zseeker** [panjf2000/gnet#56]
connection_windows.go

code
203 func (c *stdConn) Close() error {
204     c.loop.ch <- stderr{c, nil}
205     return nil
206 }

**Comment by panjf2000** [comment]
为什么不起作用？描述一下详细的表现。

**Comment by zseeker** [comment]
windows环境测试代码，客户端连接未被关闭

type echoServer struct {
	*gnet.EventServer
}

func (es *echoServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	c.Close()  // can not close connect
	//action = gnet.Close  // can close connect
	return
}

**Comment by panjf2000** [comment]
不会吧，gnet_test.go 里有写测试代码并且是通过了的，你试试在`OnClosed`方法里打一下 logs 看看，应该会打印出来的。

**Comment by zseeker** [comment]
![测试截图_20200222121708](https://user-images.githubusercontent.com/51727441/75086339-e3363c00-556d-11ea-92ea-1a4ce202c10d.png)

**Comment by panjf2000** [comment]
https://github.com/panjf2000/gnet/blob/e19f553afaef01e8a523e4f68544b388422df777/eventloop_windows.go#L162-L180
应该是在这里关闭连接的时候失败了，返回了错误。至于原因，我猜和你用的这个网络工具有关，可能是连接服务器的方式有什么特别的导致服务端无法主动关闭连接，你可以在上面源码的地方把 error 打印出来看看是什么。

**Comment by zseeker** [comment]
由于Close() 代码中 c.loop.ch.(type) 是 stderr 而非 *stderr
https://github.com/panjf2000/gnet/blob/e19f553afaef01e8a523e4f68544b388422df777/connection_windows.go#L203-L206

因此在loopRun()代码中 第54行loopError不会执行
https://github.com/panjf2000/gnet/blob/e19f553afaef01e8a523e4f68544b388422df777/eventloop_windows.go#L43-L63

修改Close() 代码如下，可以正常关闭
func (c *stdConn) Close() error {
	c.loop.ch <- func() error {
		_ = c.loop.loopClose(c)
		return nil
	}
	return nil
}

**Comment by panjf2000** [comment]
的确，这里是一个 bug，谢谢指出。有兴趣提个 PR 改一下这里吗？😁

**Comment by panjf2000** [comment]
修改的话，直接把 Close() 里的 stderr 改成 *stderr 应该就可以了，不需要再写成你上面的那种。

**Comment by zseeker** [comment]
经过测试，stderr{} 改成 &stderr{}，gnet程序进程直接退出

**Comment by zseeker** [comment]
PR已经提交了
