### ISSUE TITLE
[Question]: I would like to verify whether this problem in the screenshot will cause the memory of the service to slowly increase.

### ISSUE THREAD

**Issue by huangweiboy2** [panjf2000/gnet#571]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

![image](https://github.com/panjf2000/gnet/assets/56343299/d266bbd1-cd73-4e43-a2aa-1e05400c0eac)
我用的版本正好是2.3.3。运维的小伙伴想我反馈说内存会缓慢的上升，所以我来求证下

**Comment by panjf2000** [comment]
Please use pprof to find out where it takes up the most memory in your production environment and we can determine if it's a bug. I'm unable to answer your question without learning more details in your production environment.
