### ISSUE TITLE
[Question]: Is the netpoll v1 version defaulting to horizontal triggering, and the V2 version defaulting to edge triggering?

### ISSUE THREAD

**Issue by chen2ding** [panjf2000/gnet#575]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

netpoll v1版本默认是水平触发，V2版本默认是边缘触发吗?

**Comment by panjf2000** [comment]
See #573

**Comment by chen2ding** [comment]
func (uc *UlebCodec) ReadULEB128(conn gnet.Conn) ([]byte, error) {
	bodyLen := 0
	ulebLen := 1
	for {
		if ulebLen > 5 {
			break
		}
		buf, err := conn.Peek(ulebLen)
		// 连接中没有数据
		if err != nil || len(buf) != ulebLen {
			return nil, nil
		}
		v := 0
		cc := 0
		for _, b := range buf {
			v += (int(b) & 0x7F) << cc
			cc += 7
			if b&0x80 == 0 {
				bodyLen = v
				break
			}
		}
		// uleb 读取完整退出循环
		if bodyLen > 0 {
			break
		}
		ulebLen++
	}
	defer conn.Discard(bodyLen + ulebLen)
	//等待读取bodyLen
	if bodyLen > uc.readBuffSize {
		return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, uc.readBuffSize)
	}
	buf, _ := conn.Peek(ulebLen + bodyLen)
	//PrintHex(buf[ulebLen:])
	return buf[ulebLen:], nil
} 同样的代码，v1升级V2后不能正常工作，上面是V2代码，下面v1
```go
func (uc *UlebCodec) ReadULEB128(conn gnet.Conn) ([]byte, error) {
	bodyLen := 0
	ulebLen := 1
	for {
		if ulebLen > 5 {
			break
		}
		n, buf := conn.ReadN(ulebLen)
		// 连接中没有数据
		if n == 0 || n != ulebLen {
			return nil, nil
		}
		v := 0
		cc := 0
		for _, b := range buf {
			v += (int(b) & 0x7F) << cc
			cc += 7
			if b&0x80 == 0 {
				bodyLen = v
				break
			}
		}
		// uleb 读取完整退出循环
		if bodyLen > 0 {
			break
		}
		ulebLen++
	}
	defer conn.ShiftN(bodyLen + ulebLen)
	//等待读取bodyLen
	if bodyLen > uc.readBuffSize {
		return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, uc.readBuffSize)
	}
	_, buf := conn.ReadN(ulebLen + bodyLen)
	return buf[ulebLen:], nil
}
```

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
func (uc *UlebCodec) ReadULEB128(conn gnet.Conn) ([]byte, error) {
bodyLen := 0
ulebLen := 1
for {
ifulebLen > 5 {
break
}
buf, err := conn.Peek(ulebLen)
// There is no data in the connection
if err != nil || len(buf) != ulebLen {
return nil, nil
}
v := 0
cc := 0
for _, b := range buf {
v += (int(b) & 0x7F) << cc
cc += 7
if b&0x80 == 0 {
bodyLen = v
break
}
}
// uleb reads completely and exits the loop
if bodyLen > 0 {
break
}
ulebLen++
}
defer conn.Discard(bodyLen + ulebLen)
//Waiting to read bodyLen
if bodyLen > uc.readBuffSize {
return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, uc.readBuffSize)
}
buf, _ := conn.Peek(ulebLen + bodyLen)
//PrintHex(buf[ulebLen:])
return buf[ulebLen:], nil
} The same code, v1 cannot work properly after upgrading to V2. The above is the V2 code, and the following v1
```go
func (uc *UlebCodec) ReadULEB128(conn gnet.Conn) ([]byte, error) {
bodyLen := 0
ulebLen := 1
for {
ifulebLen > 5 {
break
}
n, buf := conn.ReadN(ulebLen)
// There is no data in the connection
if n == 0 || n != ulebLen {
return nil, nil
}
v := 0
cc := 0
for _, b := range buf {
v += (int(b) & 0x7F) << cc
cc += 7
if b&0x80 == 0 {
bodyLen = v
break
}
}
// uleb reads completely and exits the loop
if bodyLen > 0 {
break
}
ulebLen++
}
defer conn.ShiftN(bodyLen + ulebLen)
//Waiting to read bodyLen
if bodyLen > uc.readBuffSize {
return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, uc.readBuffSize)
}
_, buf := conn.ReadN(ulebLen + bodyLen)
return buf[ulebLen:], nil
}
```

**Comment by chen2ding** [comment]
@panjf2000 请问这是什么问题呢

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
@panjf2000 What is the problem?

**Comment by chen2ding** [comment]
@panjf2000 调试感觉是buf中的数据我没有读完，然后后面就不触发OnTraffic了，v1版本正常的

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
@panjf2000 The debugging feeling is that I haven’t finished reading the data in buf, and then OnTraffic will not be triggered later. The v1 version is normal.

**Comment by chen2ding** [comment]
@panjf2000 已经格式化了，麻烦看下上面代码呢

**Comment by panjf2000** [comment]
One of the best practices with `gnet` v2 is to keep reading and decoding packets until you reach an incomplete packet, otherwise the `OnTraffic` won't be invoked again until there is new arrival of data on the socket. I think the root cause of your issue here is that `gnet` v1 would loop reading and decoding packets internally while `gnet` v2 wouldn't.

**Comment by chen2ding** [comment]
> v2的最佳实践之一`gnet`是继续读取和解码数据包，直到到达不完整的数据包，否则不会`OnTraffic`再次调用，直到套接字上有新数据到达。我认为你的问题的根本原因是`gnet`v1 会在内部循环读取和解码数据包，而`gnet`v2 不会。

我可以确认v1版本没有在内部循环读取，decode代码在上面
这个是V1外层代码
````go
func (s *Server) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	msg := BinaryJson.DecodeGJson(frame)
	if msg == nil {
		action = gnet.Close
		return
	}
	client, ok := c.Context().(*Client)
	if !ok || client == nil {
		return
	}
	task := func() {
		msgType, _ := msg.GetInt("t")
		switch msgType {
		case rpc.PingMsg:
			if err := s.Codec.WriteULEB128(client.Conn, rpc.NewPingResp()); err != nil {
				client.Close()
			}
			client.UpdateLastPingTime()
		case rpc.PongMsg:
		case rpc.ReqMsg, rpc.PushMsg:
			req := &rpc.Req{}
			req.FromGJson(msg)
			if req.Param == nil {
				return
			}
			resp := s.Handler.HandleReq(client, req)
			// 不需要回复的请求获取响应不做处理
			if resp == nil {
				return
			}
			// 判断是否是错误响应消息
			if _, ok := msg.GetString("e"); ok {
				client.Close() // 错误的响应信息,主动关闭连接
				return
			}
			if _, ok := msg.GetString("ec"); ok {
				client.Close() // 错误的响应信息,主动关闭连接
				return
			}
			if err := s.Codec.WriteULEB128(client.Conn, resp); err != nil {
				client.Close()
			}
		case rpc.RespMsg:
			resp := &rpc.Resp{}
			resp.FromGJson(msg)
			s.Handler.HandleResp(client, resp)
		default:
			xlog.Ins.Error(s.Handler.Name(), zap.Error(fmt.Errorf("未知消息类型:%d", msgType)))
		}
	}
	_ = s.pool.Submit(task)
	return
}
````

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
> One of the best practices with v2 `gnet` is to continue reading and decoding packets until an incomplete packet arrives, otherwise not calling `OnTraffic` again until new data arrives on the socket. I think the root cause of your problem is that `gnet`v1 internally loops reading and decoding packets, while `gnet`v2 does not.

I can confirm that the v1 version is not reading in the inner loop, the decode code is above
This is the V1 outer code
````go
func (s *Server) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
msg := BinaryJson.DecodeGJson(frame)
if msg == nil {
action = gnet.Close
return
}
client, ok := c.Context().(*Client)
if !ok || client == nil {
return
}
task := func() {
msgType, _ := msg.GetInt("t")
switch msgType {
case rpc.PingMsg:
if err := s.Codec.WriteULEB128(client.Conn, rpc.NewPingResp()); err != nil {
client.Close()
}
client.UpdateLastPingTime()
case rpc.PongMsg:
case rpc.ReqMsg, rpc.PushMsg:
req := &rpc.Req{}
req.FromGJson(msg)
if req.Param == nil {
return
}
resp := s.Handler.HandleReq(client, req)
// Requests that do not require a reply will not be processed if the response is obtained.
if resp == nil {
return
}
// Determine whether it is an error response message
if _, ok := msg.GetString("e"); ok {
client.Close() // Wrong response information, actively close the connection
return
}
if _, ok := msg.GetString("ec"); ok {
client.Close() // Wrong response information, actively close the connection
return
}
if err := s.Codec.WriteULEB128(client.Conn, resp); err != nil {
client.Close()
}
case rpc.RespMsg:
resp := &rpc.Resp{}
resp.FromGJson(msg)
s.Handler.HandleResp(client, resp)
default:
xlog.Ins.Error(s.Handler.Name(), zap.Error(fmt.Errorf("Unknown message type: %d", msgType)))
}
}
_ = s.pool.Submit(task)
return
}
````

**Comment by panjf2000** [comment]
https://github.com/panjf2000/gnet/blob/1.x/eventloop_unix.go#L125-L126

**Comment by chen2ding** [comment]
> https://github.com/panjf2000/gnet/blob/1.x/eventloop_unix.go#L125-L126

哦哦，了解

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
> https://github.com/panjf2000/gnet/blob/1.x/eventloop_unix.go#L125-L126

Oh, I understand
