### ISSUE TITLE
[Bug]: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by iqinlongfei** [panjf2000/gnet#577]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

![image](https://github.com/panjf2000/gnet/assets/105924538/0c92e8b1-3e5b-4817-a487-35b2cbef441f)

### Major version of gnet

v2

### Specific version of gnet

v2.3.3

### Operating system

Linux

### OS version

Linux 5.15.56.bsk.1-amd64 x86_64

### Go version

go1.19.2

### Relevant log output

```shell
fatal error: concurrent map read and map write

goroutine 398788 [running]:
github.com/panjf2000/gnet/v2.(*connMatrix).getConn(...)
	/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.3/conn_map.go:66
github.com/panjf2000/gnet/v2.(*eventloop).close(0xc354050380, 0xc4d02c3960, {0x1099680, 0xc50f578860})
	/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.3/eventloop_unix.go:174 +0xc5
github.com/panjf2000/gnet/v2.(*conn).write(0xc4d02c3960, {0xc4b0751b30, 0xee, 0xee})
	/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.3/connection_unix.go:137 +0x165
github.com/panjf2000/gnet/v2.(*conn).Write(0xc483353680?, {0xc4b0751b30?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.3/connection_unix.go:353 +0x5b
```

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
Did you call some APIs that are not concurrency-safe outside the eventloop? Please provide a reproducer for this issue.
