### ISSUE TITLE
HTTP 压测问题

### ISSUE THREAD

**Issue by willcuster66** [panjf2000/gnet#58]
**Describe the bug**

在macbook 下使用ab测试官方给出的http例子，全部超时，浏览器可正常访问，不管是否带-k，请问你是用什么工具测试的，怎样设置超时

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Info (please complete the following information):**
 - OS (e.g. Ubuntu 18.04): 
 - Go version (e.g. Go 1.13): 
 - gnet version (e.g. v1.0.0): 

**Additional context**

**Comment by panjf2000** [comment]
https://github.com/panjf2000/gnet_benchmarks/blob/master/bench-http.sh
