### ISSUE TITLE
Any plan to integrate and test with f-stack?

### ISSUE THREAD

**Issue by hxiaodon** [panjf2000/gnet#6]
Hi,
Do you consider about integrating gnet with [f-stack](https://github.com/F-Stack/f-stack/blob/dev/lib/ff_epoll.h) or other dpdk-family net-dev lib as the second option?
Maybe the performance should be more better in some scenarios.

**Comment by panjf2000** [comment]
That is a constructive proposal, I will pay attention to the `DPDK` and go to investigate it after I 
finish the main jobs of `gnet`, thank you for the proposal.😊

**Comment by panjf2000** [comment]
I am closing this issue and I will come back notify you if I decide to add DPDK into `gnet`, thanks~
