### ISSUE TITLE
[Bug]: Discard() panic

### ISSUE THREAD

**Issue by chen2ding** [panjf2000/gnet#605]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

Discard(n int ) panic slice bounds out of range  

### Major version of gnet

v2

### Specific version of gnet

v2.4.2

### Operating system

macOS

### OS version

Darwin 23.3.0 arm64

### Go version

go version go1.22.1 darwin/arm64

### Relevant log output

```shell
github.com/panjf2000/gnet/v2.(*conn).Discard(0x14000355180, 0x5)
       go/pkg/mod/github.com/panjf2000/gnet/v2@v2.4.2/connection_unix.go:353 +0x1f4
```

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by chen2ding** [comment]
panic: runtime error: slice bounds out of range [5:0]
goroutine 44 [running]:
runtime/debug.Stack()
        /Users/dingchen/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-arm64/src/runtime/debug/stack.go:24 +0x64
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /Users/dingchen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.9.0/worker.go:56 +0xb0
panic({0x1009cc740?, 0x140003761f8?})
        /Users/dingchen/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-arm64/src/runtime/panic.go:770 +0x124
github.com/panjf2000/gnet/v2.(*conn).Discard(0x14000355180, 0x5)
        /Users/dingchen/go/pkg/mod/github.com/panjf2000/gnet/v2@v2.4.2/connection_unix.go:353 +0x1f4

**Comment by panjf2000** [comment]
It seems that you were calling a non-concurrency-safe method in a goroutine outside the event loop. That's illegal.

**Comment by panjf2000** [comment]
Please post your code in this issue, that way I can examine it.

**Comment by chen2ding** [comment]
`func (c *GnetConn) ReadMessage() (bjson.JsonObject, error) {
	bodyLen := 0
	ulebLen := 1
	for {
		if ulebLen > 5 {
			break
		}
		buf, err := c.Peek(ulebLen)
		// 连接中没有数据或者数据不足
		if err != nil || len(buf) != ulebLen {
			return nil, ErrIncompletePacket
		}
		v := 0
		cc := 0
		for _, b := range buf {
			v += (int(b) & 0x7F) << cc
			cc += 7
			if b&0x80 == 0 {
				bodyLen = v
				break
			}
		}
		// uleb 读取完整退出循环
		if bodyLen > 0 {
			break
		}
		ulebLen++
	}
	msgLen := bodyLen + ulebLen
	if c.InboundBuffered() < msgLen {
		return nil, ErrIncompletePacket
	}

	defer func(conn *GnetConn, n int) {
		_, _ = conn.Discard(n)
	}(c, msgLen)

	//等待读取bodyLen
	if bodyLen > c.readBuffSize {
		return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, c.readBuffSize)
	}
	buf, _ := c.Peek(msgLen)
	msg, err := bjson.DecodeObject(buf[ulebLen:])
	if err != nil {
		return nil, err
	}
	return msg, nil
}`

这段代码在一个协成池中执行，会有并发问题吗

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
`func (c *GnetConn) ReadMessage() (bjson.JsonObject, error) {
bodyLen := 0
ulebLen := 1
for {
ifulebLen > 5 {
break
}
buf, err := c.Peek(ulebLen)
// There is no data or insufficient data in the connection
if err != nil || len(buf) != ulebLen {
return nil, ErrIncompletePacket
}
v := 0
cc := 0
for _, b := range buf {
v += (int(b) & 0x7F) << cc
cc += 7
if b&0x80 == 0 {
bodyLen = v
break
}
}
// uleb reads completely and exits the loop
if bodyLen > 0 {
break
}
ulebLen++
}
msgLen := bodyLen + ulebLen
if c.InboundBuffered() < msgLen {
return nil, ErrIncompletePacket
}

defer func(conn *GnetConn, n int) {
_, _ = conn.Discard(n)
}(c, msgLen)

//Waiting to read bodyLen
if bodyLen > c.readBuffSize {
return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, c.readBuffSize)
}
buf, _ := c.Peek(msgLen)
msg, err := bjson.DecodeObject(buf[ulebLen:])
if err != nil {
return nil, err
}
return msg, nil
}`

This code is executed in a synergy pool. Will there be any concurrency issues?

**Comment by chen2ding** [comment]
```
func (c *GnetConn) ReadMessage() (bjson.JsonObject, error) {
	bodyLen := 0
	ulebLen := 1
	for {
		if ulebLen > 5 {
			break
		}
		buf, err := c.Peek(ulebLen)
		// 连接中没有数据或者数据不足
		if err != nil || len(buf) != ulebLen {
			return nil, ErrIncompletePacket
		}
		v := 0
		cc := 0
		for _, b := range buf {
			v += (int(b) & 0x7F) << cc
			cc += 7
			if b&0x80 == 0 {
				bodyLen = v
				break
			}
		}
		// uleb 读取完整退出循环
		if bodyLen > 0 {
			break
		}
		ulebLen++
	}
	msgLen := bodyLen + ulebLen
	if c.InboundBuffered() < msgLen {
		return nil, ErrIncompletePacket
	}

	defer func(conn *GnetConn, n int) {
		_, _ = conn.Discard(n)
	}(c, msgLen)

	//等待读取bodyLen
	if bodyLen > c.readBuffSize {
		return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, c.readBuffSize)
	}
	buf, _ := c.Peek(msgLen)
	msg, err := bjson.DecodeObject(buf[ulebLen:])
	if err != nil {
		return nil, err
	}
	return msg, nil
}

```

这段代码在一个协成池中执行，会有并发问题吗

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
```
func (c *GnetConn) ReadMessage() (bjson.JsonObject, error) {
bodyLen := 0
ulebLen := 1
for {
ifulebLen > 5 {
break
}
buf, err := c.Peek(ulebLen)
// There is no data or insufficient data in the connection
if err != nil || len(buf) != ulebLen {
return nil, ErrIncompletePacket
}
v := 0
cc := 0
for _, b := range buf {
v += (int(b) & 0x7F) << cc
cc += 7
if b&0x80 == 0 {
bodyLen = v
break
}
}
// uleb reads completely and exits the loop
if bodyLen > 0 {
break
}
ulebLen++
}
msgLen := bodyLen + ulebLen
if c.InboundBuffered() < msgLen {
return nil, ErrIncompletePacket
}

defer func(conn *GnetConn, n int) {
_, _ = conn.Discard(n)
}(c, msgLen)

//Waiting to read bodyLen
if bodyLen > c.readBuffSize {
return nil, fmt.Errorf("abnormal msg bodyLen:%d > readBuffSize:%d", bodyLen, c.readBuffSize)
}
buf, _ := c.Peek(msgLen)
msg, err := bjson.DecodeObject(buf[ulebLen:])
if err != nil {
return nil, err
}
return msg, nil
}

```

This code is executed in a synergy pool. Will there be any concurrency issues?

**Comment by panjf2000** [comment]
Most of the methods of `gnet.Conn` are not concurrency-safe, thus they can't be called outside the `OnOpen`/`OnTraffic()`/`OnClose`/...

Please check out the doc: https://pkg.go.dev/github.com/panjf2000/gnet/v2#Conn

**Comment by chen2ding** [comment]
请问一下，那每个连接都在OnTraffic中同步解析，处理性能如何呢

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
I would like to ask, how is the processing performance when each connection is parsed synchronously in OnTraffic?

**Comment by panjf2000** [comment]
所有基于 I/O 多路复用的网络库都是同步解析网络包，因为这一步正常来说是不会阻塞当前的线程的，参考 redis/nginx 等等。如果解析完网络包之后的处理过程中有阻塞操作（比如需要读数据库或者磁盘文件），则需要把解析后的包复制一份传给单独的 worker 去处理，最后处理完了可以直接调用 `c.AsyncWrite()`/`c.AsyncWritev()` 把响应包写回客户端，这两个方法是并发安全的。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
All network libraries based on I/O multiplexing parse network packets synchronously, because this step normally does not block the current thread, refer to redis/nginx, etc. If there are blocking operations during the processing after parsing the network packet (such as needing to read a database or disk file), you need to copy the parsed packet and pass it to a separate worker for processing. After the final processing, you can directly call `c. AsyncWrite()`/`c.AsyncWritev()` writes the response packet back to the client. These two methods are concurrency-safe.

**Comment by chen2ding** [comment]
好的，谢谢

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
OK, thanks

**Comment by chen2ding** [comment]
> > 🤖 检测到非英语文本，正在翻译……
> 
> 所有基于 I/O 多路复用的网络库都是同步解析网络包的，因为这一步一般不会阻塞当前线程，参考 redis/nginx 等。如果解析网络包之后的处理过程中有阻塞操作（比如需要读取数据库或者磁盘文件），则需要将解析好的包复制一份交给单独的 worker 处理。最终处理完之后直接调用`c. AsyncWrite()`/`c.AsyncWritev()`写回响应包给客户端即可。这两种方式都是并发安全的。

但是后续会copy buf 数据吧

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
> > 🤖 Non-English text detected, translating...
>
> All network libraries based on I/O multiplexing parse network packets synchronously, because this step generally does not block the current thread, refer to redis/nginx, etc. If there are blocking operations during the processing after parsing the network packet (such as needing to read a database or disk file), you need to copy the parsed packet to a separate worker for processing. After the final processing, just call `c. AsyncWrite()`/`c.AsyncWritev()` to write back the response packet to the client. Both methods are concurrency safe.

But we will copy the buf data later.

**Comment by panjf2000** [comment]
其实严格来说也不算多拷贝了一份数据，因为你使用 `c.Read()`/`c.Next()`/`c.Peek()` 读出来的那个 buffer 实际上是当前这个 event loop 上的所有 `gnet.Conn` 共享的，所以只能在当前 event loop 所在的 goroutine 里读写而不能放到新的 goroutine 里去操作。而通常用户读取 buffer 里的数据之后还需要进行包解析操作，然后把解析后的包存到自己的内存里，比如反序列化成到一个 `struct` 里，这时候通常就是把这个 `struct` 的指针传给业务相应的业务处理函数，而这个函数可以放到一个新的 goroutine 里去处理，这个时候你并不需要再把前面的那个 `struct` 里的数据复制一遍，直接传给函数就行。 

比如你的那个 `ReadMessage()` 函数，需要把 `bjson.DecodeObject()` 相关的逻辑拆出来放到另一个函数比如 `ParseMessage()`，它的返回值是 `bjson.DecodeObject()` 的返回值，然后这个函数就只能在 `OnTraffic` 里调用；接着， `ReadMessage()` 使用 `bjson.DecodeObject()` 的返回类型作为函数参数，前一个函数的返回值直接传给这个函数就行了，放到一个新的 goroutine 去处理，最后处理完之后在新的 goroutine 里直接调用 `c.AsyncWrite` 回写数据即可。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
In fact, strictly speaking, it is not an extra copy of data, because the buffer you read using `c.Read()`/`c.Next()`/`c.Peek()` is actually the current one. All `gnet.Conn` on the event loop are shared, so they can only be read and written in the goroutine where the current event loop is located and cannot be placed in a new goroutine for operation. Usually after users read the data in the buffer, they need to perform package parsing operations, and then store the parsed package in their own memory, such as deserializing it into a `struct`. At this time, this `struct` is usually The pointer is passed to the corresponding business processing function of the business, and this function can be placed in a new goroutine for processing. At this time, you do not need to copy the data in the previous struct again, just pass it directly to the function. . 

For example, in your `ReadMessage()` function, you need to separate out the logic related to `bjson.DecodeObject()` and put it into another function such as `ParseMessage()`. Its return value is `bjson.DecodeObject()`. Return value, then this function can only be called in `OnTraffic`; then, `ReadMessage()` uses the return type of `bjson.DecodeObject()` as a function parameter, and the return value of the previous function can be passed directly to this function. Now, place it in a new goroutine for processing. After the final processing, directly call `c.AsyncWrite` in the new goroutine to write back the data.
