### ISSUE TITLE
[Feature]: `io_uring` support

### ISSUE THREAD

**Issue by sprappcom** [panjf2000/gnet#608]
### Description of new feature

io uring is really much faster. hope gnet can port it asap too.

### Scenarios for new feature

performance

### Breaking changes or not?

No

### Alternatives for new feature

None.

### Additional context (optional)

None.

**Comment by panjf2000** [comment]
`io_uring` support is on our roadmap. It may be implemented someday, but there is no specific guarantee for that.

`epoll` should suffice to support the most cases, thus `io_uring` shouldn't be so pressing at this point. Are you experiencing some performance bottlenecks currently?

**Comment by sprappcom** [comment]
@panjf2000 sry for late reply.
my only perf bottleneck is without io_uring.

this benchmark is like an eyesore, it makes my gnet implementation looks terrible. 
https://github.com/y001j/uringnet

**Comment by sprappcom** [comment]
@panjf2000 can u pls help with standardizing the example for use with tls? it's already there but there doesnt seem to have support or example on how to use it.

please support it with examples for https / tcp connection:

https://github.com/gnet-io/tls

can u take a look into this? i'm trying to upgrade redhub to use v2 and tls:

https://github.com/sprappcom/redhub/blob/main/redhub.go

**Comment by panjf2000** [comment]
I think #565 is still WIP.

**Comment by panjf2000** [comment]
Duplicate issue, move to #327

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Duplicate issue, move to #327
