### ISSUE TITLE
[Question]: there's gnet https server now, how to use gnet https client?

### ISSUE THREAD

**Issue by sprappcom** [panjf2000/gnet#609]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

how can i use gnet as https client? pls provide an example. thx.

also, pls update to use latest gnet-io/tls example for https.

thx!

**Comment by panjf2000** [comment]
For this kind of question, please go to our discord channel.
