### ISSUE TITLE
UDP FD handle is not released

### ISSUE THREAD

**Issue by vela-security** [panjf2000/gnet#610]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

# srv code
`
err = gnet.Run(srv, yml.Bind,
			gnet.WithLoadBalancing(gnet.LeastConnections),
			gnet.WithNumEventLoop(yml.Workers),
		)
`

# traffic
`
func (srv *Server) OnTraffic(c gnet.Conn) gnet.Action {
	srv.incr()
	body, err := c.Next(-1)
	if err != nil {
		return gnet.Close
	}
	srv.handle(body, c)
	return gnet.Close
}
`

# result
![image](https://github.com/panjf2000/gnet/assets/7379009/992a6917-5e5e-46c5-847f-dae34d9bb8ff)

### Major version of gnet

v2

### Specific version of gnet

v2.5.0

### Operating system

Linux

### OS version

Linux 3.10.0-862.el7.x86_64 x86_64

### Go version

go version go1.22.2 linux/amd64

### Relevant log output

```shell
时间长了 回到too many open files 报错
```

### Code snippets (optional)

```go
# srv code
`
err = gnet.Run(srv, yml.Bind,
			gnet.WithLoadBalancing(gnet.LeastConnections),
			gnet.WithNumEventLoop(yml.Workers),
		)
`

# traffic
`
func (srv *Server) OnTraffic(c gnet.Conn) gnet.Action {
	srv.incr()
	body, err := c.Next(-1)
	if err != nil {
		return gnet.Close
	}
	srv.handle(body, c)
	return gnet.Close
}
`
```

### How to Reproduce

# srv code
`
err = gnet.Run(srv, yml.Bind,
			gnet.WithLoadBalancing(gnet.LeastConnections),
			gnet.WithNumEventLoop(yml.Workers),
		)
`

# traffic
`
func (srv *Server) OnTraffic(c gnet.Conn) gnet.Action {
	srv.incr()
	body, err := c.Next(-1)
	if err != nil {
		return gnet.Close
	}
	srv.handle(body, c)
	return gnet.Close
}
`

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
I don't think these file descriptors were created by `gnet` because a UDP server typically does not create a new file descriptor every time it receives a datagram. A UDP server creates a single file descriptor for the socket when it's initialized. This file descriptor is then used for both sending and receiving datagrams throughout the server's lifetime.

You need to examine your own codebase to ensure that all file descriptors created by youself will be closed when not needed.
