### ISSUE TITLE
[Question]: The redis server service implemented using gnet has too many read tcp i/o timeouts in the production environment.

### ISSUE THREAD

**Issue by xingfu89** [panjf2000/gnet#611]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

我们之前是用go net包实现的redis server，线上环境client没有出现过io timeout，但换成gnet后，会出现很多的read tcp i/o timeoutl了，想请教下会是什么原因造成的
我们的server使用cgoup限了8核，NumEventLoop设置的8，其他配置都是默认值
线上redis命令都是mget 10个key，每个key的value值长度在1KB

**Comment by panjf2000** [comment]
Please provide some example code.

**Comment by xingfu89** [comment]
**gnet启动**
gnetOptions := gnet.Options{
   NumEventLoop: 8,
   ReusePort: true,
   ReuseAddr: true,
}

**EventHandler相关代码**
type Server struct {
    *gnet.BuiltinEventEngine
    eng      gnet.Engine
    connMu   sync.RWMutex
    connMap  map[gnet.Conn]*Client
    ...
}

type Writer struct {
    *bytes.Buffer
    ...
}


type Client struct {
    Writer *Writer
    ...
}

func (s *Server) OnBoot(eng gnet.Engine) (action gnet.Action) {
    s.eng = eng
    return
}

func (s *Server) OnOpen(conn gnet.Conn) (out []byte, action gnet.Action) {
    s.connMu.Lock()
    defer s.connMu.Unlock()

    remoteAddr := conn.RemoteAddr().String()
    s.connMap[conn] = &Client{
        Writer: &Writer{},
    }

    return
}

func (s *Server) OnClose(conn gnet.Conn, err error) (action gnet.Action) {
    s.connMu.Lock()
    defer s.connMu.Unlock()

    if c, ok := s.connMap[conn]; ok {
        c.Close()
        delete(s.connMap, conn)
    }

    return
}

func (s *Server) OnTraffic(conn gnet.Conn) (action gnet.Action) {
    s.connMu.RLock()
    defer s.connMu.RUnlock()

    c, ok := s.connMap[conn]
    if !ok {
        return gnet.Close
    }

   
    var readBuf []byte
    connBuf, _ := conn.Next(-1)
    hasLastByte := c.Reader.Len() > 0
    // 解析redis command
    cmds, err := ReadCommands(connBuf)
    if err != nil {
        return gnet.Close
    }
   
    for _, cmd := range cmds {
        // 处理redis command逻辑, 将resp写到c.Writer
        c.HandleRequest(cmd.Args)
        // 将c.Writer.Buf中的数据写到conn中
        conn.Write(c.Writer.Bytes())
        c.Writer.Reset()
    }

    return gnet.None
}

**Comment by xingfu89** [comment]
还有个问题，NumEventLoop是不是应该跟runtime.GOMAXPROCS设置的值相同才能达到最优性能，我们runtime.GOMAXPROCS设置的8，使用memtier_benchmark压测get，value128B，
开始NumEventLoop设置64，p99.9Latency达到了130ms，NumEventLoop调整为8，p99.9Latency就降到了3.5ms

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
There is another question, should NumEventLoop be the same as the value set by runtime.GOMAXPROCS to achieve optimal performance? We set runtime.GOMAXPROCS to 8, use memtier_benchmark stress test get, value128B,
Start NumEventLoop setting 64, p99.9Latency reaches 130ms, adjust NumEventLoop to 8, p99.9Latency drops to 3.5ms

**Comment by xingfu89** [comment]
> Please provide some example code.

gnet启动
gnetOptions := gnet.Options{
    NumEventLoop: 8,
    ReusePort: true,
    ReuseAddr: true,
}

EventHandler相关代码
type Server struct {
    *gnet.BuiltinEventEngine
    eng gnet.Engine
    connMu sync.RWMutex
    connMap map[gnet.Conn]*Client
    ...
}

type Writer struct {
     *bytes.Buffer
     ...
}

type Client struct {
    Writer *Writer
    ...
}

func (s *Server) OnBoot(eng gnet.Engine) (action gnet.Action) {
    s.eng = eng
    return
}

func (s *Server) OnOpen(conn gnet.Conn) (out []byte, action gnet.Action) {
    s.connMu.Lock()
    defer s.connMu.Unlock()

    remoteAddr := conn.RemoteAddr().String()
    s.connMap[conn] = &Client{
        Writer: &Writer{},
    }

    return
}

func (s *Server) OnClose(conn gnet.Conn, err error) (action gnet.Action) {
    s.connMu.Lock()
    defer s.connMu.Unlock()

    if c, ok := s.connMap[conn]; ok {
        c.Close()
        delete(s.connMap, conn)
    }

    return
}

func (s *Server) OnTraffic(conn gnet.Conn) (action gnet.Action) {
    s.connMu.RLock()
    defer s.connMu.RUnlock()

    c, ok := s.connMap[conn]
    if !ok {
        return gnet.Close
    }

    var readBuf []byte
    connBuf, _ := conn.Next(-1)
    hasLastByte := c.Reader.Len() > 0
    // func  ReadCommands parse redis command
    cmds, err := ReadCommands(connBuf)
    if err != nil {
        return gnet.Close
    }

    for _, cmd := range cmds {
        //  handle redis command, and write the command resp data to c.Writer
        c.HandleRequest(cmd.Args)
        // wtite c.Writer resp data to conn
        conn.Write(c.Writer.Bytes())
        c.Writer.Reset()
    }

    return gnet.None
}

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
I found out through online logging that the return value of a request for the mget command may be 100KB, and it takes hundreds of milliseconds to call the gnet.Conn Write method. Why is this synchronous writing so time-consuming? I saw the comment that the AsyncWrite method cannot be used in OnTraffic. Called in EventHandler, is there any good way to solve this problem?

**Comment by panjf2000** [comment]
首先，`AsyncWrite()` 可以在 `OnTraffic()` 里调用，只不过这个方法通常是给 event loop 之外的 goroutine 使用的；其次，`gnet.Conn.Write()` 只是直接调用系统调用 `write(2)`，而且 socket 都是非阻塞的，如果当前还有未发送完的数据则直接写入本地 buffer 然后返回，连系统调用都没有，所以写 100KB 的数据的延迟是几百毫秒肯定是有问题的，我建议你排查一下你的系统网络，或者就是你的代码有问题，是不是别的地方大量占用 CPU 导致 event loop 没有机会运行，跑一下性能测试看看 CPU 的分布状况；最后，如果是需要一次性写出多个 buffers，可以考虑使用 `gnet.Conn.Writev()` 减少系统调用，具体可看文档。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
First of all, `AsyncWrite()` can be called in `OnTraffic()`, but this method is usually used by goroutines outside the event loop; secondly, `gnet.Conn.Write()` just directly calls the system call` write(2)`, and sockets are non-blocking. If there is currently unsent data, it will be written directly to the local buffer and then returned. There is not even a system call, so the delay of writing 100KB data is definitely a few hundred milliseconds. If there is a problem, I suggest you check your system network, or there is a problem with your code. Is it that other places are occupying a lot of CPU, causing the event loop to have no chance to run? Run a performance test to see the distribution of the CPU; finally, If you need to write multiple buffers at once, you can consider using `gnet.Conn.Writev()` to reduce system calls. Please see the documentation for details.
