### ISSUE TITLE
[bug]: socket fd being reused during `OnClose()` lead to data corruption

### ISSUE THREAD

**Issue by fanties** [panjf2000/gnet#621]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

我在本地(mac)测试发现，一个gnet.Conn触发OnClose之后，依然可以调用该Conn Write数据，并且没有报错，排查了一下,是因为客户端重启，但是前后两个socket连接的文件描述符是相同的，所以gnet Write写入数据成功了
我看了一下源码，似乎是先释放的fd，再调用的OnClose回调、设置Addr为空等操作
<img width="1323" alt="image" src="https://github.com/panjf2000/gnet/assets/22397401/f508bb7c-dddb-4206-9ea3-d729a1fd54ba">
这样会不会出现：
文件描述符被回收了，又立马被新的连接占用了，此时写入正在关闭的这个连接，却write成功，但是数据却写错了目标呢？

**Comment by panjf2000** [comment]
确实可能会有这样的问题，现在把逻辑修改成先调用 `OnClose()` 再关闭 fd
业务层的逻辑也需要保证 `OnClose()` 事件之后不能再操作对应的连接。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
It is true that there may be such a problem. Now modify the logic to call `OnClose()` first and then close fd
The logic of the business layer also needs to ensure that the corresponding connection cannot be operated after the `OnClose()` event.

**Comment by promisingMan** [comment]
这个问题会导致fd一直增长吗？我在生产环境使用的是v2.0.3版本，发现fd会一直增长，最终触发了我们的告警。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Will this problem cause fd to keep growing? I am using version v2.0.3 in the production environment and found that fd will keep growing, eventually triggering our alarm.

**Comment by panjf2000** [comment]
> 这个问题会导致fd一直增长吗？我在生产环境使用的是v2.0.3版本，发现fd会一直增长，最终触发了我们的告警。

感觉说的不是一个问题，请升级到最新版本确认还有没有问题。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
> Will this problem cause fd to keep growing? I am using version v2.0.3 in the production environment and found that fd will keep growing, eventually triggering our alarm.

It doesn't seem to be a problem. Please upgrade to the latest version to check if there are still any problems.
