### ISSUE TITLE
[Question]: where is the example project?

### ISSUE THREAD

**Issue by ayamzh** [panjf2000/gnet#626]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

where is the example project?

**Comment by panjf2000** [comment]
https://github.com/gnet-io/gnet-examples

**Comment by ayamzh** [comment]
> https://github.com/gnet-io/gnet-examples

感谢，但是我运行tcp的例子遇到个问题，这个程序不能再windows下运行

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
> https://github.com/gnet-io/gnet-examples

Thanks, but I encountered a problem when running the tcp example. This program cannot be run under windows.
