### ISSUE TITLE
[Question]: type engine struct {

### ISSUE THREAD

**Issue by ayamzh** [panjf2000/gnet#627]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

Will gnetv2 support KCP in the future? Game companies often use KCP in frame synchronization scenarios.

**Comment by panjf2000** [comment]
Duplicate #318

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Duplicate #318
