### ISSUE TITLE
[Question]: client blocks when dialing new connections

### ISSUE THREAD

**Issue by zhao890516** [panjf2000/gnet#629]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

我是用一个client对象连接了两个不同的服务器，在连接第二个时在如下位置被阻塞住，请问这个openChan调用时机是什么？阻塞在这里可能原因是什么？
![image](https://github.com/panjf2000/gnet/assets/66517603/f459ef76-10f3-4de3-9805-c28d7f8367db)

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Please provide code that reproduces this issue.

**Comment by zhao890516** [comment]
![image](https://github.com/panjf2000/gnet/assets/66517603/91d53d05-42d0-444e-960b-ad04826ca9de)
![image](https://github.com/panjf2000/gnet/assets/66517603/d909cc44-6978-4d4b-96b2-abea9ec0a6f7)
![image](https://github.com/panjf2000/gnet/assets/66517603/5d9e3dcb-36de-4a65-b63c-ab720e43ff5a)
![image](https://github.com/panjf2000/gnet/assets/66517603/813b5e0d-73a5-4b43-a22f-e4d35397c3ab)

**Comment by panjf2000** [comment]
请提供操作系统和版本、gnet 版本、Go 版本。

下次这种问题不要用这个 issue 模板，这个是用来问一些通用的问题的，很容易缺失很多必要的信息，如果使用过程中遇到问题用[这个模板](https://github.com/panjf2000/gnet/issues/new?assignees=panjf2000&labels=bug&projects=&template=bug-report.yaml&title=%5BBug%5D%3A+)

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Please provide operating system and version, gnet version, Go version.

Don’t use this issue template next time for this kind of question. This is used to ask some general questions. It is easy to miss a lot of necessary information. If you encounter problems during use, use [this template](https://github.com /panjf2000/gnet/issues/new?assignees=panjf2000&labels=bug&projects=&template=bug-report.yaml&title=%5BBug%5D%3A+)

**Comment by zhao890516** [comment]
好的。
系统：Linux ubuntu 5.15.0-113-generic #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
gnet版本:github.com/panjf2000/gnet/v2 v2.5.5
go version：go1.22.3 linux/amd64

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
OK
System: Linux ubuntu 5.15.0-113-generic #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
gnet version:github.com/panjf2000/gnet/v2 v2.5.5
go version: go1.22.3 linux/amd64

**Comment by panjf2000** [comment]
你那个 `ConnectToCouplerByGnet()` 是在哪里调用的？要注意不能再 event loop 所在的 goroutine 里调用，否则就会阻塞。因为 gnet client 是单 event loop 的实现。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Where did you call `ConnectToCouplerByGnet()`? Be careful not to call it in the goroutine where the event loop is located, otherwise it will block. Because gnet client is an implementation of a single event loop.

**Comment by zhao890516** [comment]
ConnectToCouplerByGnet() 这个是另一个线程里边

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
ConnectToCouplerByGnet() This is in another thread

**Comment by zhao890516** [comment]
现在的情况是，我尝试连接的对端是OPEN-SSH服务器没问题，当连接的对端是HTTP服务器时，这里会在
![image](https://github.com/panjf2000/gnet/assets/66517603/d089f18c-aa5e-4a41-8b16-d46b982b3656)
这段完成之前先收到一条715字节的数据，然后连接就被阻塞了

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
The current situation is that the peer I am trying to connect to is an OPEN-SSH server, no problem. When the peer to connect is an HTTP server, here will be
![image](https://github.com/panjf2000/gnet/assets/66517603/d089f18c-aa5e-4a41-8b16-d46b982b3656)
Before this section is completed, a 715-byte data is received, and then the connection is blocked.

**Comment by panjf2000** [comment]
是不是其他回调函数里有阻塞的逻辑？比如 OnOpen 或者 OnClose，或者 AsyncWrite 的回调函数，这些回调里如果阻塞了也会导致 Dial 阻塞。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
Is there blocking logic in other callback functions? For example, OnOpen or OnClose, or AsyncWrite's callback function, if blocked in these callbacks, it will also cause Dial to block.

**Comment by zhao890516** [comment]
[Desktop.zip](https://github.com/user-attachments/files/16171115/Desktop.zip)
没有阻塞的逻辑。
这里是完整的代码，里边有个测试方法
![image](https://github.com/panjf2000/gnet/assets/66517603/6bd19854-7b1c-4512-a32b-5c7457fbfe52)
写一个简单的服务端
![image](https://github.com/panjf2000/gnet/assets/66517603/910cd92f-deab-4e06-a5ae-9ac2b3ccc02e)
这样子稳定复现
下边是日志，两次连接，只有一次成功
![image](https://github.com/panjf2000/gnet/assets/66517603/2097584c-6e5d-4e00-891a-a29ae5a630a6)

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
[Desktop.zip](https://github.com/user-attachments/files/16171115/Desktop.zip)
There is no blocking logic.
Here is the complete code, with a test method inside
![image](https://github.com/panjf2000/gnet/assets/66517603/6bd19854-7b1c-4512-a32b-5c7457fbfe52)
Write a simple server
![image](https://github.com/panjf2000/gnet/assets/66517603/910cd92f-deab-4e06-a5ae-9ac2b3ccc02e)
This is a stable recurrence
Below is the log. Two connections were made, only one was successful.
![image](https://github.com/panjf2000/gnet/assets/66517603/2097584c-6e5d-4e00-891a-a29ae5a630a6)

**Comment by zhao890516** [comment]
我解决了 ，犯了个低级错误，datachan忘记设容量，导致OnTraffic阻塞了，多谢你的帮助！

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
I solved it. I made a simple mistake. Datachan forgot to set the capacity, which caused OnTraffic to be blocked. Thank you for your help!
