### ISSUE TITLE
[Question]: How to set the client write timeout parameter?

### ISSUE THREAD

**Issue by xspren** [panjf2000/gnet#630]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

我使用 gnet v2 的 Client 用于发送数据，请问如何设置写入超时这个参数？或则有什么更优雅的实现方式么？

**Comment by panjf2000** [comment]
gnet 使用的是非阻塞 I/O，所以写数据的时候不会阻塞，如果出错会直接返回，你检查返回的错误即可。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
gnet uses non-blocking I/O, so it will not block when writing data. If an error occurs, it will be returned directly. You can just check the returned error.
