### ISSUE TITLE
[Question]: Communicate with netty

### ISSUE THREAD

**Issue by 879611427** [panjf2000/gnet#631]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

业务场景：以前是服务端、客户端都采用spring boot+netty，现在客户端要转go，服务端不变，gnet可以实现与netty的互通吗？

**Comment by panjf2000** [comment]
只要都是基于 TCP/UDP，那就肯定可以通信，和对端使用哪个框架没关系。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating...         
----    
As long as they are all based on TCP/UDP, communication will definitely be possible, regardless of which framework the peer uses.
