### ISSUE TITLE
[Question]: conn.RemoteAddr() null pointer

### ISSUE THREAD

**Issue by wangxinshuo** [panjf2000/gnet#642]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

gnet版本v1.6.6

在React()方法中存储客户端连接gnet.Conn连接到sync.Map中， 然后在其它协程（清理心跳超时的连接）中取出sync.Map的连接conn，并调用conn.RemoteAddr().String() 会产生 panic 

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74f2f1]

在另一个issue中看到gnet 需要回收 localAddr 和 remoteAddr 的内存， 不确定跟这个有没有关系
[https://github.com/panjf2000/gnet/issues/544](url)

onClosed的时候有从sync.Map中删除conn
[https://github.com/panjf2000/gnet/issues/126](url)

**Comment by panjf2000** [comment]
`RemoteAddr()` 不是线程安全的方法，不能在 gnet 事件函数 之外调用，用户需要预先保存起来：https://pkg.go.dev/github.com/panjf2000/gnet/v2#Conn

还有，建议不要使用 v1 了，切换到 v2，v1 目前不维护了。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
`RemoteAddr()` is not a thread-safe method and cannot be called outside the gnet event function. Users need to save it in advance: https://pkg.go.dev/github.com/panjf2000/gnet/v2#Conn

Also, it is recommended not to use v1 and switch to v2. v1 is currently not maintained.

**Comment by wangxinshuo** [comment]
gnet.Conn已经保存到了sync.Map中， 为什么还会空指针呢

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
gnet.Conn has been saved in sync.Map, why is there still a null pointer?

**Comment by wangxinshuo** [comment]
@panjf2000

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
@panjf2000

**Comment by wangxinshuo** [comment]
> gnet.Conn已经保存到了sync.Map中， 为什么还会空指针呢

@panjf2000 可以解答下吗，谢谢

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
> gnet.Conn has been saved in sync.Map, why is there a null pointer?

@panjf2000 Can you answer this question? Thank you.

**Comment by panjf2000** [comment]
不是因为 `gnet.Conn` 是空指针，而是因为其内部的 remoteAddr 字段是空，这里之所以会 panic 是因为调用了 `RemoteAddr().String()`.

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
It's not because `gnet.Conn` is a null pointer, but because its internal remoteAddr field is empty. The reason why there is a panic here is because `RemoteAddr().String()` is called.

**Comment by LeftH0ok** [comment]
remoteAddr 字段在什么情况下会是空的呢， 我在onClose的时候调用RemoteAddr()会提示空指针

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
Under what circumstances will the remoteAddr field be empty? When I call RemoteAddr() on onClose, it will prompt a null pointer

**Comment by LeftH0ok** [comment]
https://github.com/panjf2000/gnet/issues/544#issuecomment-2003759264

![Image](https://github.com/user-attachments/assets/95b6b481-dca5-4a4a-a1f9-ff646712e7b2)

需要自己维护conn吗

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
https://github.com/panjf2000/gnet/issues/544#issuecomment-2003759264

![Image](https://github.com/user-attachments/assets/95b6b481-dca5-4a4a-a1f9-ff646712e7b2)

Do you need to maintain the conn by yourself?

**Comment by panjf2000** [comment]
有问题请提交新的 issue，填写必要的信息，现在什么信息都没有无法分析。

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
If you have any questions, please submit a new issue and fill in the necessary information. Now there is no information that cannot be analyzed.
