### ISSUE TITLE
[Bug]: conn.Next not safe

### ISSUE THREAD

**Issue by zhongweikang** [panjf2000/gnet#647]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

https://github.com/panjf2000/gnet/blob/v2.5.9/connection_unix.go#L327-L330

代码`329行`，返回了`c.inboundBuffer`内部的字节数组
代码`327行`，`defer c.inboundBuffer.Discard(n)`，会回收`c.inboundBuffer`中的字节数组，回收到`sync.Pool`中

假设有两个`goroutine`
一个`goroutine`正在使用`329行`返回的字节数组
另一个`goroutine`读取到了`327行`回收的字节数组（因为被回收了，所以另一个`goroutine`能被复用）
导致两个`goroutine`同时操作了同一块字节数组，**报文错乱！**

### Major version of gnet

v2

### Specific version of gnet

V2

### Operating system

Linux, macOS

### OS version

Linux 3.10.0

### Go version

go1.17.12

### Relevant log output

```shell
无
```

### Code snippets (optional)

```go
defer c.inboundBuffer.Discard(n) //nolint:errcheck
	if len(head) >= n {
		return head[:n], err
	}
```

### How to Reproduce

多个事件循环并发执行时概率复现

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
看文档，这个方法本来就是非线程安全的：https://pkg.go.dev/github.com/panjf2000/gnet/v2#Conn

**Comment by gh-translator** [comment]
> 🤖 Non-English text detected, translating ...         
----    
Looking at the documentation, this method is inherently non-thread-safe: https://pkg.go.dev/github.com/panjf2000/gnet/v2#Conn
