### ISSUE TITLE
[Bug]: the buff of  eventloop.cache  used  cannot be released

### ISSUE THREAD

**Issue by szza** [panjf2000/gnet#659]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

the buff of eventloop.cache always occupied
<img width="577" alt="1" src="https://github.com/user-attachments/assets/58c7102e-78df-4ec3-949e-94e0e6aa051a">

### Major version of gnet

v2

### Specific version of gnet

github.com/panjf2000/gnet/v2 v2.5.2

### Operating system

Linux

### OS version

Linux 6.2.0-39-generic x86_64

### Go version

1.21.6

### Relevant log output

```shell
1
```

### Code snippets (optional)

```go
1
```

### How to Reproduce

the buff of eventloop.cache always occupied after no data communication 

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
The `eventloop.cache` is supposed to retain for the life of your `gnet` application, which is how this was designed.

Did it lead to any issues?

**Comment by szza** [comment]
> The `eventloop.cache` is supposed to retain for the life of your `gnet` application, which is how this was designed.
> 
> Did it lead to any issues?
the issue is: 
When the data traffic is very low, the memory previously occupied by eventloop.cache cannot be released and continues to occupy a large amount of memory.

**Comment by panjf2000** [comment]
There is one buffer for each event loop and the number of the event loops is typically equal to the number of CPU. Besides, the buffer size is not expected to be large because it only caches the bytes every time you read data from the connection.

When you said "a large amount of memory", how many bytes were you referring to? Any statistics you can show me?

**Comment by szza** [comment]
71 %  after data traffic decrease
<img width="1372" alt="2" src="https://github.com/user-attachments/assets/4fd83479-1eca-435b-ae77-c8f54f45a6b7">

**Comment by szza** [comment]
> There is one buffer for each event loop and the number of the event loops is typically equal to the number of CPU. Besides, the buffer size is not expected to be large because it only caches the bytes every time you read data from the connection.
> 
> When you said "a large amount of memory", how many bytes were you referring to? Any statistics you can show me?

71 % after data traffic decrease
<img width="1375" alt="3" src="https://github.com/user-attachments/assets/ac5406be-2768-4cc4-963e-fe4b59f82b3b">

**Comment by panjf2000** [comment]
This is uncanny, normally `eventloop.cache` shouldn't grow this big. Could you show me the code you write in `OnTraffic`?

**Comment by szza** [comment]
reduce the code: 
```
func (cm *connectionManager) OnTraffic(c gnet.Conn) (action gnet.Action) {
	for c.InboundBuffered() > 0 {
		// 1. decode
		if h, msg, err := ZeroCopyDecode(c); err != nil {
			if err == io.ErrShortBuffer {
				return
			}
			return gnet.Close
		}

		//... handle the msg
	}

	return gnet.None
}

// used for gent receive message
func ZeroCopyDecode(c gnet.Reader) (*Header, pb.Message, error) {
	total, err := c.Peek(MaxIntSize)
	if err != nil {
		return nil, nil, err
	}
	lenSize, length := DecodeInt(total)
	if lenSize > length {
		return nil, nil, proto.ErrorInvalidPacket
	}
	buff, err := c.Peek(length)
	if err != nil {
		return nil, nil, err
	}

	defer c.Discard(length)
	return DocodeBody(buff[lenSize:])
}


func DocodeBody(buff []byte) (h *Header, msg pb.Message, err error) {
	// 1. decode header
	h = FetchHeader(0)
	h.ReadFromBytes(buff)

	// 2. deocde body length
	bodySize, bodyLen := DecodeInt(buff[h.Size():])
	if bodyLen != len(buff)-bodySize-h.Size() {
		err = proto.ErrLenMismatch
		return
	}

	// 3. decode body
	msg = proto.NewMessage(h.Uri)
	if msg == nil || bodyLen == 0 {
		return
	}

	throughputBytesDetail.WithLabelValues(ToUri(h.Uri)).Observe(float64(bodyLen))
	err = pb.Unmarshal(buff[h.Size()+bodySize:h.Size()+bodySize+bodyLen], msg)
	return
}
```

**Comment by szza** [comment]
> This
The code has been pasted above.

**Comment by szza** [comment]
> This is uncanny, normally `eventloop.cache` shouldn't grow this big. Could you show me the code you write in `OnTraffic`?
The code has been pasted above.

**Comment by panjf2000** [comment]
> total, err := c.Peek(MaxIntSize)

What's this `MaxIntSize`? Is it the maximum value of `int` type? If so, it should be the first thing you need to fix because that's the root cause of this issue. You should peek one packet at a time, otherwise the `eventloop.cache` will be bloated if you peek a large size.

**Comment by szza** [comment]
> > total, err := c.Peek(MaxIntSize)
> 
> What's this `MaxIntSize`? Is it the maximum value of `int` type? If so, it should be the first thing you need to fix because that's the root cause of this issue. You should peek one packet at a time, otherwise the `eventloop.cache` will be bloated if you peek a large size.

const (
	MaxIntSize          = 8
)

**Comment by szza** [comment]
> > total, err := c.Peek(MaxIntSize)
> 
> What's this `MaxIntSize`? Is it the maximum value of `int` type? If so, it should be the first thing you need to fix because that's the root cause of this issue. You should peek one packet at a time, otherwise the `eventloop.cache` will be bloated if you peek a large size.

actually, we decode the one packet every time as the code pasted above:
1. `ZeroCopyDecode` a packet  to get a `msg`, and then
2. handle the msg
util meet the error `io.ErrShortBuffer ` or read buff empty.

**Comment by panjf2000** [comment]
How big is a packet? Also, what's the version of `gnet` you're using? You didn't fill out the issue template right.

**Comment by szza** [comment]
> How big is a packet? Also, what's the version of `gnet` you're using? You didn't fill out the issue template right.

Sorry，gent version is 'v2.5.2', mistakenly viewed the gnet version as the linux version.

The average size of packets should generally not exceed 32k; under certain exceptional circumstances, it may double,  may be grow to a few megabytes.

**Comment by panjf2000** [comment]
If you keep reading data until `io.ErrShortBuffer` in `OnTracffic`, the `eventloop.cache` shouldn't wind up to be bigger than your maximum packet size. Are you absolutely sure there is no some particularly large packet coming in?

**Comment by panjf2000** [comment]
Like over one hundred megabytes?

**Comment by szza** [comment]
> Like over one hundred megabytes?

impossible to exceed 10 M

**Comment by panjf2000** [comment]
> I think using `bsPool` to fetch memory and release it in `Discard` func might be a solution.

This could work for `Conn.Peek()`, but not for `Conn.Next()`.

I'll run some tests with big packets and see if it can reproduce your issue. Next move will depend on the test result.

**Comment by panjf2000** [comment]
#660 should fix this issue.

However, I discovered another uncanny "issue" when I did pprof on `gnet` transmitting 10MB packets, idle connections would have inuse memory of the `elastic.RingBuffer`, which should have been released:
![gnet-conn-mem-pprof](https://github.com/user-attachments/assets/b090ef43-0770-43e0-acab-43d25b71c468)
Did you see this when you ran pprof with your `gnet` server? @szza

**Comment by szza** [comment]
Idle connections still occupy memory, which the ringbuf cannot release.

<img width="1458" alt="5" src="https://github.com/user-attachments/assets/ce02c4f8-31a0-4ffe-a7fe-5b9c873253cd">

**Comment by szza** [comment]
Enable ET mode is a temporary solution ?
