### ISSUE TITLE
[Bug]: Idle connections still occupy memory, the ringbuf cannot be released

### ISSUE THREAD

**Issue by szza** [panjf2000/gnet#662]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

After experiencing high traffic, when the connection becomes idle, the memory in the ringbuf still cannot be released. 

<img width="1458" alt="5" src="https://github.com/user-attachments/assets/6d26007e-3bcb-409f-b7f4-acd256d4b364">

Emerged after solving the problem #659 

### Major version of gnet

v2

### Specific version of gnet

v2.6.1-cache-fix

### Operating system

Linux

### OS version

Linux 6.2.0-39-generic x86_64

### Go version

1.21.6

### Relevant log output

```shell
1
```

### Code snippets (optional)

```go
1
```

### How to Reproduce

After experiencing high traffic, when the connection becomes idle, the memory in the ringbuf still cannot be released

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment]
[v2.6.2](https://github.com/panjf2000/gnet/releases/tag/v2.6.2) should have fixed this issue, please try it out and let me know if it works.

**Comment by szza** [comment]
> [v2.6.2](https://github.com/panjf2000/gnet/releases/tag/v2.6.2) should have fixed this issue, please try it out and let me know if it works.

like nice.
