### ISSUE TITLE
[Question]: eng.Dup() not supported by windows

### ISSUE THREAD

**Issue by fearlessfe** [panjf2000/gnet#666]
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations about this problem but still have no answer.
- [X] I've searched the Github Issues/Discussions but didn't find any similar problems that have been solved.
- [X] I've searched the internet for this problem but didn't find anything helpful.

### Questions with details

I want to use gnet to send and reveice udp data on the same ip and port, the gnet version is `github.com/panjf2000/gnet/v2 v2.6.3`

I found some information on issue #345 , but it cannot work on windows.

Does it has any other method to work on windows?

### Code snippets (optional)

```go
type gnetConn struct {
	gnet.BuiltinEventEngine
	conn       *net.UDPConn
	log        log.Logger
	localAddr  net.Addr
	eng        gnet.Engine
	packetChan chan packet
	startChan  chan struct{}
}

func NewGnetConn(log log.Logger) *gnetConn {
	return &gnetConn{
		log:        log,
		packetChan: make(chan packet, 1024),
		startChan:  make(chan struct{}),
	}
}

func (gc *gnetConn) ListenUDP(ctx context.Context, addr string) error {
	udpAddr, err := net.ResolveUDPAddr("udp", addr)
	if err != nil {
		return err
	}
	go func() {
		err := gnet.Run(gc, "udp://"+addr)
		gc.log.Error("gnet run failed", "err", err)
	}()
	<-gc.startChan
	return nil
}

func (gc *gnetConn) OnTraffic(c gnet.Conn) gnet.Action {
	packet := packet{}
	data, err := c.Next(-1)

	if err != nil {
		return gnet.None
	}
	gc.log.Debug("<< reveice data", "remote", c.RemoteAddr())
	dst := make([]byte, len(data))
	copy(dst, data)
	packet.n = len(dst)
	packet.data = dst
	remote := c.RemoteAddr().(*net.UDPAddr)
	packet.addr = netip.AddrPortFrom(
		netip.AddrFrom4([4]byte(remote.IP.To4())),
		uint16(remote.Port),
	)
	gc.packetChan <- packet

	return gnet.None
}

func (gc *gnetConn) OnBoot(eng gnet.Engine) gnet.Action {
	fd, err := eng.Dup()
	if err != nil {
		gc.log.Error("on boot dup failed", "err", err)
		return gnet.Shutdown
	}
	file := os.NewFile(uintptr(fd), "udp")

	conn, err := net.FileConn(file)
	if err != nil {
		gc.log.Error("on boot file conn failed", "err", err)
		return gnet.Shutdown
	}

	udpConn := conn.(*net.UDPConn)
	gc.conn = udpConn
	gc.eng = eng
	gc.startChan <- struct{}{}
	return gnet.None
}
```

**Comment by panjf2000** [comment]
You can't just simply throw some code and say it doesn't work. That's no help for solving the problem. You need to provide more contexts and details explaining how it's not working.

**Comment by fearlessfe** [comment]
I need a server that also acts as a client (which mentioned by issue #345 ) , because I want to reveice and send udp data on the same address. 

In the `OnBoot` method, I call  `fd, err := eng.Dup()` the fd and make fd to a conn, these code work on linux and arm. But in window, maybe there are no fd, so `eng.Dup()` will return err, the err is `windows are not support`

Does it have other method which can work on windows

**Comment by panjf2000** [comment]
Please use [this template](https://github.com/panjf2000/gnet/issues/new?assignees=panjf2000&labels=bug&projects=&template=bug-report.yaml&title=%5BBug%5D%3A+) to open a bug report and provides more details.
