### ISSUE TITLE
react能否支持自定义的返回值

### ISSUE THREAD

**Issue by youngperson** [panjf2000/gnet#69]
**What is your question about gnet?**
Please describe your question meticulously.
func (es *echoServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	fmt.Println(c.RemoteAddr().String())
	// Echo synchronously.
	out = frame
	return
}
里面的out能不能自定义值去返回？？

**Comment by panjf2000** [comment]
为什么要自定义？你最后写回客户端都是字节码啊！

**Comment by youngperson** [comment]
> 为什么要自定义？你最后写回客户端都是字节码啊！

比如我接收到的数据比较大，不想再原样返回那么大的数据到客户端去。只想返回一个[]byte("1")这种的

**Comment by panjf2000** [comment]
不明白，那你直接 `out = []byte("1")` 不就好了？

**Comment by panjf2000** [comment]
我猜你理解错了，例子里之所以是的 `out = frame`，是因为是 echo 协议，所以直接把接收到的数据原样返回，out 变量本来就是要根据你自己的需求赋值的，你想赋什么值都可以。
