### ISSUE TITLE
如何拼接数据量较大的报文？

### ISSUE THREAD

**Issue by nickhell** [panjf2000/gnet#70]
因业务需要，gnet接收到的数据包过大，接收的数据在React函数中通过frame调用，但数据出现在多个React调用中。如何将这些数据打包成一个frame，一次完整使用？或如何将这些frame拼接起来？

**Comment by panjf2000** [comment]
`gnet` 一次接收的数据量是有上限的：64KB，如果你的数据包大于这个量，那肯定是会分成多块的，要获取完整的包也不需要你自己来拼装，`gnet` 内部有 ring-buffer 会自动缓冲数据，你可以实现自己的 codec，在 `Decode` 方法里每次读取一下数据，看看是不是一个完整的包，是的话就读取出来返回，不是的话就什么也不做，直接返回 nil，这样等收集到了一个完整的包的时候才会去调用 React 事件函数，到时候你就可以处理数据了。

@nickhell

**Comment by nickhell** [comment]
数据量确实超过了64KB。能给个简单的例子吗？不知道怎么调用Decode

**Comment by panjf2000** [comment]
简单来说，Decode 方法就是你对数据进行分包的地方，这个函数会在每一次读取 client 发来的数据的时候调用，你可以在这里依据你自己的规则对数据进行分析，比如你的数据包是用某个特定的分隔符分开的、或者你的每个数据包是定长的等等，然后判断是不是一个完整的包，如果有一个完整的包你就把数据返回，这个数据就是你最后会在 React 里接收的 frame。

这里有一个数据包定长的分包的 Decode 方法，你可以参考下：https://github.com/panjf2000/gnet/blob/master/codec.go#L116-L123

**Comment by nickhell** [comment]
type echoServer struct {
	*gnet.EventServer
	*gnet.FixedLengthFrameCodec
}

func (es *echoServer) Decode(c gnet.Conn) ([]byte, error) {
	size, buf := c.ReadN(5)
	if size == 0 {
		return nil, gnet.ErrUnexpectedEOF
	}
	c.ShiftN(size)
	return buf, nil
}

func (es *echoServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	// Echo synchronously.
	fmt.Printf("Recv : %s\n", frame)
...
}

func main() {
	var port int
	var multicore bool

	// Example command: go run echo.go --port 18885 --multicore=true
	flag.IntVar(&port, "port", 18885, "--port 18885")
	flag.BoolVar(&multicore, "multicore", false, "--multicore true")
	flag.Parse()
	echo := new(echoServer)
	log.Fatal(gnet.Serve(echo, fmt.Sprintf("tcp://:%d", port), gnet.WithMulticore(multicore)))
}

是这样使用吗？

**Comment by panjf2000** [comment]
不是，codec.go 里面那几个 codec 是已经实现好了的，你不需要再自己写 Decode 函数了，只需要传入你需要的一个定长值就行了，然后通过 options 的 `WithCodec` 方法传给 gent.Serve 方法就行了，你这完全是乱的，只有当现有的 codec 满足不了你的需求的时候，你要自己实现一个 codec 才需要去实现 Decode 和 Encode 函数，你还是参考一下这里吧：
https://github.com/panjf2000/gnet/blob/master/gnet_test.go#L43
https://github.com/panjf2000/gnet/blob/master/gnet_test.go#L241

**Comment by panjf2000** [comment]
还有没有问题？如果还不清楚可以继续问，要是没问题了麻烦 close 一下这个 issue。

@nickhell

**Comment by nickhell** [comment]
通过自定义不同的结束符进行判断，功能是实现了。但有个缺陷，就是结尾标识不同的话要定义多个结束标识字符串。
`
type DelimitersBasedFrameCodec struct {
	delimiters []string
}

// NewDelimitersBasedFrameCodec instantiates and returns a codec with a specific delimiter.
func NewDelimitersBasedFrameCodec(delimiters []string) *DelimitersBasedFrameCodec {
	return &DelimitersBasedFrameCodec{delimiters}
}

// Encode ...
func (cc *DelimitersBasedFrameCodec) Encode(c gnet.Conn, buf []byte) ([]byte, error) {
	return append(buf, []byte(cc.delimiters[0])...), nil
}

// Decode ...
func (cc *DelimitersBasedFrameCodec) Decode(c gnet.Conn) ([]byte, error) {
	buf := c.Read()
	
	idx := -1
	var delimiter_len int
	
	for _, delimiter := range cc.delimiters {
		idx = strings.Index(string(buf), delimiter)
		if idx != -1 {
			delimiter_len = len(delimiter)
		}
	}

	if idx == -1 {
		return nil, gnet.ErrDelimiterNotFound
	}
	c.ShiftN(idx + delimiter_len)
	return buf[:idx+delimiter_len], nil
}
`

**Comment by nickhell** [comment]
系统设计是通过表头携带data长度，判断获取整个data。我代码如下：
```
type HttpCodec struct {
}

func (hc *HttpCodec) Encode(c gnet.Conn, buf []byte) ([]byte, error) {
	return buf, nil
}

func (hc *HttpCodec) Decode(c gnet.Conn) ([]byte, error) {
	buf := c.Read()

	// 取出整个header
	idx2 := strings.Index(string(buf), "\r\n\r\n")
	if idx2 == -1 {
		if len(buf) > 0 {
			return nil, gnet.ErrDelimiterNotFound
		} else {
			return nil, gnet.ErrDelimiterNotFound
		}
	}
	header := string(buf[:idx2])

	// 获取数据长度
	data_len := -1
	header_elements := strings.Split(header, "\r\n")
	for _, element := range header_elements {
		if strings.HasPrefix(element, "Content-Length:") {
			if l, err := strconv.Atoi(strings.Trim(strings.Split(element, ": ")[1], " ")); err == nil {
				data_len = l
			}
		}
	}
	if data_len == -1 {
		return nil, gnet.ErrDelimiterNotFound
	}

	// 等待全部数据接收
	size := len(header) + 4 + data_len //+ utf8.RuneCountInString(string(buf[idx2+4:]))
	c.ShiftN(size + 1)
	return buf, nil
}
```
但在Decode方法中接收到的数据不全，而DelimitersBasedFrameCodec的Decode接收到的数据是完整的。因为对gnet内部实现了解不足，请指教下如何解决。

**Comment by panjf2000** [comment]
你这个自定义的 codec 实现得很不好，`delimiters` 直接使用 []byte 不就好了？你现在里面一大堆 string 和 []byte 的转换，完全是浪费性能！

`delimiters` 用 []byte，然后用 bytes 包的 bytes.Index(s, sep []byte) 就行了。

**Comment by nickhell** [comment]
确实是，感谢。第二个实现，通过data length来获取数据的方法怎么修改呢？

**Comment by panjf2000** [comment]
> 但在Decode方法中接收到的数据不全，而DelimitersBasedFrameCodec的Decode接收到的数据是完整的。因为对gnet内部实现了解不足，请指教下如何解决。

c.Read() 读出来的是 buffer + 当前最新的数据，是当前能读到的全部数据，如果数据还不全说明要不是客户端的全部数据还没完全到服务端，要不就是服务端还没全部读完，数据的完整性是你需要在 Decode 函数里确认的，你得确定读到了完整的数据才能开始下一步的逻辑，要不然就要直接返回 nil，gnet 会把不完整的数据继续存到 buffer 里，等下次再读的时候你再确认数据是不是完整了，反正就是一直这个循环，一直到你拿到了完整的数据才开始下一步的逻辑。

**Comment by nickhell** [comment]
Decode的返回值是([]byte, error)，[]byte是返回nil，error返回什么呢？error返回得不同，gnet的处理会有区别吗？

**Comment by panjf2000** [comment]
error 目前没有处理，都是以 out 是否为 nil 为准的。

还有我看你这个 HttpCodec 也有点问题，你在 header 里找到了 Content-Length 就直接默认是拿到了完整的数据，这个完全是不合理的，因为你不知道后面真正的内容数据是不是完整的，有可能就只有 header 的数据，content 是缺失的，结果你就这么返回了，后面的数据就全乱套了，你得确认当前的 buf 里已经包含了完整的 content 之后才能继续！

写这种网络应用还是得思考严密一点，不然后期一堆 bug。

**Comment by nickhell** [comment]
明白了，非常感谢
