### ISSUE TITLE
請問io事件是否不能保证先后顺序

### ISSUE THREAD

**Issue by jp3411952** [panjf2000/gnet#71]
**What is your question about gnet?**
Please describe your question meticulously.
是否有多个线程在调用 EventHandler.React等事件

**Comment by panjf2000** [comment]
如果开启 `Multicore`，那就是多 event-loops 的，每一个 event-loop 都是一个单独的 goroutine，React 肯定是会被所有 event-loops 调用的，但是对于每一个 connection 来说 IO 事件肯定是串行化的，因为每一个 connection 都是在一个固定的 event-loop 里，也就是说永远是同一个 goroutine 里。

**Comment by jp3411952** [comment]
假如有2个连接，连接1比连接2的消息早1ns到达服务器，就不能保证连接1的React事件 早于连接2的React事件执行哦

**Comment by panjf2000** [comment]
如果两个连接不在一个 event-loop 上的话当然保证不了，再说了你也没法保证哪个连接发出的消息一定会先到服务端，网络环境本身就是不稳定的，延迟、重传都会导致与期待不符的到达顺序。
