### ISSUE TITLE
epoll wake fd 系统调用的疑问

### ISSUE THREAD

**Issue by hegnee** [panjf2000/gnet#72]
**What is your question about gnet?**
epoll.go 中 func OpenPoller()
```r0, _, errno := unix.Syscall(unix.SYS_EVENTFD2, unix.O_CLOEXEC, unix.O_NONBLOCK, 0)```,不应该是
 ```r0, _, errno := unix.Syscall(unix.SYS_EVENTFD2, uintptr(initval), uintptr(flags), 0)``` 么，或者直接用unix. Eventfd

**Comment by hegnee** [comment]
直接用```r0,errno:=unix.Eventfd(0, unix.O_NONBLOCK | unix.O_CLOEXEC)```

**Comment by panjf2000** [comment]
的确，这里有点问题，我晚上改一下，或者你有兴趣提个 PR 改一下吗？

@hegnee
