### ISSUE TITLE
关于 gnet 如何接收完整数据包的问题

### ISSUE THREAD

**Issue by huangkun41** [panjf2000/gnet#73]
在tcp echo中传输多个很大的数据的时候，数据包被拆分为多个，如何控制buff接受数据大小？

如题：传输比较大的数据的时候，数据包被拆分传递。
func (es *echoServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
  fmt.Println(string(frame[:]))
}
经过测试这个例子里面的数据是不完整的。
如何类似socket while True一直循环解释数据，将数据进行拼接。

**Comment by panjf2000** [comment]
参考 #70

**Comment by huangkun41** [comment]
看了上面的交流，我说下我的理解，你看是否正确。（刚入手写go，以前写的是python，我把逻辑写出来，代码我再研究转换）
func (cc *LineBasedFrameCodec) Decode(c Conn) ([]byte, error) {
    buf := c.Read()
    framelen = int(c.Read()[8:12])   //起始包的8-12是完整数据包的长度
    if len(buf)%cc.framelen != 0 {   //判断buff和完整数据包是否等长
        return nil, ErrInvalidFixedLength   //如果不是那就返回nill
    }                
    c.ShiftN(framelen)
    return buf,nil  //这里的buff是接收的全部信息吗？
}

我的困惑是没有看到while True的循环一直对buf进行累加，然后进行判断数据包的长度。

python版本的代码如下：
while True:
    struct_bytes = self.request.recv(12)
    data_len = struct.unpack('>i', struct_bytes[8:])[0]
    #print(struct_bytes)
    recv_data = b''
    while len(recv_data) < data_len:
        if data_len - len(recv_data) > 1024:
            data = self.request.recv(1024)
        else:
            data = self.request.recv(data_len-len(recv_data))
        recv_data += data

**Comment by panjf2000** [comment]
我都怀疑你根本没看懂。。。

**Comment by panjf2000** [comment]
https://github.com/panjf2000/gnet/issues/70#issuecomment-612313131
这一段我已经说了，每次客户端有数据进来，你调用 c.Read() 返回的数据就已经是当前的读进来的数据加上存在内部 buffer 里的数据了，也就是当前能拿到的全部数据了。至于这个数据是不是一个完整的包，要你自己判断，如果你能解析出来一个完整的包，那就把这个数据包给 return 了，不然就返回 nil，这样 gnet 就会自动帮你把当前读进来的数据存到 buffer 里，你下次再调用 c.Read() 的时候还可以拿到。

> 我的困惑是没有看到while True的循环一直对buf进行累加，然后进行判断数据包的长度。

我不明白你这段想表达什么，你说的这个是业务逻辑吧，和 gnet 没关系，这个你得自己实现，在 codec 的 Decode 函数里。至于说 buffer 的累加，这个在 gnet 内部是自动做的，就是我前面说的，你只要没有得到一个完整的包就直接返回 nil，那 gnet 就会自动把这次读进来的数据存入 buffer，等下次再调用 Decode 的时候，你再调用 c.Read()，就是之前的数据加上当前的数据，然后你再判断是不是一个完整的包。你说的循环，在 gnet 内部就是不断循环调用 Decode，所以你才不用去操心循环判断和累加进 buffer 这些操作，因为在内部都实现好了。

P.S. 下次贴代码用好 md 的语法，不然格式太乱。

**Comment by huangkun41** [comment]
```go
func (cc *LineBasedFrameCodec) Decode(c Conn) ([]byte, error) {
    buf := c.Read()
    framelen = int(buf[8:12])   //这个是python写法，我后面再研究
    if len(buf)%cc.framelen != 0 {
        return nil, ErrInvalidFixedLength 
    }                
    c.ShiftN(12 + framelen)   //c.ShiftN是什么意思。
    return buf,nil 
}
```
我又明白了，只要不return buf,就一直在内部buffer缓存，每次调用c.Read() 会返回buffer里面所有的内容。循环的事情内部搞定了，不需要我操心了。

md标注代码刚刚学会，我还在诧异别人代码为何那么整齐。。

**Comment by panjf2000** [comment]
> 我又明白了，只要不return buf,就一直在内部buffer缓存，每次调用c.Read() 会返回buffer里面所有的内容。循环的事情内部搞定了，不需要我操心了。

对。

简单来说，就是 gnet 有内部 buffer 用来累加数据，读了数据之后需要清掉 buffer 里占用的空间，c.Read()/c.ReadN(int) 读取数据是 lazily read，也就是没有把 buffer 的那部分数据真正清掉，因为清掉了之后是不可逆的，所以必须完全确认了数据一个完整包之后才能去清理，c.ResetBuffer()/c.ShiftN(int) 就是来做这件事的，前者是整个清空，后者是指定清除多少数据。

下次记得先看接口文档，都有注释的：https://pkg.go.dev/github.com/panjf2000/gnet?tab=doc#Conn, 我不会每次都给别人解释这些文档里就能看到的东西！

**Comment by huangkun41** [comment]
明白了，明白了，非常感谢。
这个文档看了，百度翻译的没看懂。。

**Comment by panjf2000** [comment]
没事，你先按照这个思路再试试，如果还有问题你再开新的 issue 就行了，Good luck~

**Comment by huangkun41** [comment]
终于调试好了，献给刚开始接触Go的小朋友
```go
func (cc *BuiltInFrameCodec) Decode(c Conn) ([]byte, error) {
        buf := c.Read()
        if len(buf) < 20{
                c.ResetBuffer()   //非常重要，要清除buffer里面的缓存。
                return buf,nil
        }
        b := buf[8:12]     //8-12byte存储数据数据包的长度
        framelen_byte := bytes.NewBuffer(b)
        var frame_len int32
        binary.Read(framelen_byte, binary.BigEndian, &frame_len)   //byte转int
        buf_len := len(buf) - 12
        if buf_len % int(frame_len) != 0 {
                return nil,ErrInvalidFixedLength
        }
        c.ResetBuffer()
        return buf,nil
```
