### ISSUE TITLE
请问svr.activateLoops(numEventLoop) 开numEventLoop个goroutine监听，会不会epoll惊群

### ISSUE THREAD

**Issue by deardeng** [panjf2000/gnet#75]
**What is your question about gnet?**
Please describe your question meticulously.

if svr.opts.ReusePort || svr.ln.pconn != nil {
	return svr.activateLoops(numEventLoop)
}
我看代码是多个goroutine的eventloop监听同一个listenfd，会不会有惊群问题？是咋解决这个问题的？

**Comment by panjf2000** [comment]
README 上有说明：(SO_REUSEPORT 端口复用)https://github.com/panjf2000/gnet/blob/master/README_ZH.md#so_reuseport-%E7%AB%AF%E5%8F%A3%E5%A4%8D%E7%94%A8

另外，多个 goroutine 的 eventloop 监听同一个 listenfd 是旧的网络模型，gnet 默认的网络模型是主从 Reactors，不会有惊群效应。
