### ISSUE TITLE
ListenFD获取可能有点问题

### ISSUE THREAD

**Issue by alberliu** [panjf2000/gnet#77]
我看源码，gnet是通过golang原生的net.Listen获取ListenFD，这样golang底层会初始化一个epoll(我是通过看源码和查看进程打开的文件描述符发现的),然后你又自己管理了一个epoll,就会同时管理两个epoll,会造成系统资源浪费。

**Comment by panjf2000** [comment]
的确会有这个问题，`net.Listen` 会初始化一个 epoll fd，而且 `gnet` 其实并没有用到这个 epoll，仅仅是用了 listener fd，所以的确是多了一个多余的 epoll fd，不过其实这点资源消耗是微乎其微，当然也自己用 syscall 实现一个 Listen， 不过要去区分 TCP、UDP 和 Unix socket，还可能搞出 bug，感觉没必要，直接用 `net.Listen` 方便点。
