### ISSUE TITLE
KCP 协议支持

### ISSUE THREAD

**Issue by overtalk** [panjf2000/gnet#79]
add kcp option ?

**Comment by overtalk** [comment]
另外我看代码，udp部分是将 udp socket 的fd 加入到多个epoll中，这样做真的可以吗？当有可以读的事件的时候只有一个epoll 会获取到吗？还是说我对代码的理解错误

**Comment by panjf2000** [comment]
我对 KCP 没有太多的研究，如果要支持的话，可能得等后面有时间去深入研究下再看看怎么在 gnet 里开发，或者是谁对 KCP 比较熟悉给我提 PR。

**Comment by panjf2000** [comment]
> 另外我看代码，udp部分是将 udp socket 的fd 加入到多个epoll中，这样做真的可以吗？当有可以读的事件的时候只有一个epoll 会获取到吗？还是说我对代码的理解错误

多个 epoll 监听同一个 fd 会引起惊群效应，不过最终只能有一个 goroutine 成功从 fd 读取数据，所以功能上是没有问题的，只是会有一些多余的唤醒操作，解决办法也有，使用 `SO_REUSEPORT` 来保证每次只唤醒一个 epoll_wait 调用，`gnet` 也是支持 `SO_REUSEPORT` 的。

**Comment by overtalk** [comment]
感谢解惑
