### ISSUE TITLE
Do you have a plan to realize gnet multi sunReactor use work queue ?

### ISSUE THREAD

**Issue by rfyiamcool** [panjf2000/gnet#8]
see tilte, thank u.

**Comment by panjf2000** [comment]
@rfyiamcool 
抱歉，不太明白，你是说把 subReactors 做成任务队列吗？但是我不觉得这样是一个好的设计，本来用 epoll/kqueue 就是为了达到用少量 goroutines 来管理大量的 connections，没有必要加任务队列吧？

**Comment by rfyiamcool** [comment]
不好意思没说明白。
我的意思是说，如果我注册的业务方法有阻塞逻辑，比如访问db，那么subReactor也会阻塞，不能及时的去监听下一个事件。我看你在readme里又说，打算解决这个问题。把业务逻辑放到一个协程池里完成。

**Comment by panjf2000** [comment]
哦，我理解了。
关于阻塞的问题，的确是我在 README 里说的那个 multi-reactors + goroutine-pool 的模型来解决，现在还在做，估计这一两周内搞完吧！

**Comment by rfyiamcool** [comment]
我也基本想明白了实现方法，只是更想看下你的实现。 😁

**Comment by panjf2000** [comment]
@rfyiamcool 
不过现在又有点纠结，主要是 goroutine pool 放置在哪一层，有两种方案：
1. 网络层：直接集成 goroutine pool 在 `gnet` 库里面，每一次执行 `Events.React()` 方法时提交到 pool；
2. 业务层：开放 goroutine pool 给 `gnet` 业务方，让业务方自己在写业务逻辑到 `Events.React()` 里面的时候适时使用 pool 来规避阻塞。

**Comment by rfyiamcool** [comment]
我觉得各有各的优点吧。我想的是第一种，还是内敛在一起比较好，用参数来控制是否要池子。 个人看法。

**Comment by panjf2000** [comment]
嗯，我再考虑一下，thanks~
