### ISSUE TITLE
关于 Decode 返回值的问题

### ISSUE THREAD

**Issue by LayGit** [panjf2000/gnet#80]
**What is your question about gnet?**
`decode` 完了之后返回 `[]byte` 类型的考虑是什么，按照 Netty 的使用习惯感觉应该是返回个 `interface{}`，按照一般的逻辑解码函数就是根据消息协议解码二进制流转换成消息对象的过程，然后在 React 中直接拿到消息对象进行相关业务处理。如果 React 函数拿到的是 []byte 中间可能还需要再序列化一次？我的理解中 gnet 的 React 函数类似于 Netty 的 channelRead，channelRead 的入参 msg 是个 Object

**Comment by panjf2000** [comment]
`Decode` 的主要目的是分包，其实并不提倡在 `Decode` 里反序列化，反序列化在 `React` 里做就行，不用 interface 是因为不想多一步类型转换损耗性能。

**Comment by LayGit** [comment]
理解你的意思，相当于Decode的作用只是根据协议读取一个完整的包，剩余的事情都丢到React方法中去。个人认为是Decode里面还应该完成消息体的拼装，比如有个私有协议，length 4 bytes header 10 bytes body xbytes ，如果只读出数据再到React里去组装感觉有点怪，下意识会觉得应该是Decode 里应该做的事情。Encode也是，一般入参是消息对象进去，然后根据协议一个个字段写入buffer，然后发送吧…至于返回interface{} 对于性能没啥影响吧，没有多一次的序列化，早一点晚一点创建的问题，如果返回 interface 那React 入参就是 interface…React中强转下类型即可直接用构造好的消息对象

可能受 netty 影响有点惯性思维~

**Comment by panjf2000** [comment]
`gnet` 有参考 netty 的一些理念，但并不会全部照搬过来，也不想做一个像 netty 那样大而全的网络框架，设计尽量简单，最大限度提升性能，interface 的转换相对于无转换来说还是有不小的性能损失的：https://www.darkcoding.net/software/go-the-price-of-interface/

用 interface 的话的确会让边界更清晰，但是也看你怎么定义边界，也可以理解成 Decode/Encode 只负责分包和组包功能，数据的具体加工在 React 做，也说得通。

**Comment by panjf2000** [comment]
感谢对 `gnet` 的关注并提出了不同视角的观点，这样的讨论挺好，有一些新的观点，促进 `gnet` 的开发，不过现在的设计是经过考虑的，并且 `gnet` 的 v1 版的 API 都已经定下来了，按照软件版本发布规范，需要有向后兼容性，所以就算以后因为一些必要的原因要换成 interface，至少也是 v2 之后的事情了。

如果有关于 `gnet` 别的方面问题，也欢迎提出~

**Comment by iHDJ** [comment]
这只是个轻量级框架，decode一般做[]byte验证和拆包处理。拆完继续把内容下传
