### ISSUE TITLE
SetDeadline for connections

### ISSUE THREAD

**Issue by majimboo** [panjf2000/gnet#83]
How can I set a deadline for connected clients that if they do not send any packets in the last 20 seconds I will disconnect them?

**Comment by panjf2000** [comment]
https://github.com/panjf2000/gnet/blob/916c255de373b3ff73eaa10cb1f0bacc2c1b6e3f/gnet.go#L194-L196
1. Get a current timestamp when `gnet.React` is called and associate it with the connection, like storing it in a map or heap
2. Start an individual goroutine, traversing all connections with the timestamps, if `now - timestamp > 20s`, then call:
https://github.com/panjf2000/gnet/blob/916c255de373b3ff73eaa10cb1f0bacc2c1b6e3f/connection_unix.go#L215-L219

**Comment by panjf2000** [comment]
Closing this issue, feel free to reopen it if you still have questions.

**Comment by chowyu08** [comment]
how do different client with different deadline ?

**Comment by sbaier1** [comment]
FYI hashed timing wheel is a superior data structure for this kind of task

https://netty.io/4.0/api/io/netty/util/HashedWheelTimer.html
https://medium.com/@raghavan99o/hashed-timing-wheel-2192b5ec8082
https://github.com/RussellLuo/timingwheel

**Comment by panjf2000** [comment]
This feature will be implemented in version `gnet` v2, stay tuned.
