### ISSUE TITLE
gnet 单核和多核配置的性能问题

### ISSUE THREAD

**Issue by charlesgreat** [panjf2000/gnet#84]
多核linux和mac下配置NumEventLoop多了反而没有没有配置1的性能高，然后用pprof查看线程不管配置1还是4，都是只有一个线程（多个协程）。
怎样能让gnet确实启动多个线程呢？

**Comment by panjf2000** [comment]
你是怎么看线程数量的？具体步骤贴一下？什么输出？

**Comment by panjf2000** [comment]
我用 `GODEBUG=schedtrace=1000` 进行调度器追踪之后发现是有启动多个 OS 线程的，我想应该是你的设置问题吧。
![image](https://user-images.githubusercontent.com/7496278/81369964-8129b380-9126-11ea-9c30-ad67ce04e48d.png)

**Comment by charlesgreat** [comment]
我是用如下方式测试的， 不知道为啥loops多了之后，TPS反而慢了
ab -c 100  -n 1000000 -k  http://127.0.0.1:50007/index.html

 (multi-cores: true, loops: 1) 的 TPS大概在200K
 (multi-cores: true, loops: 2) 的 TPS大概是175K

**Comment by panjf2000** [comment]
贴一下 server 的代码我看下？

**Comment by charlesgreat** [comment]
package main

import (
	"bytes"
	"flag"
	"fmt"
	"github.com/panjf2000/gnet"
	"log"
	"net/http"
)


type httpServer struct {
	*gnet.EventServer
}

var rtn_close="HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: text/html;charset=utf-8\r\nContent-Length:2\r\n\r\nok "
var rtn="HTTP/1.1 200 OK\r\nConnection: keep-alive\r\nContent-Type: text/html;charset=utf-8\r\nContent-Length:2\r\n\r\nok "


func (hs *httpServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	if c.Context() != nil {
		// bad thing happened
		action = gnet.Close
		return
	}

	if bytes.Contains(frame, []byte("Keep-Alive")) || bytes.Contains(frame, []byte("keep-alive")) {
		out = append(out, rtn...)
	} else {
		out = append(out, rtn_close...)
		action = gnet.Close
	}

	return
}

func (hs *httpServer) OnInitComplete(srv gnet.Server) (action gnet.Action) {
	log.Printf("HTTP server is listening on %s (multi-cores: %t, loops: %d)\n",
		srv.Addr.String(), srv.Multicore, srv.NumEventLoop)
	return
}

func main() {

	var port int
	var NumEventLoop int

	// Example command: go run http.go --port 8080
	flag.IntVar(&port, "port", 50007, "server port")
	flag.IntVar(&NumEventLoop, "NumEventLoop", 4, "num loops")
	flag.Parse()

	http := new(httpServer)

	// Start serving!
	log.Fatal(gnet.Serve(http, fmt.Sprintf("tcp://:%d", port), gnet.WithNumEventLoop(NumEventLoop), gnet.WithMulticore(true)))
}

**Comment by charlesgreat** [comment]
已经发到github上面了



在 2020-05-08 23:34:53，"Andy Pan" <notifications@github.com> 写道：

贴一下 server 的代码我看下？

**Comment by panjf2000** [comment]
抱歉，回复晚了。
首先，`NumEventLoop` 和 `Multicore` 不用两个都设置，前者会覆盖后者的。不过单看你这个代码，我看不出什么问题，你有没有试过继续增加 `NumEventLoop` ? 增加后性能有没有提升？

@charlesgreat

**Comment by guonaihong** [comment]
ab 是单核心测试工具，试下wrk呢。

**Comment by charlesgreat** [comment]
> ab 是单核心测试工具，试下wrk呢。我猜和客户端有关系，客户端只能使用一个物理核心的算力，服务端加两个核心，benchmark数据也是上不去的。

上不去也不应该下降吧

**Comment by panjf2000** [comment]
可能是测试结果波动？多测几次也是这样吗？或者试试只设置 `gnet.WithMulticore(true)` 呢？

**Comment by cctse** [comment]
通过下面设置单核真的比默认开启多核性能高
runtime.GOMAXPROCS(1)

@panjf2000

**Comment by charlesgreat** [comment]
测试代码业务处理很快，瓶颈在I/0， 启动多核后也无法解决I/0的瓶颈
如果业务代码加点耗时的话，配置多核会比单核快

**Comment by ballontt** [comment]
> 测试代码业务处理很快，瓶颈在I/0， 启动多核后也无法解决I/0的瓶颈
> 如果业务代码加点耗时的话，配置多核会比单核快

请问这个问题得到了验证吗

**Comment by lomoye** [comment]
我用wrk本地单机测试，同样有这个问题，服务端代码跑的是官网上提供的那个http的例子。
gnet.WithMulticore(multicore)这个multicore设置为false并发可以达到90000左右，设为true只有80000多一点。。
![image](https://user-images.githubusercontent.com/16068555/125789307-058715b4-875a-43cd-a44b-7f82ac58b7e6.png)

开启多核后：
![image](https://user-images.githubusercontent.com/16068555/125789349-ff49e733-b433-4e98-92c2-66c797f6acb9.png)

**Comment by someview** [comment]
我们利用gnet实现的ws框架，性能4核的时候是1核的2倍多一点，很好奇这个cpu 亲和性是怎么做的
