### ISSUE TITLE
关于 gnet 中 kqueue 的使用问题

### ISSUE THREAD

**Issue by overtalk** [panjf2000/gnet#87]
[kqueue部分的代码](https://github.com/panjf2000/gnet/blob/master/internal/netpoll/kqueue.go#L138)

Question1 ：`ModReadWrite` 函数是不是需要再增加一个 read 的 Kevent？
Question2：`Delete` 函数没有实现，我看在 [`gnet/eventloop_unix.go` 文件](https://github.com/panjf2000/gnet/blob/master/eventloop_unix.go#L179)中会调用，这样会不会造成mac下kqueue中的事件一直增加

**Comment by panjf2000** [comment]
> ModReadWrite 函数是不是需要再增加一个 read 的 Kevent？

不需要，因为每一个 fd 上的 read 事件在 accept 之后已经注册并且会一直存在于该 fd，因此 `ModReadWrite` 只需要再加一个 write 事件即可。

> Delete 函数没有实现，我看在 gnet/eventloop_unix.go 文件中会调用，这样会不会造成mac下kqueue中的事件一直增加

不会，因为 kqueue 会在 fd 被 closed 之后自动移除该 fd 上的所有事件，所以 kqueue 是不需要手动删除 fd 的，看 kqueue 的 manual：
> Calling close() on a file descriptor will remove any kevents that reference the descriptor.

https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2

epoll 本来也是会自动移除 fd，但是因为 epoll 本身的设计问题，内核实际管理的是 "file description" 对象，用户使用的是 "file descriptor" 数字，后者和前者可能是多对一的关系，即多个 "file descriptor" 指向同一个 "file description"，epoll 采用引用计数来决定是否销毁底层的 "file description" 对象，也就是只有当全部的 "file descriptor" 都被关闭了，epoll 才会真正地销毁底层的 "file description"，所以 epoll 是需要手动移除 fd 的。

具体看 epoll 的 manual：

> Q6 Will closing a file descriptor cause it to be removed from all epoll sets automatically?
>
> A6 Yes, but be aware of the following point. A file descriptor is a reference to an open file description (see open(2)). Whenever a descriptor is duplicated via dup(2), dup2(2), fcntl(2) F_DUPFD, or fork(2), a new file descriptor referring to the same open file description is created. An open file description continues to exist until all file descriptors referring to it have been closed. A file descriptor is removed from an epoll set only after all the file descriptors referring to the underlying open file description have been closed (or before if the descriptor is explicitly removed using epoll_ctl(2) EPOLL_CTL_DEL). This means that even after a file descriptor that is part of an epoll set has been closed, events may be reported for that file descriptor if other file descriptors referring to the same underlying file description remain open.

http://man7.org/linux/man-pages/man7/epoll.7.html

**Comment by overtalk** [comment]
thanks，感谢大佬
