### ISSUE TITLE
大量连接测试的情况下，库内部报错

### ISSUE THREAD

**Issue by apple00000** [panjf2000/gnet#88]
系统：ubuntu
goverion：1.13
gnet version：1.2.0

连接数在50000的情况下，向所有连接发消息，库内部会产生panic

报错信息:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9ebe0d]

goroutine 158 [running]:
github.com/panjf2000/gnet/ringbuffer.(*RingBuffer).IsEmpty(...)
	/github.com/panjf2000/gnet@v1.2.0/ringbuffer/ring_buffer.go:359
github.com/panjf2000/gnet.(*eventloop).loopCloseConn(0xc000481b00, 0xc0019dac80, 0x0, 0x0, 0x0, 0x1a)
	/github.com/panjf2000/gnet@v1.2.0/eventloop_unix.go:176 +0x2d
github.com/panjf2000/gnet.(*conn).Close.func1(0xc0000f0b90, 0x8)
	/github.com/panjf2000/gnet@v1.2.0/connection_unix.go:217 +0x3b
github.com/panjf2000/gnet/internal.(*AsyncJobQueue).ForEach(0xc0000b1c48, 0xc0000f0b88, 0x8)
	/github.com/panjf2000/gnet@v1.2.0/internal/queue.go:40 +0xae
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling(0xc0000b1c20, 0xc000629f90, 0xc000232fc0, 0xc0000f2cc0)
	/github.com/panjf2000/gnet@v1.2.0/internal/netpoll/epoll.go:94 +0x280
github.com/panjf2000/gnet.(*server).activateSubReactor(0xc000384360, 0xc000481b00)
	/github.com/panjf2000/gnet@v1.2.0/reactor_linux.go:32 +0xd7
github.com/panjf2000/gnet.(*server).startReactors.func1.1(0xc000384360, 0xc000481b00)
	/github.com/panjf2000/gnet@v1.2.0/server_unix.go:73 +0x35
created by github.com/panjf2000/gnet.(*server).startReactors.func1
	/github.com/panjf2000/gnet@v1.2.0/server_unix.go:72 +0x6a

**Comment by panjf2000** [comment]
看起来像是调用了在已经关闭的 conn 上再一次调用 c.Close()，导致空指针报错，因为 conn 关闭之后会把 buffer 释放掉。可能是你的使用问题，或者你在https://github.com/panjf2000/gnet/blob/master/eventloop_unix.go#L175 这个函数里的开头加一个判断：
```go
if !c.opened {
	return nil
}
```
也可以顺便把 c.opened 这个值打印出来，看看是不是的确是多次关闭一个 conn.

@apple00000

**Comment by apple00000** [comment]
多谢！
