### ISSUE TITLE
增加自定义协议的codec示例

### ISSUE THREAD

**Issue by theoneLee** [panjf2000/gnet#89]
**Is your feature request related to a problem? Please describe.**
增加自定义协议的codecde示例
起因是自己想用go写一个基于tcp的长连接项目，然后想到你之前在博客上写的一篇博文介绍你这个gnet的框架，然后想着要不就使用这个网络库来做这个需求吧。在看文档的过程中，想先试着写一个自定义codec的内容。感觉这个示例应该还是有部分人需要的，例如这个issue（#70 ）

如果可以的话，我就fork项目然后把这个示例代码作为一个pr提交给你，你也可以做下review。希望能够帮助到使用这个网络库的人。

thx。

**Comment by panjf2000** [comment]
能说下你的自定义 codec 是基于什么协议的吗？增加示例我是很欢迎的，不过如果要加的话我还是希望能有比较详细的协议说明，不然的话用户看了可能也无法真正理解。

@theoneLee

**Comment by theoneLee** [comment]
@panjf2000 
其实就是一个测试用的协议，由以下字段构成，
version+actionType+dataLength+data
其中version+actionType+dataLength为header，data为payload。
在这个协议上实现了gnet的ICodec接口，在decode时除了正常分包外，还做了对于version和actionType的判断，非法就`c.ResetBuffer()`。
附带一个echo版本的server和client用于运行这个示例。

我待会提交一个pr吧。会整理下代码和添加点注释（如业务协议的所包含的字段）。

**Comment by panjf2000** [comment]
嗯，你提 PR 吧，不过最好可以在 README 里把你的协议说明一下，位置就放到 https://github.com/panjf2000/gnet#echo-server-with-blocking-logic 这一节下面那几个示例那里，跟其他的示例一样，折叠起来。谢谢！

@theoneLee

**Comment by fbbin** [comment]
您好 我自己写了一个encode/decode 为啥decode出来的数据已经没有包头了，只是包体了，这个哪里设置呢？`func (p *PackEncrypt) Decode(c gnet.Conn) ([]byte, error) {
	// 读取包头
	// p.MemSet(p.headBuf, 0)
	// p.headBuf = make([]byte, PACK_HEAD_SIZE)
	// headSizeByte, headBuf := c.ReadN(PACK_HEAD_SIZE)
	headBuf := c.Read()
	// if headSizeByte <= 0 {/
	// 	return nil, errors.New("数据包头读取错误")
	// }
	bodyLength := int(binary.LittleEndian.Uint16(headBuf[0:2]))
	fmt.Println(headBuf, bodyLength, c.BufferLength())
	if bodyLength > p.MaxPacketSize {
		return nil, errors.New("数据包内容过大")
	}

	// 读取包体内容
	bodyBuff := p.Alloc(bodyLength)
	p.MemSet(bodyBuff, 0)

	var bodySizeByte int
	bodySizeByte, bodyBuff = c.ReadN(bodyLength)
	if bodySizeByte <= 0 {
		p.Free(bodyBuff)
		return nil, errors.New("数据内容读取错误")
	}
	buf := append(p.headBuf, bodyBuff...)
	c.ShiftN(len(buf))
	return buf, nil
}`

**Comment by panjf2000** [comment]
@fbbin 

麻烦不要在这里讨论你的问题，新开一个 issue，还有用好 MD 的代码展示语法，我帮你修改了一下，你看下吧。
