### ISSUE TITLE
WebSocket support?

### ISSUE THREAD

**Issue by UltraNemesis** [panjf2000/gnet#9]
It would be good have WebSocket support for this. Maybe some of the protocol code from https://github.com/gobwas/ws can be utilized for it.

**Comment by panjf2000** [comment]
Hi,
WebSocket is one of the application-layer protocols, just like HTTP. 

`gnet` is a networking library which works on the transportation layer, users use `gnet` to implement their own servers, if you want a HTTP server then implement HTTP protocol upon `gnet`, therefore if you want a WebSocket service then implement the WebSocket protocol upon `gnet`.

`gnet` will only provide the transport-layer network APIs, the implementation of application-layer protocol is out of the scope of `gnet`, please note.
