### ISSUE TITLE
Gnet can be a micro service gateway？

### ISSUE THREAD

**Issue by sanxun0325** [panjf2000/gnet#92]
Can set up a route similar to gin in gnet？

**Comment by panjf2000** [comment]
Sorry, I don't quite get your question? Please describe it in more detail.

**Comment by sanxun0325** [comment]
I want to use GNET as a gateway for microservices, leveraging the high performance of GNET.
But I found out that GNET is just a framework for the network, and next I'm going to try to integrate the routing functions myself.
If you have good advice, you can remind me.

**Comment by panjf2000** [comment]
If you were dealing with HTTP protocol, then maybe you could take a look at httprouter? which is also the router Gin uses, I hope it helps.

**Comment by panjf2000** [comment]
Closing this issue, feel free to reopen it if you have any new questions about it.
