### ISSUE TITLE
eventloop中connections存在并发读写的问题吗？

### ISSUE THREAD

**Issue by zhoukangch** [panjf2000/gnet#93]
mainEventLoop往subEventLoop增加conn，subEventLoop 删除conn等等

**Comment by panjf2000** [comment]
不会有 race 问题，你注意看源码，所有 conn 相关的操作都是利用 Linux 的 eventfd (FreeBSD/Darwin 下类似的机制) 发送到 event-loop 关联的 goroutine 里执行的，是串行的，自然就不会有并发问题。
