### ISSUE TITLE
Poller 中 asyncJobQueue 作用？

### ISSUE THREAD

**Issue by zhoukangch** [panjf2000/gnet#94]
**What is your question about gnet?**
Please describe your question meticulously.

**Comment by panjf2000** [comment]
asyncJobQueue 是为了保证 gnet 无 race 问题而设计的，所有和 event-loop、conn 相关的操作都会放到这个队列里，然后发一个消息唤醒 epoll/kqueue，在对应的 event-loop 里执行这些任务，也就是把任务串行化，规避了 race 问题。
