### ISSUE TITLE
心跳包应该怎么处理？

### ISSUE THREAD

**Issue by zhmh2020** [panjf2000/gnet#95]
**What is your question about gnet?**
Please describe your question meticulously.

**Comment by panjf2000** [comment]
把问题详细描述一下，这样我没法理解你的具体需求。

**Comment by zhmh2020** [comment]
客户端和服务端保持长连接，维持长连接，互相定时发送心跳数据包。 想请问下gnet有这种设计吗？Tick这个方法的使用场景是什么？

**Comment by panjf2000** [comment]
这个需求可以参考：https://github.com/panjf2000/gnet/blob/master/examples/push/push.go#L34-L44
