### ISSUE TITLE
custom_codec里的demo小问题,Field写错了.应该是Version

### ISSUE THREAD

**Issue by rizzi37** [panjf2000/gnet#96]
[目标Line](https://github.com/panjf2000/gnet/blob/687c7fcc4694b9d7664834dfe448175b531f087e/examples/custom_codec/protocol/pb.go#L31)

**Comment by panjf2000** [comment]
好像的确是，我有空改下，或者你有兴趣提个PR修正一下吗？

@rizzi37

**Comment by panjf2000** [comment]
#89 @theoneLee

**Comment by theoneLee** [comment]
确实是我当初改动 `Pack()` 的时候写错了。不过demo还是会正常运行，也就没发现。因为这个是server encode后返回给client的，而client的decode并没有检查header的version和type字段，所以client也会正常接收到数据。

**Comment by theoneLee** [comment]
现在改了就好。thx。
