### ISSUE TITLE
How to integrate pprof in gnet

### ISSUE THREAD

**Issue by sanxun0325** [panjf2000/gnet#99]
**How to integrate pprof in gnet**
I tried to integrate Pprof as follows, but it doesn't seem to work.

> import (
> 	"bufio"
> 	"bytes"
> 	"fmt"
> 	"ggateway/pkg/ggateway"
> 	"github.com/panjf2000/gnet"
> 	"github.com/panjf2000/gnet/pool/goroutine"
> 	"log"
> 	"net/http"
> 	**_ "net/http/pprof"**
> )
> 
> type httpServer struct {
> 	*gnet.EventServer
> 	pool   *goroutine.Pool
> 	router *ggateway.Router
> }
> 
> type httpCodec struct {
> }
> 
> var errMsg = "Internal Server Error"
> var errMsgBytes = []byte(errMsg)
> 
> func (h httpCodec) Encode(c gnet.Conn, buf []byte) ([]byte, error) {
> 	return buf, nil
> }
> 
> func (h httpCodec) Decode(c gnet.Conn) (out []byte, err error) {
> 	buf := c.Read()
> 	c.ResetBuffer()
> 	req, err := http.ReadRequest(bufio.NewReader(bytes.NewReader(buf)))
> 	c.SetContext(Context{req: req, w: new(ggateway.GatewayHTTPResponseWriter)})
> 	if len(buf) > 0 {
> 		return buf, err
> 	} else {
> 		return
> 	}
> }
> 
> func Server(port int, multicore bool, router *ggateway.Router) {
> 	p := goroutine.Default()
> 	defer p.Release()
> 
> 	http := &httpServer{pool: p, router: router}
> 	hc := new(httpCodec)
> 	// Start serving!
> 	log.Fatal(gnet.Serve(http, fmt.Sprintf("tcp://:%d", port), gnet.WithMulticore(multicore), gnet.WithCodec(hc)))
> }

**Comment by panjf2000** [comment]
用 md 的语法把代码格式化一下，这样可读性很差。

**Comment by sanxun0325** [comment]
@panjf2000 
I just want to ask how pprof can be integrated into the supplied httpServer sample code.
https://github.com/panjf2000/gnet/blob/master/examples/http/http.go

**Comment by panjf2000** [comment]
> @panjf2000
> I just want to ask how pprof can be integrated into the supplied httpServer sample code.
> https://github.com/panjf2000/gnet/blob/master/examples/http/http.go

Just do it as everybody else did, I used to integrate pprof with `gnet`, in both ways of `http/pprof` and `runtime/pprof` (without any special steps, just like everyone else) and it worked fine, so I would suggest you search demos on the internet and just follow those demos to fulfill your work.
